package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C21 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA(" yá mǎi jiā chǒu jú ");
        details.setDescriptionB("牙买加丑橘");
        details.setDescriptionC("Uglifruit /Jamaican tangelo  ");
        details.setDescriptionD("Агли фрукт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chéng zi ");
        details.setDescriptionB("橙子");
        details.setDescriptionC("Orange");
        details.setDescriptionD("Апельсин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng níng méng ");
        details.setDescriptionB("香柠檬");
        details.setDescriptionC(" Bergamot  orange");
        details.setDescriptionD("Бергамот/ Апельсин-бергамот ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  pú táo yòu");
        details.setDescriptionB("葡萄柚");
        details.setDescriptionC("Grapefruit (pink)");
        details.setDescriptionD("Грейпфрут ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白葡萄柚");
        details.setDescriptionB("bái pú táo yòu");
        details.setDescriptionC("White grapefruit");
        details.setDescriptionD("Белый грейпфрут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tū pèng ");
        details.setDescriptionB("凸椪");
        details.setDescriptionC("Dekopon ");
        details.setDescriptionD("Декопон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chòu chéng ");
        details.setDescriptionB("臭橙");
        details.setDescriptionC("Kabosu");
        details.setDescriptionD("Кабосу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng jīn jú ");
        details.setDescriptionB("青金桔");
        details.setDescriptionC("Citrus keraji");
        details.setDescriptionD("Каламанси лайм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā lì méng dì yà jú ");
        details.setDescriptionB("加利蒙地亚橘");
        details.setDescriptionC("Calamondin/ Calamansi ");
        details.setDescriptionD("Каламондин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎ fēi ěr lái mǔ / tài guó níng méng ");
        details.setDescriptionB("卡菲尔莱姆/泰国柠檬");
        details.setDescriptionC("Kaffir lime");
        details.setDescriptionD("Кафир лайм / Лима");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kè lái mén shì xiǎo gān jú ");
        details.setDescriptionB("克莱门氏小柑橘");
        details.setDescriptionC("Clementine ");
        details.setDescriptionD("Клементин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiě hóng qīng níng ");
        details.setDescriptionB("血红青柠");
        details.setDescriptionC("Blood lime");
        details.setDescriptionD("Кровавый лайм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuè chéng");
        details.setDescriptionB("血橙");
        details.setDescriptionC("Blood orange");
        details.setDescriptionD("Кровавый апельсин /Красный апельсин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn jú / jīn jú ");
        details.setDescriptionB("金橘/金桔");
        details.setDescriptionC(" Kumquat ");
        details.setDescriptionD("Кумкват/ Фортунелла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào zhōu yuán qīng níng ");
        details.setDescriptionB("澳洲圆青柠");
        details.setDescriptionC(" Australian Round Lime ");
        details.setDescriptionD("Круглый австралийский лайм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng níng/ lái mǔ ");
        details.setDescriptionB("青柠/ 莱姆");
        details.setDescriptionC("Lime ");
        details.setDescriptionD("Лайм ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián qīng níng");
        details.setDescriptionB("甜青柠 ");
        details.setDescriptionC("Sweet lime/ Sweet limetta");
        details.setDescriptionD("Лайм сладкий / Лиметта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái níng méng ");
        details.setDescriptionB("白柠檬");
        details.setDescriptionC(" Limequat ");
        details.setDescriptionD("Лаймкват");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng ");
        details.setDescriptionB("柠檬");
        details.setDescriptionC("Lemon");
        details.setDescriptionD("Лимон ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gān jú ");
        details.setDescriptionB("柑橘");
        details.setDescriptionC(" Mandarin orange/ Mandarine ");
        details.setDescriptionD("Мандарин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wēn zhōu mì gān /wú hé jú");
        details.setDescriptionB(" 温州蜜柑/无核桔");
        details.setDescriptionC("Satsuma orange");
        details.setDescriptionD("Мандарин Уншио");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shòu gān");
        details.setDescriptionB("寿柑");
        details.setDescriptionC("Murcott / Honey tangerine ");
        details.setDescriptionD("Муркотт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū luán");
        details.setDescriptionB("朱栾");
        details.setDescriptionC("Orangelo");
        details.setDescriptionD(" Оранжело");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái jīn yòu ");
        details.setDescriptionB("白金柚");
        details.setDescriptionC(" Oroblanco / Sweetie ");
        details.setDescriptionD("Оробланко/ Свити");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào zhōu zhǐ jú/zhǐ chéng ");
        details.setDescriptionB("澳洲指橘/指橙");
        details.setDescriptionC(" Australian finger lime ");
        details.setDescriptionD("Пальчиковый лайм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yí chāng chéng ");
        details.setDescriptionB("宜昌橙");
        details.setDescriptionC("Ichang Papeda");
        details.setDescriptionD("Папеда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yòu zi ");
        details.setDescriptionB("柚子");
        details.setDescriptionC("Pomelo/ Shaddock");
        details.setDescriptionD("Помело /Шеддок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng xīn yòu ");
        details.setDescriptionB("红心柚");
        details.setDescriptionC("Pink pomelo");
        details.setDescriptionD("Помело красный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" suān chéng");
        details.setDescriptionB("酸橙");
        details.setDescriptionC("Bitter orange");
        details.setDescriptionD("Померанец/ Горький апельсин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  lú gān ");
        details.setDescriptionB(" 芦柑");
        details.setDescriptionC("Ponkan");
        details.setDescriptionD("Понкан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ shí / tiě lí zhài ");
        details.setDescriptionB("枳实/铁篱寨");
        details.setDescriptionC(" Trifoliate orange ");
        details.setDescriptionD("Понцирус / Колючий лимон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào zhōu shā mò qīng níng");
        details.setDescriptionB("澳洲沙漠青柠");
        details.setDescriptionC(" Australian desert lime ");
        details.setDescriptionD(" Австралийский пустынный лайм ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sāi wéi lì yǎ gān jú ");
        details.setDescriptionB("塞维利亚柑橘");
        details.setDescriptionC("Seville orange");
        details.setDescriptionD("Севильский апельсин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cù jú");
        details.setDescriptionB("酢橘");
        details.setDescriptionC("Sudachi");
        details.setDescriptionD(" Судачи ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hú yòu ");
        details.setDescriptionB("胡柚");
        details.setDescriptionC("Tangelo ");
        details.setDescriptionD("Танжело ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā shuò ");
        details.setDescriptionB("八朔");
        details.setDescriptionC(" Hassaku orange ");
        details.setDescriptionD("Хассаку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ chéng ");
        details.setDescriptionB("枳橙");
        details.setDescriptionC("Citrange");
        details.setDescriptionD("Цитранж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng yuán/ jǔ yuán ");
        details.setDescriptionB("香橼/ 枸橼");
        details.setDescriptionC("Yemenite citron");
        details.setDescriptionD(" Этрог/Йеменский цитрон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fó shǒu ");
        details.setDescriptionB("佛手");
        details.setDescriptionC(" Buddha's hand / Fingered citron ");
        details.setDescriptionD("Цитрон Рука Будды");
        detailsList.add(details);


    }
}
