package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C26 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("xiāng jiá lán");
        details.setDescriptionB("香荚兰");
        details.setDescriptionC(" Vanilla ");
        details.setDescriptionD("Ваниль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuè guì yè");
        details.setDescriptionB("月桂叶");
        details.setDescriptionC("Bay leaf");
        details.setDescriptionD("Лавровый лист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huí xiāng ");
        details.setDescriptionB("茴香");
        details.setDescriptionC(" Fennel ");
        details.setDescriptionD("Фенхель/  Укроп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǔ huí xiāng / shí luó ");
        details.setDescriptionB("土茴香/ 莳萝");
        details.setDescriptionC(" Dill");
        details.setDescriptionD("Укроп зеленый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǔ cài");
        details.setDescriptionB("韭菜");
        details.setDescriptionC(" Chinese chives ");
        details.setDescriptionD("Лук душистый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě jiǔ cài / xióng cōng");
        details.setDescriptionB("野韭菜/熊葱");
        details.setDescriptionC("  Wild garlic /Bear's garlic ");
        details.setDescriptionD("Черемша/ Лук медвежий ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng dì cài /tóng hāo");
        details.setDescriptionB("皇帝菜/茼蒿");
        details.setDescriptionC(" Crown daisy ");
        details.setDescriptionD(" Хризантема салатная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  xiāng qín ");
        details.setDescriptionB("香芹");
        details.setDescriptionC(" Parsley ");
        details.setDescriptionD("Петрушка кудрявая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu qín ");
        details.setDescriptionB("欧芹");
        details.setDescriptionC("Parsley");
        details.setDescriptionD("Петрушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng cài ");
        details.setDescriptionB("香菜");
        details.setDescriptionC(" Coriander");
        details.setDescriptionD(" Кориандр/Кинза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luó lè ");
        details.setDescriptionB("罗勒");
        details.setDescriptionC("Basil");
        details.setDescriptionD("Базилик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ yè luó lè ");
        details.setDescriptionB("紫叶罗勒");
        details.setDescriptionC(" Purple basil ");
        details.setDescriptionD("Базилик фиолетовый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bò hé ");
        details.setDescriptionB("薄荷");
        details.setDescriptionC("Mint");
        details.setDescriptionD("Мята");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng fēng huā");
        details.setDescriptionB("香蜂花");
        details.setDescriptionC("Melissa");
        details.setDescriptionD("Мелисса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò jiǎo lán ");
        details.setDescriptionB("墨角兰");
        details.setDescriptionC("Marjoram");
        details.setDescriptionD("Майоран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú zhì ");
        details.setDescriptionB("牛至");
        details.setDescriptionC("Oregano");
        details.setDescriptionD("Душица/ Орегано");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí dié xiāng");
        details.setDescriptionB("迷迭香");
        details.setDescriptionC("Rosemary");
        details.setDescriptionD("Розмарин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎi lǐ xiāng");
        details.setDescriptionB("百里香");
        details.setDescriptionC("Thyme");
        details.setDescriptionD("Тимьян");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dōng xiāng bò hé ");
        details.setDescriptionB("冬香薄荷");
        details.setDescriptionC("Savory");
        details.setDescriptionD("Чабер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lóng  hāo/shé hāo yè");
        details.setDescriptionB("龙蒿/蛇蒿叶");
        details.setDescriptionC("Tarragon/Estragon");
        details.setDescriptionD("Эстрагон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("là gēn");
        details.setDescriptionB("辣根");
        details.setDescriptionC(" Horseradish ");
        details.setDescriptionD("Хрен ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǔ wěi cǎo ");
        details.setDescriptionB("鼠尾草");
        details.setDescriptionC("Sage ");
        details.setDescriptionD("Шалфей");
        detailsList.add(details);


    }
}
