package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C27 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("xīn nián/ yuán dàn jié ");
        details.setDescriptionB("新年/元旦节");
        details.setDescriptionC("New Year");
        details.setDescriptionD("Новый год");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chūn jié");
        details.setDescriptionB("春节");
        details.setDescriptionC("Chinese New Year/ Spring Festival");
        details.setDescriptionD("Китайский Новый год/ Праздник весны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuán xiāo jié ");
        details.setDescriptionB("元宵节 ");
        details.setDescriptionC("Lantern Festival ");
        details.setDescriptionD("Праздник фонарей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qíng rén jié ");
        details.setDescriptionB("情人节");
        details.setDescriptionC("Valentine's Day");
        details.setDescriptionD("День святого Валентина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fù nǚ jié");
        details.setDescriptionB("妇女节");
        details.setDescriptionC("International Women's Day");
        details.setDescriptionD("Международный женский день");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ qīn jié");
        details.setDescriptionB("母亲节");
        details.setDescriptionC("Mother's Day");
        details.setDescriptionD("День матери");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí shù jié");
        details.setDescriptionB("植树节");
        details.setDescriptionC("Arbor Day");
        details.setDescriptionD("День посадки деревьев");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú rén jié ");
        details.setDescriptionB("愚人节");
        details.setDescriptionC(" April Fools' Day ");
        details.setDescriptionD("День смеха/ День дураков");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng míng jié ");
        details.setDescriptionB("清明节");
        details.setDescriptionC(" Qingming /Ching Ming festival ");
        details.setDescriptionD("Цинмин/ День поминовения усопших");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǔ yī guó jì láo dòng jié/láo dòng jié ");
        details.setDescriptionB("五一国际劳动节/劳动节");
        details.setDescriptionC(" International Workers' Day/May Day ");
        details.setDescriptionD(" День труда /Первое мая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é luó sī shèng lì jié");
        details.setDescriptionB("俄罗斯胜利节");
        details.setDescriptionC("Victory Day");
        details.setDescriptionD("День Победы ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duān wǔ jié ");
        details.setDescriptionB("端午节 ");
        details.setDescriptionC("Dragon Boat Festival ");
        details.setDescriptionD(" Праздник драконьих лодок/Дуань-у");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng nián jié ");
        details.setDescriptionB("青年节");
        details.setDescriptionC(" Youth festival ");
        details.setDescriptionD("День молодёжи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fù huó jié ");
        details.setDescriptionB("复活节");
        details.setDescriptionC("Easter");
        details.setDescriptionD("Пасха/ Воскресение Христово");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó jì ér tóng jié");
        details.setDescriptionB("国际儿童节");
        details.setDescriptionC("International Children's Day");
        details.setDescriptionD("Международный день защиты детей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qī xī jié");
        details.setDescriptionB("七夕节");
        details.setDescriptionC(" Chinese Valentine's Day /Double Seventh Festival");
        details.setDescriptionD("Праздник влюблёных/ Цисицзе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào shī jié");
        details.setDescriptionB("教师节 ");
        details.setDescriptionC("Teachers' Day ");
        details.setDescriptionD("День учителя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng qiū jié");
        details.setDescriptionB("中秋节");
        details.setDescriptionC(" Mid-Autumn Festival ");
        details.setDescriptionD("Праздник середины осени");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó qìng jié");
        details.setDescriptionB("国庆节 ");
        details.setDescriptionC("National Day ");
        details.setDescriptionD(" День образования КНР");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wàn shèng jié");
        details.setDescriptionB("万圣节");
        details.setDescriptionC("Halloween  ");
        details.setDescriptionD("Хэллоуин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn ēn jié");
        details.setDescriptionB("感恩节");
        details.setDescriptionC("Thanksgiving Day");
        details.setDescriptionD("День благодарения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shèng dàn jié ");
        details.setDescriptionB("圣诞节");
        details.setDescriptionC("Christmas");
        details.setDescriptionD("Рождество");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēng rì ");
        details.setDescriptionB("生日");
        details.setDescriptionC("Birthday");
        details.setDescriptionD("День рождения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shēng rì kuài lè");
        details.setDescriptionB("生日快乐");
        details.setDescriptionC("Happy birthday!");
        details.setDescriptionD("C Днём рождения!");
        detailsList.add(details);
        

    }
}
