package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C30 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("yǔ háng yuán");
        details.setDescriptionB(" 宇航员");
        details.setDescriptionC("Astronaut");
        details.setDescriptionD("Астронавт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng yuán");
        details.setDescriptionB("运动员");
        details.setDescriptionC("Sportsman");
        details.setDescriptionD("Спортсмен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kōng jiě");
        details.setDescriptionB("空姐");
        details.setDescriptionC("Stewardess");
        details.setDescriptionD("Стюардесса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi xíng yuán ");
        details.setDescriptionB("飞行员");
        details.setDescriptionC("Pilot");
        details.setDescriptionD("Пилот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǎn lǐ yuán ");
        details.setDescriptionB("管理员");
        details.setDescriptionC("Administrator");
        details.setDescriptionD("Администратор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ zhě ");
        details.setDescriptionB("舞者");
        details.setDescriptionC("Dancer ");
        details.setDescriptionD("Танцор/ Танцовщица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā lěi wǔ yǎn yuán");
        details.setDescriptionB("芭蕾舞演员");
        details.setDescriptionC("Ballet-dancer");
        details.setDescriptionD("Балерина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā tíng zhǔ fù");
        details.setDescriptionB("家庭主妇");
        details.setDescriptionC("Housewife");
        details.setDescriptionD("Домохозяйка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāo fáng yuán ");
        details.setDescriptionB("消防员");
        details.setDescriptionC("Fireman");
        details.setDescriptionD("Пожарный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jǐng chá ");
        details.setDescriptionB("警察");
        details.setDescriptionC("Policeman");
        details.setDescriptionD("Полицейский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiāo tōng jǐng chá");
        details.setDescriptionB("交通警察");
        details.setDescriptionC("Traffic police ");
        details.setDescriptionD("Дорожная полиция ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎo ān ");
        details.setDescriptionB("保安");
        details.setDescriptionC("Security guard ");
        details.setDescriptionD("Охранник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎo biāo");
        details.setDescriptionB("保镖");
        details.setDescriptionC("Bodyguard");
        details.setDescriptionD("Телохранитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shì bīng");
        details.setDescriptionB("士兵");
        details.setDescriptionC("Soldier");
        details.setDescriptionD("Солдат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qián gōng");
        details.setDescriptionB("钳工");
        details.setDescriptionC("Fitter");
        details.setDescriptionD("Монтёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhē gōng ");
        details.setDescriptionB("车工");
        details.setDescriptionC("Turner");
        details.setDescriptionD("Токарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hàn jiē gōng");
        details.setDescriptionB("焊接工");
        details.setDescriptionC("Welder");
        details.setDescriptionD("Сварщик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàn zhù gōng rén ");
        details.setDescriptionB("建筑工人");
        details.setDescriptionC("Builder");
        details.setDescriptionD("Строитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàn zhù shī ");
        details.setDescriptionB("建筑师");
        details.setDescriptionC(" Architect");
        details.setDescriptionD(" Архитектор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù jiàng");
        details.setDescriptionB("木匠");
        details.setDescriptionC("Carpenter");
        details.setDescriptionD("Плотник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jì zhě ");
        details.setDescriptionB("记者");
        details.setDescriptionC("Journalist/ Reporter ");
        details.setDescriptionD("Журналист/ Репортёр ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín háng jiā");
        details.setDescriptionB("银行家");
        details.setDescriptionC("Banker");
        details.setDescriptionD("Банкир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīn wén bō yīn yuán ");
        details.setDescriptionB("新闻播音员");
        details.setDescriptionC("Newsreader");
        details.setDescriptionD("Ведущая новостей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō yīn yuán");
        details.setDescriptionB("播音员");
        details.setDescriptionC("Announcer");
        details.setDescriptionD("Диктор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù shī");
        details.setDescriptionB("牧师");
        details.setDescriptionC("Priest");
        details.setDescriptionD("Cвященник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó shù shī");
        details.setDescriptionB("魔术师");
        details.setDescriptionC("Magician");
        details.setDescriptionD("Волшебник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān yì yuán");
        details.setDescriptionB("翻译员（口译）");
        details.setDescriptionC("Interpreter");
        details.setDescriptionD("Устный переводчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǎo shī");
        details.setDescriptionB("老师");
        details.setDescriptionC("Teacher ");
        details.setDescriptionD("Учитель/Учительница ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xué jiào shī ");
        details.setDescriptionB("大学教师");
        details.setDescriptionC(" University teacher");
        details.setDescriptionD("Преподаватель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào shòu ");
        details.setDescriptionB("教授");
        details.setDescriptionC("Professor ");
        details.setDescriptionD("Профессор ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xué shēng ");
        details.setDescriptionB("学生");
        details.setDescriptionC("Student");
        details.setDescriptionD("Студент/ Ученик ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zú qiú yùn dòng yuán");
        details.setDescriptionB("足球运动员");
        details.setDescriptionC("Football player");
        details.setDescriptionD("Футболист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liè rén");
        details.setDescriptionB("猎人");
        details.setDescriptionC("Hunter");
        details.setDescriptionD("Охотник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ shī ");
        details.setDescriptionB("律师");
        details.setDescriptionC("Lawyer");
        details.setDescriptionD("Адвокат/ Юрист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fǎ guān ");
        details.setDescriptionB("法官");
        details.setDescriptionC("Judge");
        details.setDescriptionD("Судья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yī shēng ");
        details.setDescriptionB("医生");
        details.setDescriptionC("Doctor");
        details.setDescriptionD("Доктор/Врач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hù shì ");
        details.setDescriptionB("护士");
        details.setDescriptionC("Nurse");
        details.setDescriptionD("Медсестра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yào jì shī ");
        details.setDescriptionB("药剂师");
        details.setDescriptionC("Pharmacist");
        details.setDescriptionD(" Фармацевт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yá yī ");
        details.setDescriptionB("牙医");
        details.setDescriptionC("Dentist");
        details.setDescriptionD("Стоматолог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wài kē yī shēng ");
        details.setDescriptionB("外科医生");
        details.setDescriptionC("Surgeon ");
        details.setDescriptionD("Хирург");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shòu yī");
        details.setDescriptionB("兽医");
        details.setDescriptionC("Vet");
        details.setDescriptionD("Ветеринар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shāng rén ");
        details.setDescriptionB("商人");
        details.setDescriptionC("Businessman");
        details.setDescriptionD("Бизнесмен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ shāng rén ");
        details.setDescriptionB("女商人");
        details.setDescriptionC("Businesswoman");
        details.setDescriptionD("Бизнес-леди");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǎo bǎn ");
        details.setDescriptionB("老板");
        details.setDescriptionC("Boss");
        details.setDescriptionD("Босс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mì shū");
        details.setDescriptionB("秘书");
        details.setDescriptionC("Secretary");
        details.setDescriptionD("Секретарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuài jì shī");
        details.setDescriptionB("会计师");
        details.setDescriptionC("Accountant");
        details.setDescriptionD("Бухгалтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shōu yín yuán ");
        details.setDescriptionB("收银员");
        details.setDescriptionC("Cashier");
        details.setDescriptionD("Кассир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīng lǐ ");
        details.setDescriptionB("经理");
        details.setDescriptionC("Manager");
        details.setDescriptionD("Менеджер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng rén");
        details.setDescriptionB("工人");
        details.setDescriptionC("Worker");
        details.setDescriptionD("Рабочий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng dì chǎn shāng  ");
        details.setDescriptionB("房地产商");
        details.setDescriptionC("Realtor ");
        details.setDescriptionD("Риэлтор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuī xiāo yuán");
        details.setDescriptionB("推销员");
        details.setDescriptionC("Seller/Salesman");
        details.setDescriptionD("Продавец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shòu huò yuán");
        details.setDescriptionB("售货员");
        details.setDescriptionC("Shop assistant");
        details.setDescriptionD("Продавец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāo shòu dài biǎo ");
        details.setDescriptionB("销售代表");
        details.setDescriptionC("Sales  representative");
        details.setDescriptionD("Торговый представитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí yuán ");
        details.setDescriptionB("职员");
        details.setDescriptionC("Staff member ");
        details.setDescriptionD("Штатный сотрудник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīng jì xué jiā ");
        details.setDescriptionB("经济学家");
        details.setDescriptionC(" Economist");
        details.setDescriptionD("Экономист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu dì yuán ");
        details.setDescriptionB("邮递员");
        details.setDescriptionC("Postman");
        details.setDescriptionD("Почтальон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi róng shī ");
        details.setDescriptionB("美容师");
        details.setDescriptionC("Beautician");
        details.setDescriptionD("Косметолог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǐ fǎ shī");
        details.setDescriptionB("理发师");
        details.setDescriptionC("Barber");
        details.setDescriptionD("Парикмахер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi fǎ shī");
        details.setDescriptionB("美发师");
        details.setDescriptionC("Hairdresser");
        details.setDescriptionD("Парикмахер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shè yǐng shī");
        details.setDescriptionB("摄影师");
        details.setDescriptionC("Photographer");
        details.setDescriptionD("Фотограф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīn yuè jiā");
        details.setDescriptionB("音乐家");
        details.setDescriptionC("Musician");
        details.setDescriptionD("Музыкант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo chǒu");
        details.setDescriptionB("小丑");
        details.setDescriptionC("Clown");
        details.setDescriptionD("Клоун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mó tè ");
        details.setDescriptionB("模特");
        details.setDescriptionC("Model ");
        details.setDescriptionD("Модель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn yuán ");
        details.setDescriptionB("演员");
        details.setDescriptionC("Actor ");
        details.setDescriptionD("Актёр ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ yǎn yuán ");
        details.setDescriptionB("女演员");
        details.setDescriptionC(" Actress ");
        details.setDescriptionD("Актриса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn yǐng míng xīng");
        details.setDescriptionB("电影明星");
        details.setDescriptionC("Film star");
        details.setDescriptionD("Кинозвезда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gē xīng");
        details.setDescriptionB("歌星");
        details.setDescriptionC("Singer");
        details.setDescriptionD("Певец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuò jiā");
        details.setDescriptionB("作家");
        details.setDescriptionC("Writer");
        details.setDescriptionD("Писатель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biān jí");
        details.setDescriptionB("编辑");
        details.setDescriptionC("Editor");
        details.setDescriptionD("Pедактор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tú shū guǎn lǐ yuán");
        details.setDescriptionB("图书管理员");
        details.setDescriptionC("Librarian");
        details.setDescriptionD("Библиотекарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīn lǐ xué jiā");
        details.setDescriptionB("心理学家");
        details.setDescriptionC("Psychologist");
        details.setDescriptionD("Психолог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà jiā");
        details.setDescriptionB("画家");
        details.setDescriptionC("Artist");
        details.setDescriptionD("Художник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diāo kè jiā");
        details.setDescriptionB("雕刻家");
        details.setDescriptionC("Sculptor");
        details.setDescriptionD("Скульптор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū bǎo jiàng");
        details.setDescriptionB("珠宝匠");
        details.setDescriptionC("Jeweller");
        details.setDescriptionD("Ювелир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sī jī");
        details.setDescriptionB("司机");
        details.setDescriptionC("Driver");
        details.setDescriptionD("Водитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chū zū chē sī jī");
        details.setDescriptionB("出租车司机");
        details.setDescriptionC("Taxi driver");
        details.setDescriptionD("Водитель такси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ chē sī jī");
        details.setDescriptionB("卡车司机");
        details.setDescriptionC("Lorry driver");
        details.setDescriptionD("Водитель грузовика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā shì sī jī");
        details.setDescriptionB("巴士司机");
        details.setDescriptionC("Bus driver");
        details.setDescriptionD("Водитель автобуса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī xiè shī");
        details.setDescriptionB("机械师");
        details.setDescriptionC("Mechanic");
        details.setDescriptionD("Механик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ nuǎn gōng ");
        details.setDescriptionB("水暖工");
        details.setDescriptionC("Plumber ");
        details.setDescriptionD("Водопроводчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ shǒu ");
        details.setDescriptionB("水手");
        details.setDescriptionC("Sailor");
        details.setDescriptionD("Моряк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuán dīng ");
        details.setDescriptionB("园丁");
        details.setDescriptionC("Gardener");
        details.setDescriptionD("Садовник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā shāng ");
        details.setDescriptionB("花商");
        details.setDescriptionC("Florist");
        details.setDescriptionD("Флорист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nóng mín ");
        details.setDescriptionB("农民");
        details.setDescriptionC("Farmer ");
        details.setDescriptionD("Фермер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú fū ");
        details.setDescriptionB("渔夫");
        details.setDescriptionC("Fisherman");
        details.setDescriptionD("Рыбак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chú shī");
        details.setDescriptionB("厨师");
        details.setDescriptionC("Chef");
        details.setDescriptionD("Повар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn bāo shī ");
        details.setDescriptionB("面包师");
        details.setDescriptionC("Baker");
        details.setDescriptionD("Пекарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǔ bǎo");
        details.setDescriptionB("酒保");
        details.setDescriptionC("Barman");
        details.setDescriptionD("Бармен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng chéng shī");
        details.setDescriptionB("工程师");
        details.setDescriptionC("Engineer");
        details.setDescriptionD("Инженер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn gōng ");
        details.setDescriptionB("电工");
        details.setDescriptionC(" Electrician ");
        details.setDescriptionD(" Электрик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Jì shù yuán");
        details.setDescriptionB("技术员");
        details.setDescriptionC("Technician");
        details.setDescriptionD("Техник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhéng xù yuán");
        details.setDescriptionB("程序员");
        details.setDescriptionC("Programmer");
        details.setDescriptionD("Программист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎo yóu");
        details.setDescriptionB("导游");
        details.setDescriptionC("Tour guide");
        details.setDescriptionD("Гид-экскурсовод");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ xíng dài lǐ");
        details.setDescriptionB("旅行代理");
        details.setDescriptionC("Travel agent");
        details.setDescriptionD("Тур-агент");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huà xué jiā ");
        details.setDescriptionB("化学家");
        details.setDescriptionC(" Chemist ");
        details.setDescriptionD("Химик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сái féng shī");
        details.setDescriptionB("裁缝师");
        details.setDescriptionC("Tailor");
        details.setDescriptionD("Портной");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fú wù yuán");
        details.setDescriptionB("服务员");
        details.setDescriptionC("Waiter");
        details.setDescriptionD("Официант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǚ fú wù yuán");
        details.setDescriptionB("女服务员");
        details.setDescriptionC("Waitress");
        details.setDescriptionD("Официантка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shè jì shī");
        details.setDescriptionB("设计师");
        details.setDescriptionC("Designer");
        details.setDescriptionD("Дизайнер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kē xué jiā");
        details.setDescriptionB("科学家");
        details.setDescriptionC("Scientist");
        details.setDescriptionD("Ученый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn tàn");
        details.setDescriptionB("侦探");
        details.setDescriptionC("Detective");
        details.setDescriptionD("Детектив");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiū lǐ gōng");
        details.setDescriptionB("修理工");
        details.setDescriptionC("Repairman");
        details.setDescriptionD("Ремонтник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng jié gōng");
        details.setDescriptionB("清洁工");
        details.setDescriptionC("Cleaner");
        details.setDescriptionD("Уборщик/ Уборщица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ fú wù yuán ");
        details.setDescriptionB("女服务员 (打扫宾馆客房的)");
        details.setDescriptionC("Chambermaid");
        details.setDescriptionD("Горничная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ yōng ");
        details.setDescriptionB("女佣");
        details.setDescriptionC("Maid");
        details.setDescriptionD("Прислуга/Служанка");
        detailsList.add(details);

        

    }
}
