package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C32 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("qīng tíng");
        details.setDescriptionB("蜻蜓");
        details.setDescriptionC("Dragonfly");
        details.setDescriptionD("Стрекоза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhà měng");
        details.setDescriptionB("蚱蜢");
        details.setDescriptionC("Grasshopper");
        details.setDescriptionD("Кузнечик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng chóng");
        details.setDescriptionB("蝗虫");
        details.setDescriptionC("Locust");
        details.setDescriptionD("Саранча");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī shuài");
        details.setDescriptionB("蟋蟀");
        details.setDescriptionC("Cricket");
        details.setDescriptionD("Сверчок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qú sōu");
        details.setDescriptionB("蠼螋");
        details.setDescriptionC("Earwig");
        details.setDescriptionD("Уховертка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kē tóu chóng");
        details.setDescriptionB("磕头虫");
        details.setDescriptionC("Snapping beetle");
        details.setDescriptionD("Жук-щелкун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yá chóng ");
        details.setDescriptionB("蚜虫");
        details.setDescriptionC("Aphid ");
        details.setDescriptionD("Тля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chòu chóng");
        details.setDescriptionB("臭虫 ");
        details.setDescriptionC("Bedbug");
        details.setDescriptionD("Клоп ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhī liǎo /chán");
        details.setDescriptionB("知了/蝉");
        details.setDescriptionC(" Cicada ");
        details.setDescriptionD("Цикада");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("piáo chóng");
        details.setDescriptionB("瓢虫");
        details.setDescriptionC("Ladybug");
        details.setDescriptionD("Божья коровка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn guī zi");
        details.setDescriptionB("金龟子");
        details.setDescriptionC(" Scarab ");
        details.setDescriptionD("Скарабей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā jīn guī ");
        details.setDescriptionB("花金龟");
        details.setDescriptionC(" Flower chafer ");
        details.setDescriptionD("Жук-бронзовка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái yǐ");
        details.setDescriptionB("白蚁 ");
        details.setDescriptionC("Termite ");
        details.setDescriptionD("Термит");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhāng láng ");
        details.setDescriptionB("蟑螂");
        details.setDescriptionC("Cockroach ");
        details.setDescriptionD("Таракан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng láng");
        details.setDescriptionB("螳螂");
        details.setDescriptionC("Mantis");
        details.setDescriptionD("Богомол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ yǐ ");
        details.setDescriptionB("蚂蚁");
        details.setDescriptionC("Ant");
        details.setDescriptionD("Муравей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng fēng ");
        details.setDescriptionB("黄蜂");
        details.setDescriptionC("Wasp");
        details.setDescriptionD("Оса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mì fēng");
        details.setDescriptionB("蜜蜂");
        details.setDescriptionC("Bee");
        details.setDescriptionD("Пчела");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xióng fēng ");
        details.setDescriptionB("熊蜂");
        details.setDescriptionC("Bumblebee");
        details.setDescriptionD("Шмель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ fēng ");
        details.setDescriptionB("马蜂");
        details.setDescriptionC(" Hornet ");
        details.setDescriptionD("Шершень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wén zi");
        details.setDescriptionB("蚊子");
        details.setDescriptionC("Mosquito");
        details.setDescriptionD("Комар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cāng yíng");
        details.setDescriptionB("苍蝇");
        details.setDescriptionC("Fly");
        details.setDescriptionD("Муха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú méng ");
        details.setDescriptionB("牛虻");
        details.setDescriptionC("Gadfly");
        details.setDescriptionD("Овод (Слепень)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yíng huǒ chóng");
        details.setDescriptionB("萤火虫");
        details.setDescriptionC(" Firefly ");
        details.setDescriptionD("Светлячок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fú yóu ");
        details.setDescriptionB("蜉蝣");
        details.setDescriptionC("Mayfly ");
        details.setDescriptionD("Однодневка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" é ");
        details.setDescriptionB("蛾");
        details.setDescriptionC("Moth");
        details.setDescriptionD("Моль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǒng què dié ");
        details.setDescriptionB("孔雀蝶 ");
        details.setDescriptionC("Peacock butterfly");
        details.setDescriptionD("Бабочка Павлиний глаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fèng dié");
        details.setDescriptionB("凤蝶");
        details.setDescriptionC("Butterfly ");
        details.setDescriptionD("Бабочка Махаон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hú dié ");
        details.setDescriptionB("蝴蝶");
        details.setDescriptionC("Butterfly");
        details.setDescriptionD("Бабочка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī dié ");
        details.setDescriptionB("灰蝶");
        details.setDescriptionC(" Copper-butterfly ");
        details.setDescriptionD("Голубянка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǐ liǎn tiān é");
        details.setDescriptionB("鬼脸天蛾");
        details.setDescriptionC(" Death's-head moth");
        details.setDescriptionD("Бражник Мёртвая голова ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiào zao ");
        details.setDescriptionB("跳蚤");
        details.setDescriptionC("Flea");
        details.setDescriptionD("Блоха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shī zi");
        details.setDescriptionB("虱子");
        details.setDescriptionC("Louse ");
        details.setDescriptionD("Вошь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǔ yuè jīn guī zi ");
        details.setDescriptionB("五月金龟子");
        details.setDescriptionC("Мay-bug");
        details.setDescriptionD("Майский жук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ líng shǔ jiǎ chóng ");
        details.setDescriptionB("马铃薯甲虫");
        details.setDescriptionC("Colorado potato beetle ");
        details.setDescriptionD("Колорадский жук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lóu gū ");
        details.setDescriptionB("蝼蛄");
        details.setDescriptionC("Mole cricket ");
        details.setDescriptionD("Медведка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dú jiǎo xiān ");
        details.setDescriptionB("独角仙");
        details.setDescriptionC("Unicorn beetle ");
        details.setDescriptionD("Жук-носорог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng jǐ dà dōu chóng ");
        details.setDescriptionB("长戟大兜虫");
        details.setDescriptionC(" Hercules beetle ");
        details.setDescriptionD("Жук-геркулес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lù jiǎo chóng ");
        details.setDescriptionB("鹿角虫");
        details.setDescriptionC("Stag-beetle");
        details.setDescriptionD("ЖУК-ОЛЕНЬ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhǒu jiǎo jiǎ chóng");
        details.setDescriptionB("丑角甲虫");
        details.setDescriptionC("Harlequin beetle");
        details.setDescriptionD("Жук-арлекин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù jiǎ");
        details.setDescriptionB("步甲");
        details.setDescriptionC("Ground beetle");
        details.setDescriptionD("Жужелица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gēn liú yá");
        details.setDescriptionB("根瘤蚜 ");
        details.setDescriptionC("Phylloxera");
        details.setDescriptionD("Филлоксера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lóng shī ");
        details.setDescriptionB("龙虱");
        details.setDescriptionC(" Predacious diving beetle");
        details.setDescriptionD("Жук-плавунец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ miǎn");
        details.setDescriptionB("水黾");
        details.setDescriptionC("Pond-skater");
        details.setDescriptionD("Водомерка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rú chóng ");
        details.setDescriptionB("蠕虫");
        details.setDescriptionC("Worm");
        details.setDescriptionD("Червяк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cán");
        details.setDescriptionB("蚕");
        details.setDescriptionC("Silkworm");
        details.setDescriptionD("Шелкопряд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo chóng");
        details.setDescriptionB("毛虫");
        details.setDescriptionC("Caterpillar");
        details.setDescriptionD("Гусеница");
        detailsList.add(details);
        

    }
}
