package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C33 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("shuǐ ");
        details.setDescriptionB("水");
        details.setDescriptionC("Water");
        details.setDescriptionD("Вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuàng quán shuǐ");
        details.setDescriptionB("矿泉水");
        details.setDescriptionC("Mineral water");
        details.setDescriptionD("Минеральная вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì pào kuàng quán shuǐ");
        details.setDescriptionB("气泡矿泉水");
        details.setDescriptionC("Sparkling mineral water");
        details.setDescriptionD("Газированная вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū dǎ shuǐ");
        details.setDescriptionB("苏打水");
        details.setDescriptionC("Soda water");
        details.setDescriptionD("Содовая вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng shuǐ ");
        details.setDescriptionB("冰水");
        details.setDescriptionC(" Ice water ");
        details.setDescriptionD("Вода со льдом ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng shuǐ");
        details.setDescriptionB("柠檬水");
        details.setDescriptionC("Water with lemon");
        details.setDescriptionD("Вода с лимоном");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kuí níng shuǐ ");
        details.setDescriptionB("奎宁水");
        details.setDescriptionC("Tonic water");
        details.setDescriptionD("Тоник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kě kǒu kě lè");
        details.setDescriptionB("可口可乐");
        details.setDescriptionC("Coca Cola");
        details.setDescriptionD("Кока-кола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎi shì kě lè");
        details.setDescriptionB("百事可乐");
        details.setDescriptionC("Pepsi");
        details.setDescriptionD("Пепси ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě bì");
        details.setDescriptionB("雪碧");
        details.setDescriptionC("Sprite");
        details.setDescriptionD("Спрайт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēn dá");
        details.setDescriptionB("芬达");
        details.setDescriptionC("Fanta");
        details.setDescriptionD("Фанта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng shuǐ");
        details.setDescriptionB("柠檬水");
        details.setDescriptionC("Lemonade");
        details.setDescriptionD("Лимонад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kè wǎ sī");
        details.setDescriptionB("克瓦斯");
        details.setDescriptionC("Kvass");
        details.setDescriptionD("Квас");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi jiǔ jīng pí jiǔ");
        details.setDescriptionB("非酒精啤酒");
        details.setDescriptionC(" Non-alcoholic beer");
        details.setDescriptionD("Безалкогольное  пиво");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táng zhǔ shuǐ guǒ");
        details.setDescriptionB("糖煮水果");
        details.setDescriptionC("Compote");
        details.setDescriptionD("Компот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guǒ yǐn liào");
        details.setDescriptionB("水果饮料");
        details.setDescriptionC("Fruit-drink");
        details.setDescriptionD("Морс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǎi xī");
        details.setDescriptionB("奶昔");
        details.setDescriptionC("Milkshake");
        details.setDescriptionD("Молочный коктейль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi nǎi xī");
        details.setDescriptionB("咖啡奶昔");
        details.setDescriptionC("Coffee milkshake");
        details.setDescriptionD("Кофейный молочный коктейль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dàn bái zhí nǎi xī");
        details.setDescriptionB("蛋白质奶昔");
        details.setDescriptionC("Protein shake");
        details.setDescriptionD("Протеиновый коктейль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yē nǎi");
        details.setDescriptionB("椰奶");
        details.setDescriptionC("Coconut milk");
        details.setDescriptionD("Кокосовое молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yē zi shuǐ");
        details.setDescriptionB("椰子水");
        details.setDescriptionC("Coconut water");
        details.setDescriptionD("Кокосовая вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǜ chá");
        details.setDescriptionB("绿茶");
        details.setDescriptionC("Green tea");
        details.setDescriptionD("Зелёный чай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng chá");
        details.setDescriptionB("红茶");
        details.setDescriptionC("Black tea");
        details.setDescriptionD("Чёрный чай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò lì huā chá");
        details.setDescriptionB("茉莉花茶");
        details.setDescriptionC("Jasmine tea");
        details.setDescriptionD("Жасминовый чай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng chá ");
        details.setDescriptionB("柠檬茶");
        details.setDescriptionC("Tea with lemon");
        details.setDescriptionD("Чай с лимоном");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng chá");
        details.setDescriptionB("冰茶");
        details.setDescriptionC("Iced tea");
        details.setDescriptionD("Чай со льдом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kě kě");
        details.setDescriptionB("可可");
        details.setDescriptionC("Cocoa");
        details.setDescriptionD("Какао");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rè qiǎo kè lì");
        details.setDescriptionB("热巧克力");
        details.setDescriptionC("Hot chocolate");
        details.setDescriptionD("Горячий шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi shì kā fēi");
        details.setDescriptionB("美式咖啡");
        details.setDescriptionC("Americano");
        details.setDescriptionD("Кофе американо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng kā fēi ");
        details.setDescriptionB("冰咖啡");
        details.setDescriptionC("Iced coffee");
        details.setDescriptionD("Кофе гляссе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ bù qí nuò");
        details.setDescriptionB("卡布奇诺");
        details.setDescriptionC("Cappuccino");
        details.setDescriptionD("Кофе капучино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǔ ěr qí kā fēi");
        details.setDescriptionB("土耳其咖啡");
        details.setDescriptionC("Turkish coffee");
        details.setDescriptionD("Кофе по-турецки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi ná tiě");
        details.setDescriptionB("咖啡拿铁");
        details.setDescriptionC("Coffee latte");
        details.setDescriptionD("Кофе-латте");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó kǎ kā fēi");
        details.setDescriptionB("摩卡咖啡");
        details.setDescriptionC(" Mocha Cafe ");
        details.setDescriptionD("Кофе мокачино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nóng suō kā fēi");
        details.setDescriptionB("浓缩咖啡");
        details.setDescriptionC("Espresso coffee");
        details.setDescriptionD("Кофе эспрессо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú nǎi kā fēi ");
        details.setDescriptionB("牛奶咖啡");
        details.setDescriptionC("Coffee with milk");
        details.setDescriptionD("Кофе с молоком");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Hibiscus tea");
        details.setDescriptionB("Каркаде");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ zhī");
        details.setDescriptionB("果汁");
        details.setDescriptionC("Juice");
        details.setDescriptionD("Сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xìng zhī");
        details.setDescriptionB("杏汁");
        details.setDescriptionC("Apricot juice");
        details.setDescriptionD("Абрикосовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō luó zhī");
        details.setDescriptionB("菠萝汁");
        details.setDescriptionC("Pineapple juice");
        details.setDescriptionD("Ананасовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chéng zhī");
        details.setDescriptionB("橙汁");
        details.setDescriptionC("Orange juice");
        details.setDescriptionD("Апельсиновый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī guā zhī");
        details.setDescriptionB("西瓜汁");
        details.setDescriptionC("Watermelon juice");
        details.setDescriptionD("Арбузный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng táo zhī ");
        details.setDescriptionB("樱桃汁");
        details.setDescriptionC(" Cherry juice ");
        details.setDescriptionD("Вишнёвый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng jiāo zhī");
        details.setDescriptionB("香蕉汁");
        details.setDescriptionC("Banana juice");
        details.setDescriptionD("Банановый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái huà shù zhī");
        details.setDescriptionB("白桦树汁");
        details.setDescriptionC("Birch juice");
        details.setDescriptionD("Берёзовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí liú zhī");
        details.setDescriptionB("石榴汁");
        details.setDescriptionC("Pomegranate juice");
        details.setDescriptionD("Гранатовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pú táo yòu zhī");
        details.setDescriptionB("葡萄柚汁");
        details.setDescriptionC("Grapefruit juice");
        details.setDescriptionD("Грейпфрутовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lí zhī");
        details.setDescriptionB("梨汁");
        details.setDescriptionC("Pear juice");
        details.setDescriptionD("Грушёвый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fù pén zi zhī");
        details.setDescriptionB("覆盆子汁");
        details.setDescriptionC("Raspberry juice");
        details.setDescriptionD("Малиновый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jú zi zhī");
        details.setDescriptionB("橘子汁");
        details.setDescriptionC("Tangerine juice");
        details.setDescriptionD("Мандариновый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hú luó bo zhī");
        details.setDescriptionB("胡萝卜汁");
        details.setDescriptionC("Carrot juice");
        details.setDescriptionD("Морковный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě yīng méi zhī ");
        details.setDescriptionB("野樱莓汁");
        details.setDescriptionC("Chokeberry juice ");
        details.setDescriptionD("Сок из черноплодной рябины ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi méi zhī");
        details.setDescriptionB("黑莓汁");
        details.setDescriptionC("Blackberry juice");
        details.setDescriptionD("Сок из ежевики");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiá guǒ zhī");
        details.setDescriptionB("荚果汁");
        details.setDescriptionC("Viburnum juice");
        details.setDescriptionD("Сок калины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí hóu táo zhī");
        details.setDescriptionB("猕猴桃汁");
        details.setDescriptionC("Kiwi juice");
        details.setDescriptionD("Сок из киви");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lú huì zhī");
        details.setDescriptionB("芦荟汁");
        details.setDescriptionC("Aloe juice");
        details.setDescriptionD("Сок алоэ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pú táo zhī");
        details.setDescriptionB("葡萄汁");
        details.setDescriptionC("Grape juice");
        details.setDescriptionD("Виноградный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng pú táo zhī ");
        details.setDescriptionB("红葡萄汁");
        details.setDescriptionC("Red grape juice");
        details.setDescriptionD("Виноградный сок (красный) ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táo zhī");
        details.setDescriptionB("桃汁");
        details.setDescriptionC("Peach juice");
        details.setDescriptionD("Персиковый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān méi zhī");
        details.setDescriptionB("酸梅汁");
        details.setDescriptionC("Plum juice");
        details.setDescriptionD("Сливовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān qié zhī");
        details.setDescriptionB("番茄汁");
        details.setDescriptionC("Tomato juice");
        details.setDescriptionD("Томатный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng guā zhī");
        details.setDescriptionB("黄瓜汁");
        details.setDescriptionC("Cucumber Juice");
        details.setDescriptionD("Огуречный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā jí guǒzhī");
        details.setDescriptionB("沙棘果汁");
        details.setDescriptionC("Sea buckthorn juice");
        details.setDescriptionD("Облепиховый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("màn yuè méi zhī");
        details.setDescriptionB("蔓越莓汁");
        details.setDescriptionC("Cranberry juice");
        details.setDescriptionD("Клюквенный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng zhī");
        details.setDescriptionB("柠檬汁");
        details.setDescriptionC("Lemon juice");
        details.setDescriptionD("Лимонный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng níng méng zhī");
        details.setDescriptionB("青柠檬汁");
        details.setDescriptionC("Lime juice");
        details.setDescriptionD("Сок лайма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qín cài zhī");
        details.setDescriptionB("芹菜汁");
        details.setDescriptionC("Celery juice");
        details.setDescriptionD("Сок сельдерея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián cài zhī");
        details.setDescriptionB("甜菜汁");
        details.setDescriptionC("Beet Juice");
        details.setDescriptionD("Свекольный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán guā zhī");
        details.setDescriptionB("南瓜汁");
        details.setDescriptionC("Pumpkin juice");
        details.setDescriptionD("Тыквенный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hùn hé xíng guǒ zhī");
        details.setDescriptionB("混合型果汁");
        details.setDescriptionC("Multifruit juice");
        details.setDescriptionD("Мультифруктовый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máng guǒ zhī");
        details.setDescriptionB("芒果汁");
        details.setDescriptionC("Mango juice");
        details.setDescriptionD("Сок манго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù guā zhī");
        details.setDescriptionB("木瓜汁");
        details.setDescriptionC("Papaya juice");
        details.setDescriptionD("Сок папайи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu táo zhī");
        details.setDescriptionB("油桃汁");
        details.setDescriptionC("Nectarine juice");
        details.setDescriptionD("Сок нектарина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián guā zhī");
        details.setDescriptionB("甜瓜汁");
        details.setDescriptionC("Melon juice");
        details.setDescriptionD("Сок дыни");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān shí liú zhī");
        details.setDescriptionB("番石榴汁");
        details.setDescriptionC("Guava juice");
        details.setDescriptionD("Сок гуавы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lán méi zhī");
        details.setDescriptionB("蓝莓汁");
        details.setDescriptionC("Blueberry juice");
        details.setDescriptionD("Черничный сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" píng guǒ zhī ");
        details.setDescriptionB("苹果汁");
        details.setDescriptionC(" Apple juice ");
        details.setDescriptionD(" Яблочный сок");
        detailsList.add(details);

        

    }
}
