package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C37 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("chuán shāo/ chuán zhāng yú ");
        details.setDescriptionB("船蛸/ 船章鱼");
        details.setDescriptionC(" Greater Argonaut ");
        details.setDescriptionD("Аргонавт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán lóng");
        details.setDescriptionB("蓝龙");
        details.setDescriptionC(" Blue dragon / Sea swallow ");
        details.setDescriptionD("Голубой дракон(Глаукус атлантический) ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí biē");
        details.setDescriptionB("石鳖");
        details.setDescriptionC("Chiton");
        details.setDescriptionD("Хитон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" quǎn é luó");
        details.setDescriptionB("犬峨螺");
        details.setDescriptionC("Dog whelk");
        details.setDescriptionD(" Красильная багрянка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wō niú ");
        details.setDescriptionB("蜗牛");
        details.setDescriptionC("Snail");
        details.setDescriptionD(" Виноградная улитка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jī xīn luó ");
        details.setDescriptionB("鸡心螺");
        details.setDescriptionC("Cone Snails ");
        details.setDescriptionD("Улитка Конус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiù kòu hǎi tù luó ");
        details.setDescriptionB("袖扣海兔螺");
        details.setDescriptionC("Flamingo Tongue Snail");
        details.setDescriptionD(" Язык фламинго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín jiǎo wō niú ");
        details.setDescriptionB("鳞脚蜗牛");
        details.setDescriptionC(" Scaly-foot Gastropod ");
        details.setDescriptionD("Железная улитка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wū zéi rú chóng");
        details.setDescriptionB("乌贼蠕虫");
        details.setDescriptionC(" Squidworm");
        details.setDescriptionD("Кальмарочервь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi tiān shǐ/luǒ hǎi dié ");
        details.setDescriptionB("海天使/裸海蝶");
        details.setDescriptionC("Sea Angel");
        details.setDescriptionD("Морской ангел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shēn hǎi guǎn shuǐ mǔ");
        details.setDescriptionB("深海管水母");
        details.setDescriptionC(" Siphonophore");
        details.setDescriptionD(" Сифонофора ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà wáng jù zú chóng ");
        details.setDescriptionB("大王具足虫");
        details.setDescriptionC("Giant Isopod");
        details.setDescriptionD("Гигантский изопод");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě rén xiè ");
        details.setDescriptionB("雪人蟹");
        details.setDescriptionC("Yeti Crab ");
        details.setDescriptionD(" Пушистая Кива /Краб Йети");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǔ yíng cǎo hǎi kuí ");
        details.setDescriptionB("捕蝇草海葵");
        details.setDescriptionC("Venus Flytrap Anemone ");
        details.setDescriptionD(" Актиния венерина мухоловка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("méi guī qiān shǒu luó");
        details.setDescriptionB("玫瑰千手螺");
        details.setDescriptionC(" Rose-branch Murex ");
        details.setDescriptionD(" Мурекс пальма-роза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi nà sī gǔ luó ");
        details.setDescriptionB("维纳斯骨螺");
        details.setDescriptionC(" Venus Comb Murex");
        details.setDescriptionD("(Украшенный мурекс)/ Гребень Венеры");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎo luó");
        details.setDescriptionB("宝螺");
        details.setDescriptionC("Сowry");
        details.setDescriptionD("Каури/Ципрея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuò yú ");
        details.setDescriptionB("蛞蝓");
        details.setDescriptionC(" Great Grey Slug ");
        details.setDescriptionD("Большой слизень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mào bèi ");
        details.setDescriptionB("帽贝");
        details.setDescriptionC("True limpets");
        details.setDescriptionD("Морское блюдечко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiān jiǎo jiāng yáo há ");
        details.setDescriptionB("尖角江珧蛤");
        details.setDescriptionC(" Noble pen shell ");
        details.setDescriptionD("Благородная пинна ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǔ lì/ háo ");
        details.setDescriptionB("牡蛎/ 蚝");
        details.setDescriptionC(" Oysters ");
        details.setDescriptionD("Устрицы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gé lí/ fēi lǜ bīn lián há ");
        details.setDescriptionB("蛤蜊/菲律宾帘蛤 ");
        details.setDescriptionC("Short Necked Clam ");
        details.setDescriptionD("Морской петушок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng hòu hǎi shàn há ");
        details.setDescriptionB("皇后海扇蛤");
        details.setDescriptionC(" Queen scallop");
        details.setDescriptionD("Морской гребешок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhēng zi ");
        details.setDescriptionB("蛏子");
        details.setDescriptionC("Pacific Razor Clam ");
        details.setDescriptionD("Морской черенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi sǔn ");
        details.setDescriptionB("海笋");
        details.setDescriptionC("  Common Piddock ");
        details.setDescriptionD("Камнеточец/ Морское сверло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàng bá bàng ");
        details.setDescriptionB("象拔蚌");
        details.setDescriptionC("Pacific Geoduck");
        details.setDescriptionD(" Гуидак  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí chēng ");
        details.setDescriptionB("石蛏");
        details.setDescriptionC("Date Mussels");
        details.setDescriptionD("Морской финик ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yí bèi ");
        details.setDescriptionB("贻贝");
        details.setDescriptionC(" Blue Mussel ");
        details.setDescriptionD("Мидия ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" běi tài píng yáng jù xíng zhāng yú ");
        details.setDescriptionB("北太平洋巨型章鱼");
        details.setDescriptionC(" Giant Pacific Octopus  ");
        details.setDescriptionD(" Гигантский осьминог ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò dǒu yú/ wū zéi ");
        details.setDescriptionB("墨斗鱼/乌贼");
        details.setDescriptionC(" Cuttlefish ");
        details.setDescriptionD("Каракатица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo fēi xiàng zhāng yú");
        details.setDescriptionB("小飞象章鱼");
        details.setDescriptionC("Dumbo Octopus ");
        details.setDescriptionD("Осьминог  гримпотевтис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhāng yú ");
        details.setDescriptionB("章鱼");
        details.setDescriptionC(" Octopus ");
        details.setDescriptionD("Осьминог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō lí zhāng yú");
        details.setDescriptionB("玻璃章鱼");
        details.setDescriptionC("Glass Octopus");
        details.setDescriptionD("Стеклянный осьминог ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dài zhuàng zǐ zhū yóu yú ");
        details.setDescriptionB("带状仔猪鱿鱼");
        details.setDescriptionC(" Piglet squid ");
        details.setDescriptionD("Кальмар-поросенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yú");
        details.setDescriptionB("鱿鱼");
        details.setDescriptionC(" Squid ");
        details.setDescriptionD("Кальмар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xī yáng ěr wū zéi");
        details.setDescriptionB("大西洋耳乌贼");
        details.setDescriptionC("Bobtail squid ");
        details.setDescriptionD("Сепиолид");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàng mó fān wū zéi ");
        details.setDescriptionB("相模帆乌贼");
        details.setDescriptionC("Jewelled Umbrella Squid ");
        details.setDescriptionD(" Кальмар \"Украшенный драгоценностями зонтик\"");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yíng huǒ yóu");
        details.setDescriptionB("萤火鱿");
        details.setDescriptionC(" Firefly Squid");
        details.setDescriptionD("Сверкающий кальмар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī xuè guǐ yóu yú ");
        details.setDescriptionB("吸血鬼鱿鱼");
        details.setDescriptionC("Vampire Squid");
        details.setDescriptionD("Адский кальмар-вампир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn zhū yīng wǔ luó ");
        details.setDescriptionB("珍珠鹦鹉螺");
        details.setDescriptionC(" Chambered nautilus");
        details.setDescriptionD("Наутилус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kù shì chē qú ");
        details.setDescriptionB("库氏砗磲 ");
        details.setDescriptionC("Giant Clam ");
        details.setDescriptionD(" Гигантская тридакна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("běi jì bèi ");
        details.setDescriptionB("北寄贝");
        details.setDescriptionC(" Surf Clam ");
        details.setDescriptionD("Сахалинская спизула/Песчанка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jìng shuǐ chuí shí luó");
        details.setDescriptionB("静水椎实螺");
        details.setDescriptionC(" Great Pond Snail");
        details.setDescriptionD("Большой прудовик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ wáng fèng huáng luó ");
        details.setDescriptionB("女王凤凰螺");
        details.setDescriptionC(" Queen Conch ");
        details.setDescriptionD("Гигантский стромбус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng guān luó");
        details.setDescriptionB("唐冠螺");
        details.setDescriptionC(" Horned Helmet ");
        details.setDescriptionD(" Рогатая шлемовидка  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi xīng");
        details.setDescriptionB("海星");
        details.setDescriptionC("Starfish");
        details.setDescriptionD(" Морская звезда ");
        detailsList.add(details);

    }
}
