package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C38 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" xìng táo rén yóu ");
        details.setDescriptionB("杏桃仁油");
        details.setDescriptionC("Apricot kernel oil");
        details.setDescriptionD(" Абрикосовое масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā shēng yóu ");
        details.setDescriptionB("花生油");
        details.setDescriptionC("Peanut oil");
        details.setDescriptionD("Арахисовое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó luò gē ā gān yóu");
        details.setDescriptionB("摩洛哥阿甘油");
        details.setDescriptionC("Argan oil");
        details.setDescriptionD("Аргановое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  jiè mò yóu ");
        details.setDescriptionB("芥末油");
        details.setDescriptionC("Mustard oil ");
        details.setDescriptionD("Горчичное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎi mù yóu/ xuě sōng yóu ");
        details.setDescriptionB("柏木油/ 雪松油");
        details.setDescriptionC("Cedar oil");
        details.setDescriptionD(" Кедровое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yē zǐ yóu");
        details.setDescriptionB("椰子油");
        details.setDescriptionC("Coconut oil");
        details.setDescriptionD("Кокосовое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù mǐ yóu");
        details.setDescriptionB("玉米油");
        details.setDescriptionC("Corn oil");
        details.setDescriptionD("Кукурузное масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhī ma yóu");
        details.setDescriptionB("芝麻油");
        details.setDescriptionC("Sesame oil");
        details.setDescriptionD("Кунжутное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yà má zǐ yóu");
        details.setDescriptionB("亚麻籽油");
        details.setDescriptionC("Linseed oil");
        details.setDescriptionD("Льняное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pú táo zǐ yóu");
        details.setDescriptionB("葡萄籽油");
        details.setDescriptionC("Grapeseed Oil");
        details.setDescriptionD("Масло виноградных косточек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hé táo yóu");
        details.setDescriptionB("核桃油");
        details.setDescriptionC("Walnut oil");
        details.setDescriptionD("Масло грецкого ореха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xìng rén yóu ");
        details.setDescriptionB("杏仁油");
        details.setDescriptionC("Almond oil");
        details.setDescriptionD("Миндальное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào zhōu jiān guǒ yóu");
        details.setDescriptionB("澳洲坚果油");
        details.setDescriptionC("Macadamia oil");
        details.setDescriptionD("Масло макадамии");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā jí yóu ");
        details.setDescriptionB("沙棘油 ");
        details.setDescriptionC("Seabuckthorn oil ");
        details.setDescriptionD("Облепиховое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn lǎn yóu ");
        details.setDescriptionB("橄榄油");
        details.setDescriptionC(" Olive oil ");
        details.setDescriptionD(" Оливковое масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zōng lǘ yóu ");
        details.setDescriptionB("棕榈油");
        details.setDescriptionC("Palm oil  ");
        details.setDescriptionD("Пальмовое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táo rén yóu");
        details.setDescriptionB("桃仁油");
        details.setDescriptionC("Peach kernel oil ");
        details.setDescriptionD("Персиковое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuí huā zǐ yóu ");
        details.setDescriptionB("葵花籽油");
        details.setDescriptionC(" Sunflower oil ");
        details.setDescriptionD("Подсолнечное масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiè huā yóu ");
        details.setDescriptionB("芥花油");
        details.setDescriptionC("Canola oil");
        details.setDescriptionD(" Рапсовое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà dòu yóu ");
        details.setDescriptionB("大豆油");
        details.setDescriptionC(" Soybean oil");
        details.setDescriptionD(" Соевое масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng lù yóu");
        details.setDescriptionB("松露油");
        details.setDescriptionC(" Truffle oil ");
        details.setDescriptionD("Трюфельное масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nán guā zǐ yóu ");
        details.setDescriptionB(" 南瓜籽油");
        details.setDescriptionC("Pumpkin seed oil");
        details.setDescriptionD(" Тыквенное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi xīn guǒ yóu");
        details.setDescriptionB("开心果油");
        details.setDescriptionC("Pistachio oil");
        details.setDescriptionD("Фисташковое масло ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mián zǐ yóu");
        details.setDescriptionB("棉籽油");
        details.setDescriptionC("Cottonseed oil");
        details.setDescriptionD("Хлопковое масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí wù yóu");
        details.setDescriptionB("植物油");
        details.setDescriptionC(" Vegetable oil");
        details.setDescriptionD(" Растительное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiáo hé yóu");
        details.setDescriptionB("调和油");
        details.setDescriptionC("Combined oil");
        details.setDescriptionD("Комбинированное масло ");
        detailsList.add(details);
        

    }
}
