package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C48 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("mù wū");
        details.setDescriptionB("木屋");
        details.setDescriptionC("Wooden house");
        details.setDescriptionD("Деревянный домик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng dèng");
        details.setDescriptionB("长凳");
        details.setDescriptionC("Bench");
        details.setDescriptionD("Скамейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎo dì");
        details.setDescriptionB("草地");
        details.setDescriptionC("Lawn");
        details.setDescriptionD("Лужайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā zi ");
        details.setDescriptionB("沙子");
        details.setDescriptionC("Sand");
        details.setDescriptionD("Песок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng huá tī ");
        details.setDescriptionB("儿童滑梯");
        details.setDescriptionC("Children's slide");
        details.setDescriptionD("Детская горка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān gàng");
        details.setDescriptionB("单杠");
        details.setDescriptionC("Horizontal bar");
        details.setDescriptionD("Турник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tī zi");
        details.setDescriptionB("梯子");
        details.setDescriptionC("Ladder");
        details.setDescriptionD("Лесенка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuán zhuǎn mù mǎ");
        details.setDescriptionB("旋转木马");
        details.setDescriptionC("Carousel");
        details.setDescriptionD("Карусель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiāo qiāo bǎn");
        details.setDescriptionB("跷跷板");
        details.setDescriptionC("See saw");
        details.setDescriptionD("Качеля-балансир ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiū qiān");
        details.setDescriptionB("秋千");
        details.setDescriptionC("Seesaw");
        details.setDescriptionD("Качеля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo yǐ zi ");
        details.setDescriptionB("小椅子");
        details.setDescriptionC(" Small chair ");
        details.setDescriptionD("Маленький стул");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáo mǎ");
        details.setDescriptionB("摇马");
        details.setDescriptionC("Rocking horse");
        details.setDescriptionD("Лошадка-качалка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān lún chē");
        details.setDescriptionB("三轮车");
        details.setDescriptionC("Tricycle");
        details.setDescriptionD("Трехколесный велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pí qiú ");
        details.setDescriptionB("皮球");
        details.setDescriptionC("Ball");
        details.setDescriptionD("Мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wán jù ");
        details.setDescriptionB("玩具");
        details.setDescriptionC("Toys");
        details.setDescriptionD("Игрушки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài dí xióng ");
        details.setDescriptionB("泰迪熊");
        details.setDescriptionC("Teddy bear ");
        details.setDescriptionD("Плюшевый медведь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wá wá ");
        details.setDescriptionB("娃娃");
        details.setDescriptionC("Doll");
        details.setDescriptionD("Кукла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē ");
        details.setDescriptionB(" 汽车");
        details.setDescriptionC("Car");
        details.setDescriptionD("Машинка");
        detailsList.add(details);
    }
}
