package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C5 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" huā shēng mǐ ");
        details.setDescriptionB("花生米");
        details.setDescriptionC(" Peanut ");
        details.setDescriptionD("Арахис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā xī lì /bā xī jiān guǒ ");
        details.setDescriptionB("巴西栗/巴西坚果");
        details.setDescriptionC("Brazil nut");
        details.setDescriptionD("Бразильский орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān máo jǔ jiān guǒ ");
        details.setDescriptionB("山毛榉坚果");
        details.setDescriptionC("Beech nut ");
        details.setDescriptionD("Буковый орех/Чинарик ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("líng jiǎo");
        details.setDescriptionB("菱角");
        details.setDescriptionC("Water caltrop");
        details.setDescriptionD("Водяной орех/ Чилим");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hé táo");
        details.setDescriptionB("核桃");
        details.setDescriptionC(" Walnut ");
        details.setDescriptionD("Грецкий орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàng zǐ");
        details.setDescriptionB("橡子");
        details.setDescriptionC("Acorn");
        details.setDescriptionD("Жёлудь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎn lì ");
        details.setDescriptionB("板栗");
        details.setDescriptionC(" Chestnut ");
        details.setDescriptionD("Каштан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sōng zǐ ");
        details.setDescriptionB("松子");
        details.setDescriptionC(" Pine nut ");
        details.setDescriptionD("Кедровый орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yāo guǒ");
        details.setDescriptionB("腰果");
        details.setDescriptionC(" Cashew ");
        details.setDescriptionD("Кешью");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  yē zi");
        details.setDescriptionB("椰子");
        details.setDescriptionC("Coconut ");
        details.setDescriptionD("Кокос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kē lā guǒ ");
        details.setDescriptionB("柯拉果");
        details.setDescriptionC("Kola nut");
        details.setDescriptionD("Орех кола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào zhōu jiān guǒ/ xià wēi yí guǒ ");
        details.setDescriptionB("澳洲坚果/夏威夷果");
        details.setDescriptionC("Macadamia nut");
        details.setDescriptionD(" Макадамия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā dàn mù   ");
        details.setDescriptionB("巴旦木");
        details.setDescriptionC("Almond");
        details.setDescriptionD("Миндаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ròu dòu kòu");
        details.setDescriptionB("肉豆蔻");
        details.setDescriptionC(" Nutmeg ");
        details.setDescriptionD("Мускатный орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  hú táo qiū");
        details.setDescriptionB("胡桃楸");
        details.setDescriptionC(" Manchurian walnut ");
        details.setDescriptionD("Орех маньчжурский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bì gēn guǒ/ měi zhōu shān hé táo ");
        details.setDescriptionB("碧根果/美洲山核桃");
        details.setDescriptionC("Pecan nut");
        details.setDescriptionD("Пекан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pī lì guǒ");
        details.setDescriptionB("霹雳果");
        details.setDescriptionC("Pili Nuts");
        details.setDescriptionD("Орех пили");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi yē zi");
        details.setDescriptionB("海椰子");
        details.setDescriptionC("Sea coconut");
        details.setDescriptionD("Сейшельский орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hùn hé jiān guǒ ");
        details.setDescriptionB("混合坚果");
        details.setDescriptionC("Mixed Nuts");
        details.setDescriptionD("Смесь орехов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiān táng jiān guǒ");
        details.setDescriptionB("天堂坚果");
        details.setDescriptionC("Paradise nut/  Sapucaia ");
        details.setDescriptionD("Райский орех ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi xīn guǒ ");
        details.setDescriptionB("开心果");
        details.setDescriptionC(" Pistachios");
        details.setDescriptionD("Фисташки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn zi / zhēn rén ");
        details.setDescriptionB("榛子/榛仁");
        details.setDescriptionC(" Hazelnut ");
        details.setDescriptionD("Фундук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi guó hēi hé táo");
        details.setDescriptionB("美国黑核桃");
        details.setDescriptionC(" American Black Walnut ");
        details.setDescriptionD(" Американский чёрный орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhì lì zhēn zi ");
        details.setDescriptionB("智利榛子");
        details.setDescriptionC("Chilean Hazelnut");
        details.setDescriptionD("Чилийский лесной орех");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu shā cǎo ");
        details.setDescriptionB("油莎草");
        details.setDescriptionC(" Chufa ");
        details.setDescriptionD("Чуфа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī guā zǐ");
        details.setDescriptionB("西瓜子");
        details.setDescriptionC(" Watermelon seeds  ");
        details.setDescriptionD("Семена арбуза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xìng rén ");
        details.setDescriptionB("杏仁");
        details.setDescriptionC("Apricot seeds");
        details.setDescriptionD("Ядро абрикосовых косточек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhī má ");
        details.setDescriptionB("芝麻");
        details.setDescriptionC(" Sesame seeds ");
        details.setDescriptionD("Семена кунжута");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi zhī má ");
        details.setDescriptionB("黑芝麻");
        details.setDescriptionC(" Black sesame seeds");
        details.setDescriptionD("Чёрный кунжут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yà má zǐ ");
        details.setDescriptionB("亚麻籽");
        details.setDescriptionC(" Flax seeds ");
        details.setDescriptionD("Семена льна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàng rì kuí zǐ");
        details.setDescriptionB("向日葵子");
        details.setDescriptionC(" Sunflower seeds ");
        details.setDescriptionD("Семечки подсолнечника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán guā zǐ");
        details.setDescriptionB("南瓜子");
        details.setDescriptionC("Pumpkin Seeds");
        details.setDescriptionD(" Семечки тыквенные ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qí yà zǐ");
        details.setDescriptionB("奇亚籽");
        details.setDescriptionC("Chia Seeds");
        details.setDescriptionD("Семена чиа");
        detailsList.add(details);
    }

}
