package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C50 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" hào mǎ");
        details.setDescriptionB("号码");
        details.setDescriptionC(" Number ");
        details.setDescriptionD("Номер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn huà ");
        details.setDescriptionB("电话");
        details.setDescriptionC("Phone");
        details.setDescriptionD("Телефон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn huà hào mǎ");
        details.setDescriptionB("电话号码");
        details.setDescriptionC(" Phone number ");
        details.setDescriptionD("Номер телефона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ de ");
        details.setDescriptionB("我的");
        details.setDescriptionC("My");
        details.setDescriptionD("Мой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǐ de");
        details.setDescriptionB("你的");
        details.setDescriptionC("Your");
        details.setDescriptionD("Твой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǐ de diàn huà hào mǎ shì duō shǎo ");
        details.setDescriptionB("你的电话号码是多少?");
        details.setDescriptionC(" What is your telephone number ?");
        details.setDescriptionD("Какой у тебя номер телефона?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ de diàn huà hào mǎ...");
        details.setDescriptionB("我的电话号码...");
        details.setDescriptionC("My phone number is ...");
        details.setDescriptionD("Мой номер телефона ...");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" líng ");
        details.setDescriptionB("零");
        details.setDescriptionC(" Zero ");
        details.setDescriptionD("Ноль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yī ");
        details.setDescriptionB("一");
        details.setDescriptionC("One ");
        details.setDescriptionD("Один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("èr");
        details.setDescriptionB("二");
        details.setDescriptionC("Two");
        details.setDescriptionD("Два");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān");
        details.setDescriptionB("三");
        details.setDescriptionC(" Three ");
        details.setDescriptionD("Три");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sì");
        details.setDescriptionB("四");
        details.setDescriptionC(" Four ");
        details.setDescriptionD("Четыре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ");
        details.setDescriptionB("五");
        details.setDescriptionC(" Five");
        details.setDescriptionD("Пять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liù ");
        details.setDescriptionB("六");
        details.setDescriptionC("Six");
        details.setDescriptionD("Шесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qī ");
        details.setDescriptionB("七");
        details.setDescriptionC("Seven");
        details.setDescriptionD("Семь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā ");
        details.setDescriptionB("八");
        details.setDescriptionC(" Eight ");
        details.setDescriptionD("Восемь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǔ ");
        details.setDescriptionB("九");
        details.setDescriptionC(" Nine ");
        details.setDescriptionD("Девять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí");
        details.setDescriptionB("十");
        details.setDescriptionC("Ten");
        details.setDescriptionD("Десять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎ diàn huà ");
        details.setDescriptionB("打电话");
        details.setDescriptionC("Call");
        details.setDescriptionD("Звонить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lái diàn");
        details.setDescriptionB("来电");
        details.setDescriptionC("Incoming call");
        details.setDescriptionD("Входящий вызов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō chū diàn huà");
        details.setDescriptionB("拨出电话");
        details.setDescriptionC("Outgoing call");
        details.setDescriptionD("Исходящий вызов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú xiàn shàng wǎng");
        details.setDescriptionB("无线上网");
        details.setDescriptionC("Wi-Fi");
        details.setDescriptionD("Вай фай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mì mǎ ");
        details.setDescriptionB("密码");
        details.setDescriptionC("Pin-code");
        details.setDescriptionD("Пин-код");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiě duǎn xìn");
        details.setDescriptionB("写短信");
        details.setDescriptionC("Write message");
        details.setDescriptionD("Писать смс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pāi zhào");
        details.setDescriptionB("拍照");
        details.setDescriptionC("Take photo");
        details.setDescriptionD("Фотографировать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì pāi");
        details.setDescriptionB("自拍");
        details.setDescriptionC("Selfie");
        details.setDescriptionD("Селфи");
        detailsList.add(details);
    }
}
