package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C6 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("yùn dòng ");
        details.setDescriptionB("运动");
        details.setDescriptionC("Sport");
        details.setDescriptionD("Спорт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiàn kāng");
        details.setDescriptionB("健康");
        details.setDescriptionC("Health");
        details.setDescriptionD("Здоровье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ cāo");
        details.setDescriptionB("体操");
        details.setDescriptionC("Gymnastics");
        details.setDescriptionD("Гимнастика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng yuán");
        details.setDescriptionB("运动员");
        details.setDescriptionC("Sportsman");
        details.setDescriptionD("Спортсмен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ yù chǎng");
        details.setDescriptionB("体育场");
        details.setDescriptionC("Stadium");
        details.setDescriptionD("Стадион");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǐ sài");
        details.setDescriptionB("比赛");
        details.setDescriptionC("Competition ");
        details.setDescriptionD("Состязание/Матч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào gāo");
        details.setDescriptionB("跳高");
        details.setDescriptionC("High jump");
        details.setDescriptionD("Прыжок в высоту");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào yuǎn");
        details.setDescriptionB("跳远");
        details.setDescriptionC("Standing long jump");
        details.setDescriptionD("Прыжок в длину");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiào shuǐ ");
        details.setDescriptionB("跳水");
        details.setDescriptionC(" Diving ");
        details.setDescriptionD("Прыжки в воду");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bèng chuáng ");
        details.setDescriptionB("蹦床");
        details.setDescriptionC("Trampoline");
        details.setDescriptionD("Прыжки на батуте");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài pǎo");
        details.setDescriptionB("赛跑");
        details.setDescriptionC("Running");
        details.setDescriptionD("Бег");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǎo bù");
        details.setDescriptionB("跑步");
        details.setDescriptionC("Jogging");
        details.setDescriptionD("Делать пробежку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ lā sōng ");
        details.setDescriptionB("马拉松");
        details.setDescriptionC("Marathon");
        details.setDescriptionD("Марафон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zìxíngchē bǐsài");
        details.setDescriptionB("自行车比赛");
        details.setDescriptionC("Bicycle race");
        details.setDescriptionD("Велогонка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì shù tǐ cāo");
        details.setDescriptionB("艺术体操");
        details.setDescriptionC(" Rhythmic  Gymnastics ");
        details.setDescriptionD("Художественная гимнастика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì yóu tǐ cāo");
        details.setDescriptionB("自由体操");
        details.setDescriptionC("Floor exercise");
        details.setDescriptionD("Вольные упражнения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng héng mù");
        details.setDescriptionB("平衡木");
        details.setDescriptionC("Balance beam");
        details.setDescriptionD("Бревно (гимнастика)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo dī gàng");
        details.setDescriptionB("高低杠");
        details.setDescriptionC("Uneven bars");
        details.setDescriptionD("Разновысокие брусья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào mǎ");
        details.setDescriptionB("跳马");
        details.setDescriptionC("Horse-Vaulting");
        details.setDescriptionD("Конь для опорных прыжков");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān mǎ ");
        details.setDescriptionB("鞍马");
        details.setDescriptionC("Pommel Horse ");
        details.setDescriptionD(" Конь гимнастический ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān gàng");
        details.setDescriptionB("单杠");
        details.setDescriptionC("Horizontal bar");
        details.setDescriptionD("Перекладина /Турник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng gàng");
        details.setDescriptionB("双杠");
        details.setDescriptionC("Parallel bars");
        details.setDescriptionD("Параллельные брусья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diào huán");
        details.setDescriptionB("吊环");
        details.setDescriptionC("Still rings");
        details.setDescriptionD("Кольца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qí mǎ ");
        details.setDescriptionB("骑马");
        details.setDescriptionC(" Horse riding ");
        details.setDescriptionD("Верховая езда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài mǎ");
        details.setDescriptionB("赛马");
        details.setDescriptionC("Horse racing");
        details.setDescriptionD("Скачки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ qiú ");
        details.setDescriptionB("马球");
        details.setDescriptionC("Polo");
        details.setDescriptionD("Поло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pái qiú");
        details.setDescriptionB("排球");
        details.setDescriptionC("Volleyball");
        details.setDescriptionD("Волейбол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā tān pái qiú ");
        details.setDescriptionB("沙滩排球");
        details.setDescriptionC("Beach volleyball");
        details.setDescriptionD("Пляжный волейбол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ lán qiú");
        details.setDescriptionB("打篮球");
        details.setDescriptionC("Play basketball");
        details.setDescriptionD("Баскетбол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lán qiú ");
        details.setDescriptionB("篮球");
        details.setDescriptionC("Basketball");
        details.setDescriptionD("Баскетбольный мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tī zú qiú");
        details.setDescriptionB("踢足球");
        details.setDescriptionC("Play football ");
        details.setDescriptionD("Играть в футбол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zú qiú ");
        details.setDescriptionB("足球");
        details.setDescriptionC(" Soccer-ball ");
        details.setDescriptionD("Футбольный мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiú");
        details.setDescriptionB("球");
        details.setDescriptionC("Ball");
        details.setDescriptionD("Мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎ pīng pāng qiú");
        details.setDescriptionB("打乒乓球");
        details.setDescriptionC(" Table tennis/Ping-pong ");
        details.setDescriptionD("Пинг-понг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pīng pāng qiú tái");
        details.setDescriptionB("乒乓球台");
        details.setDescriptionC("Ping-pong table");
        details.setDescriptionD("Стол для настольного тенниса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pīng pāng qiú");
        details.setDescriptionB("乒乓球");
        details.setDescriptionC("Table tennis ball");
        details.setDescriptionD("Мяч для пинг-понга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pīng pāng qiú pāi");
        details.setDescriptionB("乒乓球拍");
        details.setDescriptionC("Table tennis racket");
        details.setDescriptionD("Ракетка для настольного тенниса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ yǔ máo qiú");
        details.setDescriptionB("打羽毛球");
        details.setDescriptionC("Badminton");
        details.setDescriptionD("Бадминтон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ máo qiú");
        details.setDescriptionB("羽毛球");
        details.setDescriptionC("Badminton Shuttlecock");
        details.setDescriptionD("Волан для бадминтона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ máo qiú pāi");
        details.setDescriptionB("羽毛球拍");
        details.setDescriptionC("Badminton racket");
        details.setDescriptionD("Ракетка для бадминтона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ wǎng qiú");
        details.setDescriptionB("打网球");
        details.setDescriptionC("Tennis");
        details.setDescriptionD("Теннис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎng qiú");
        details.setDescriptionB("网球");
        details.setDescriptionC("Tennis ball");
        details.setDescriptionD("Теннисный мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎng qiú pāi");
        details.setDescriptionB("网球拍");
        details.setDescriptionC("Tennis racket ");
        details.setDescriptionD("Теннисная ракетка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo ěr fū qiú ");
        details.setDescriptionB("高尔夫球");
        details.setDescriptionC("Golf");
        details.setDescriptionD("Гольф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shè jī ");
        details.setDescriptionB("射击");
        details.setDescriptionC("Shooting");
        details.setDescriptionD("Стрельба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn lǎn qiú");
        details.setDescriptionB("橄榄球");
        details.setDescriptionC("Rugby");
        details.setDescriptionD("Регби");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi shì gǎn lǎn qiú");
        details.setDescriptionB("美式橄榄球");
        details.setDescriptionC("American football ");
        details.setDescriptionD("Американский футбол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu qiú");
        details.setDescriptionB("手球");
        details.setDescriptionC(" Handball ");
        details.setDescriptionD("Гандбол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiān qiú");
        details.setDescriptionB("铅球");
        details.setDescriptionC("Shot put");
        details.setDescriptionD("Толкание ядра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qū gùn qiú");
        details.setDescriptionB("曲棍球");
        details.setDescriptionC("Field Hockey ");
        details.setDescriptionD("Хоккей на траве");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tài jí quán");
        details.setDescriptionB("太极拳");
        details.setDescriptionC(" Tai ji quan / Tai chi");
        details.setDescriptionD("Гимнастика Тайцзицюань ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng fū");
        details.setDescriptionB("功夫");
        details.setDescriptionC("Kung Fu");
        details.setDescriptionD("Кунг-фу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("róu dào");
        details.setDescriptionB("柔道");
        details.setDescriptionC("Judo");
        details.setDescriptionD("Дзюдо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāi jiāo ");
        details.setDescriptionB("摔跤");
        details.setDescriptionC(" Wrestling ");
        details.setDescriptionD("Борьба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì yóu shì shuāi jiāo");
        details.setDescriptionB("自由式摔跤");
        details.setDescriptionC(" Wrestling Freestyle");
        details.setDescriptionD("Вольная борьба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǔ diǎn shì shuāi jiāo ");
        details.setDescriptionB("古典式摔跤");
        details.setDescriptionC("Greco-Roman wrestling");
        details.setDescriptionD("Греко-римская борьба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tái quán dào");
        details.setDescriptionB("跆拳道");
        details.setDescriptionC("Taekwondo");
        details.setDescriptionD("Тэквандо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("quán jí");
        details.setDescriptionB("拳击");
        details.setDescriptionC("Boxing");
        details.setDescriptionD("Бокс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jǔ zhòng ");
        details.setDescriptionB("举重");
        details.setDescriptionC("Weightlifting ");
        details.setDescriptionD("Тяжёлая атлетика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lún huá");
        details.setDescriptionB("轮滑");
        details.setDescriptionC("Roller skating");
        details.setDescriptionD(" Катание на роликах");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá bǎn yùn dòng ");
        details.setDescriptionB("滑板运动");
        details.setDescriptionC("Skateboarding ");
        details.setDescriptionD("Скейтбординг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ shàng yùn dòng");
        details.setDescriptionB("水上运动");
        details.setDescriptionC("Water sport");
        details.setDescriptionD("Водный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ");
        details.setDescriptionB(" shuǐ shàng fēi xíng ");
        details.setDescriptionC("水上飞行");
        details.setDescriptionD("Flyboarding");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān chuán ");
        details.setDescriptionB("帆船");
        details.setDescriptionC("Sailing");
        details.setDescriptionD("Парусный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí huá tǐng");
        details.setDescriptionB("皮划艇");
        details.setDescriptionC(" Canoeing and Kayaking");
        details.setDescriptionD(" Гребля на байдарках и каноэ ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài tǐng ");
        details.setDescriptionB("赛艇");
        details.setDescriptionC(" Rowing");
        details.setDescriptionD("Гребля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu yǒng");
        details.setDescriptionB("游泳");
        details.setDescriptionC("Swimming");
        details.setDescriptionD("Плавание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wā yǒng");
        details.setDescriptionB("蛙泳");
        details.setDescriptionC("Breaststroke");
        details.setDescriptionD("Брасс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ lā sōng yóu yǒng");
        details.setDescriptionB("马拉松游泳");
        details.setDescriptionC("Marathon swimming");
        details.setDescriptionD("Марафонское плавание ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ qiú");
        details.setDescriptionB("水球");
        details.setDescriptionC("Water polo ");
        details.setDescriptionD("Водное поло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā yàng yóu yǒng");
        details.setDescriptionB("花样游泳");
        details.setDescriptionC("Synchronised swimming");
        details.setDescriptionD("Синхронное плавание ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá shuǐ");
        details.setDescriptionB("滑水");
        details.setDescriptionC("Water skiing");
        details.setDescriptionD("Водные лыжи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wěi bō huá shuǐ");
        details.setDescriptionB("尾波滑水");
        details.setDescriptionC(" Wakeboarding ");
        details.setDescriptionD("Вейкбординг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎng bǎn chōng làng ");
        details.setDescriptionB("桨板冲浪");
        details.setDescriptionC("Paddle boarding");
        details.setDescriptionD("Падлбординг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chōng làng");
        details.setDescriptionB("冲浪");
        details.setDescriptionC("Surfing ");
        details.setDescriptionD("Сёрфинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng zhēng chōng làng");
        details.setDescriptionB("风筝冲浪");
        details.setDescriptionC(" Kitesurfing ");
        details.setDescriptionD("Кайтсёрфинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiǎn shuǐ chōng làng");
        details.setDescriptionB("浅水冲浪");
        details.setDescriptionC("Skimboarding ");
        details.setDescriptionD("Скимбординг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuán yá tiào shuǐ");
        details.setDescriptionB("悬崖跳水");
        details.setDescriptionC(" Cliff diving ");
        details.setDescriptionD("Клифф-дайвинг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qián shuǐ  ");
        details.setDescriptionB("潜水");
        details.setDescriptionC("Diving");
        details.setDescriptionD("Дайвинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì yóu qián shuǐ");
        details.setDescriptionB("自由潜水");
        details.setDescriptionC(" Free diving ");
        details.setDescriptionD("Фридайвинг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" piāo liú");
        details.setDescriptionB("飘流");
        details.setDescriptionC("Rafting");
        details.setDescriptionD("Рафтинг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí huá tǐng  ");
        details.setDescriptionB("皮划艇");
        details.setDescriptionC("Kayaking");
        details.setDescriptionD(" Каякинг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó tuō tǐng yùn dòng");
        details.setDescriptionB("摩托艇运动");
        details.setDescriptionC("Motorboat sport");
        details.setDescriptionD("Водно-моторный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn dài dōng jì liǎng xiàng");
        details.setDescriptionB("现代冬季两项");
        details.setDescriptionC("Biathlon");
        details.setDescriptionD(" Биатлон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīng hú");
        details.setDescriptionB("冰壶");
        details.setDescriptionC("Curling ");
        details.setDescriptionD("Кёрлинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīng qiú");
        details.setDescriptionB("冰球");
        details.setDescriptionC("Ice hockey");
        details.setDescriptionD("Хоккей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě qiāo");
        details.setDescriptionB("雪橇");
        details.setDescriptionC("Sled");
        details.setDescriptionD(" Cанный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě qiāo ");
        details.setDescriptionB("雪橇");
        details.setDescriptionC(" Bobsleigh/ Bobsled  ");
        details.setDescriptionD(" Бобслей ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú duò xuě qiāo");
        details.setDescriptionB("无舵雪橇 ");
        details.setDescriptionC("Luge ");
        details.setDescriptionD("Тобогган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāng jià xuě chē ");
        details.setDescriptionB("钢架雪车");
        details.setDescriptionC(" Skeleton");
        details.setDescriptionD(" Скелетон ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā yàng huá bīng ");
        details.setDescriptionB("花样滑冰");
        details.setDescriptionC("Figure skating");
        details.setDescriptionD("Фигурное катание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sù dù huá bīng");
        details.setDescriptionB("速度滑冰");
        details.setDescriptionC(" Speed skating ");
        details.setDescriptionD("Конькобежный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào tái huá xuě ");
        details.setDescriptionB("跳台滑雪");
        details.setDescriptionC("Ski jumping");
        details.setDescriptionD(" Прыжки на лыжах с трамплина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá xuě ");
        details.setDescriptionB("滑雪 ");
        details.setDescriptionC("Skiing");
        details.setDescriptionD("Лыжный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān bǎn huá xuě ");
        details.setDescriptionB("单板滑雪");
        details.setDescriptionC(" Snowboarding ");
        details.setDescriptionD("Сноубординг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī  jiàn");
        details.setDescriptionB("击剑");
        details.setDescriptionC("Fencing");
        details.setDescriptionD("Фехтование");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā jiàn");
        details.setDescriptionB("花剑");
        details.setDescriptionC("Fencing foil");
        details.setDescriptionD("Рапира");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhòng jiàn");
        details.setDescriptionB("重剑");
        details.setDescriptionC("Court sword");
        details.setDescriptionD("Шпага");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàn shēn");
        details.setDescriptionB("健身");
        details.setDescriptionC("Fitness");
        details.setDescriptionD("Фитнес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎng bēi");
        details.setDescriptionB("奖杯");
        details.setDescriptionC(" Trophy ");
        details.setDescriptionD(" Кубок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn pái");
        details.setDescriptionB("金牌");
        details.setDescriptionC("Golden medal");
        details.setDescriptionD("Золотая медаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín pái");
        details.setDescriptionB("银牌");
        details.setDescriptionC("Silver medal");
        details.setDescriptionD("Серебряная медаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóng pái");
        details.setDescriptionB("铜牌");
        details.setDescriptionC("Bronze medal");
        details.setDescriptionD("Бронзовая медаль");
        detailsList.add(details);

    }

}
