package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C60 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("lú huì");
        details.setDescriptionB("芦荟");
        details.setDescriptionC("Aloe");
        details.setDescriptionD("Алоэ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ wǎn huā");
        details.setDescriptionB("紫菀花");
        details.setDescriptionC("Aster");
        details.setDescriptionD("Астра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān sè jǐn");
        details.setDescriptionB("三色堇");
        details.setDescriptionC("Pansy");
        details.setDescriptionD("Анютины глазки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǐ chē jú ");
        details.setDescriptionB("矢车菊");
        details.setDescriptionC("Cornflower ");
        details.setDescriptionD("Василёк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiū hǎi táng");
        details.setDescriptionB("秋海棠");
        details.setDescriptionC("Begonia");
        details.setDescriptionD("Бегония");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dīng xiāng ");
        details.setDescriptionB("丁香");
        details.setDescriptionC(" Сarnation ");
        details.setDescriptionD("Гвоздика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà lì huā");
        details.setDescriptionB("大丽花");
        details.setDescriptionC("Dahlia");
        details.setDescriptionD("Георгин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiān zhú kuí");
        details.setDescriptionB("天竺葵");
        details.setDescriptionC("Geranium");
        details.setDescriptionD("Герань");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táng chāng pú/jiàn lán");
        details.setDescriptionB("唐菖蒲/剑兰");
        details.setDescriptionC("Gladiolus");
        details.setDescriptionD("Гладиолус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng xìn zǐ");
        details.setDescriptionB("风信子");
        details.setDescriptionC("Hyacinth");
        details.setDescriptionD("Гиацинт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiù qiú huā");
        details.setDescriptionB("绣球花");
        details.setDescriptionC("Hydrangea");
        details.setDescriptionD("Гортензия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò lì huā");
        details.setDescriptionB("茉莉花");
        details.setDescriptionC("Jasmine");
        details.setDescriptionD("Жасмин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuān wě");
        details.setDescriptionB("鸢尾");
        details.setDescriptionC("Iris");
        details.setDescriptionD("Ирис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tí lián");
        details.setDescriptionB("马蹄莲");
        details.setDescriptionC("Calla");
        details.setDescriptionD("Калла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiān rén zhǎng");
        details.setDescriptionB("仙人掌");
        details.setDescriptionC("Cactus");
        details.setDescriptionD("Кактус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng líng cǎo");
        details.setDescriptionB("风铃草");
        details.setDescriptionC("Bluebell");
        details.setDescriptionD("Колокольчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān yè cǎo ");
        details.setDescriptionB("三叶草");
        details.setDescriptionC("Shamrock");
        details.setDescriptionD("Клевер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān hóng huā ");
        details.setDescriptionB("番红花");
        details.setDescriptionC("Crocus ");
        details.setDescriptionD("Крокус/ Шафран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" líng lán ");
        details.setDescriptionB("铃兰 ");
        details.setDescriptionC("Lily of the valley ");
        details.setDescriptionD("Ландыш");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xūn yī cǎo");
        details.setDescriptionB("薰衣草");
        details.setDescriptionC("Lavender ");
        details.setDescriptionD("Лаванда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎi hé ");
        details.setDescriptionB("百合");
        details.setDescriptionC("Lily");
        details.setDescriptionD("Лилия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hé huā");
        details.setDescriptionB("荷花");
        details.setDescriptionC("Lotus");
        details.setDescriptionD("Лотос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng sù huā");
        details.setDescriptionB("罂粟花");
        details.setDescriptionC("Poppy");
        details.setDescriptionD("Мак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài xī");
        details.setDescriptionB("黛西");
        details.setDescriptionC("Daisy");
        details.setDescriptionD("Маргаритка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn hé huān ");
        details.setDescriptionB("金合欢");
        details.setDescriptionC("Sweet Acacia ");
        details.setDescriptionD("Мимоза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ xiān");
        details.setDescriptionB("水仙");
        details.setDescriptionC("Daffodil");
        details.setDescriptionD("Нарцисс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wù wàng wǒ");
        details.setDescriptionB("勿忘我");
        details.setDescriptionC("Forget-me-not");
        details.setDescriptionD("Незабудка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pú gōng yīng");
        details.setDescriptionB("蒲公英");
        details.setDescriptionC("Dandelion");
        details.setDescriptionD("Одуванчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lán huā");
        details.setDescriptionB("兰花");
        details.setDescriptionC("Orchid");
        details.setDescriptionD("Орхидея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jué lèi");
        details.setDescriptionB("蕨类");
        details.setDescriptionC("Fern");
        details.setDescriptionD("Папоротник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ dān huā");
        details.setDescriptionB("牡丹花");
        details.setDescriptionC("Peony");
        details.setDescriptionD("Пион");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuí huā");
        details.setDescriptionB("葵花");
        details.setDescriptionC("Sunflower");
        details.setDescriptionD("Подсолнух");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě huā lián");
        details.setDescriptionB("雪花莲");
        details.setDescriptionC("Snowdrop");
        details.setDescriptionD("Подснежник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("méiguī");
        details.setDescriptionB("玫瑰");
        details.setDescriptionC("Rose");
        details.setDescriptionD("Роза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng gān jú");
        details.setDescriptionB("洋甘菊");
        details.setDescriptionC("Сamomile");
        details.setDescriptionD("Ромашка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ dīng xiāng");
        details.setDescriptionB("紫丁香");
        details.setDescriptionC("Lilac");
        details.setDescriptionD("Сирень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù jīn xiāng");
        details.setDescriptionB("郁金香");
        details.setDescriptionC("Tulip");
        details.setDescriptionD("Тюльпан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ luó lán");
        details.setDescriptionB("紫罗兰");
        details.setDescriptionC("Viola");
        details.setDescriptionD("Фиалка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jú huā");
        details.setDescriptionB("菊花");
        details.setDescriptionC("Golden-daisy");
        details.setDescriptionD("Хризантема");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("méi huā");
        details.setDescriptionB("梅花");
        details.setDescriptionC(" Plum flower");
        details.setDescriptionD("Цветы японской сливы");
        detailsList.add(details);
    }
}
