package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C63 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);

    }
}
