package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C64 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" bái huà/huà shù ");
        details.setDescriptionB("白桦/桦树");
        details.setDescriptionC(" Birch  ");
        details.setDescriptionD("Берёза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān máo jǔ ");
        details.setDescriptionB("山毛榉");
        details.setDescriptionC(" Beech ");
        details.setDescriptionD("Бук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú shù ");
        details.setDescriptionB("榆树");
        details.setDescriptionC(" Elm  ");
        details.setDescriptionD("Вяз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàng shù ");
        details.setDescriptionB("橡树");
        details.setDescriptionC(" Oak ");
        details.setDescriptionD("Дуб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yún shān ");
        details.setDescriptionB("云杉");
        details.setDescriptionC("Christmas tree ");
        details.setDescriptionD("Ель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liǔ shù ");
        details.setDescriptionB("柳树");
        details.setDescriptionC(" Willow ");
        details.setDescriptionD("Ива");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wú huā guǒ shù ");
        details.setDescriptionB("无花果树");
        details.setDescriptionC("Fig tree");
        details.setDescriptionD("Инжир/Фиговое дерево ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lì zǐ shù ");
        details.setDescriptionB("栗子树");
        details.setDescriptionC("Chestnut tree ");
        details.setDescriptionD("Каштан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě sōng ");
        details.setDescriptionB("雪松");
        details.setDescriptionC("Cedar");
        details.setDescriptionD("Кедр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎi shù ");
        details.setDescriptionB("柏树");
        details.setDescriptionC(" Cypress ");
        details.setDescriptionD("Кипарис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng shù ");
        details.setDescriptionB("枫树");
        details.setDescriptionC("Maple ");
        details.setDescriptionD("Клён");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duàn shù ");
        details.setDescriptionB("椴树");
        details.setDescriptionC("Linden");
        details.setDescriptionD("Липа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luò yè sōng");
        details.setDescriptionB("落叶松");
        details.setDescriptionC("Larch");
        details.setDescriptionD("Лиственница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bó lì yǎ luò yè sōng");
        details.setDescriptionB("西伯利亚落叶松");
        details.setDescriptionC("Siberian larch ");
        details.setDescriptionD(" Лиственница сибирская");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn lǎn shù ");
        details.setDescriptionB("橄榄树");
        details.setDescriptionC(" Olive tree ");
        details.setDescriptionD("Маслина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù lán");
        details.setDescriptionB("木兰");
        details.setDescriptionC("Magnolia");
        details.setDescriptionD("Магнолия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī qī mù ");
        details.setDescriptionB("灰桤木");
        details.setDescriptionC("Alder ");
        details.setDescriptionD("Ольха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ā sī péng");
        details.setDescriptionB("阿斯彭");
        details.setDescriptionC("Aspen tree");
        details.setDescriptionD("Осина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zōng lǘ/ zōng shù ");
        details.setDescriptionB("棕榈/棕树");
        details.setDescriptionC("Palm  tree");
        details.setDescriptionD("Пальма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lěng shān ");
        details.setDescriptionB("冷杉");
        details.setDescriptionC("Fir tree");
        details.setDescriptionD("Пихта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ dīng xiāng");
        details.setDescriptionB("紫丁香");
        details.setDescriptionC(" Lilac  ");
        details.setDescriptionD("Сирень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǐ zǐ shù ");
        details.setDescriptionB("李子树");
        details.setDescriptionC("Plum tree ");
        details.setDescriptionD("Слива");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng shù ");
        details.setDescriptionB("松树");
        details.setDescriptionC(" Pine tree ");
        details.setDescriptionD("Сосна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yáng shù ");
        details.setDescriptionB("杨树");
        details.setDescriptionC("Poplar/Сottonwood");
        details.setDescriptionD("Тополь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān shù");
        details.setDescriptionB("桉树");
        details.setDescriptionC("Eucalyptus ");
        details.setDescriptionD("Эвкалипт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái là shù");
        details.setDescriptionB("白蜡树");
        details.setDescriptionC("Ash  ");
        details.setDescriptionD("Ясень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù zhī ");
        details.setDescriptionB("树枝");
        details.setDescriptionC("Branch");
        details.setDescriptionD("Ветка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù cái");
        details.setDescriptionB("木材");
        details.setDescriptionC("Wood");
        details.setDescriptionD("Древесина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù zhōng kōng ");
        details.setDescriptionB("树中空");
        details.setDescriptionC("Hollow");
        details.setDescriptionD("Дупло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù zhēn ");
        details.setDescriptionB("树针");
        details.setDescriptionC("Needle");
        details.setDescriptionD("Иголка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù pí ");
        details.setDescriptionB("树皮");
        details.setDescriptionC("Bark");
        details.setDescriptionD("Кора");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù gēn ");
        details.setDescriptionB("树根");
        details.setDescriptionC("Root");
        details.setDescriptionD("Корень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù guān");
        details.setDescriptionB("树冠");
        details.setDescriptionC("Crown of tree");
        details.setDescriptionD("Крона дерева");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yè zi ");
        details.setDescriptionB("叶子");
        details.setDescriptionC("Leaf");
        details.setDescriptionD("Лист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yá ");
        details.setDescriptionB("芽");
        details.setDescriptionC("Bud");
        details.setDescriptionD("Почка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù zhuāng ");
        details.setDescriptionB("树桩");
        details.setDescriptionC("Stump");
        details.setDescriptionD("Пень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù gàn ");
        details.setDescriptionB("树干");
        details.setDescriptionC("Trunk");
        details.setDescriptionD("Ствол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sōng tǎ/sōng guǒ ");
        details.setDescriptionB("松塔/松果");
        details.setDescriptionC("Pinecone");
        details.setDescriptionD("Шишка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng lín");
        details.setDescriptionB("松林");
        details.setDescriptionC("Pine forest");
        details.setDescriptionD("Бор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cóng lín ");
        details.setDescriptionB("丛林");
        details.setDescriptionC("Jungle");
        details.setDescriptionD("Джунгли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sēn lín");
        details.setDescriptionB("森林");
        details.setDescriptionC("Forest");
        details.setDescriptionD("Лес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài jiā lín ");
        details.setDescriptionB("泰加林");
        details.setDescriptionC("Taiga Forest ");
        details.setDescriptionD("Тайга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòng yuán/ tái yuán ");
        details.setDescriptionB("冻原/苔原");
        details.setDescriptionC("Tundra");
        details.setDescriptionD("Тундра");
        detailsList.add(details);
    }
}
