package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C66 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" báo jiān bǐng ");
        details.setDescriptionB("薄煎饼");
        details.setDescriptionC("Pancake ");
        details.setDescriptionD("Блин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng jiāo chuán ");
        details.setDescriptionB("香蕉船");
        details.setDescriptionC("Banana split ");
        details.setDescriptionD(" Банана-сплит/Мороженое с бананом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yìng miàn bāo quān ");
        details.setDescriptionB("硬面包圈");
        details.setDescriptionC("Bagel");
        details.setDescriptionD("Бублик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wēi huà bǐng ");
        details.setDescriptionB("威化饼");
        details.setDescriptionC("Waffles");
        details.setDescriptionD("Вафли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng táo pài ");
        details.setDescriptionB("樱桃派");
        details.setDescriptionC(" Cherry pie ");
        details.setDescriptionD("Вишнёвый пирог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo miàn bāo ");
        details.setDescriptionB("小面包");
        details.setDescriptionC("Bun ");
        details.setDescriptionD("Cдобная булочка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎi yóu ");
        details.setDescriptionB("奶油");
        details.setDescriptionC("Cream");
        details.setDescriptionD("Крем-сливки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ jiàng ");
        details.setDescriptionB("果酱");
        details.setDescriptionC("Jam ");
        details.setDescriptionD("Джем/ Варенье  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ dòng ");
        details.setDescriptionB("果冻");
        details.setDescriptionC("Jelly ");
        details.setDescriptionD(" Желе ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bàng  bàng táng ");
        details.setDescriptionB("棒棒糖");
        details.setDescriptionC("Lollipop ");
        details.setDescriptionD("Леденец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎo píng guǒ ");
        details.setDescriptionB("烤苹果");
        details.setDescriptionC("Baked apple");
        details.setDescriptionD(" Запеченное яблоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mián huā ruǎn táng");
        details.setDescriptionB("棉花软糖");
        details.setDescriptionC("Marshmallow ");
        details.setDescriptionD("Зефир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāng bǐng ");
        details.setDescriptionB("姜饼");
        details.setDescriptionC("Gingerbread ");
        details.setDescriptionD("Имбирный пряник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán méi sōng bǐng ");
        details.setDescriptionB("蓝莓松饼");
        details.setDescriptionC("Blueberry muffin ");
        details.setDescriptionD("Кекс с черникой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ fǔ ");
        details.setDescriptionB("果脯");
        details.setDescriptionC("Preserved fruit ");
        details.setDescriptionD("Консервированные фрукты ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng guǒ ");
        details.setDescriptionB("糖果");
        details.setDescriptionC("Candy");
        details.setDescriptionD("Конфета");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎi táng/tài fēi táng ");
        details.setDescriptionB("奶糖/太妃糖");
        details.setDescriptionC("Toffee ");
        details.setDescriptionD("Ириска ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎi yóu xiàn bǐng ");
        details.setDescriptionB("奶油馅饼");
        details.setDescriptionC("Cream pie ");
        details.setDescriptionD("Кремовый пирог ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сuì bǐng gān ");
        details.setDescriptionB("脆饼干");
        details.setDescriptionC("Cracker ");
        details.setDescriptionD("Крекер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā shēng cuì piàn ");
        details.setDescriptionB("花生脆片");
        details.setDescriptionC(" Peanut brittle ");
        details.setDescriptionD(" Козинак арахисовый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú jiǎo miàn bāo ");
        details.setDescriptionB("牛角面包");
        details.setDescriptionC("Croissant");
        details.setDescriptionD("Круасан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǔ ěr qí ruǎn táng");
        details.setDescriptionB("土耳其软糖");
        details.setDescriptionC("Lokum");
        details.setDescriptionD("Лукум");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuè bǐng ");
        details.setDescriptionB("月饼");
        details.setDescriptionC("Mooncake");
        details.setDescriptionD("Лунный пряник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā xīn ");
        details.setDescriptionB("夹心");
        details.setDescriptionC("Filling ");
        details.setDescriptionD("Начинка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān guǒ jiàng");
        details.setDescriptionB(" 酸果酱");
        details.setDescriptionC("Marmalade  ");
        details.setDescriptionD("Мармелад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xìng rén bǐng gān ");
        details.setDescriptionB("杏仁饼干");
        details.setDescriptionC("Almond cookie ");
        details.setDescriptionD("Миндальное печенье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě gāo/ bīng qí lín ");
        details.setDescriptionB("雪糕/冰淇淋");
        details.setDescriptionC("Ice cream ");
        details.setDescriptionD(" Мороженое ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sōng bǐng ");
        details.setDescriptionB("松饼");
        details.setDescriptionC("Muffin");
        details.setDescriptionD("Маффин/Кекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù sī ");
        details.setDescriptionB("慕思");
        details.setDescriptionC("Mousse");
        details.setDescriptionD("Мусс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú gá táng ");
        details.setDescriptionB("牛轧糖");
        details.setDescriptionC("Nougat ");
        details.setDescriptionD("Нуга ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yàn mài bǐng gān ");
        details.setDescriptionB("燕麦饼干");
        details.setDescriptionC("Oatmeal cookie ");
        details.setDescriptionD("Овсяное печенье ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bá kè lā fú bǐng ");
        details.setDescriptionB("拔克拉弗饼");
        details.setDescriptionC("Baklava ");
        details.setDescriptionD("Пахлава");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǐng gān ");
        details.setDescriptionB("饼干");
        details.setDescriptionC("Cookie");
        details.setDescriptionD("Печенье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn bǐng ");
        details.setDescriptionB("馅饼");
        details.setDescriptionC("Pie");
        details.setDescriptionD("Пирог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tián tián quān ");
        details.setDescriptionB("甜甜圈");
        details.setDescriptionC("Donut");
        details.setDescriptionD("Пончик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bào mǐ huā ");
        details.setDescriptionB("爆米花");
        details.setDescriptionC("Popcorn");
        details.setDescriptionD("Попкорн");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù dīng ");
        details.setDescriptionB("布丁");
        details.setDescriptionC("Pudding");
        details.setDescriptionD("Пудинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dàn nǎi sū ");
        details.setDescriptionB("蛋奶酥");
        details.setDescriptionC("Souffle ");
        details.setDescriptionD("Суфле");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhī shì bǐng");
        details.setDescriptionB("芝士饼");
        details.setDescriptionC("Сheese pancake");
        details.setDescriptionD("Сырники");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng lù qiǎo kè lì ");
        details.setDescriptionB("松露巧克力");
        details.setDescriptionC("Truffle ");
        details.setDescriptionD(" Трюфель ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dàn gāo");
        details.setDescriptionB("蛋糕");
        details.setDescriptionC("Cake");
        details.setDescriptionD("Торт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēng rì dàn gāo ");
        details.setDescriptionB("生日蛋糕");
        details.setDescriptionC("Birthday cake");
        details.setDescriptionD("Торт ко дню рождения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jié hūn dàn gāo ");
        details.setDescriptionB("结婚蛋糕");
        details.setDescriptionC(" Wedding cake ");
        details.setDescriptionD("Свадебный торт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhī shì dàn gāo");
        details.setDescriptionB("芝士蛋糕");
        details.setDescriptionC("Cheesecake ");
        details.setDescriptionD("Торт «Чизкейк»");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tí lā mǐ sū");
        details.setDescriptionB("提拉米苏");
        details.setDescriptionC("Tiramisu");
        details.setDescriptionD("Тирамису");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ rén qiǎo kè lì cuì bǐng");
        details.setDescriptionB("果仁巧克力脆饼");
        details.setDescriptionC(" Florentine ");
        details.setDescriptionD("Флорентинка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guǒ dàn gāo");
        details.setDescriptionB("水果蛋糕");
        details.setDescriptionC("Fruit cake");
        details.setDescriptionD("Фруктовый торт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guǒ xiàn bǐng");
        details.setDescriptionB("水果馅饼");
        details.setDescriptionC("Fruit tart");
        details.setDescriptionD("Фруктовая тарталетка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guǒ shā lā");
        details.setDescriptionB("水果沙拉");
        details.setDescriptionC("Fruit salad");
        details.setDescriptionD("Фруктовый салат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū táng");
        details.setDescriptionB("酥糖");
        details.setDescriptionC("Halva");
        details.setDescriptionD("Халва");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn bāo bàng");
        details.setDescriptionB("面包棒");
        details.setDescriptionC("Bread sticks");
        details.setDescriptionD("Хлебные палочки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ zhī bīng gāo");
        details.setDescriptionB("果汁冰糕");
        details.setDescriptionC("Sorbet/ sherbet ");
        details.setDescriptionD("Шербет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" píng guǒ pài ");
        details.setDescriptionB("苹果派");
        details.setDescriptionC("Apple pie");
        details.setDescriptionD("Яблочный пирог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiǎo kè lì ");
        details.setDescriptionB("巧克力");
        details.setDescriptionC("Chocolate");
        details.setDescriptionD("Шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái qiǎo kè lì ");
        details.setDescriptionB("白巧克力");
        details.setDescriptionC("White chocolate");
        details.setDescriptionD("Белый шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi qiǎo kè lì ");
        details.setDescriptionB("黑巧克力");
        details.setDescriptionC("Black chocolate ");
        details.setDescriptionD("Чёрный шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú nǎi qiǎo kè lì");
        details.setDescriptionB("牛奶巧克力");
        details.setDescriptionC("Milk chocolate");
        details.setDescriptionD("Молочный шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiǎo kè lì hé ");
        details.setDescriptionB("巧克力盒");
        details.setDescriptionC("Box of chocolates ");
        details.setDescriptionD("Коробка конфет ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiǎo kè lì bàng ");
        details.setDescriptionB("巧克力棒");
        details.setDescriptionC("Chocolate bar ");
        details.setDescriptionD("Плитка шоколада");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiǎo kè lì dàn gāo");
        details.setDescriptionB("巧克力蛋糕");
        details.setDescriptionC("Chocolate cake");
        details.setDescriptionD("Шоколадный торт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiǎo kè lì huǒ guō ");
        details.setDescriptionB("巧克力火锅");
        details.setDescriptionC(" Chocolate fondue ");
        details.setDescriptionD("Шоколадное фондю");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiǎo kè lì jiàng ");
        details.setDescriptionB("巧克力酱");
        details.setDescriptionC("Chocolate spread ");
        details.setDescriptionD("Шоколадная паста ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā shēng jiàng ");
        details.setDescriptionB("花生酱");
        details.setDescriptionC("Peanut butter ");
        details.setDescriptionD("Арахисовая паста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xìng rén hú ");
        details.setDescriptionB("杏仁糊");
        details.setDescriptionC("Marzipan ");
        details.setDescriptionD("Марципан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǒu xiāng táng ");
        details.setDescriptionB("口香糖");
        details.setDescriptionC("Chewing gum ");
        details.setDescriptionD("Жевательная резинка");
        detailsList.add(details);
    }
}
