package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C83 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("huáng jīng guǒ ");
        details.setDescriptionB("黄晶果");
        details.setDescriptionC(" Abiu ");
        details.setDescriptionD("Абиу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xìng ");
        details.setDescriptionB("杏");
        details.setDescriptionC("Apricot");
        details.setDescriptionD("Абрикос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāng chéng ");
        details.setDescriptionB("桑橙");
        details.setDescriptionC("Osage orange ");
        details.setDescriptionD("Адамово яблоко/Маклюра ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chì hú guǒ ");
        details.setDescriptionB("赤湖果");
        details.setDescriptionC(" Aguaje fruit ");
        details.setDescriptionD("Агуахе ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  ");
        details.setDescriptionB("xīng guǒ zōng ");
        details.setDescriptionC("星果棕");
        details.setDescriptionD("Awara/ Tucum ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("è lí ");
        details.setDescriptionB("鳄梨");
        details.setDescriptionC("  Avocado ");
        details.setDescriptionD("Авокадо /Аллигаторова груша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā pó/pào pào guǒ ");
        details.setDescriptionB("巴婆/泡泡果");
        details.setDescriptionC("Paw Paw");
        details.setDescriptionD("Азимина/ Пау Пау");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēn bó ");
        details.setDescriptionB("榅桲");
        details.setDescriptionC("Quince");
        details.setDescriptionD("Айва");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ā jī guǒ / xī fēi lì zhī guǒ ");
        details.setDescriptionB("阿基果/ 西非荔枝果");
        details.setDescriptionC("Ackee/ Ackee apple ");
        details.setDescriptionD("Аки ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng táo lǐ/ yě suān méi");
        details.setDescriptionB("樱桃李/野酸梅");
        details.setDescriptionC("Сherry plum / Myrobalan plum");
        details.setDescriptionD(" Алыча");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīn láng qīng");
        details.setDescriptionB("槟榔青");
        details.setDescriptionC(" Ambarella ");
        details.setDescriptionD("Амбарелла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fèng lí/bō luó ");
        details.setDescriptionB("凤梨/菠萝");
        details.setDescriptionC(" Pineapple ");
        details.setDescriptionD("Ананас ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī yìn dù cù lì ");
        details.setDescriptionB("西印度醋栗");
        details.setDescriptionC(" Otaheite gooseberry ");
        details.setDescriptionD("Антильский крыжовник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī dì guǒ");
        details.setDescriptionB("思帝果");
        details.setDescriptionC(" Araza ");
        details.setDescriptionD("Араза ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luó hàn guǒ ");
        details.setDescriptionB(" 罗汉果");
        details.setDescriptionC(" Arhat /Monk fruit ");
        details.setDescriptionD("Архат ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā xī méi/ ā sà yī ");
        details.setDescriptionB("巴西莓/ 阿萨伊");
        details.setDescriptionC("Acai berry");
        details.setDescriptionD("Асаи ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shì jiā fèng lí ");
        details.setDescriptionB("释迦凤梨");
        details.setDescriptionC("Atemoya/ Custard apple");
        details.setDescriptionD(" Атемойя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě máng guǒ ");
        details.setDescriptionB("野芒果 ");
        details.setDescriptionC("Bambangan ");
        details.setDescriptionD("Бам-балан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù jú");
        details.setDescriptionB("木橘 ");
        details.setDescriptionC(" Bael ");
        details.setDescriptionD("Баиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bó luó huò ");
        details.setDescriptionB("博罗霍");
        details.setDescriptionC(" Borojó ");
        details.setDescriptionD("Борожоа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāngjiāo");
        details.setDescriptionB("香蕉");
        details.setDescriptionC("Banana ");
        details.setDescriptionD("Банан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā jiāo");
        details.setDescriptionB("芭蕉");
        details.setDescriptionC(" Japanese banana ");
        details.setDescriptionD(" Банан японский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ lóng jiāo /hóng xiāng jiāo");
        details.setDescriptionB("火龙蕉/红香蕉");
        details.setDescriptionC("Red banana");
        details.setDescriptionD("Красный банан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fěn xiāng jiāo ");
        details.setDescriptionB("粉香蕉");
        details.setDescriptionC(" Velvet pink banana ");
        details.setDescriptionD(" Бархатный розовый банан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán xiāng jiāo ");
        details.setDescriptionB("蓝香蕉");
        details.setDescriptionC(" Blue Banana  ");
        details.setDescriptionD("Голубой банан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě xiāng jiāo /bā yuè guā ");
        details.setDescriptionB("野香蕉/八月瓜");
        details.setDescriptionC(" Wild banana ");
        details.setDescriptionD("Дикий банан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóu miàn bāo shù ");
        details.setDescriptionB("猴面包树");
        details.setDescriptionC(" Baobab ");
        details.setDescriptionD(" Баобаб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng jiāo bǎi xiāng guǒ ");
        details.setDescriptionB("香蕉百香果");
        details.setDescriptionC("Banana passion fruit");
        details.setDescriptionD("Банановая гранадилла/Куру́ба  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà guǒ xī fān lián ");
        details.setDescriptionB("大果西番莲");
        details.setDescriptionC(" Giant granadilla");
        details.setDescriptionD("Гигантская гранадилла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tián bǎi xiāng guǒ ");
        details.setDescriptionB("甜百香果");
        details.setDescriptionC(" Sweet granadilla ");
        details.setDescriptionD("Сладкая гранадилла ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhāng yè xī fān lián ");
        details.setDescriptionB("樟叶西番莲");
        details.setDescriptionC(" Water lemon ");
        details.setDescriptionD("Жёлтая гранадилла ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhēn yè yīng táo ");
        details.setDescriptionB("针叶樱桃");
        details.setDescriptionC("Acerola berry");
        details.setDescriptionD("Барбадосская вишня /Ацерола ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù qí lín ");
        details.setDescriptionB("木麒麟");
        details.setDescriptionC(" Barbados gooseberry ");
        details.setDescriptionD("Барбадосский крыжовник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng ròu guǒ");
        details.setDescriptionB("香肉果 ");
        details.setDescriptionC("White Sapote");
        details.setDescriptionD("Белая сапота ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǔ yuè chá ");
        details.setDescriptionB("五月茶");
        details.setDescriptionC(" Bignay");
        details.setDescriptionD("Бигнай ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  sān liǎn ");
        details.setDescriptionB("三敛");
        details.setDescriptionC("  Bilimbi/ Cucumber tree ");
        details.setDescriptionD("Билимби / Огуречное дерево");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě shēng fān lì zhī ");
        details.setDescriptionB("野生番荔枝");
        details.setDescriptionC(" Biribá /Wild sugar-apple ");
        details.setDescriptionD("Бириба ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù nǎi guǒ /miǎn diàn pú táo ");
        details.setDescriptionB("木奶果/缅甸葡萄");
        details.setDescriptionC(" Burmese Grape");
        details.setDescriptionD("Бирманский виноград ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng pí guǒ ");
        details.setDescriptionB("黄皮果");
        details.setDescriptionC(" Wampee ");
        details.setDescriptionD("Вампи ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě ōu zhā ");
        details.setDescriptionB("野欧楂");
        details.setDescriptionC(" African medlar ");
        details.setDescriptionD("Вангерия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yáng méi ");
        details.setDescriptionB("杨梅");
        details.setDescriptionC(" Red bayberry ");
        details.setDescriptionD("Восковница красная ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù biē guǒ / mù biē zǐ ");
        details.setDescriptionB("木鳖果/木鳖子");
        details.setDescriptionC("Gac");
        details.setDescriptionD("Гак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi zhōu gé ní pà shù ");
        details.setDescriptionB("美洲格尼帕树");
        details.setDescriptionC("Genip ");
        details.setDescriptionD("Генипа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gē lǐ ");
        details.setDescriptionB("鸽李");
        details.setDescriptionC(" Pigeon plum ");
        details.setDescriptionD("Голубиная слива ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā xī yīng táo ");
        details.setDescriptionB("巴西樱桃");
        details.setDescriptionC(" Grumichama /Brazil Cherry");
        details.setDescriptionD("Грумичама/ Бразильская вишня ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi lì qiú huā dòu ");
        details.setDescriptionB("美丽球花豆");
        details.setDescriptionC(" Petai/ Stink bean ");
        details.setDescriptionD(" Горькие бобы ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lí");
        details.setDescriptionB("梨");
        details.setDescriptionC(" Pear");
        details.setDescriptionD("Груша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān shí liú ");
        details.setDescriptionB("番石榴");
        details.setDescriptionC("Guava ");
        details.setDescriptionD("Гуава ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cǎo méi fān shí liú ");
        details.setDescriptionB("草莓番石榴");
        details.setDescriptionC(" Strawberry guava ");
        details.setDescriptionD(" Гуава земляничная ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guā lā nà ");
        details.setDescriptionB("瓜拉那");
        details.setDescriptionC(" Guarana  ");
        details.setDescriptionD("Гуарана ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shí liú ");
        details.setDescriptionB("石榴");
        details.setDescriptionC(" Pomegranate");
        details.setDescriptionD("Гранат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dài wéi sēn lǐ zǐ ");
        details.setDescriptionB("戴维森李子");
        details.setDescriptionC(" Davidson's plum ");
        details.setDescriptionD("Давидсония");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" māo ér shǐ / ǎi qǐ shù ");
        details.setDescriptionB("猫儿屎/矮杞树");
        details.setDescriptionC(" Blue bean plant/Blue sausage fruit ");
        details.setDescriptionD("Декенея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù píng guǒ / xiàng jú ");
        details.setDescriptionB("木苹果/ 象橘");
        details.setDescriptionC("Wood Apple ");
        details.setDescriptionD("Деревянное яблоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fó luó pú tí ");
        details.setDescriptionB("佛螺菩提");
        details.setDescriptionC(" Desert quandong ");
        details.setDescriptionD("Десертный квандонг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā bǎo guǒ ");
        details.setDescriptionB("嘉宝果");
        details.setDescriptionC(" Jaboticaba ");
        details.setDescriptionD("Джаботикаба ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kěn shì pú táo");
        details.setDescriptionB("肯氏蒲桃");
        details.setDescriptionC("Jambolan/ Java plum ");
        details.setDescriptionD("Джамболан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ pú táo ");
        details.setDescriptionB("水蒲桃");
        details.setDescriptionC(" Watery rose apple ");
        details.setDescriptionD(" Джамбу /Водяное яблоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bō luó mì  ");
        details.setDescriptionB("菠萝蜜  ");
        details.setDescriptionC(" Jackfruit ");
        details.setDescriptionD("Джекфрут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liú lián ");
        details.setDescriptionB("榴梿");
        details.setDescriptionC(" Durian  ");
        details.setDescriptionD("Дуриан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng píng guǒ ");
        details.setDescriptionB("星苹果");
        details.setDescriptionC("Star apple");
        details.setDescriptionD(" Звёздное яблоко  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shé pí guǒ");
        details.setDescriptionB("蛇皮果");
        details.setDescriptionC("Snakeskin fruit / Salak  ");
        details.setDescriptionD(" Змеиный фрукт /Салак ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yī kǒu kě méi ");
        details.setDescriptionB("一口可梅");
        details.setDescriptionC("Coco plum");
        details.setDescriptionD("Икако ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú huā guǒ ");
        details.setDescriptionB("无花果");
        details.setDescriptionC(" Fig");
        details.setDescriptionD("Инжир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dàn huáng guǒ");
        details.setDescriptionB("蛋黄果");
        details.setDescriptionC("Canistel/Eggfruit");
        details.setDescriptionD("Канистель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liǔ yè yě hēi yīng");
        details.setDescriptionB("柳叶野黑樱");
        details.setDescriptionC(" Capulin ");
        details.setDescriptionD("Капулин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yáng táo ");
        details.setDescriptionB("杨桃");
        details.setDescriptionC(" Carambola/ Starfruit ");
        details.setDescriptionD("Карамбола ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà huā jiǎ hǔ cì ");
        details.setDescriptionB("大花假虎刺");
        details.setDescriptionC(" Natal plum ");
        details.setDescriptionD("Карисса ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng jiāo guā ");
        details.setDescriptionB("香蕉瓜");
        details.setDescriptionC("Сassabanana");
        details.setDescriptionD("Кассабанана ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán fēi xī lán méi ");
        details.setDescriptionB("南非锡兰莓");
        details.setDescriptionC(" Kei Apple");
        details.setDescriptionD("Кафрская слива");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng bō guǒ ");
        details.setDescriptionB("香波果");
        details.setDescriptionC(" Kepel Fruit");
        details.setDescriptionD("Кепел ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī lán méi ");
        details.setDescriptionB("锡兰莓");
        details.setDescriptionC("  Ketembilla ");
        details.setDescriptionD("Кетембилла ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yāo guǒ ");
        details.setDescriptionB("腰果");
        details.setDescriptionC(" Cashew ");
        details.setDescriptionD("Кешью");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yēzi");
        details.setDescriptionB("椰子");
        details.setDescriptionC("Coconut");
        details.setDescriptionD("Кокос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú xīn guǒ ");
        details.setDescriptionB("牛心果");
        details.setDescriptionC("Custard apple /Bullock’s heart");
        details.setDescriptionD("Кремовое яблоко/ Бычье сердце ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yìn jiā dòu ");
        details.setDescriptionB("印加豆");
        details.setDescriptionC("Ice-cream-bean ");
        details.setDescriptionD("Кремовый боб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǔ bù yà sū ");
        details.setDescriptionB("古布亚苏");
        details.setDescriptionC(" Cupuaçu ");
        details.setDescriptionD("Купуасу ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mí hóu táo ");
        details.setDescriptionB("猕猴桃");
        details.setDescriptionC(" Kiwi ");
        details.setDescriptionD("Киви");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kē kē nà guǒ ");
        details.setDescriptionB("科科纳果");
        details.setDescriptionC(" Cocona ");
        details.setDescriptionD("Кокона ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuò shù ");
        details.setDescriptionB("拓树");
        details.setDescriptionC(" Cudrang/ Chinese Che ");
        details.setDescriptionD("Кудрания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lóng gōng guǒ ");
        details.setDescriptionB("龙功果");
        details.setDescriptionC(" Langsat ");
        details.setDescriptionD("Лансиум/Лангсат ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" suān shān yóu gān guǒ ");
        details.setDescriptionB("酸山油柑果");
        details.setDescriptionC(" Lemon aspen ");
        details.setDescriptionD("Лимонная осина ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lì zhī ");
        details.setDescriptionB("荔枝 ");
        details.setDescriptionC(" Lychee");
        details.setDescriptionD("Личи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lóng yǎn");
        details.setDescriptionB("龙眼");
        details.setDescriptionC("Longan");
        details.setDescriptionD("Лонган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lì qí mǎ ");
        details.setDescriptionB("利奇马");
        details.setDescriptionC(" Lucuma ");
        details.setDescriptionD("Лукума ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yì sè shì ");
        details.setDescriptionB("异色柿");
        details.setDescriptionC("Mabolo ");
        details.setDescriptionD("Маболо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shén mì guǒ ");
        details.setDescriptionB("神秘果");
        details.setDescriptionC(" Miracle Fruit ");
        details.setDescriptionD("Магический фрукт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ liù jiǎ pú táo ");
        details.setDescriptionB("马六甲蒲桃");
        details.setDescriptionC(" Malay apple ");
        details.setDescriptionD("Малайское яблоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ mǐ xìng ");
        details.setDescriptionB("马米杏");
        details.setDescriptionC("  Mammee apple ");
        details.setDescriptionD("Мамея /Американский абрикос ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mì méi");
        details.setDescriptionB("蜜莓");
        details.setDescriptionC(" Spanish Lime");
        details.setDescriptionD("Мамончилло /Лайм испанский ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" máng guǒ ");
        details.setDescriptionB("芒果");
        details.setDescriptionC(" Mango ");
        details.setDescriptionD("Манго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān zhú ");
        details.setDescriptionB("山竹 ");
        details.setDescriptionC("Mangosteen ");
        details.setDescriptionD("Мангостин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎixiāng guǒ");
        details.setDescriptionB("百香果");
        details.setDescriptionC(" Passion fruit ");
        details.setDescriptionD(" Маракуйя ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú tí dòu /yáng suān jiǎo ");
        details.setDescriptionB("牛蹄豆/洋酸角");
        details.setDescriptionC(" Madras thorn ");
        details.setDescriptionD("Манильский тамаринд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēn fāng bō luó mì ");
        details.setDescriptionB("芬芳波罗蜜");
        details.setDescriptionC(" Marang");
        details.setDescriptionD("Маранг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gēng dà lì ");
        details.setDescriptionB("庚大利");
        details.setDescriptionC(" Marian plum/ Gandaria");
        details.setDescriptionD("Марианская слива / Гандария");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guǒ lǎn ");
        details.setDescriptionB("美果榄");
        details.setDescriptionC(" Mamey sapote ");
        details.setDescriptionD("Мармеладный плод /Сапота  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ lǔ lā guǒ /bó ěr yìng hú táo ");
        details.setDescriptionB("马鲁拉果/伯尔硬胡桃");
        details.setDescriptionC("Marula ");
        details.setDescriptionD("Марула ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng bīn láng qīng ");
        details.setDescriptionB("黄槟榔青");
        details.setDescriptionC(" Yellow mombin ");
        details.setDescriptionD("Момбин жёлтый ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guī bèi zhú ");
        details.setDescriptionB("龟背竹");
        details.setDescriptionC(" Swiss Cheese Plant ");
        details.setDescriptionD("Монстера привлекательная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi pú táo ");
        details.setDescriptionB("海葡萄");
        details.setDescriptionC(" Sea grape ");
        details.setDescriptionD("Морской виноград");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pí pá ");
        details.setDescriptionB("枇杷");
        details.setDescriptionC(" Loquat");
        details.setDescriptionD("Мушмула японская/Локва");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu táo ");
        details.setDescriptionB("油桃");
        details.setDescriptionC("Nectarine");
        details.setDescriptionD("Нектарин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nuò lì guǒ /hǎi bā jǐ ");
        details.setDescriptionB("诺丽果/海巴戟");
        details.setDescriptionC(" Noni fruit ");
        details.setDescriptionD("Нони");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō luó mì /hóu miàn guǒ ");
        details.setDescriptionB("菠萝蜜/猴面果");
        details.setDescriptionC(" Lakoocha /Monkey jack fruit");
        details.setDescriptionD("Обезьянье хлебное дерево");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǐ lǎo shǔ shù ");
        details.setDescriptionB("米老鼠树");
        details.setDescriptionC(" Mickey Mouse Plant ");
        details.setDescriptionD("Охна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóu chéng ");
        details.setDescriptionB("猴橙 ");
        details.setDescriptionC("Monkey orange ");
        details.setDescriptionD("Обезьяний апельсин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō luó méi ");
        details.setDescriptionB("菠萝莓");
        details.setDescriptionC("Pineberry");
        details.setDescriptionD(" Пайнберри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě bō luó /jiǎ bō luó ");
        details.setDescriptionB("野菠萝/假菠萝");
        details.setDescriptionC(" Pandan ");
        details.setDescriptionD("Пандан/Панданус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù guā ");
        details.setDescriptionB("木瓜");
        details.setDescriptionC("Papaya ");
        details.setDescriptionD("Папайя ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā xī yóu táo mù guǒ ");
        details.setDescriptionB("巴西油桃木果");
        details.setDescriptionC(" Pequi  ");
        details.setDescriptionD("Пекуи ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rén shēn guǒ ");
        details.setDescriptionB("人参果");
        details.setDescriptionC(" Pepino ");
        details.setDescriptionD("Пепино ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táo zǐ ");
        details.setDescriptionB("桃子");
        details.setDescriptionC("Peach");
        details.setDescriptionD("Персик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ lóng  guǒ");
        details.setDescriptionB("火龙果");
        details.setDescriptionC(" Pitahaya /Pitaya / Dragon Fruit ");
        details.setDescriptionD(" Питахайя/Питайя/ Драконий фрукт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng xīn huǒ lóng guǒ ");
        details.setDescriptionB("红心火龙果");
        details.setDescriptionC(" Purple pitahaya ");
        details.setDescriptionD("Питахайя красная ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng huǒ lóng guǒ ");
        details.setDescriptionB("黄火龙果");
        details.setDescriptionC("Yellow pitahaya ");
        details.setDescriptionD("Питахайя желтая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā kù lì guǒ ");
        details.setDescriptionB("巴库利果");
        details.setDescriptionC(" Bacuri ");
        details.setDescriptionD("Платония ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ jǔ zǐ ");
        details.setDescriptionB("枳椇子");
        details.setDescriptionC(" Japanese raisin tree ");
        details.setDescriptionD("Плодоножки конфетного дерева");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng yē zǐ ");
        details.setDescriptionB("糖椰子");
        details.setDescriptionC(" Ice apple");
        details.setDescriptionD("Плоды пальмировой пальмы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táo yē zǐ ");
        details.setDescriptionB("桃椰子");
        details.setDescriptionC(" Peach palm coconut ");
        details.setDescriptionD("Плоды персиковой пальмы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn bāo guǒ ");
        details.setDescriptionB("面包果 ");
        details.setDescriptionC("Breadfruit ");
        details.setDescriptionD("Плоды хлебного дерева");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pú táo sāng ");
        details.setDescriptionB("葡萄桑");
        details.setDescriptionC(" Pulasan ");
        details.setDescriptionD("Пуласан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóu gòu dié ");
        details.setDescriptionB("侯购谍");
        details.setDescriptionC("Red Mombin/ Jocote ");
        details.setDescriptionD("Пурпурный момбин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mó shì mù nǎi guǒ ");
        details.setDescriptionB("摩氏木奶果");
        details.setDescriptionC(" Rambai");
        details.setDescriptionD("Рамбай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng máo dān ");
        details.setDescriptionB("红毛丹");
        details.setDescriptionC(" Rambutan ");
        details.setDescriptionD("Рамбутан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pú táo ");
        details.setDescriptionB("蒲桃");
        details.setDescriptionC(" Malabar plum /Rose apple ");
        details.setDescriptionD(" Малабарская слива /Розовое яблоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎ mǔ jiā bǎo guǒ ");
        details.setDescriptionB("卡姆嘉宝果");
        details.setDescriptionC("  Rumberry/ Guavaberry ");
        details.setDescriptionD("Ромовая ягода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rén xīn guǒ ");
        details.setDescriptionB("人心果");
        details.setDescriptionC(" Sapodilla/ Sapota ");
        details.setDescriptionD("Саподилла ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiān dū guǒ ");
        details.setDescriptionB("仙都果");
        details.setDescriptionC(" Santol ");
        details.setDescriptionD("Сантол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā fó /fēi zhōu lí ");
        details.setDescriptionB("沙佛/非洲梨");
        details.setDescriptionC("Safou/ African Pear");
        details.setDescriptionD("Сафу/ Африканская груша ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǐ zǐ ");
        details.setDescriptionB("李子");
        details.setDescriptionC("Plum");
        details.setDescriptionD("Слива");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī kè mò wú huā guǒ ");
        details.setDescriptionB("西克莫无花果");
        details.setDescriptionC(" Sycamore fig ");
        details.setDescriptionD("Сикомор ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān lì zhī /fó tóu guǒ ");
        details.setDescriptionB("番荔枝/佛头果");
        details.setDescriptionC("Sugar-apple/ Sweetsop  ");
        details.setDescriptionD("Сахарное яблоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ yā guǒ / dì lún táo ");
        details.setDescriptionB("五桠果/第伦桃");
        details.setDescriptionC(" Elephant Apple ");
        details.setDescriptionD("Слоновое яблоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cì guǒ fān lì zhī ");
        details.setDescriptionB("刺果番荔枝");
        details.setDescriptionC("  Soursop/ Graviola ");
        details.setDescriptionD("Сметанное яблоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ kǎ dù lǐ ");
        details.setDescriptionB("卡卡杜李");
        details.setDescriptionC(" Kakadu Plum");
        details.setDescriptionD("Слива какаду");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ fān lì zhī ");
        details.setDescriptionB("紫番荔枝");
        details.setDescriptionC(" Soncoya ");
        details.setDescriptionD("Сонкойя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng guǒ zǎi ");
        details.setDescriptionB("红果仔");
        details.setDescriptionC(" Suriname cherry ");
        details.setDescriptionD("Суринамская вишня/ Питанга ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù fān qié ");
        details.setDescriptionB("树番茄");
        details.setDescriptionC(" Tamarillo  ");
        details.setDescriptionD("Тамарилло/ Томатное дерево   ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" suān jiǎo ");
        details.setDescriptionB("酸角");
        details.setDescriptionC(" Tamarind  ");
        details.setDescriptionD("Тамаринд ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi yóu guǒ ");
        details.setDescriptionB("菲油果");
        details.setDescriptionC("Feijoa /Pineapple Guava ");
        details.setDescriptionD("Фейхоа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dēng lóng guǒ ");
        details.setDescriptionB("灯笼果");
        details.setDescriptionC("  Cape gooseberry");
        details.setDescriptionD("Физалис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi zǎo  /yē zǎo ");
        details.setDescriptionB("海枣/椰枣");
        details.setDescriptionC(" Date ");
        details.setDescriptionD("Финик ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shìzi ");
        details.setDescriptionB("柿子");
        details.setDescriptionC(" Persimmon ");
        details.setDescriptionD("Хурма ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiān rén zhǎng guǒ ");
        details.setDescriptionB("仙人掌果");
        details.setDescriptionC(" Сactus pear");
        details.setDescriptionD("Цабр/ Опунция индийская ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liú lián mì /jiān mì lā ");
        details.setDescriptionB("榴莲蜜/尖蜜拉");
        details.setDescriptionC(" Cempedak");
        details.setDescriptionD("Чемпедак ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" máo yè fān lì zhī ");
        details.setDescriptionB("毛叶番荔枝");
        details.setDescriptionC(" Сherimoya ");
        details.setDescriptionD("Черимойя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  hēi ròu shì ");
        details.setDescriptionB("黑肉柿");
        details.setDescriptionC("Black sapote ");
        details.setDescriptionD("Чёрная сапота");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú gān zǐ ");
        details.setDescriptionB("余甘子");
        details.setDescriptionC(" Emblic ");
        details.setDescriptionD("Эмблика/ Индийский крыжовник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" píng guǒ ");
        details.setDescriptionB("苹果");
        details.setDescriptionC(" Apple ");
        details.setDescriptionD("Яблоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lián wù  ");
        details.setDescriptionB("莲雾");
        details.setDescriptionC("Java apple / Rose-apple");
        details.setDescriptionD("Яванское яблоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wén dìng guǒ ");
        details.setDescriptionB("文定果");
        details.setDescriptionC(" Jamaica cherry /Capulin ");
        details.setDescriptionD("Ямайская вишня ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" luán yè dòu");
        details.setDescriptionB("孪叶豆");
        details.setDescriptionC("West Indian locust ");
        details.setDescriptionD("Ятоба ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Сhupa-chupa/ South American sapote ");
        details.setDescriptionB("Чупа -чупа ");
        details.setDescriptionC("(лат.Quararibea cordata)");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" Chilean Guava ");
        details.setDescriptionB(" Угни чилийский ");
        details.setDescriptionC("(Ugni molinae)");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" Bacupari");
        details.setDescriptionB("Бакупари");
        details.setDescriptionC(" (лат. Garcinia gardneriana)");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("- ");
        details.setDescriptionB("Mountain papaya");
        details.setDescriptionC("Горная папайя ");
        details.setDescriptionD("(Carica candamarcensis)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Imbu/ Brazil plum ");
        details.setDescriptionB("Имбу/Бразильская слива ");
        details.setDescriptionC("(Spondias tuberosa; Anacardiaceae)");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" -");
        details.setDescriptionB(" Nance ");
        details.setDescriptionC("Нансе");
        details.setDescriptionD(" (Byrsonima crassifolia)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("-");
        details.setDescriptionB(" Naranjilla ");
        details.setDescriptionC("Наранхилла");
        details.setDescriptionD(" (Solanum quitoense)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("-");
        details.setDescriptionB(" Korlan ");
        details.setDescriptionC("Корлан ");
        details.setDescriptionD("(лат. Nephelium hypoleucum)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" Silver peanut butter fruit");
        details.setDescriptionB("Бунхозия серебристая ");
        details.setDescriptionC("(Bunchosia argentea)");
        details.setDescriptionD("");
        detailsList.add(details);
    }
}
