package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C87 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" péng yǒu ");
        details.setDescriptionB("朋友");
        details.setDescriptionC("Friend ");
        details.setDescriptionD("Друг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín jū ");
        details.setDescriptionB("邻居");
        details.setDescriptionC(" Neighbour ");
        details.setDescriptionD("Сосед/соседка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shú rén ");
        details.setDescriptionB("熟人");
        details.setDescriptionC(" Acquaintance");
        details.setDescriptionD("Знакомый/ знакомая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǐ yǒu ");
        details.setDescriptionB("笔友");
        details.setDescriptionC("Penfriend");
        details.setDescriptionD("Друг по переписке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóng jū");
        details.setDescriptionB("同居");
        details.setDescriptionC("Cohabitant");
        details.setDescriptionD("Сожитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèi hūn fū qī ");
        details.setDescriptionB("未婚夫妻");
        details.setDescriptionC("Engaged couple");
        details.setDescriptionD("Помолвленная пара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fū qī ");
        details.setDescriptionB("夫妻");
        details.setDescriptionC("Married couple");
        details.setDescriptionD("Супружеская пара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qíng lǚ");
        details.setDescriptionB("情侣");
        details.setDescriptionC("Couple");
        details.setDescriptionD("Пара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nán péng yǒu ");
        details.setDescriptionB("男朋友");
        details.setDescriptionC(" Boyfriend ");
        details.setDescriptionD("Бойфренд/ парень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǚ péng yǒu ");
        details.setDescriptionB("女朋友");
        details.setDescriptionC(" Girlfriend ");
        details.setDescriptionD("Любимая девушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhù shǒu ");
        details.setDescriptionB("助手");
        details.setDescriptionC("Assistant");
        details.setDescriptionD("Ассистент");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīng lǐ ");
        details.setDescriptionB("经理");
        details.setDescriptionC("Manager");
        details.setDescriptionD("Менеджер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shēng yì huǒ bàn ");
        details.setDescriptionB("生意伙伴");
        details.setDescriptionC("Business partner");
        details.setDescriptionD("Бизнес партнёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóng shì ");
        details.setDescriptionB("同事");
        details.setDescriptionC("Colleague");
        details.setDescriptionD("Коллега");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gù yuán");
        details.setDescriptionB("雇员");
        details.setDescriptionC(" Employee ");
        details.setDescriptionD(" Работник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gù zhǔ");
        details.setDescriptionB("雇主");
        details.setDescriptionC("Employer ");
        details.setDescriptionD("Работодатель");
        detailsList.add(details);
    }
}
