package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C14 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("西瓜");
        details.setDescriptionB("xī guā");
        details.setDescriptionC("Watermelon");
        details.setDescriptionD("Арбуз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("野樱莓");
        details.setDescriptionB("yě yīng méi");
        details.setDescriptionC("Aronia/ Black chokeberry");
        details.setDescriptionD("(Арония черноплодная)/ Черноплодная рябина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("斑叶阿诺母/马蹄莲");
        details.setDescriptionB("bān yè ā nuò mǔ/mǎ tí lián");
        details.setDescriptionC("Arum lily");
        details.setDescriptionD("Аронник пятнистый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("巴西莓/ 阿萨伊");
        details.setDescriptionB("bā xī méi/ ā sà yī");
        details.setDescriptionC("Acai berry");
        details.setDescriptionD("Асаи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("刺檗");
        details.setDescriptionB("cì bò");
        details.setDescriptionC("Barberry");
        details.setDescriptionD("Барбарис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白醋栗");
        details.setDescriptionB("bái cù lì");
        details.setDescriptionC("White currant");
        details.setDescriptionD("Белая смородина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("山楂");
        details.setDescriptionB("shān zhā");
        details.setDescriptionC("Hawthorn");
        details.setDescriptionD("Боярышник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("越桔");
        details.setDescriptionB("yuè jú");
        details.setDescriptionC("Cowberry/ Lingonberry");
        details.setDescriptionD("Брусника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("接骨木/马尿烧");
        details.setDescriptionB("jiē gǔ mù/ mǎ niào shāo");
        details.setDescriptionC("Red Elderberry");
        details.setDescriptionD("Бузина красная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("葡萄");
        details.setDescriptionB("pú táo");
        details.setDescriptionC("Grapes");
        details.setDescriptionD("Виноград");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("樱桃");
        details.setDescriptionB("yīng táo");
        details.setDescriptionC("Cherry");
        details.setDescriptionD("Вишня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("岩高兰");
        details.setDescriptionB("yán gāo lán");
        details.setDescriptionC("Crowberry");
        details.setDescriptionD("Водяника/ Вороника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北美白珠树");
        details.setDescriptionB("běi měi bái zhū shù");
        details.setDescriptionC("Salal");
        details.setDescriptionD("Салал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("枸杞");
        details.setDescriptionB("gǒu qǐ");
        details.setDescriptionC("Goji/ Goji berry/ Wolfberry");
        details.setDescriptionD("Годжи /Дереза обыкновенная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("笃斯越桔");
        details.setDescriptionB("dǔ sī yuè jú");
        details.setDescriptionC("Bog bilberry");
        details.setDescriptionD("Голубика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑果荚蒾");
        details.setDescriptionB("hēi guǒ jiá mí");
        details.setDescriptionC("Wayfaring tree");
        details.setDescriptionD("Калина гордовина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("木半夏");
        details.setDescriptionB("mù bàn xià");
        details.setDescriptionC("Goumi/Gumi/  Cherry silverberry");
        details.setDescriptionD("Гуми/ Лох многоцветковый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("香瓜");
        details.setDescriptionB("xiāng guā");
        details.setDescriptionC("Melon");
        details.setDescriptionD("Дыня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑莓");
        details.setDescriptionB("hēi méi");
        details.setDescriptionC("Blackberry");
        details.setDescriptionD("Ежевика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("地莓子/黄帽子");
        details.setDescriptionB("di méi zi/huáng mào zi");
        details.setDescriptionC("Yellow Raspberry");
        details.setDescriptionD("Желтоплодная малина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蓝靛果");
        details.setDescriptionB("lán diàn guǒ");
        details.setDescriptionC("Sweetberry honeysuckle");
        details.setDescriptionD("Жимолость");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("苦糖果/杈杷果");
        details.setDescriptionB("kǔ táng guǒ/chā pá guǒ");
        details.setDescriptionC("Standish Honeysuckle");
        details.setDescriptionD("Жимолость Стэндиша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("野草莓");
        details.setDescriptionB("yě cǎo méi");
        details.setDescriptionC("Wild strawberry");
        details.setDescriptionD("Земляника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("无花果");
        details.setDescriptionB("wú huā guǒ");
        details.setDescriptionC("Fig");
        details.setDescriptionD("Инжир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("唐棣");
        details.setDescriptionB("táng dì");
        details.setDescriptionC("Shadberry");
        details.setDescriptionD("Ирга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("Yoshta");
        details.setDescriptionD("Йошта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("花楸果");
        details.setDescriptionB("huā qiū guǒ");
        details.setDescriptionC("Guelder rose");
        details.setDescriptionD("Калина красная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("山茱萸");
        details.setDescriptionB("shān zhū yú");
        details.setDescriptionC("Cornelian cherry/ Dogwood");
        details.setDescriptionD("Кизил");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("草莓");
        details.setDescriptionB("cǎo méi");
        details.setDescriptionC("Strawberry");
        details.setDescriptionD("Клубника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蔓越莓");
        details.setDescriptionB("màn yuè méi");
        details.setDescriptionC("Cranberry");
        details.setDescriptionD("Клюква");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北悬钩子");
        details.setDescriptionB("běi xuán gōu zi");
        details.setDescriptionC("Arctic raspberry");
        details.setDescriptionD("Княженика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("石生悬钩子");
        details.setDescriptionB("shí shēng xuán gōu zi");
        details.setDescriptionC("Stone bramble");
        details.setDescriptionD("Костяника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("红醋栗/红加仑");
        details.setDescriptionB("hóng cù lì/ hóng jiā lún");
        details.setDescriptionC("Red currant");
        details.setDescriptionD("Красная смородина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鹅莓");
        details.setDescriptionB("é méi");
        details.setDescriptionC("Gooseberry");
        details.setDescriptionD("Крыжовник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("商陆");
        details.setDescriptionB("shāng lù");
        details.setDescriptionC("Pokeberry");
        details.setDescriptionD("Лаконос ягодный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蛇莓");
        details.setDescriptionB("shé méi");
        details.setDescriptionC("Indian strawberry");
        details.setDescriptionD("Лапчатка индийская ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("五味子");
        details.setDescriptionB("wǔ wèi zǐ");
        details.setDescriptionC("Magnolia berry");
        details.setDescriptionD("Лимонник китайский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("罗甘莓");
        details.setDescriptionB("luó gān méi");
        details.setDescriptionC("Loganberry");
        details.setDescriptionD("Логанова ягода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("冬青叶十大功劳");
        details.setDescriptionB("dōng qīng yè shí dà gōng láo");
        details.setDescriptionC("Oregon grape");
        details.setDescriptionD("Орегонский виноград");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("山莓");
        details.setDescriptionB("shān méi");
        details.setDescriptionC("Wild raspberry");
        details.setDescriptionD("Малина лесная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("树莓/覆盆子/红莓");
        details.setDescriptionB("shù méi/ fù pénzi/ hóng méi");
        details.setDescriptionC("Raspberry");
        details.setDescriptionD("Малина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("红泡刺藤");
        details.setDescriptionB("hóng pào cì téng");
        details.setDescriptionC("Mysore Raspberry");
        details.setDescriptionD("Майсурская малина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("金娘桃");
        details.setDescriptionB("jīn niáng táo");
        details.setDescriptionC("Chilean Myrtle");
        details.setDescriptionD("Мирт лу́ма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("云莓");
        details.setDescriptionB("yún méi");
        details.setDescriptionC("Cloudberry/ Yellowberry");
        details.setDescriptionD("Морошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("欧洲刺柏");
        details.setDescriptionB("ōu zhōu cì bǎi");
        details.setDescriptionC("Juniper berry");
        details.setDescriptionD("Можжевельник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("沙棘果");
        details.setDescriptionB("shā jí guǒ");
        details.setDescriptionC("Sea-buckthorn");
        details.setDescriptionD("Облепиха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("橄榄");
        details.setDescriptionB("gǎn lǎn");
        details.setDescriptionC("Olives");
        details.setDescriptionD("Оливки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("欧洲冬青");
        details.setDescriptionB("ōu zhōu dōng qīng");
        details.setDescriptionC("European holly");
        details.setDescriptionD("Падуб остролистный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("冬青");
        details.setDescriptionB("dōng qīng");
        details.setDescriptionC("Chinese holly");
        details.setDescriptionD("Падуб китайский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("龙葵");
        details.setDescriptionB("lóng kuí");
        details.setDescriptionC("European black nightshade");
        details.setDescriptionD("Паслён чёрный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("花楸浆果");
        details.setDescriptionB("huā qiū jiāng guǒ");
        details.setDescriptionC("Rowanberry");
        details.setDescriptionD("Рябина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑刺李");
        details.setDescriptionB("hēi cì lǐ");
        details.setDescriptionC("Blackthorn plum");
        details.setDescriptionD("Терновник( Тёрн)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("红豆杉果");
        details.setDescriptionB("hóng dòu shān guǒ");
        details.setDescriptionC("European yew");
        details.setDescriptionD("Тисс ягодный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("熊果/ 熊葡萄");
        details.setDescriptionB("xióng guǒ/ xióng pú táo");
        details.setDescriptionC("Bearberry");
        details.setDescriptionD("Толокнянка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("菲油果");
        details.setDescriptionB("fēi yóu guǒ");
        details.setDescriptionC("Feijoa");
        details.setDescriptionD("Фейхоа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("金菇娘/黄金莓");
        details.setDescriptionB("jīn gū niáng / huáng jīn méi");
        details.setDescriptionC("Physalis");
        details.setDescriptionD("Физалис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("麻黄");
        details.setDescriptionB("má huáng");
        details.setDescriptionC("Ephedra");
        details.setDescriptionD("Хвойник / Эфедра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("柿子");
        details.setDescriptionB("shì zi");
        details.setDescriptionC("Persimmon");
        details.setDescriptionD("Хурма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("稠李果");
        details.setDescriptionB("сhóu lǐ guǒ");
        details.setDescriptionC("Bird cherry");
        details.setDescriptionD("Черёмуха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("樱桃");
        details.setDescriptionB("yīng táo");
        details.setDescriptionC("Sweet cherry");
        details.setDescriptionD("Черешня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑醋栗/ 黑加仑");
        details.setDescriptionB("hēi cù lì / hēi jiā lún");
        details.setDescriptionC("Black currant");
        details.setDescriptionD("Чёрная смородина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑果枸杞");
        details.setDescriptionB("hēi guǒ gǒu qǐ");
        details.setDescriptionC("Black Goji / /n Black fruit wolfberry");
        details.setDescriptionD("Чёрный годжи (Дереза русская)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蓝莓");
        details.setDescriptionB("lán méi");
        details.setDescriptionC("Blueberry");
        details.setDescriptionD("Черника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白桑");
        details.setDescriptionB("bái sāng");
        details.setDescriptionC("White mulberry");
        details.setDescriptionD("Шелковица белая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑桑");
        details.setDescriptionB("hēi sāng");
        details.setDescriptionC("Black mulberry");
        details.setDescriptionD("Шелковица чёрная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("水牛果");
        details.setDescriptionB("shuǐ niú guǒ");
        details.setDescriptionC("Shepherdia/Buffaloberry/Bullberry");
        details.setDescriptionD("Шефердия/Ягода буйвола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("玫瑰果");
        details.setDescriptionB("méi guī guǒ");
        details.setDescriptionC("Rosehip");
        details.setDescriptionD("Шиповник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("仙人掌果");
        details.setDescriptionB("xiān rén zhǎng guǒ");
        details.setDescriptionC("Barbary Fig");
        details.setDescriptionD("Опунция индийская");
        detailsList.add(details);


    }
}
