package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C17 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("xiào chē");
        details.setDescriptionB("校车");
        details.setDescriptionC("School bus");
        details.setDescriptionD("Школьный автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xué xí");
        details.setDescriptionB("学习");
        details.setDescriptionC("Study/ Learn");
        details.setDescriptionD("Учить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dú");
        details.setDescriptionB("读");
        details.setDescriptionC("Read");
        details.setDescriptionD("Читать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dú");
        details.setDescriptionB("读");
        details.setDescriptionC("Read");
        details.setDescriptionD("Читать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiě");
        details.setDescriptionB("写");
        details.setDescriptionC("Write");
        details.setDescriptionD("Писать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà");
        details.setDescriptionB("画");
        details.setDescriptionC("Draw");
        details.setDescriptionD("Рисовать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán xué shēng");
        details.setDescriptionB("男学生");
        details.setDescriptionC("Schoolboy");
        details.setDescriptionD("Ученик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǚ xué shēng");
        details.setDescriptionB("女学生");
        details.setDescriptionC("Schoolgirl");
        details.setDescriptionD("Ученица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiào fú");
        details.setDescriptionB("校服");
        details.setDescriptionC("School uniform");
        details.setDescriptionD("Школьная форма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán lǎo shī");
        details.setDescriptionB("男老师");
        details.setDescriptionC("Male teacher");
        details.setDescriptionD("Учитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǚ lǎo shī");
        details.setDescriptionB("女老师");
        details.setDescriptionC("Female teacher");
        details.setDescriptionD("Учительница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiào zhǎng");
        details.setDescriptionB("校长");
        details.setDescriptionC("Head teacher/Principal");
        details.setDescriptionD("Директор школы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("líng");
        details.setDescriptionB("铃");
        details.setDescriptionC("Bell");
        details.setDescriptionD("Звонок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào shì");
        details.setDescriptionB("教室");
        details.setDescriptionC("Classroom");
        details.setDescriptionD("Классная комната");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mén");
        details.setDescriptionB("门");
        details.setDescriptionC("Door");
        details.setDescriptionD("Дверь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chuāng hù");
        details.setDescriptionB("窗户");
        details.setDescriptionC("Window");
        details.setDescriptionD("Окно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi bǎn");
        details.setDescriptionB("黑板");
        details.setDescriptionC("Blackboard");
        details.setDescriptionD("Школьная доска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fěn bǐ");
        details.setDescriptionB("粉笔");
        details.setDescriptionC("Chalk");
        details.setDescriptionD("Мел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng biǎo");
        details.setDescriptionB("钟表");
        details.setDescriptionC("Clock");
        details.setDescriptionD("Часы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huàn dēng jī");
        details.setDescriptionB("幻灯机");
        details.setDescriptionC("Overhead projector");
        details.setDescriptionD("Проектор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yī jià");
        details.setDescriptionB("衣架");
        details.setDescriptionC("Coat hanger");
        details.setDescriptionD("Вешалка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū zhuō/kè zhuō");
        details.setDescriptionB("书桌/课桌");
        details.setDescriptionC("Desk");
        details.setDescriptionD("Парта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎng tái");
        details.setDescriptionB("讲台");
        details.setDescriptionC("Teacher's table");
        details.setDescriptionD("Учительский стол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diǎn míng bù");
        details.setDescriptionB("点名簿");
        details.setDescriptionC("Roll-call book");
        details.setDescriptionD("Классный журнал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dì lǐ dì tú");
        details.setDescriptionB("地理地图");
        details.setDescriptionC("Map");
        details.setDescriptionD("Географическая карта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǐ zi");
        details.setDescriptionB("椅子");
        details.setDescriptionC("Chair");
        details.setDescriptionD("Стул");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū");
        details.setDescriptionB("书");
        details.setDescriptionC("Book");
        details.setDescriptionD("Книга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào kē shū");
        details.setDescriptionB("教科书");
        details.setDescriptionC("Textbook");
        details.setDescriptionD("Учебник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tú shū guǎn");
        details.setDescriptionB("图书馆");
        details.setDescriptionC("Library");
        details.setDescriptionD("Библиотека");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì diǎn");
        details.setDescriptionB("字典");
        details.setDescriptionC("Dictionary");
        details.setDescriptionD("Словарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū bāo");
        details.setDescriptionB("书包");
        details.setDescriptionC("School bag");
        details.setDescriptionD("Школьный рюкзак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jì suàn qì");
        details.setDescriptionB("计算器");
        details.setDescriptionC("Calculator");
        details.setDescriptionD("Калькулятор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liàn xí běn");
        details.setDescriptionB("练习本");
        details.setDescriptionC("Exercise book");
        details.setDescriptionD("Тетрадь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ jì běn");
        details.setDescriptionB("笔记本");
        details.setDescriptionC("Notebook");
        details.setDescriptionD("Блокнот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāng bǐ");
        details.setDescriptionB("钢笔");
        details.setDescriptionC("Pen");
        details.setDescriptionD("Ручка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiān bǐ");
        details.setDescriptionB("铅笔");
        details.setDescriptionC("Pencil");
        details.setDescriptionD("Карандаш");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сǎi sè qiān bǐ");
        details.setDescriptionB("彩色铅笔");
        details.setDescriptionC("Coloured pencils");
        details.setDescriptionD("Цветные карандаши");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("juǎn bǐ dāo");
        details.setDescriptionB("卷笔刀");
        details.setDescriptionC("Pencil sharpener");
        details.setDescriptionD("Точилка для карандашей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí chǐ");
        details.setDescriptionB("直尺");
        details.setDescriptionC("Ruler");
        details.setDescriptionD("Линейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān jiǎo bǎn");
        details.setDescriptionB("三角板");
        details.setDescriptionC("Set square");
        details.setDescriptionD("Угольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liáng jiǎo qì");
        details.setDescriptionB("量角器");
        details.setDescriptionC("Protractor");
        details.setDescriptionD("Транспортир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàng pí");
        details.setDescriptionB("橡皮");
        details.setDescriptionC("Eraser");
        details.setDescriptionD("Ластик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wén jù hé");
        details.setDescriptionB("文具盒");
        details.setDescriptionC("Pencil-box");
        details.setDescriptionD("Пенал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kè");
        details.setDescriptionB("课");
        details.setDescriptionC("Lesson");
        details.setDescriptionD("Урок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zuò yè");
        details.setDescriptionB("作业");
        details.setDescriptionC("Homework");
        details.setDescriptionD("Домашнее задание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo shì");
        details.setDescriptionB("考试");
        details.setDescriptionC("Exam/Examination");
        details.setDescriptionD("Экзамен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù xué");
        details.setDescriptionB("数学");
        details.setDescriptionC("Maths");
        details.setDescriptionD("Математика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jǐ hé");
        details.setDescriptionB("几何");
        details.setDescriptionC("Geometry");
        details.setDescriptionD("Геометрия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suàn shù");
        details.setDescriptionB("算术");
        details.setDescriptionC("Arithmetic");
        details.setDescriptionD("Арифметика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lì shǐ");
        details.setDescriptionB("历史");
        details.setDescriptionC("History");
        details.setDescriptionD("История");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīn yuè");
        details.setDescriptionB("音乐");
        details.setDescriptionC("Music");
        details.setDescriptionD("Музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dì lǐ");
        details.setDescriptionB("地理");
        details.setDescriptionC("Geography");
        details.setDescriptionD("География");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shēng wù xué");
        details.setDescriptionB("生物学");
        details.setDescriptionC("Biology");
        details.setDescriptionD("Биология");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà xué");
        details.setDescriptionB("化学");
        details.setDescriptionC("Chemistry");
        details.setDescriptionD("Химия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wù lǐ");
        details.setDescriptionB("物理");
        details.setDescriptionC("Physics");
        details.setDescriptionD("Физика");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi shù");
        details.setDescriptionB("美术");
        details.setDescriptionC("Painting/Art");
        details.setDescriptionD("Рисование");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ yù");
        details.setDescriptionB("体育");
        details.setDescriptionC("Physical education");
        details.setDescriptionD("Физкультура");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wài yǔ");
        details.setDescriptionB("外语");
        details.setDescriptionC("Foreign language");
        details.setDescriptionD("Иностранный язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng yǔ");
        details.setDescriptionB("英语");
        details.setDescriptionC("English");
        details.setDescriptionD("Английский язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng wén/ hànyǔ");
        details.setDescriptionB("中文/汉语");
        details.setDescriptionC("Chinese");
        details.setDescriptionD("Китайский язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é yǔ");
        details.setDescriptionB("俄语");
        details.setDescriptionC("Russian language");
        details.setDescriptionD("Русский язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wén xué");
        details.setDescriptionB("文学");
        details.setDescriptionC("Literature");
        details.setDescriptionD("Литература");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jì shù");
        details.setDescriptionB("计数");
        details.setDescriptionC("Count");
        details.setDescriptionD("Считать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā hào");
        details.setDescriptionB("加号");
        details.setDescriptionC("Plus");
        details.setDescriptionD("Плюс (знак)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎn hào");
        details.setDescriptionB("减号");
        details.setDescriptionC("Minus");
        details.setDescriptionD("Минус (знак)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("děng yú");
        details.setDescriptionB("等于");
        details.setDescriptionC("Equals");
        details.setDescriptionD("Равно (знак)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā");
        details.setDescriptionB("加");
        details.setDescriptionC("Add");
        details.setDescriptionD("Прибавлять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎn");
        details.setDescriptionB("减");
        details.setDescriptionC("Subtract");
        details.setDescriptionD("Вычитать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chéng");
        details.setDescriptionB("乘");
        details.setDescriptionC("Multiply");
        details.setDescriptionD("Умножать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chú");
        details.setDescriptionB("除");
        details.setDescriptionC("Divide");
        details.setDescriptionD("Делить");
        detailsList.add(details);


    }
}
