package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C24 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" è yú ");
        details.setDescriptionB("鳄鱼");
        details.setDescriptionC("Crocodile");
        details.setDescriptionD("Крокодил");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duǎn wěn è ");
        details.setDescriptionB("短吻鳄");
        details.setDescriptionC("Alligator");
        details.setDescriptionD("Аллигатор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng  wěn è ");
        details.setDescriptionB("长吻鳄");
        details.setDescriptionC(" Gharial/ Gavial ");
        details.setDescriptionD("Гавиал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎi mén è ");
        details.setDescriptionB("凯门鳄");
        details.setDescriptionC("Caiman");
        details.setDescriptionD("Кайман");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī yì ");
        details.setDescriptionB("蜥蜴");
        details.setDescriptionC("Lizard");
        details.setDescriptionD("Ящерица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǜ xī yì ");
        details.setDescriptionB("绿蜥蜴");
        details.setDescriptionC("Green lizard");
        details.setDescriptionD("Зелёная ящерица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bì hǔ ");
        details.setDescriptionB("壁虎");
        details.setDescriptionC(" Gecko ");
        details.setDescriptionD("Геккон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大壁虎");
        details.setDescriptionB("dà bì hǔ ");
        details.setDescriptionC("Tokay gecko");
        details.setDescriptionD("Геккон токи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí xī ");
        details.setDescriptionB("棘蜥");
        details.setDescriptionC("Moloch/Thorny Devil");
        details.setDescriptionD("Ящерица молох");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sǎn xī ");
        details.setDescriptionB("伞蜥");
        details.setDescriptionC("Frilled Lizard");
        details.setDescriptionD("Плащеносная ящерица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jù xī");
        details.setDescriptionB("巨蜥");
        details.setDescriptionC("Varan");
        details.setDescriptionD("Варан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn bān jù xī ");
        details.setDescriptionB("眼斑巨蜥");
        details.setDescriptionC("Perentie");
        details.setDescriptionD("Гигантский варан/Перенти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liè xī ");
        details.setDescriptionB("鬣蜥");
        details.setDescriptionC("Iguana");
        details.setDescriptionD("Игуана");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā lā pà gē sī hǎi liè xī ");
        details.setDescriptionB("加拉帕戈斯海鬣蜥");
        details.setDescriptionC("Marine Iguana");
        details.setDescriptionD("Морская игуана");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" biàn sè lóng ");
        details.setDescriptionB("变色龙");
        details.setDescriptionC(" Chameleon ");
        details.setDescriptionD(" Хамелеон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān jiǎo biàn sè lóng ");
        details.setDescriptionB("三角变色龙");
        details.setDescriptionC("Jackson's three-horned chameleon");
        details.setDescriptionD("Хамелеон Джексона/ Трёхрогий хамелеон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wū guī / lù guī ");
        details.setDescriptionB("乌龟/陆龟");
        details.setDescriptionC("Tortoise");
        details.setDescriptionD("Черепаха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi guī ");
        details.setDescriptionB("海龟");
        details.setDescriptionC("Sea turtle");
        details.setDescriptionD("Морская черепаха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("róng yuán");
        details.setDescriptionB("蝾螈");
        details.setDescriptionC("Salamander ");
        details.setDescriptionD("Саламандра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu huá yuán ");
        details.setDescriptionB("  欧洲滑螈");
        details.setDescriptionC("Newt");
        details.setDescriptionD("Тритон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòng yuán /máng yuán");
        details.setDescriptionB("洞螈/盲螈");
        details.setDescriptionC("Olm /Proteus ");
        details.setDescriptionD("Олм/Протей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng wā ");
        details.setDescriptionB("青蛙");
        details.setDescriptionC("Frog");
        details.setDescriptionD("Лягушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("há ma/chán chú");
        details.setDescriptionB("蛤蟆/蟾蜍");
        details.setDescriptionC("Toad");
        details.setDescriptionD("Жаба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shù wā ");
        details.setDescriptionB("树蛙");
        details.setDescriptionC("Tree frog");
        details.setDescriptionD("Квакша/Древесная лягушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng yǎn shù wā ");
        details.setDescriptionB("红眼树蛙");
        details.setDescriptionC(" Red-eyed tree frog ");
        details.setDescriptionD("Красноглазая квакша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shé");
        details.setDescriptionB("蛇");
        details.setDescriptionC("Snake");
        details.setDescriptionD("Змея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái shé");
        details.setDescriptionB("白蛇");
        details.setDescriptionC(" White snake ");
        details.setDescriptionD("Белая змея ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn jìng wáng shé ");
        details.setDescriptionB("眼镜王蛇");
        details.setDescriptionC("King Cobra");
        details.setDescriptionD(" Королевская кобра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jù rán ");
        details.setDescriptionB("巨蚺");
        details.setDescriptionC("Boa snake");
        details.setDescriptionD("Боа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎng shé");
        details.setDescriptionB("蟒蛇");
        details.setDescriptionC("Python");
        details.setDescriptionD("Питон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kuí shé ");
        details.setDescriptionB("蝰蛇");
        details.setDescriptionC(" Adder ");
        details.setDescriptionD("Гадюка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎng wěi shé");
        details.setDescriptionB("响尾蛇");
        details.setDescriptionC("Rattlesnake");
        details.setDescriptionD("Гремучая змея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shān hú shé ");
        details.setDescriptionB("珊瑚蛇");
        details.setDescriptionC(" Coral snake");
        details.setDescriptionD("Коралловая змея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yà mǎ xùn sēn rán ");
        details.setDescriptionB("亚马逊森蚺");
        details.setDescriptionC("Anaconda");
        details.setDescriptionD("Анаконда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ shé");
        details.setDescriptionB("水蛇");
        details.setDescriptionC("Grass snake/Water snake");
        details.setDescriptionD("Уж ");
        detailsList.add(details);
        

    }
}
