package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C4 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("出生");
        details.setDescriptionB("chū shēng");
        details.setDescriptionC("Birth");
        details.setDescriptionD("Рождение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("出生证明");
        details.setDescriptionB("сhū shēng zhèng míng");
        details.setDescriptionC("Birth certificate");
        details.setDescriptionD("Свидетельство о рождении");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("洗礼");
        details.setDescriptionB("xǐ lǐ");
        details.setDescriptionC("Christening");
        details.setDescriptionD("Крещение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("上幼儿园");
        details.setDescriptionB("shàng yòu ér yuán");
        details.setDescriptionC("Go to a kindergarten");
        details.setDescriptionD("Пойти в детский сад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("交朋友");
        details.setDescriptionB("jiāo péng yǒu");
        details.setDescriptionC("Make friends");
        details.setDescriptionD("Заводить друзей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("入学/上学");
        details.setDescriptionB("rù xué/ shàng xué");
        details.setDescriptionC("Go to school");
        details.setDescriptionD("Пойти в школу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("毕业");
        details.setDescriptionB("bì yè");
        details.setDescriptionC("Graduate");
        details.setDescriptionD("Окончить учебное заведение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("毕业典礼");
        details.setDescriptionB("bì yè diǎn lǐ");
        details.setDescriptionC("Graduation");
        details.setDescriptionD("Выпускной");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("恋爱");
        details.setDescriptionB("liàn ài");
        details.setDescriptionC("Fall in love");
        details.setDescriptionD("Влюбиться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("就业");
        details.setDescriptionB("jiù yè");
        details.setDescriptionC("Get a job");
        details.setDescriptionD("Получить работу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("移民");
        details.setDescriptionB("yí mín");
        details.setDescriptionC("Emigrate");
        details.setDescriptionD("Эмигрировать/ Переселяться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("结婚");
        details.setDescriptionB("jié hūn");
        details.setDescriptionC("Get married");
        details.setDescriptionD("Пожениться/Выйти замуж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("婚礼");
        details.setDescriptionB("hūn lǐ");
        details.setDescriptionC("Wedding");
        details.setDescriptionD("Бракосочетание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("婚宴");
        details.setDescriptionB("hūn yàn");
        details.setDescriptionC("Wedding party");
        details.setDescriptionD("Свадьба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蜜月");
        details.setDescriptionB("mì yuè");
        details.setDescriptionC("Honeymoon");
        details.setDescriptionD("Медовый месяц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("纪念日");
        details.setDescriptionB("jì niàn rì");
        details.setDescriptionC("Anniversary");
        details.setDescriptionD("Юбилей/ Годовщина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("生孩子");
        details.setDescriptionB("shēng hái zi");
        details.setDescriptionC("Have a baby");
        details.setDescriptionD("Рождение ребенка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("离婚");
        details.setDescriptionB("lí hūn");
        details.setDescriptionC("Divorce");
        details.setDescriptionD("Развод");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("退休");
        details.setDescriptionB("tuì xiū");
        details.setDescriptionC("Retire");
        details.setDescriptionD("Выйти на пенсию");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("死亡");
        details.setDescriptionB("sǐ wáng");
        details.setDescriptionC("Die");
        details.setDescriptionD("Умереть/Скончаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("死亡");
        details.setDescriptionB("sǐ wáng");
        details.setDescriptionC("Death");
        details.setDescriptionD("Смерть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("葬礼");
        details.setDescriptionB("zàng lǐ");
        details.setDescriptionC("Funeral");
        details.setDescriptionD("Похороны");
        detailsList.add(details);

    }

}
