package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C41 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("bīng xiāng");
        details.setDescriptionB("冰箱");
        details.setDescriptionC("Fridge");
        details.setDescriptionD("Холодильник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lěng guì");
        details.setDescriptionB("冷柜");
        details.setDescriptionC("Freezer");
        details.setDescriptionD("Морозильная камера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ yī jī");
        details.setDescriptionB("洗衣机");
        details.setDescriptionC("Washing machine");
        details.setDescriptionD("Стиральная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn nuǎn qì ");
        details.setDescriptionB("电暖气");
        details.setDescriptionC("Heater");
        details.setDescriptionD("Обогреватель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rè shuǐ qì");
        details.setDescriptionB("热水器");
        details.setDescriptionC("Water heater");
        details.setDescriptionD("Водонагреватель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guò lǜ qì ");
        details.setDescriptionB("水过滤器");
        details.setDescriptionC("Water filter");
        details.setDescriptionD("Фильтр для воды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kōng tiáo");
        details.setDescriptionB("空调");
        details.setDescriptionC(" Air conditioner");
        details.setDescriptionD("Кондиционер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn fēng shàn ");
        details.setDescriptionB("电风扇");
        details.setDescriptionC("Fan");
        details.setDescriptionD("Вентилятор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kōng qì jìng huà qì ");
        details.setDescriptionB("空气净化器");
        details.setDescriptionC("Air purifier");
        details.setDescriptionD("Очиститель воздуха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kōng qì jiā shī qì ");
        details.setDescriptionB("空气加湿器");
        details.setDescriptionC("Humidifier");
        details.setDescriptionD("Увлажнитель воздуха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī yóu yān jī ");
        details.setDescriptionB("吸油烟机");
        details.setDescriptionC("Kitchen hood");
        details.setDescriptionD("Вытяжка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēi bō lú ");
        details.setDescriptionB("微波炉");
        details.setDescriptionC("Microwave oven");
        details.setDescriptionD("Микроволновая печь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duō gōng néng chuī jù ");
        details.setDescriptionB("多功能炊具");
        details.setDescriptionC("Multi-Cooker");
        details.setDescriptionD("Мультиварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo yā  guō");
        details.setDescriptionB("高压锅");
        details.setDescriptionC("Pressure cooker");
        details.setDescriptionD("Скороварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shāo kǎo lú");
        details.setDescriptionB("烧烤炉");
        details.setDescriptionC("BBQ Grill");
        details.setDescriptionD("Электрошашлычница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn dòng jiǎo ròu jī ");
        details.setDescriptionB("电动绞肉机");
        details.setDescriptionC("Electric meat grinder");
        details.setDescriptionD("Электромясорубка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu dòng jiǎo ròu jī ");
        details.setDescriptionB("手动绞肉机");
        details.setDescriptionC(" Meat grinder");
        details.setDescriptionD("Мясорубка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn kǎo bǐng guō ");
        details.setDescriptionB("电烤饼锅");
        details.setDescriptionC("Pancake maker");
        details.setDescriptionD("Электроблинница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn shuǐ hú ");
        details.setDescriptionB("电水壶");
        details.setDescriptionC("Electric kettle");
        details.setDescriptionD("Электрочайник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhēng guō ");
        details.setDescriptionB("蒸锅");
        details.setDescriptionC("Double boiler ");
        details.setDescriptionD("Пароварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn fàn bāo ");
        details.setDescriptionB("电饭煲");
        details.setDescriptionC("Rice cooker");
        details.setDescriptionD("Рисоварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu zhá guō ");
        details.setDescriptionB(" 油炸锅");
        details.setDescriptionC("Deep fryer");
        details.setDescriptionD("Фритюрница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān nǎi jī ");
        details.setDescriptionB("酸奶机");
        details.setDescriptionC("Yogurt maker");
        details.setDescriptionD("Йогуртница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kā fēi jī ");
        details.setDescriptionB("咖啡机");
        details.setDescriptionC("Coffee machine");
        details.setDescriptionD("Кофеварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi yán mó jī ");
        details.setDescriptionB("咖啡研磨机");
        details.setDescriptionC("Coffee grinder");
        details.setDescriptionD("Кофемолка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn bāo jī ");
        details.setDescriptionB("面包机");
        details.setDescriptionC("Bread machine/ Bread maker ");
        details.setDescriptionD("Хлебопечка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎo miàn bāo jī ");
        details.setDescriptionB("烤面包机");
        details.setDescriptionC(" Toaster ");
        details.setDescriptionD("Тостер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng dǎ dàn qì ");
        details.setDescriptionB("电动打蛋器");
        details.setDescriptionC(" Egg-beater ");
        details.setDescriptionD("Миксер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǔ dàn qì ");
        details.setDescriptionB("煮蛋器");
        details.setDescriptionC(" Egg cooker ");
        details.setDescriptionD("Яйцеварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎo bàn jī ");
        details.setDescriptionB("搅拌机");
        details.setDescriptionC("Blender");
        details.setDescriptionD("Блендер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě gāo jī /bīng qí lín jī ");
        details.setDescriptionB("雪糕机/冰淇淋机");
        details.setDescriptionC("Ice cream maker");
        details.setDescriptionD("Мороженница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ zhī jī / zhà zhī jī ");
        details.setDescriptionB("果汁机/榨汁机");
        details.setDescriptionC("Juice machine ");
        details.setDescriptionD("Соковыжималка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā suàn qì ");
        details.setDescriptionB("压蒜器");
        details.setDescriptionC(" Garlic press ");
        details.setDescriptionD(" Пресс для чеснока / Чесночница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ wǎn jī ");
        details.setDescriptionB("洗碗机");
        details.setDescriptionC("Dishwasher");
        details.setDescriptionD("Посудомоечная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rán qì zào");
        details.setDescriptionB("燃气灶");
        details.setDescriptionC(" Gas stove ");
        details.setDescriptionD("Плита газовая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn lú ");
        details.setDescriptionB("电炉");
        details.setDescriptionC("Electric stove");
        details.setDescriptionD("Плита электрическая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn cí lú ");
        details.setDescriptionB("电磁炉");
        details.setDescriptionC("Induction cooker");
        details.setDescriptionD("Плита индукционная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo xiāng ");
        details.setDescriptionB("烤箱");
        details.setDescriptionC(" Oven ");
        details.setDescriptionD("Духовка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī chén qì");
        details.setDescriptionB("吸尘器");
        details.setDescriptionC("Vacuum cleaner");
        details.setDescriptionD("Пылесос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāo dú chú guì ");
        details.setDescriptionB("消毒橱柜");
        details.setDescriptionC(" Disinfection cupboard ");
        details.setDescriptionD("Дезинфекционный шкаф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn nǎo ");
        details.setDescriptionB("电脑");
        details.setDescriptionC(" Сomputer ");
        details.setDescriptionD("Компьютер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ jì běn diàn nǎo ");
        details.setDescriptionB("笔记本电脑");
        details.setDescriptionC("Laptop");
        details.setDescriptionD("Ноутбук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhào piàn dǎ yìn jī");
        details.setDescriptionB("照片打印机");
        details.setDescriptionC("Photo printer");
        details.setDescriptionD("Фотопринтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎ yìn jī ");
        details.setDescriptionB("打印机");
        details.setDescriptionC("Printer");
        details.setDescriptionD("Принтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lù yīn bǐ ");
        details.setDescriptionB("录音笔");
        details.setDescriptionC("Dictaphone");
        details.setDescriptionD("Диктофон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("MP3");
        details.setDescriptionB("MP3 player");
        details.setDescriptionC("MP3-плеер ");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("CD bō fàng qì ");
        details.setDescriptionB(" CD播放器");
        details.setDescriptionC("CD player ");
        details.setDescriptionD("CD-плеер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shōu yīn jī ");
        details.setDescriptionB("收音机");
        details.setDescriptionC("Radio");
        details.setDescriptionD("Радио");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lù xiàng jī ");
        details.setDescriptionB("录像机");
        details.setDescriptionC("Video recorder");
        details.setDescriptionD("Видеомагнитофон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn shì jī ");
        details.setDescriptionB("电视机");
        details.setDescriptionC("TV-set");
        details.setDescriptionD("Телевизор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn shì jī dǐng hé ");
        details.setDescriptionB("电视机顶盒");
        details.setDescriptionC(" TV set-top box ");
        details.setDescriptionD("ТВ приставка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mài kè fēng ");
        details.setDescriptionB("麦克风");
        details.setDescriptionC("Microphone");
        details.setDescriptionD("Микрофон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā tíng yǐng yuàn ");
        details.setDescriptionB("家庭影院");
        details.setDescriptionC("Home cinema");
        details.setDescriptionD("Домашний кинотеатр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn huà");
        details.setDescriptionB("电话");
        details.setDescriptionC("Telephone");
        details.setDescriptionD("Телефон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu jī");
        details.setDescriptionB("手机");
        details.setDescriptionC("Mobile phone");
        details.setDescriptionD("Мобильный телефон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàng jī/shù mǎ xiàng jī");
        details.setDescriptionB("相机/数码相机");
        details.setDescriptionC("Digital camera");
        details.setDescriptionD("Цифровой фотоаппарат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shè xiàng jī ");
        details.setDescriptionB("摄像机");
        details.setDescriptionC("Video camera");
        details.setDescriptionD("Видеокамера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xū nǐ xiàn shí yǎn jìng");
        details.setDescriptionB("虚拟现实眼镜");
        details.setDescriptionC("Virtual reality glasses");
        details.setDescriptionD("Очки виртуальной реальности");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng bǎn diàn nǎo ");
        details.setDescriptionB("平板电脑");
        details.setDescriptionC("Tablet");
        details.setDescriptionD("Планшет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn zǐ chèng ");
        details.setDescriptionB("电子秤");
        details.setDescriptionC(" Electronic scale ");
        details.setDescriptionD(" Электронные весы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sǎo dì jī qì rén ");
        details.setDescriptionB("扫地机器人");
        details.setDescriptionC("Robot vacuum cleaner ");
        details.setDescriptionD("Робот-пылесос ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn zǐ tǐ wēn jì ");
        details.setDescriptionB("电子体温计 ");
        details.setDescriptionC(" Electronic thermometer ");
        details.setDescriptionD("Электронный термометр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēn dù jì ");
        details.setDescriptionB("温度计");
        details.setDescriptionC("Thermometer");
        details.setDescriptionD("Термометр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chuī fēng jī");
        details.setDescriptionB("吹风机");
        details.setDescriptionC("Hair dryer");
        details.setDescriptionD("Фен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" juǎn fà bàng /juǎn fà qì ");
        details.setDescriptionB("卷发棒/卷发器");
        details.setDescriptionC("Hair curling iron");
        details.setDescriptionD("Плойка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhí fà qì ");
        details.setDescriptionB("直发器");
        details.setDescriptionC("Straightening iron");
        details.setDescriptionD("Утюжка для волос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pào jiǎo pén ");
        details.setDescriptionB("泡脚盆");
        details.setDescriptionC("  Foot bath ");
        details.setDescriptionD("Гидромассажная ванночка для ног");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn dòng àn mó qì");
        details.setDescriptionB("电动按摩器");
        details.setDescriptionC("Electric massager");
        details.setDescriptionD("Электромассажёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí nǐ rì guāng yù ");
        details.setDescriptionB("迷你日光浴");
        details.setDescriptionC("Mini solarium");
        details.setDescriptionD("Мини-солярий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("féng rèn jī");
        details.setDescriptionB("缝纫机");
        details.setDescriptionC("Sewing machine");
        details.setDescriptionD("Швейная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suǒ fèng jī");
        details.setDescriptionB(" 锁缝机");
        details.setDescriptionC("Overlock machine");
        details.setDescriptionD("Оверлок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hōng gān jī");
        details.setDescriptionB("烘干机");
        details.setDescriptionC("Drying machine/Dryer");
        details.setDescriptionD("Сушильная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn tàng jī");
        details.setDescriptionB("熨烫机");
        details.setDescriptionC("Ironing press");
        details.setDescriptionD("Гладильный пресс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dǒu ");
        details.setDescriptionB("熨斗");
        details.setDescriptionC("Iron");
        details.setDescriptionD("Утюг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guà tàng jī ");
        details.setDescriptionB("挂烫机");
        details.setDescriptionC("Clothes steamer");
        details.setDescriptionD("Отпариватель для одежды ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gān xié qì ");
        details.setDescriptionB("干鞋器");
        details.setDescriptionC("Shoes dryer");
        details.setDescriptionD("Сушилка для обуви");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng wài xiàn tǐ wēn jì");
        details.setDescriptionB("红外线体温计");
        details.setDescriptionC(" Infrared electric thermometer");
        details.setDescriptionD("Инфрокрасный электрический термометр");
        detailsList.add(details);
    }
}
