package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C44 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" bái guàn ");
        details.setDescriptionB("白鹳");
        details.setDescriptionC("White Stork ");
        details.setDescriptionD("Белый аист ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi guàn ");
        details.setDescriptionB("黑鹳");
        details.setDescriptionC(" Black Stork ");
        details.setDescriptionD("Чёрный аист ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  dōng fāng bái guàn ");
        details.setDescriptionB("东方白鹳");
        details.setDescriptionC("Oriental Stork ");
        details.setDescriptionD("Дальневосточный  аист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái fù guàn ");
        details.setDescriptionB("白腹鹳");
        details.setDescriptionC(" Abdim's stork/ White-bellied stork ");
        details.setDescriptionD(" Белобрюхий аист  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái jǐng guàn ");
        details.setDescriptionB("白颈鹳");
        details.setDescriptionC("Woolly-necked Stork");
        details.setDescriptionD(" Белошейный аист ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi wěi guàn ");
        details.setDescriptionB("黑尾鹳");
        details.setDescriptionC(" Maguari stork ");
        details.setDescriptionD(" Американский аист ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān zuǐ guàn ");
        details.setDescriptionB("鞍嘴鹳");
        details.setDescriptionC("Saddle-billed Stork ");
        details.setDescriptionD(" Седлоклювый ябиру");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng liǎn guàn ");
        details.setDescriptionB("黄脸鹳");
        details.setDescriptionC("Storm's Stork");
        details.setDescriptionD(" Малайский шерстистошейный аист ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng zuǐ huán guàn ");
        details.setDescriptionB("黄嘴鹮鹳");
        details.setDescriptionC("Yellow-billed Stork");
        details.setDescriptionD(" Африканский клювач ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái tóu huán guàn ");
        details.setDescriptionB("白头鹮鹳");
        details.setDescriptionC("Painted Stork ");
        details.setDescriptionD("Индийский клювач ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái hè");
        details.setDescriptionB("白鹤");
        details.setDescriptionC(" Crane ");
        details.setDescriptionD("Белый журавль/ Стерх");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi zhōu hè");
        details.setDescriptionB("美洲鹤");
        details.setDescriptionC("Whooping Crane");
        details.setDescriptionD("Американский журавль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái zhěn hè ");
        details.setDescriptionB("白枕鹤");
        details.setDescriptionC("White-naped Crane ");
        details.setDescriptionD(" Даурский журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī hè ");
        details.setDescriptionB(" 灰鹤");
        details.setDescriptionC("  Common Crane ");
        details.setDescriptionD("Серый журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào zhōu hè ");
        details.setDescriptionB("澳洲鹤");
        details.setDescriptionC(" Australian crane ");
        details.setDescriptionD("Австралийский журавль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ròu chuí hè ");
        details.setDescriptionB("肉垂鹤");
        details.setDescriptionC("Wattled crane ");
        details.setDescriptionD("Серёжчатый журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蓑羽鹤");
        details.setDescriptionB(" suō yǔ hè ");
        details.setDescriptionC("Demoiselle Crane");
        details.setDescriptionD("Журавль-красавка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā qiū hè ");
        details.setDescriptionB("沙丘鹤");
        details.setDescriptionC("  Sandhill Crane ");
        details.setDescriptionD("Канадский журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhì jǐng hè ");
        details.setDescriptionB("赤颈鹤");
        details.setDescriptionC(" Sarus Crane ");
        details.setDescriptionD("Индийский журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán suō yǔ hè ");
        details.setDescriptionB("蓝蓑羽鹤");
        details.setDescriptionC(" Blue Crane ");
        details.setDescriptionD("Райский журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi jǐng hè");
        details.setDescriptionB("黑颈鹤");
        details.setDescriptionC("Black-necked Crane");
        details.setDescriptionD("Черношейный журавль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān dǐng hè ");
        details.setDescriptionB("丹顶鹤");
        details.setDescriptionC(" Red-crowned crane/ Japanese Crane");
        details.setDescriptionD("Японский журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi guān hè");
        details.setDescriptionB("黑冠鹤");
        details.setDescriptionC(" Black Crowned Crane ");
        details.setDescriptionD("Венценосный журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huī guān hè ");
        details.setDescriptionB("灰冠鹤");
        details.setDescriptionC("Grey crowned-crane ");
        details.setDescriptionD("Восточный венценосный журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái tóu hè ");
        details.setDescriptionB("白头鹤");
        details.setDescriptionC("Hooded Crane ");
        details.setDescriptionD("Чёрный журавль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái huán");
        details.setDescriptionB("白鹮");
        details.setDescriptionC("White Ibis/Black-headed Ibis");
        details.setDescriptionD(" Черноголовый ибис/Индийский ибис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shèng huán");
        details.setDescriptionB("圣鹮");
        details.setDescriptionC(" African sacred ibis ");
        details.setDescriptionD("Священный ибис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сǎi huán ");
        details.setDescriptionB("彩鹮");
        details.setDescriptionC("Glossy ibis");
        details.setDescriptionD(" Каравайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi zhōu hóng huán ");
        details.setDescriptionB("美洲红鹮");
        details.setDescriptionC("Scarlet Ibis ");
        details.setDescriptionD("Красный ибис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǜ huán");
        details.setDescriptionB("绿鹮");
        details.setDescriptionC(" Green Ibis");
        details.setDescriptionD("Зелёный ибис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǐn huán ");
        details.setDescriptionB("隐鹮");
        details.setDescriptionC(" Northern Bald Ibis ");
        details.setDescriptionD("Лесной ибис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fǎn zuǐ yù ");
        details.setDescriptionB("反嘴鹬");
        details.setDescriptionC("American Avocet ");
        details.setDescriptionD("Американская шилоклювка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǒng què ");
        details.setDescriptionB("孔雀");
        details.setDescriptionC(" Peacock ");
        details.setDescriptionD("Павлин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ kǒng què ");
        details.setDescriptionB("绿孔雀 ");
        details.setDescriptionC("Green peafowl ");
        details.setDescriptionD("Зелёный павлин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gāng guǒ kǒng què ");
        details.setDescriptionB("刚果孔雀");
        details.setDescriptionC(" Congo peafowl  ");
        details.setDescriptionD("Конголезский павлин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái kǒng què ");
        details.setDescriptionB("白孔雀");
        details.setDescriptionC("White Peacock ");
        details.setDescriptionD("Белый павлин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi kǒng què");
        details.setDescriptionB("黑孔雀");
        details.setDescriptionC("Black Peacock");
        details.setDescriptionD("Угольный павлин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhì jī");
        details.setDescriptionB("雉鸡");
        details.setDescriptionC("Pheasant");
        details.setDescriptionD(" Фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī kǒng què zhì ");
        details.setDescriptionB("灰孔雀雉");
        details.setDescriptionC("Grey Peacock-Pheasant");
        details.setDescriptionD(" Серый павлиний фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān kǒng què zhì ");
        details.setDescriptionB("山孔雀雉 ");
        details.setDescriptionC("Mountain Peacock Pheasant");
        details.setDescriptionD("Горный павлиний фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tóng wěi kǒng què zhì ");
        details.setDescriptionB("铜尾孔雀雉");
        details.setDescriptionC("Bronze-tailed Peacock-Pheasant  ");
        details.setDescriptionD(" Бронзовохвостый павлиний фазан  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ lái kǒng què zhì ");
        details.setDescriptionB("马来孔雀雉");
        details.setDescriptionC("Malayan Peacock-Pheasant ");
        details.setDescriptionD(" Малайский павлиний фазан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn bān kǒng què zhì ");
        details.setDescriptionB("眼斑孔雀雉");
        details.setDescriptionC("Germain's Peacock-Pheasant ");
        details.setDescriptionD("Павлиний фазан Жермена ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā lā wàng kǒng què zhì ");
        details.setDescriptionB("巴拉望孔雀雉");
        details.setDescriptionC(" Palawan peacock-pheasant ");
        details.setDescriptionD("Палаванский павлиний фазан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pó luó zhōu kǒng què zhì ");
        details.setDescriptionB("婆罗洲孔雀雉");
        details.setDescriptionC("Bornean Peacock-Pheasant ");
        details.setDescriptionD("Борнейский павлиний фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zàng mǎ jī ");
        details.setDescriptionB("藏马鸡 ");
        details.setDescriptionC("Tibetan Eared Pheasant");
        details.setDescriptionD(" Тибетский ушастый фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi xián");
        details.setDescriptionB("黑鹇");
        details.setDescriptionC("Kalij Pheasant");
        details.setDescriptionD("Непальский фазан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng jī ");
        details.setDescriptionB("松鸡 ");
        details.setDescriptionC("Western Capercaillie /Wood grouse ");
        details.setDescriptionD("Глухарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà bái lù ");
        details.setDescriptionB(" 大白鹭");
        details.setDescriptionC(" Great White Heron ");
        details.setDescriptionD("Большая белая цапля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cāng lù ");
        details.setDescriptionB("苍鹭");
        details.setDescriptionC("Grey Heron/ Gray Heron ");
        details.setDescriptionD(" Серая цапля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà lán lù ");
        details.setDescriptionB("大蓝鹭");
        details.setDescriptionC("Great Blue Heron ");
        details.setDescriptionD("Большая голубая цапля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi tóu lù");
        details.setDescriptionB("黑头鹭");
        details.setDescriptionC("Black-headed Heron");
        details.setDescriptionD("Черношейная цапля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi lù ");
        details.setDescriptionB("黑鹭");
        details.setDescriptionC(" Black Heron ");
        details.setDescriptionD("Чёрная цапля ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сǎo lù ");
        details.setDescriptionB("草鹭");
        details.setDescriptionC(" Purple Heron ");
        details.setDescriptionD("Рыжая цапля ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ liè niǎo ");
        details.setDescriptionB("火烈鸟");
        details.setDescriptionC(" Flamingo ");
        details.setDescriptionD("Фламинго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà hóng guàn ");
        details.setDescriptionB("大红鹳");
        details.setDescriptionC("Greater flamingo");
        details.setDescriptionD(" Розовый фламинго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā lè bǐ hǎi hóng guàn ");
        details.setDescriptionB("加勒比海红鹳 ");
        details.setDescriptionC("American Flamingo/ Caribbean Flamingo ");
        details.setDescriptionD("Красный фламинго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo hóng guàn / xiǎo huǒ liè niǎo ");
        details.setDescriptionB("小红鹳/小火烈鸟");
        details.setDescriptionC(" Lesser flamingo ");
        details.setDescriptionD("Малый фламинго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhān mǔ sī huǒ liè niǎo ");
        details.setDescriptionB("詹姆斯火烈鸟");
        details.setDescriptionC("James's flamingo");
        details.setDescriptionD(" Фламинго Джемса  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhì lì hóng guàn ");
        details.setDescriptionB("智利红鹳");
        details.setDescriptionC("Chilean Flamingo ");
        details.setDescriptionD("Чилийский фламинго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān dì sī hóng guàn");
        details.setDescriptionB("安第斯红鹳");
        details.setDescriptionC("Andean flamingo");
        details.setDescriptionD("Андский фламинго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi zhōu pí lù");
        details.setDescriptionB("非洲琵鹭");
        details.setDescriptionC("African Spoonbill");
        details.setDescriptionD("Белая колпица/ Африканская колпица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fěn hóng pí lù ");
        details.setDescriptionB("粉红琵鹭 ");
        details.setDescriptionC("Roseate Spoonbill ");
        details.setDescriptionD("Розовая колпица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái pí lù ");
        details.setDescriptionB("白琵鹭");
        details.setDescriptionC("Eurasian spoonbill");
        details.setDescriptionD("Обыкновенная колпица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào zhōu pí lù ");
        details.setDescriptionB("澳洲琵鹭");
        details.setDescriptionC("Royal Spoonbill ");
        details.setDescriptionD("Королевская колпица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi liǎn pí lù ");
        details.setDescriptionB("黑脸琵鹭");
        details.setDescriptionC("Black-faced spoonbill ");
        details.setDescriptionD("Малая колпица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng zuǐ pí lù ");
        details.setDescriptionB("黄嘴琵鹭");
        details.setDescriptionC(" Yellow-billed Spoonbill ");
        details.setDescriptionD("Желтоклювая колпица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tí hú ");
        details.setDescriptionB("鹈鹕");
        details.setDescriptionC(" Pelican ");
        details.setDescriptionD("Пеликан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("美洲白鹈鹕");
        details.setDescriptionB(" měi zhōu bái tí hú ");
        details.setDescriptionC("American White Pelican ");
        details.setDescriptionD("Американский белый пеликан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǔ tōng lú cí ");
        details.setDescriptionB("普通鸬鹚 ");
        details.setDescriptionC("Great Cormorant ");
        details.setDescriptionD("Большой баклан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng xìn tiān wēng ");
        details.setDescriptionB("皇信天翁");
        details.setDescriptionC("Royal Albatross ");
        details.setDescriptionD("Королевский альбатрос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" piāo bó xìn tiān wēng ");
        details.setDescriptionB("漂泊信天翁");
        details.setDescriptionC(" Wandering Albatross ");
        details.setDescriptionD("Странствующий альбатрос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi yǔ yàn ");
        details.setDescriptionB("黑雨燕");
        details.setDescriptionC("Black Swift");
        details.setDescriptionD(" Чёрный американский стриж ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  gāo shān yǔ yàn ");
        details.setDescriptionB("高山雨燕");
        details.setDescriptionC("Alpine swift");
        details.setDescriptionD("Белобрюхий стриж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pǔ tōng lóu yàn ");
        details.setDescriptionB("普通楼燕");
        details.setDescriptionC("Swift");
        details.setDescriptionD(" Чёрный стриж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái yāo yǔ yàn ");
        details.setDescriptionB("白腰雨燕");
        details.setDescriptionC("Pacific Swift");
        details.setDescriptionD("Белопоясный стриж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīng tóu guàn");
        details.setDescriptionB("鲸头鹳");
        details.setDescriptionC("Shoebill");
        details.setDescriptionD("Китоглав/Королевская цапля ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu yè yīng ");
        details.setDescriptionB("欧夜鹰");
        details.setDescriptionC("European Nightjar ");
        details.setDescriptionD("Обыкновенный козодой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǔ tōng cuì niǎo ");
        details.setDescriptionB("普通翠鸟");
        details.setDescriptionC("Kingfisher");
        details.setDescriptionD("Обыкновенный зимородок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái xiōng fěi cuì ");
        details.setDescriptionB("白胸翡翠");
        details.setDescriptionC(" White-throated kingfisher ");
        details.setDescriptionD("Белогрудый зимородок/ Красноносый зимородок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  bān yú gǒu ");
        details.setDescriptionB("斑鱼狗 ");
        details.setDescriptionC("Pied kingfisher ");
        details.setDescriptionD("Mалый пегий зимородок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài píng niǎo ");
        details.setDescriptionB("太平鸟");
        details.setDescriptionC("Bohemian Waxwing");
        details.setDescriptionD(" Свиристель ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lì shì guān jiāo juān ");
        details.setDescriptionB("利氏冠蕉鹃");
        details.setDescriptionC(" Livingstone's Turaco ");
        details.setDescriptionD(" Турако Ливингстона ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā shì guān jiāo juān  ");
        details.setDescriptionB("沙氏冠蕉鹃");
        details.setDescriptionC("Schalow's turaco");
        details.setDescriptionD("Турако Шалова ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ lái xī niǎo ");
        details.setDescriptionB("马来犀鸟");
        details.setDescriptionC(" Rhinoceros Hornbill ");
        details.setDescriptionD("Малайский калао ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qū guān cù shé jù zuǐ niǎo ");
        details.setDescriptionB("曲冠簇舌巨嘴鸟");
        details.setDescriptionC("Curl-crested Aracari");
        details.setDescriptionD("Южноамериканский тукан курчавый арасари");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hòu zuǐ jù zuǐ niǎo ");
        details.setDescriptionB("厚嘴巨嘴鸟 ");
        details.setDescriptionC("Rainbow-billed Toucan ");
        details.setDescriptionD("Радужный тукан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuó kōng/ jù zuǐ niǎo ");
        details.setDescriptionB("鵎鵼/巨嘴鸟");
        details.setDescriptionC("  Toco toucan ");
        details.setDescriptionD("Большой тукан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng jiāo zuǐ què ");
        details.setDescriptionB("红交嘴雀");
        details.setDescriptionC("Common Crossbill");
        details.setDescriptionD(" Клёст-еловик  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑剪嘴鸥");
        details.setDescriptionB(" hēi jiǎn zuǐ ōu ");
        details.setDescriptionC("Black skimmer");
        details.setDescriptionD("Чёрный водорез");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("双角犀鸟");
        details.setDescriptionB(" shuāng jiǎo xī niǎo ");
        details.setDescriptionC("Great Hornbill");
        details.setDescriptionD("Большой индийский калао/ Двурогий калао");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сù hǎi yīng");
        details.setDescriptionB("簇海鹦");
        details.setDescriptionC(" Тufted puffin");
        details.setDescriptionD("Топорик/ Топорок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("běi jí hǎi yīng");
        details.setDescriptionB("北极海鹦");
        details.setDescriptionC("Puffin");
        details.setDescriptionD("Тупик ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  dāo zuǐ hǎi què ");
        details.setDescriptionB("刀嘴海雀");
        details.setDescriptionC("Razorbill");
        details.setDescriptionD(" Гагарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yá hǎi yā ");
        details.setDescriptionB("崖海鸦");
        details.setDescriptionC("Guillemot");
        details.setDescriptionD("Тонкоклювая кайра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duǎn chì xiǎo hǎi què ");
        details.setDescriptionB("短翅小海雀");
        details.setDescriptionC(" Little auk/ Dovekie ");
        details.setDescriptionD("Люрик/ Малая гагарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dì qì é ");
        details.setDescriptionB("帝企鹅");
        details.setDescriptionC("Emperor penguin ");
        details.setDescriptionD("Императорский пингвин ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī wéi niǎo");
        details.setDescriptionB("几维鸟");
        details.setDescriptionC("Kiwi");
        details.setDescriptionD("Киви ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎn wěi wáng bà wēng ");
        details.setDescriptionB("剪尾王霸鹟");
        details.setDescriptionC("Scissor-tailed flycatcher ");
        details.setDescriptionD("Длиннохвостый королевский тиранн ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín hóu cháng wěi shān què");
        details.setDescriptionB("银喉长尾山雀");
        details.setDescriptionC("Long-tailed Tit");
        details.setDescriptionD("Длиннохвостая синица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сháng wěi qiǎo zhī què ");
        details.setDescriptionB("长尾巧织雀");
        details.setDescriptionC("Long-tailed widowbirds ");
        details.setDescriptionD("Длиннохвостый бархатный ткач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng fù jǐn jī ");
        details.setDescriptionB(" 红腹锦鸡");
        details.setDescriptionC("Golden Pheasant ");
        details.setDescriptionD("Золотой фазан ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huá lì qín niǎo");
        details.setDescriptionB("华丽琴鸟");
        details.setDescriptionC("Superb Lyrebird ");
        details.setDescriptionD("Большой лирохвост");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wēi shì jí lè niǎo ");
        details.setDescriptionB("威氏极乐鸟");
        details.setDescriptionC("Wilson’s bird-of-paradise ");
        details.setDescriptionD("Синеголовая великолепная райская птица (лат.Cicinnurus respublica)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shòu dài cháng wěi fēng niǎo");
        details.setDescriptionB("绶带长尾风鸟");
        details.setDescriptionC("Ribbon-tailed Astrapia ");
        details.setDescriptionD("Астрапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàng shù zhuó mù niǎo ");
        details.setDescriptionB("橡树啄木鸟");
        details.setDescriptionC("Acorn Woodpecker");
        details.setDescriptionD(" Муравьиный меланерпес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà bān zhuó mù niǎo ");
        details.setDescriptionB("大斑啄木鸟");
        details.setDescriptionC("Great spotted woodpecker");
        details.setDescriptionD(" Большой пёстрый дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng bān zhuó mù niǎo ");
        details.setDescriptionB("中斑啄木鸟");
        details.setDescriptionC("Middle spotted woodpecker");
        details.setDescriptionD(" Средний пёстый дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo bān zhuó mù niǎo ");
        details.setDescriptionB("小斑啄木鸟");
        details.setDescriptionC("Lesser spotted woodpecker");
        details.setDescriptionD(" Малый пёстрый дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ zhuó mù niǎo ");
        details.setDescriptionB("绿啄木鸟");
        details.setDescriptionC("Green woodpecker");
        details.setDescriptionD(" Зелёный дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī tóu lǜ zhuó mù niǎo ");
        details.setDescriptionB("灰头绿啄木鸟");
        details.setDescriptionC("Grey-headed woodpecker");
        details.setDescriptionD(" Седой дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sān zhǐ zhuó mù niǎo ");
        details.setDescriptionB("三趾啄木鸟");
        details.setDescriptionC("Three-toed woodpecker ");
        details.setDescriptionD(" Трёхпалый дятел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi zhuó mù niǎo ");
        details.setDescriptionB("黑啄木鸟");
        details.setDescriptionC("Black woodpecker");
        details.setDescriptionD(" Чёрный дятел ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǐ liè ");
        details.setDescriptionB("蚁鴷");
        details.setDescriptionC("Wryneck");
        details.setDescriptionD(" Вертишейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fèng tóu mài jī ");
        details.setDescriptionB("凤头麦鸡");
        details.setDescriptionC("Lapwing ");
        details.setDescriptionD("Чибис/ Пигалица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà bān fèng tóu juān ");
        details.setDescriptionB("大斑凤头鹃");
        details.setDescriptionC("Great spotted cuckoo");
        details.setDescriptionD(" Хохлатая кукушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà dù juān ");
        details.setDescriptionB("大杜鹃");
        details.setDescriptionC("Cuckoo");
        details.setDescriptionD("Обыкновенная кукушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài shèng ");
        details.setDescriptionB("戴胜");
        details.setDescriptionC(" Hoopoe ");
        details.setDescriptionD("Удод ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán xiōng fó fǎ sēng ");
        details.setDescriptionB("蓝胸佛法僧");
        details.setDescriptionC(" European Roller ");
        details.setDescriptionD("Обыкновенная сизоворонка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng hóu fēng hǔ ");
        details.setDescriptionB(" 黄喉蜂虎");
        details.setDescriptionC("European bee-eater");
        details.setDescriptionD("Золотистая щурка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng lǐng lǜ yīng wǔ ");
        details.setDescriptionB("红领绿鹦鹉");
        details.setDescriptionC("Rose-ringed parakeet");
        details.setDescriptionD(" Ожереловый попугай Крамера ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi é zhī què");
        details.setDescriptionB("黑额织雀");
        details.setDescriptionC("African Masked Weaver ");
        details.setDescriptionD(" Чернолобый ткач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shé jiù ");
        details.setDescriptionB("蛇鹫");
        details.setDescriptionC(" Secretary Bird ");
        details.setDescriptionD("Птица-секретарь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái gē ");
        details.setDescriptionB("白鸽");
        details.setDescriptionC("White dove ");
        details.setDescriptionD("Белый голубь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zōng bān jiū ");
        details.setDescriptionB("棕斑鸠 ");
        details.setDescriptionC("Laughing Dove ");
        details.setDescriptionD("Малая  горлица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī bān jiū");
        details.setDescriptionB("灰斑鸠");
        details.setDescriptionC("Collared dove");
        details.setDescriptionD("Кольчатая горлица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu bānjiū ");
        details.setDescriptionB("欧斑鸠");
        details.setDescriptionC("Turtle dove ");
        details.setDescriptionD(" Обыкновенная горлица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān wěi lín gē ");
        details.setDescriptionB("斑尾林鸽");
        details.setDescriptionC("Woodpigeon");
        details.setDescriptionD(" Вяхирь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuán gē/ yě gēzi ");
        details.setDescriptionB("原鸽/ 野鸽子");
        details.setDescriptionC("Rock dove");
        details.setDescriptionD(" Сизый голубь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yán gē ");
        details.setDescriptionB("岩鸽");
        details.setDescriptionC(" Hill pigeon ");
        details.setDescriptionD("Скалистый голубь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái fù shā jī ");
        details.setDescriptionB("白腹沙鸡  ");
        details.setDescriptionC("Pin-tailed sandgrouse");
        details.setDescriptionD(" Белобрюхий рябок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xǐ què ");
        details.setDescriptionB("喜鹊");
        details.setDescriptionC("Magpie ");
        details.setDescriptionD("Сорока");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tái wān lán què ");
        details.setDescriptionB("台湾蓝鹊");
        details.setDescriptionC(" Taiwan Blue Magpie ");
        details.setDescriptionD("Толстоклювая лазоревая сорока");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng zuǐ xǐ què ");
        details.setDescriptionB("黄嘴喜鹊");
        details.setDescriptionC("Yellow-billed Magpie ");
        details.setDescriptionD("Калифорнийская сорока ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guān lán yā/ lán sōng yā ");
        details.setDescriptionB("冠蓝鸦/ 蓝松鸦");
        details.setDescriptionC("Blue Jay ");
        details.setDescriptionD("Голубая сойка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sōng yā ");
        details.setDescriptionB("松鸦");
        details.setDescriptionC(" Jay ");
        details.setDescriptionD("Сойка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng zuǐ shān yā ");
        details.setDescriptionB("红嘴山鸦 ");
        details.setDescriptionC("Red-billed сhough");
        details.setDescriptionD(" Клушица ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà zuǐ wū yā ");
        details.setDescriptionB("大嘴乌鸦");
        details.setDescriptionC("Large-billed Crow");
        details.setDescriptionD(" Большеклювая ворона  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guān xiǎo zuǐ wū yā ");
        details.setDescriptionB("冠小嘴乌鸦");
        details.setDescriptionC(" Hooded Crow ");
        details.setDescriptionD("Серая ворона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wū yā");
        details.setDescriptionB("乌鸦");
        details.setDescriptionC(" Сrow");
        details.setDescriptionD("Чёрная ворона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dù yā ");
        details.setDescriptionB("渡鸦");
        details.setDescriptionC(" Common Raven ");
        details.setDescriptionD("Ворон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yá shā yàn ");
        details.setDescriptionB("崖沙燕");
        details.setDescriptionC("Sand martin");
        details.setDescriptionD("Береговая ласточка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā yàn ");
        details.setDescriptionB("家燕");
        details.setDescriptionC(" Swallow/ Barn  Swallow");
        details.setDescriptionD("Деревенская ласточка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái fù máo jiǎo yàn ");
        details.setDescriptionB("白腹毛脚燕");
        details.setDescriptionC("House martin");
        details.setDescriptionD("Городская ласточка/ Воронок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn yāo yàn ");
        details.setDescriptionB("金腰燕");
        details.setDescriptionC("Red-rumped swallow");
        details.setDescriptionD(" Рыжепоясничная ласточка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yán yàn");
        details.setDescriptionB("岩燕");
        details.setDescriptionC("Crag martin");
        details.setDescriptionD("Скалистая ласточка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi ōu ");
        details.setDescriptionB("海鸥");
        details.setDescriptionC("Common gull");
        details.setDescriptionD("Сизая чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà hēi bèi ōu ");
        details.setDescriptionB("大黑背鸥");
        details.setDescriptionC("Great black-backed gull");
        details.setDescriptionD(" Большая морская чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo ōu ");
        details.setDescriptionB("小鸥");
        details.setDescriptionC("Little gull");
        details.setDescriptionD("Малая чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo hēi bèi ōu ");
        details.setDescriptionB("小黑背鸥");
        details.setDescriptionC("Lesser black-backed gull");
        details.setDescriptionD("Клуша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xì zuǐ ōu ");
        details.setDescriptionB("细嘴鸥");
        details.setDescriptionC("Slender-billed gull");
        details.setDescriptionD("Морской голубок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng zuǐ ōu ");
        details.setDescriptionB("红嘴鸥");
        details.setDescriptionC("Black-headed gull");
        details.setDescriptionD("Озёрная чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dì zhōng hǎi ōu ");
        details.setDescriptionB(" 地中海鸥");
        details.setDescriptionC("Audouin’s gull");
        details.setDescriptionD("Чайка Одуэна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  hēi tóu ōu ");
        details.setDescriptionB("黑头鸥");
        details.setDescriptionC("Mediterranean gull");
        details.setDescriptionD("Черноголовая чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dōng jiāo liáo ");
        details.setDescriptionB("冬鹪鹩");
        details.setDescriptionC(" Winter Wren ");
        details.setDescriptionD("Крапивник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn sī què ");
        details.setDescriptionB("金丝雀");
        details.setDescriptionC("Canary -bird");
        details.setDescriptionD("Канарейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сāng tóu yàn què");
        details.setDescriptionB("苍头燕雀");
        details.setDescriptionC("Eurasian Chaffinch");
        details.setDescriptionD("Зяблик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà shān què ");
        details.setDescriptionB("大山雀");
        details.setDescriptionC(" Great Tit ");
        details.setDescriptionD("Большая синица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu yà qú/zhī gēng niǎo ");
        details.setDescriptionB("欧亚鸲/知更鸟 ");
        details.setDescriptionC("Robin ");
        details.setDescriptionD("Зарянка/ Малиновка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng niǎo ");
        details.setDescriptionB("蜂鸟 ");
        details.setDescriptionC("Hummingbird ");
        details.setDescriptionD("Колибри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dāo zuǐ fēng niǎo ");
        details.setDescriptionB(" 刀嘴蜂鸟");
        details.setDescriptionC(" Sword-billed Hummingbird");
        details.setDescriptionD("Колибри-мечеклюв ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" má què ");
        details.setDescriptionB("麻雀");
        details.setDescriptionC("Sparrow");
        details.setDescriptionD("Воробей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bào fēng hù ");
        details.setDescriptionB("暴风鹱");
        details.setDescriptionC("Fulmar /Northern fulmar ");
        details.setDescriptionD("Глупыш ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yín huī bào fēng hù ");
        details.setDescriptionB("银灰暴风鹱");
        details.setDescriptionC(" Southern Fulmar");
        details.setDescriptionD(" Антарктический глупыш");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎi shé niǎo ");
        details.setDescriptionB("百舌鸟");
        details.setDescriptionC(" Common Blackbird ");
        details.setDescriptionD("Чёрный дрозд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǎn shì gū dōng");
        details.setDescriptionB("坦氏孤鸫");
        details.setDescriptionC(" Townsend's solitaire ");
        details.setDescriptionD("Дрозд-отшельник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  yàn què ");
        details.setDescriptionB("燕雀");
        details.setDescriptionC("Brambling ");
        details.setDescriptionD("Вьюрок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu gē qú ");
        details.setDescriptionB("欧歌鸲");
        details.setDescriptionC(" Thrush nightingale ");
        details.setDescriptionD("Обыкновенный соловей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi dǐng lín yīng");
        details.setDescriptionB("黑顶林莺");
        details.setDescriptionC("Eurasian blackcap");
        details.setDescriptionD("Черноголовая славка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shàn wěi shā zhuī");
        details.setDescriptionB("扇尾沙锥");
        details.setDescriptionC("Common Snipe");
        details.setDescriptionD("Бекас");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng zuǐ biāo yù ");
        details.setDescriptionB("长嘴杓鹬");
        details.setDescriptionC(" Long-billed curlew ");
        details.setDescriptionD("Длинноклювый кроншнеп ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiū yù");
        details.setDescriptionB("丘鹬");
        details.setDescriptionC("Eurasian Woodcock");
        details.setDescriptionD("Вальдшнеп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī fāng yāng jī ");
        details.setDescriptionB("西方秧鸡");
        details.setDescriptionC(" Water Rail ");
        details.setDescriptionD("Водяной пастушок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng zuǐ yāng jī");
        details.setDescriptionB("长嘴秧鸡");
        details.setDescriptionC(" Mangrove rail");
        details.setDescriptionD("Пастушок-трескун ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hán yā ");
        details.setDescriptionB("寒鸦");
        details.setDescriptionC("  Jackdaw ");
        details.setDescriptionD("Галка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǔ tōng qián niǎo ");
        details.setDescriptionB("普通潜鸟");
        details.setDescriptionC(" Common Loon ");
        details.setDescriptionD(" Черноклювая гагара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái zuǐ qián niǎo ");
        details.setDescriptionB("白嘴潜鸟");
        details.setDescriptionC("Yellow-billed Loon");
        details.setDescriptionD("Белоклювая гагара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng hóu qián niǎo ");
        details.setDescriptionB("红喉潜鸟");
        details.setDescriptionC("Red-throated diver");
        details.setDescriptionD("Краснозобая гагара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi hóu qián niǎo ");
        details.setDescriptionB("黑喉潜鸟");
        details.setDescriptionC("Black-throated diver/ Arctic Loon  ");
        details.setDescriptionD("Чернозобая гагара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài píng yáng qián niǎo ");
        details.setDescriptionB("太平洋潜鸟");
        details.setDescriptionC(" Pacific Loon ");
        details.setDescriptionD("Белошейная гагара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng xiōng qiū shā yā ");
        details.setDescriptionB("红胸秋沙鸭");
        details.setDescriptionC("Red-breasted Merganser");
        details.setDescriptionD(" Средний крохаль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zuǐ què");
        details.setDescriptionB("锡嘴雀");
        details.setDescriptionC("Hawfinch");
        details.setDescriptionD("Обыкновенный дубонос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà yàn ");
        details.setDescriptionB("大雁");
        details.setDescriptionC("Wild goose");
        details.setDescriptionD("Дикий гусь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yún què");
        details.setDescriptionB("云雀");
        details.setDescriptionC("Sky lark ");
        details.setDescriptionD(" Полевой жаворонок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大短趾百灵");
        details.setDescriptionB(" dà duǎn zhǐ bǎi líng ");
        details.setDescriptionC("Greater short-toed lark");
        details.setDescriptionD("Малый жаворонок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сǎo yuán bǎi líng ");
        details.setDescriptionB("草原百灵");
        details.setDescriptionC("Calandra lark ");
        details.setDescriptionD(" Степной жаворонок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín bǎi líng ");
        details.setDescriptionB("林百灵");
        details.setDescriptionC("Woodlark");
        details.setDescriptionD(" Лесной жаворонок/ Юла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fèng tóu bǎi líng ");
        details.setDescriptionB("凤头百灵");
        details.setDescriptionC("Crested lark ");
        details.setDescriptionD("Хохлатый жаворонок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān shí yù ");
        details.setDescriptionB("翻石鹬");
        details.setDescriptionC(" Ruddy Turnstone ");
        details.setDescriptionD("Камнешарка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng jí líng");
        details.setDescriptionB("黄鹡鸰");
        details.setDescriptionC("Yellow Wagtail");
        details.setDescriptionD("Жёлтая трясогузка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu jīn chì què ");
        details.setDescriptionB("欧金翅雀");
        details.setDescriptionC(" European Greenfinch ");
        details.setDescriptionD("Зеленушка обыкновенная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi yuān ");
        details.setDescriptionB("黑鸢");
        details.setDescriptionC("Black Kite");
        details.setDescriptionD("Чёрный коршун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wū huī yào ");
        details.setDescriptionB("乌灰鹞");
        details.setDescriptionC("Montagu's Harrier ");
        details.setDescriptionD("Луговой лунь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái wěi yào ");
        details.setDescriptionB("白尾鹞");
        details.setDescriptionC(" Northern Harrier ");
        details.setDescriptionD("Полевой лунь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng wú ");
        details.setDescriptionB("黄鹀 ");
        details.setDescriptionC("Yellowhammer ");
        details.setDescriptionD("Обыкновенная овсянка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī shān chún ");
        details.setDescriptionB("灰山鹑");
        details.setDescriptionC(" Grey Partridge ");
        details.setDescriptionD("Серая куропатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān chún ");
        details.setDescriptionB("鹌鹑");
        details.setDescriptionC(" Common quail");
        details.setDescriptionD("Обыкновенный перепел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū jǐng líng chún");
        details.setDescriptionB("珠颈翎鹑");
        details.setDescriptionC("California Quail");
        details.setDescriptionD("Калифорнийский перепел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī bīn yù ");
        details.setDescriptionB("姬滨鹬");
        details.setDescriptionC(" Least Sandpiper   ");
        details.setDescriptionD(" Песочник-крошка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ chì liáng niǎo ");
        details.setDescriptionB("紫翅椋鸟");
        details.setDescriptionC(" Common starling");
        details.setDescriptionD("Обыкновенный скворец ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng zhǎo sǔn ");
        details.setDescriptionB("黄爪隼 ");
        details.setDescriptionC("Lesser Kestrel ");
        details.setDescriptionD("Степная пустельга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng sǔn ");
        details.setDescriptionB("红隼 ");
        details.setDescriptionC("Common Kestrel ");
        details.setDescriptionD("Обыкновенная пустельга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu jīn héng ");
        details.setDescriptionB("欧金鸻");
        details.setDescriptionC(" Eurasian Golden Plover ");
        details.setDescriptionD("Золотистая ржанка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn kuàng héng");
        details.setDescriptionB("金眶鸻");
        details.setDescriptionC("Little Ringed Plover ");
        details.setDescriptionD("Малый зуёк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huán jǐng héng ");
        details.setDescriptionB("环颈鸻");
        details.setDescriptionC(" Snowy plover");
        details.setDescriptionD("Морской зуёк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сháng ěr xiāo ");
        details.setDescriptionB("长耳鸮");
        details.setDescriptionC("Long-eared Owl");
        details.setDescriptionD("Ушастая сова");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng xiāo ");
        details.setDescriptionB("鹰鸮");
        details.setDescriptionC("Brown Hawk-owl");
        details.setDescriptionD("Филин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  huī lín xiāo");
        details.setDescriptionB("灰林鸮");
        details.setDescriptionC("Tawny owl");
        details.setDescriptionD("Серая неясыть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zòng wén fù xiǎo xiāo ");
        details.setDescriptionB("纵纹腹小鸮 ");
        details.setDescriptionC("Little owl ");
        details.setDescriptionD("Домовый сыч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" héng bān lín yīng ");
        details.setDescriptionB("横斑林莺");
        details.setDescriptionC(" Barred Warbler ");
        details.setDescriptionD("Ястребиная славка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái hóu lín yīng ");
        details.setDescriptionB("白喉林莺");
        details.setDescriptionC(" Lesser Whitethroat ");
        details.setDescriptionD("Славка-завирушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng fù huī què ");
        details.setDescriptionB("红腹灰雀");
        details.setDescriptionC(" Eurasian bullfinch ");
        details.setDescriptionD("Снегирь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī fù huī què ");
        details.setDescriptionB("灰腹灰雀");
        details.setDescriptionC("Oriental Bullfinch ");
        details.setDescriptionD(" Уссурийский снегирь  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng tóu huī què ");
        details.setDescriptionB("红头灰雀");
        details.setDescriptionC("Red-headed Bullfinch");
        details.setDescriptionD(" Красноголовый снегирь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī fù huī què dōng běi yà zhǒng ");
        details.setDescriptionB("灰腹灰雀东北亚种");
        details.setDescriptionC(" Baikal Bullfinch/ Grey bullfinch ");
        details.setDescriptionD("Серый снегирь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tián liù ");
        details.setDescriptionB("田鹨");
        details.setDescriptionC(" Richard's Pipit ");
        details.setDescriptionD("Степной конёк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  bái gǔ dǐng jī ");
        details.setDescriptionB("白骨顶鸡");
        details.setDescriptionC(" Coot /Eurasian coot ");
        details.setDescriptionD("Лысуха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi chì cháng jiǎo yù ");
        details.setDescriptionB("黑翅长脚鹬 ");
        details.setDescriptionC("Black-winged Stilt ");
        details.setDescriptionD("Ходулочник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér miáo ");
        details.setDescriptionB("鸸鹋 ");
        details.setDescriptionC("Emu ");
        details.setDescriptionD("Эму");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi zhōu tuó niǎo ");
        details.setDescriptionB("非洲鸵鸟");
        details.setDescriptionC(" African Ostrich ");
        details.setDescriptionD("Африканский страус ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hú wù jiù ");
        details.setDescriptionB("胡兀鹫 ");
        details.setDescriptionC("Bearded Vulture ");
        details.setDescriptionD("Бородач / Ягнятник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hā pèi diāo ");
        details.setDescriptionB("哈佩雕");
        details.setDescriptionC(" Harpy eagle ");
        details.setDescriptionD("Южноамериканская гарпия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sǔn ");
        details.setDescriptionB("隼 ");
        details.setDescriptionC("Falcon ");
        details.setDescriptionD("Сокол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu sǔn/huā lí yīng ");
        details.setDescriptionB("游隼/花梨鹰");
        details.setDescriptionC("Peregrine Falcon");
        details.setDescriptionD("Сокол-сапсан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān lín sǔn ");
        details.setDescriptionB("斑林隼");
        details.setDescriptionC(" Barred Forest Falcon ");
        details.setDescriptionD("Лесной сокол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiào sǔn");
        details.setDescriptionB("笑隼   ");
        details.setDescriptionC("Laughing Falcon ");
        details.setDescriptionD(" Смеющийся сокол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi zhōu zhū sǔn ");
        details.setDescriptionB("非洲侏隼");
        details.setDescriptionC("  African pygmy falcon ");
        details.setDescriptionD("Африканский малый сокол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǐ yóu sǔn ");
        details.setDescriptionB("拟游隼");
        details.setDescriptionC(" Barbary falcon ");
        details.setDescriptionD("Шахин / Пустынный сокол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi zhōu hǎi diāo ");
        details.setDescriptionB("非洲海雕");
        details.setDescriptionC("African Fish Eagle");
        details.setDescriptionD(" Орлан-крикун ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái fù sǔn diāo ");
        details.setDescriptionB("白腹隼雕");
        details.setDescriptionC("  European Bonelli's Eagles ");
        details.setDescriptionD("Ястребиный орёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn diāo ");
        details.setDescriptionB("金雕");
        details.setDescriptionC("Golden Eagle");
        details.setDescriptionD("Беркут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái jiān diāo ");
        details.setDescriptionB("白肩雕");
        details.setDescriptionC(" Eastern Imperial Eagle ");
        details.setDescriptionD("Орёл-могильник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zōng fù sǔn diāo ");
        details.setDescriptionB("棕腹隼雕");
        details.setDescriptionC(" Rufous-bellied Hawk Eagle ");
        details.setDescriptionD("Индийский ястребиный орёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chá sè diāo ");
        details.setDescriptionB("茶色雕");
        details.setDescriptionC("  Tawny eagle ");
        details.setDescriptionD("Каменный орёл ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎo yuán diāo");
        details.setDescriptionB("草原雕");
        details.setDescriptionC("Steppe eagle");
        details.setDescriptionD("Степной орёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi diāo ");
        details.setDescriptionB("黑雕");
        details.setDescriptionC(" Verreaux's Eagle/ Black Eagle ");
        details.setDescriptionD("Кафрский орёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuē sǔn diāo ");
        details.setDescriptionB("靴隼雕");
        details.setDescriptionC("Booted eagle");
        details.setDescriptionD("Орёл-карлик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiē wěi diāo ");
        details.setDescriptionB("楔尾雕");
        details.setDescriptionC("Wedge-tailed Eagle");
        details.setDescriptionD("Клинохвостый орёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng wěi kuáng ");
        details.setDescriptionB("红尾鵟");
        details.setDescriptionC(" Red-tailed Hawk ");
        details.setDescriptionD("Краснохвостый сарыч ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" què yīng  ");
        details.setDescriptionB("雀鹰 ");
        details.setDescriptionC("Eurasian Sparrowhawk ");
        details.setDescriptionD("Ястреб-перепелятник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái wù jiù ");
        details.setDescriptionB("白兀鹫 ");
        details.setDescriptionC("Egyptian vulture ");
        details.setDescriptionD("Стервятник");
        detailsList.add(details);
    }
}
