package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C47 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("diàn nǎo yóu xì ");
        details.setDescriptionB("电脑游戏");
        details.setDescriptionC(" Сomputer game ");
        details.setDescriptionD(" Компьютерная игра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiào xiàng pí jīn ");
        details.setDescriptionB("跳橡皮筋");
        details.setDescriptionC(" Jump through the gum ");
        details.setDescriptionD("Резиночка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǔn lún zǐ ");
        details.setDescriptionB("滚轮子");
        details.setDescriptionC("Hoop rolling");
        details.setDescriptionD("Катание колеса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tào quān ");
        details.setDescriptionB("套圈");
        details.setDescriptionC("Ring Toss/ ring-a-bottle");
        details.setDescriptionD("Метание колец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chōu tuó luó ");
        details.setDescriptionB("抽陀螺");
        details.setDescriptionC("Pumping gyro");
        details.setDescriptionD("Вращение юлы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chě líng zǐ ");
        details.setDescriptionB("扯铃子");
        details.setDescriptionC(" Chinese yo-yo/diabolo");
        details.setDescriptionD("Диаболо(игра) ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kōng zhú  ");
        details.setDescriptionB("空竹");
        details.setDescriptionC("Diabolo ");
        details.setDescriptionD("Диаболо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuó luó ");
        details.setDescriptionB("陀螺");
        details.setDescriptionC("Gyro ");
        details.setDescriptionD("Юла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎo líng qiú ");
        details.setDescriptionB("保龄球");
        details.setDescriptionC("Bowling");
        details.setDescriptionD(" Боулинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù zhù ");
        details.setDescriptionB("木柱");
        details.setDescriptionC(" Skittle ");
        details.setDescriptionD("Кегля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiú ");
        details.setDescriptionB("球");
        details.setDescriptionC(" Ball ");
        details.setDescriptionD("Шар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tái qiú");
        details.setDescriptionB("台球");
        details.setDescriptionC("Billiards");
        details.setDescriptionD("Бильярд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiú gǎn ");
        details.setDescriptionB("球杆");
        details.setDescriptionC("Billiard cue ");
        details.setDescriptionD("Кий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dòng ");
        details.setDescriptionB("洞");
        details.setDescriptionC("Pocket");
        details.setDescriptionD("Луза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chōu cǎi yóu xì ");
        details.setDescriptionB("抽彩游戏");
        details.setDescriptionC("Lottery");
        details.setDescriptionD("Лото");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jì shù kǎ ");
        details.setDescriptionB("计数卡");
        details.setDescriptionC("Cards");
        details.setDescriptionD("Карточки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù chóu ");
        details.setDescriptionB("数筹");
        details.setDescriptionC("Numbers");
        details.setDescriptionD("Номера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí wǔ zǐ qí ");
        details.setDescriptionB("十五子棋");
        details.setDescriptionC("Backgammon");
        details.setDescriptionD("Нарды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǎi·zi ");
        details.setDescriptionB("骰子");
        details.setDescriptionC("Dice");
        details.setDescriptionD("Кубики/кости");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duō mǐ nuò gǔ pái ");
        details.setDescriptionB("多米诺骨牌");
        details.setDescriptionC("Domino");
        details.setDescriptionD("Домино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duō mǐ nuò gǔ ");
        details.setDescriptionB("多米诺骨");
        details.setDescriptionC("Domino dice");
        details.setDescriptionD("Кости домино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǐ pái ");
        details.setDescriptionB("纸牌");
        details.setDescriptionC("Playing cards");
        details.setDescriptionD("Игральные карты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pū kè");
        details.setDescriptionB("扑克");
        details.setDescriptionC("Poker");
        details.setDescriptionD("Покер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào qí ");
        details.setDescriptionB("跳棋");
        details.setDescriptionC("Checkers");
        details.setDescriptionD("Шашки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi qí zǐ ");
        details.setDescriptionB("黑棋子");
        details.setDescriptionC("Black checker");
        details.setDescriptionD("Чёрная  шашка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái qí zǐ ");
        details.setDescriptionB("白棋子");
        details.setDescriptionC("White checker");
        details.setDescriptionD("Белая шашка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qí zǐ ");
        details.setDescriptionB("棋子");
        details.setDescriptionC("King");
        details.setDescriptionD("Дамка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó jì xiàng qí ");
        details.setDescriptionB("国际象棋");
        details.setDescriptionC(" International chess ");
        details.setDescriptionD("Шахматы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí pán ");
        details.setDescriptionB("棋盘");
        details.setDescriptionC(" Chess board ");
        details.setDescriptionD("Шахматная доска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāng sǐ ");
        details.setDescriptionB("将死");
        details.setDescriptionC("Checkmate");
        details.setDescriptionD("Шах и мат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīng ");
        details.setDescriptionB("兵");
        details.setDescriptionC("Pawn");
        details.setDescriptionD("Пешка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jū ");
        details.setDescriptionB("车");
        details.setDescriptionC("Rook");
        details.setDescriptionD("Ладья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ ");
        details.setDescriptionB("马");
        details.setDescriptionC("Knight");
        details.setDescriptionD("Конь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàng");
        details.setDescriptionB("象");
        details.setDescriptionC("Bishop");
        details.setDescriptionD("Слон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hòu ");
        details.setDescriptionB("后");
        details.setDescriptionC(" Queen ");
        details.setDescriptionD("Королева/ферзь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wáng ");
        details.setDescriptionB("王");
        details.setDescriptionC("King");
        details.setDescriptionD("Король");
        detailsList.add(details);
    }
}
