package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C55 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("yìn dù cǎo yī xué ");
        details.setDescriptionB("印度草医学");
        details.setDescriptionC("Ayurveda");
        details.setDescriptionD("Аюрведа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yú jiā ");
        details.setDescriptionB("瑜珈");
        details.setDescriptionC("Yoga");
        details.setDescriptionD("Йога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fǔ dǎo jiào shī ");
        details.setDescriptionB("辅导教师");
        details.setDescriptionC("Teacher");
        details.setDescriptionD("Учитель/Инструктор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn zi");
        details.setDescriptionB("垫子");
        details.setDescriptionC("Mat");
        details.setDescriptionD("Коврик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("àn mó");
        details.setDescriptionB("按摩");
        details.setDescriptionC("Massage");
        details.setDescriptionD("Массаж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ yā àn mó");
        details.setDescriptionB("指压按摩");
        details.setDescriptionC("Shiatsu");
        details.setDescriptionD("Шиацу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zú dǐ fǎn shè liáo fǎ");
        details.setDescriptionB("足底反射疗法");
        details.setDescriptionC("Reflexology");
        details.setDescriptionD("Рефлексология");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhěng gǔ shù ");
        details.setDescriptionB("整骨术");
        details.setDescriptionC("Osteopathy");
        details.setDescriptionD(" Остеопатия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhěng jí àn mó fǎ");
        details.setDescriptionB("整脊按摩法");
        details.setDescriptionC("Chiropractic ");
        details.setDescriptionD("Мануальная терапия ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhēn cì liáo fǎ ");
        details.setDescriptionB("针刺疗法");
        details.setDescriptionC("Acupuncture");
        details.setDescriptionD("Иглоукалывание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" líng qì liáo fǎ ");
        details.setDescriptionB("灵气疗法");
        details.setDescriptionC("Reiki");
        details.setDescriptionD("Рейки/Рэйки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ yā liáo fǎ ");
        details.setDescriptionB("指压疗法");
        details.setDescriptionC("Acupressure");
        details.setDescriptionD("Акупрессура");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fāng xiāng liáo fǎ");
        details.setDescriptionB("芳香疗法");
        details.setDescriptionC("Aromatherapy");
        details.setDescriptionD("Ароматерапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīng yóu");
        details.setDescriptionB("精油");
        details.setDescriptionC("Essential oils");
        details.setDescriptionD("Эфирные масла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yào cǎo");
        details.setDescriptionB("药草");
        details.setDescriptionC("Herb");
        details.setDescriptionD("Лекарственное растение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì rán liáo fǎ");
        details.setDescriptionB("自然疗法");
        details.setDescriptionC("Naturopathy");
        details.setDescriptionD("Натуропатия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shùn shì liáo fǎ");
        details.setDescriptionB("顺势疗法");
        details.setDescriptionC("Homeopathy");
        details.setDescriptionD("Гомеопатия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí wù yào liáo fǎ");
        details.setDescriptionB("植物药疗法");
        details.setDescriptionC("Phytotherapy");
        details.setDescriptionD("Фитотерапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ liáo");
        details.setDescriptionB("水疗");
        details.setDescriptionC("Hydrotherapy");
        details.setDescriptionD("Гидротерапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīng shén zhì liáo");
        details.setDescriptionB("精神治疗");
        details.setDescriptionC("Psychotherapy");
        details.setDescriptionD("Психотерапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сuī mián liáo fǎ");
        details.setDescriptionB("催眠疗法");
        details.setDescriptionC("Hypnotherapy");
        details.setDescriptionD("Гипнотерапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí tǐ liáo fǎ");
        details.setDescriptionB("集体疗法");
        details.setDescriptionC("Group therapy");
        details.setDescriptionD("Групповая терапия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhì liáo shī");
        details.setDescriptionB("治疗师");
        details.setDescriptionC("Therapist");
        details.setDescriptionD("Терапевт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gù wèn");
        details.setDescriptionB("顾问");
        details.setDescriptionC("Counselor");
        details.setDescriptionD("Консультант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fàng sōng");
        details.setDescriptionB("放松");
        details.setDescriptionC("Relaxation");
        details.setDescriptionD("Расслабление ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("míng xiǎng");
        details.setDescriptionB("冥想");
        details.setDescriptionC("Meditation");
        details.setDescriptionD("Медитация");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng shuǐ");
        details.setDescriptionB("风水");
        details.setDescriptionC("Feng shui");
        details.setDescriptionD("Фэн-Шуй");
        detailsList.add(details);
    }
}
