package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C58 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("сhéng shì");
        details.setDescriptionB("城市");
        details.setDescriptionC("City");
        details.setDescriptionD("Город");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mó tiān dà lóu ");
        details.setDescriptionB("摩天大楼");
        details.setDescriptionC(" Skyscraper ");
        details.setDescriptionD("Небоскрёб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fáng zi/lóu fáng");
        details.setDescriptionB(" 房子/楼房");
        details.setDescriptionC("Building");
        details.setDescriptionD("Здание");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cūn zhuāng ");
        details.setDescriptionB("村庄");
        details.setDescriptionC(" Village ");
        details.setDescriptionD("Село/Деревня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn yǐng yuàn");
        details.setDescriptionB("电影院");
        details.setDescriptionC("Cinema");
        details.setDescriptionD("Кинотеатр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bó wù guǎn");
        details.setDescriptionB("博物馆");
        details.setDescriptionC("Museum");
        details.setDescriptionD("Музей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jù chǎng");
        details.setDescriptionB("剧场");
        details.setDescriptionC("Theatre");
        details.setDescriptionD("Театр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ xì");
        details.setDescriptionB("马戏");
        details.setDescriptionC("Circus");
        details.setDescriptionD("Цирк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xué xiào");
        details.setDescriptionB("学校");
        details.setDescriptionC("School");
        details.setDescriptionD("Школа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà xué");
        details.setDescriptionB("大学");
        details.setDescriptionC("University");
        details.setDescriptionD("Университет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn pù ");
        details.setDescriptionB("店铺");
        details.setDescriptionC("Shop");
        details.setDescriptionD("Магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chāo shì");
        details.setDescriptionB("超市");
        details.setDescriptionC("Supermarket");
        details.setDescriptionD("Супермаркет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shì chǎng");
        details.setDescriptionB("市场");
        details.setDescriptionC("Market");
        details.setDescriptionD("Рынок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào táng");
        details.setDescriptionB("教堂");
        details.setDescriptionC("Church");
        details.setDescriptionD("Церковь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yī yuàn");
        details.setDescriptionB("医院");
        details.setDescriptionC("Hospital");
        details.setDescriptionD("Больница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yào diàn");
        details.setDescriptionB("药店");
        details.setDescriptionC("Pharmacy");
        details.setDescriptionD("Аптека");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu jú /yóu zhèng");
        details.setDescriptionB("邮局/邮政");
        details.setDescriptionC("Post office");
        details.setDescriptionD("Почта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng yuán");
        details.setDescriptionB("公园");
        details.setDescriptionC("Park");
        details.setDescriptionD("Парк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yòu ér yuán");
        details.setDescriptionB("幼儿园");
        details.setDescriptionC("Kindergarten");
        details.setDescriptionD("Детский сад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí zì lù kǒu");
        details.setDescriptionB("十字路口");
        details.setDescriptionC("Crossroads");
        details.setDescriptionD("Перекрёсток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jì niàn bēi");
        details.setDescriptionB("纪念碑");
        details.setDescriptionC("Monument");
        details.setDescriptionD("Памятник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiāo tōng dēng");
        details.setDescriptionB("交通灯");
        details.setDescriptionC("Traffic light");
        details.setDescriptionD("Светофор");
        detailsList.add(details);
    }
}
