package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C68 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("yuán xíng");
        details.setDescriptionB("圆形");
        details.setDescriptionC("Circle");
        details.setDescriptionD("Круг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bàn yuán");
        details.setDescriptionB("半圆");
        details.setDescriptionC("Semicircle");
        details.setDescriptionD("Полукруг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuǒ yuán xíng");
        details.setDescriptionB("椭圆形");
        details.setDescriptionC("Oval");
        details.setDescriptionD("Овал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("líng xíng");
        details.setDescriptionB("菱形");
        details.setDescriptionC("Diamond");
        details.setDescriptionD("Ромб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhèng fāng xíng ");
        details.setDescriptionB("正方形");
        details.setDescriptionC("Square");
        details.setDescriptionD("Квадрат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān jiǎo xíng");
        details.setDescriptionB("三角形");
        details.setDescriptionC("Triangle");
        details.setDescriptionD("Треугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tī xíng");
        details.setDescriptionB("梯形");
        details.setDescriptionC("Trapezium");
        details.setDescriptionD("Трапеция");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng fāng xíng");
        details.setDescriptionB("长方形");
        details.setDescriptionC("Rectangle");
        details.setDescriptionD("Прямоугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng xíng sì biān xíng");
        details.setDescriptionB("平行四边形");
        details.setDescriptionC("Parallelogram");
        details.setDescriptionD("Параллелограмм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ biān xíng ");
        details.setDescriptionB("五边形");
        details.setDescriptionC("Pentagon");
        details.setDescriptionD("Пятиугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liù jiǎo xíng ");
        details.setDescriptionB("六角形");
        details.setDescriptionC("Hexagon");
        details.setDescriptionD("Шестиугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qī biān xíng");
        details.setDescriptionB("七边形");
        details.setDescriptionC("Heptagon");
        details.setDescriptionD("Семиугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā biān xíng");
        details.setDescriptionB("八边形");
        details.setDescriptionC("Octagon");
        details.setDescriptionD("Восьмиугольник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiú tǐ");
        details.setDescriptionB("球体");
        details.setDescriptionC("Sphere");
        details.setDescriptionD("Cфера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lì fāng tǐ");
        details.setDescriptionB("立方体");
        details.setDescriptionC("Cube");
        details.setDescriptionD("Куб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuán zhuī tǐ");
        details.setDescriptionB("圆锥体");
        details.setDescriptionC("Cone");
        details.setDescriptionD("Конус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("léng zhuī tǐ ");
        details.setDescriptionB("棱锥体");
        details.setDescriptionC("Pyramid");
        details.setDescriptionD("Пирамида");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng xíng ");
        details.setDescriptionB("星形");
        details.setDescriptionC("Star");
        details.setDescriptionD("Звезда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīn");
        details.setDescriptionB("心");
        details.setDescriptionC("Heart");
        details.setDescriptionD("Сердце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí zì xíng ");
        details.setDescriptionB("十字形");
        details.setDescriptionC("Cross");
        details.setDescriptionD("Крест");
        detailsList.add(details);
    }
}
