package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C70 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" сhī zǎo cān");
        details.setDescriptionB("吃早餐");
        details.setDescriptionC("Have breakfast ");
        details.setDescriptionD("Завтракать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǎo shang nǐ xǐ huān chī shén me ");
        details.setDescriptionB("早上你喜欢吃什么？");
        details.setDescriptionC("What do you like for breakfast?");
        details.setDescriptionD("Что ты любишь на завтрак?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" báo jiān bǐng");
        details.setDescriptionB("薄煎饼");
        details.setDescriptionC("Pancake ");
        details.setDescriptionD(" Блин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng mì");
        details.setDescriptionB("蜂蜜");
        details.setDescriptionC("Honey");
        details.setDescriptionD("Мёд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ jiàng ");
        details.setDescriptionB("果酱");
        details.setDescriptionC("Jam");
        details.setDescriptionD("Джем");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ jiàng tǔ sī ");
        details.setDescriptionB("果酱吐司");
        details.setDescriptionC("Toasts with jam");
        details.setDescriptionD("Тосты с джемом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǔ sī");
        details.setDescriptionB("吐司");
        details.setDescriptionC("Toast");
        details.setDescriptionD("Тост");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī fàn ");
        details.setDescriptionB("稀饭");
        details.setDescriptionC("Porridge ");
        details.setDescriptionD("Каша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng cháng");
        details.setDescriptionB("香肠");
        details.setDescriptionC("Sausages");
        details.setDescriptionD("Сосиски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǔ jī dàn");
        details.setDescriptionB("煮鸡蛋");
        details.setDescriptionC("Boiled egg");
        details.setDescriptionD("Вареное яйцо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chǎo jī dàn");
        details.setDescriptionB("炒鸡蛋");
        details.setDescriptionC("Scrambled eggs");
        details.setDescriptionD("Яичница/ Омлет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" péi gēn chǎo dàn ");
        details.setDescriptionB("培根炒蛋");
        details.setDescriptionC("Bacon and eggs");
        details.setDescriptionD(" Яичница с беконом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān míng zhì");
        details.setDescriptionB("三明治");
        details.setDescriptionC("Sandwich ");
        details.setDescriptionD("Cэндвич");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn bāo hé huáng yóu");
        details.setDescriptionB("面包和黄油");
        details.setDescriptionC("Bread and butter");
        details.setDescriptionD("Хлеб с маслом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  miàn bāo ");
        details.setDescriptionB("面包");
        details.setDescriptionC("Bread ");
        details.setDescriptionD("Хлеб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù mǐ piàn ");
        details.setDescriptionB("玉米片");
        details.setDescriptionC("Corn-flakes");
        details.setDescriptionD(" Кукурузные хлопья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guǒ wèi suān nǎi ");
        details.setDescriptionB("果味酸奶");
        details.setDescriptionC("Fruit yogurt");
        details.setDescriptionD("Фруктовый йогурт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǎi lào");
        details.setDescriptionB(" 奶酪");
        details.setDescriptionC("Cheese");
        details.setDescriptionD("Сыр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú nǎi ");
        details.setDescriptionB("牛奶");
        details.setDescriptionC("Milk");
        details.setDescriptionD("Молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rè qiǎo kè lì");
        details.setDescriptionB("热巧克力");
        details.setDescriptionC("Hot chocolate");
        details.setDescriptionD("Горячий шоколад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi");
        details.setDescriptionB("咖啡");
        details.setDescriptionC("Coffee");
        details.setDescriptionD("Кофе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yī bēi chá ");
        details.setDescriptionB("一杯茶");
        details.setDescriptionC("A cup of tea");
        details.setDescriptionD("Чашка чая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yī bēi xiān zhà guǒ zhī ");
        details.setDescriptionB("一杯鲜榨果汁");
        details.setDescriptionC("A glass of fresh juice ");
        details.setDescriptionD("Cтакан свежего сока");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ zhī");
        details.setDescriptionB("果汁");
        details.setDescriptionC("Juice");
        details.setDescriptionD("Сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiān zhà guǒ zhī ");
        details.setDescriptionB("鲜榨果汁");
        details.setDescriptionC(" Fresh juice ");
        details.setDescriptionD("Свежевыжатый сок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīn xiān shuǐ guǒ ");
        details.setDescriptionB("新鲜水果");
        details.setDescriptionC("Fresh fruits");
        details.setDescriptionD("Свежие фрукты");
        detailsList.add(details);
    }
}
