package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C71 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" háng kōng gōng sī ");
        details.setDescriptionB("航空公司");
        details.setDescriptionC("Airlines");
        details.setDescriptionD("Авиакомпания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi jī chǎng ");
        details.setDescriptionB("飞机场");
        details.setDescriptionC("Airport");
        details.setDescriptionD("Аэропорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi jī");
        details.setDescriptionB("飞机");
        details.setDescriptionC("(Air)plane");
        details.setDescriptionD("Самолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dēng jī  ");
        details.setDescriptionB("登机");
        details.setDescriptionC("to get on/ to board the plane");
        details.setDescriptionD("Садиться в самолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qǐ fēi ");
        details.setDescriptionB("起飞");
        details.setDescriptionC("to take off/ to leave the ground");
        details.setDescriptionD("Взлетать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàng luò ");
        details.setDescriptionB("降落");
        details.setDescriptionC("To land");
        details.setDescriptionD("Приземляться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xià fēi jī ");
        details.setDescriptionB("下飞机");
        details.setDescriptionC("to get off the plane ");
        details.setDescriptionD("Сходить с самолёта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xíng lǐ ");
        details.setDescriptionB("行李");
        details.setDescriptionC("Baggage/ Luggage");
        details.setDescriptionD("Багаж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu tí xiāng");
        details.setDescriptionB("手提箱");
        details.setDescriptionC("Suitcase");
        details.setDescriptionD("Чемодан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bēi bāo");
        details.setDescriptionB("背包");
        details.setDescriptionC("Backpack");
        details.setDescriptionD("Рюкзак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiù shēng yī");
        details.setDescriptionB("救生衣");
        details.setDescriptionC("Life-jacket");
        details.setDescriptionD("Спасательный жилет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hù zhào ");
        details.setDescriptionB("护照");
        details.setDescriptionC("Passport");
        details.setDescriptionD("Паспорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiān zhèng");
        details.setDescriptionB("签证");
        details.setDescriptionC("Visa");
        details.setDescriptionD("Виза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huò bì");
        details.setDescriptionB("货币");
        details.setDescriptionC("Currency");
        details.setDescriptionD("Валюта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dì tú");
        details.setDescriptionB("地图");
        details.setDescriptionC("Map");
        details.setDescriptionD("Карта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("piào");
        details.setDescriptionB("票");
        details.setDescriptionC("Ticket");
        details.setDescriptionD("Билет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ chē ");
        details.setDescriptionB("火车");
        details.setDescriptionC("Train");
        details.setDescriptionD("Поезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dào dá ");
        details.setDescriptionB("到达");
        details.setDescriptionC("to arrive");
        details.setDescriptionD("Прибывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sòng xíng");
        details.setDescriptionB("送行");
        details.setDescriptionC("to see off");
        details.setDescriptionD("Провожать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǒu guǐ diàn chē ");
        details.setDescriptionB("有轨电车");
        details.setDescriptionC("Tram");
        details.setDescriptionD("Трамвай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng gòng qì chē / bā shì ");
        details.setDescriptionB("公共汽车/巴士");
        details.setDescriptionC("Bus");
        details.setDescriptionD("Автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chū zū chē");
        details.setDescriptionB("出租车");
        details.setDescriptionC("Taxi");
        details.setDescriptionD("Такси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì chē");
        details.setDescriptionB("汽车");
        details.setDescriptionC("Car/Automobile");
        details.setDescriptionD("Машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì yóu");
        details.setDescriptionB("汽油");
        details.setDescriptionC("Gas/Gasoline");
        details.setDescriptionD("Бензин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chuán");
        details.setDescriptionB("船");
        details.setDescriptionC("Ship");
        details.setDescriptionD("Корабль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lún chuán");
        details.setDescriptionB("轮船");
        details.setDescriptionC("Steamship");
        details.setDescriptionD("Пароход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǎng kǒu");
        details.setDescriptionB("港口");
        details.setDescriptionC("Port/ Harbor");
        details.setDescriptionD("Порт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó tuō chē");
        details.setDescriptionB("摩托车");
        details.setDescriptionC("Motorcycle/Motorbike");
        details.setDescriptionD("Мотоцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì xíng chē");
        details.setDescriptionB("自行车");
        details.setDescriptionC("Bicycle/Bike");
        details.setDescriptionD("Велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ chē zhàn ");
        details.setDescriptionB("火车站");
        details.setDescriptionC("Railway station / Train station");
        details.setDescriptionD("Вокзал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guó nèi lǚ yóu ");
        details.setDescriptionB("国内旅游");
        details.setDescriptionC("Domestic tourism");
        details.setDescriptionD("Внутренний туризм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó jì lǚ yóu");
        details.setDescriptionB("国际旅游");
        details.setDescriptionC("International tourism");
        details.setDescriptionD("Международный туризм (выездной туризм)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lín shí xìng yí mín");
        details.setDescriptionB("临时性移民");
        details.setDescriptionC("Temporary migration");
        details.setDescriptionD("Временная миграция");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhāo dài suǒ ");
        details.setDescriptionB("招待所");
        details.setDescriptionC("Guest house");
        details.setDescriptionD("Гостевой дом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ guǎn");
        details.setDescriptionB("旅馆");
        details.setDescriptionC("Hotel");
        details.setDescriptionD("Гостиница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biān jìng");
        details.setDescriptionB("边境");
        details.setDescriptionC("Border/Frontier");
        details.setDescriptionD("Граница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guó jì biān jiè ");
        details.setDescriptionB("国际边界");
        details.setDescriptionC("International boundaries");
        details.setDescriptionD("Международные границы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ yóu jǐng diǎn ");
        details.setDescriptionB("旅游景点");
        details.setDescriptionC("Attractions");
        details.setDescriptionD("Достопримечательности");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ōu zhōu guó jiā");
        details.setDescriptionB("欧洲国家");
        details.setDescriptionC("European countries");
        details.setDescriptionD("Европейские страны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī ōu ");
        details.setDescriptionB("西欧");
        details.setDescriptionC("Western Europe");
        details.setDescriptionD("Западная Европа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài xīn jià qī");
        details.setDescriptionB("带薪假期");
        details.setDescriptionC("Paid vacations");
        details.setDescriptionD("Оплачиваемый отпуск");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nián jià");
        details.setDescriptionB("年假");
        details.setDescriptionC("Annual vacation");
        details.setDescriptionD("Ежегодный отпуск");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chū guó");
        details.setDescriptionB("出国");
        details.setDescriptionC("To go abroad");
        details.setDescriptionD("Ехать за границу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guó wài");
        details.setDescriptionB("国外");
        details.setDescriptionC("Abroad");
        details.setDescriptionD("За границей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiě lù");
        details.setDescriptionB("铁路");
        details.setDescriptionC("Railway");
        details.setDescriptionD("Железная дорога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wài guó rén");
        details.setDescriptionB("外国人");
        details.setDescriptionC("Foreigner");
        details.setDescriptionD("Иностранец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  wài guó de");
        details.setDescriptionB("外国的");
        details.setDescriptionC("Foreign");
        details.setDescriptionD("Иностранный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuō yīng yǔ");
        details.setDescriptionB("说英语");
        details.setDescriptionC("To speak English");
        details.setDescriptionD("Говорить по-английски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǐ jiě ");
        details.setDescriptionB("理解");
        details.setDescriptionC("to understand");
        details.setDescriptionD("Понимать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng de ");
        details.setDescriptionB("轻的");
        details.setDescriptionC("Light ");
        details.setDescriptionD("Лёгкий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fāng xiàng ");
        details.setDescriptionB("方向");
        details.setDescriptionC("Direction");
        details.setDescriptionD("Направление");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ diàn ");
        details.setDescriptionB("旅店");
        details.setDescriptionC("Inn/ Hostelry");
        details.setDescriptionD("Небольшой отель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ guǎn fáng jiān ");
        details.setDescriptionB("旅馆房间");
        details.setDescriptionC("Hotel room");
        details.setDescriptionD("Номер в отеле");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huán jìng ");
        details.setDescriptionB("环境");
        details.setDescriptionC("Environment");
        details.setDescriptionD("Окружающая среда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎo yǔ guó jiā ");
        details.setDescriptionB("岛屿国家");
        details.setDescriptionC("Island state");
        details.setDescriptionD("Островное государство");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiū xí ");
        details.setDescriptionB("休息");
        details.setDescriptionC("Rest");
        details.setDescriptionD("Отдых");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dù jià ");
        details.setDescriptionB("度假");
        details.setDescriptionC("to be on vacation");
        details.setDescriptionD("Отдыхать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("míng xìn piàn ");
        details.setDescriptionB("明信片");
        details.setDescriptionC("Postcard");
        details.setDescriptionD("Открытка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎng niàn ");
        details.setDescriptionB("想念");
        details.setDescriptionC("To miss");
        details.setDescriptionD("Скучать (по)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hán shǔ jià ");
        details.setDescriptionB("寒暑假");
        details.setDescriptionC("Vacation");
        details.setDescriptionD("Каникулы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jià qī");
        details.setDescriptionB("假期");
        details.setDescriptionC("Vacation");
        details.setDescriptionD("Отпуск");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chū fā ");
        details.setDescriptionB("出发");
        details.setDescriptionC("to leave/ to depart");
        details.setDescriptionD("Отправляться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhàng péng ");
        details.setDescriptionB("帐篷");
        details.setDescriptionC("Tent");
        details.setDescriptionD("Палатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháo shèng shèng dì ");
        details.setDescriptionB("朝圣圣地");
        details.setDescriptionC("Pilgrimages to sacred places");
        details.setDescriptionD("Паломничество по святым местам");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn shū");
        details.setDescriptionB("运输");
        details.setDescriptionC("Transportation");
        details.setDescriptionD("Перевозка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ chéng");
        details.setDescriptionB("旅程");
        details.setDescriptionC("Journey/Trip/Tour");
        details.setDescriptionD("Поездка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bāo jià lǚ yóu ");
        details.setDescriptionB("包价旅游");
        details.setDescriptionC("Package tour");
        details.setDescriptionD("Поездка по путевке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ chéng/lù chéng ");
        details.setDescriptionB("旅程 /路程");
        details.setDescriptionC("Journey/ Voyage");
        details.setDescriptionD("Путешествие");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ xíng");
        details.setDescriptionB("旅行");
        details.setDescriptionC("to travel");
        details.setDescriptionD("Путешествовать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ yóu ");
        details.setDescriptionB("旅游");
        details.setDescriptionC("Tourism");
        details.setDescriptionD("Туризм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú lè");
        details.setDescriptionB("娱乐");
        details.setDescriptionC("Recreation");
        details.setDescriptionD("Развлечение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǔ tí lè yuán");
        details.setDescriptionB("主题乐园");
        details.setDescriptionC("Theme park");
        details.setDescriptionD("Парк отдыха с аттракционами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cān guǎn");
        details.setDescriptionB("餐馆");
        details.setDescriptionC("Restaurant");
        details.setDescriptionD("Ресторан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chéng shì");
        details.setDescriptionB("城市");
        details.setDescriptionC("Town /City");
        details.setDescriptionD("Город");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu dū");
        details.setDescriptionB("首都");
        details.setDescriptionC("Capital");
        details.setDescriptionD("Столица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó jiā");
        details.setDescriptionB("国家");
        details.setDescriptionC("Country");
        details.setDescriptionD("Страна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jì niàn pǐn shāng diàn");
        details.setDescriptionB("纪念品商店");
        details.setDescriptionC("Souvenir shops");
        details.setDescriptionD("Сувенирные магазины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ kè fú wù ");
        details.setDescriptionB("旅客服务");
        details.setDescriptionC("Services for travelers");
        details.setDescriptionD("Услуги для путешественников");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiū xián dù jià shèng dì ");
        details.setDescriptionB("休闲度假胜地");
        details.setDescriptionC("Resort");
        details.setDescriptionD("Курорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi bīn");
        details.setDescriptionB("海滨");
        details.setDescriptionC("Seaside/Coast");
        details.setDescriptionD("Побережье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi tān ");
        details.setDescriptionB("海滩");
        details.setDescriptionC("Beach");
        details.setDescriptionD("Пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rì guāng yù ");
        details.setDescriptionB("日光浴");
        details.setDescriptionC(" Sun spa ");
        details.setDescriptionD("Загорать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wēn quán ");
        details.setDescriptionB("温泉");
        details.setDescriptionC("Thermal spring");
        details.setDescriptionD("Термальный источник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kuàng quán shuǐ dù jià cūn ");
        details.setDescriptionB("矿泉水度假村");
        details.setDescriptionC("Spa");
        details.setDescriptionD(" Курорт с минеральными водами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán fāng");
        details.setDescriptionB("南方");
        details.setDescriptionC("the South");
        details.setDescriptionD("Юг");
        detailsList.add(details);
    }
}
