package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C72 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" zhōu mò ");
        details.setDescriptionB("周末");
        details.setDescriptionC("Weekend ");
        details.setDescriptionD("Выходные");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kàn");
        details.setDescriptionB("看");
        details.setDescriptionC(" Watch/Read ");
        details.setDescriptionD("Смотреть/Читать (про себя)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kàn diàn shì");
        details.setDescriptionB("看电视");
        details.setDescriptionC("Watch TV");
        details.setDescriptionD("Смотреть телевизор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn shì jié mù");
        details.setDescriptionB("电视节目");
        details.setDescriptionC(" TV show ");
        details.setDescriptionD(" Tелепередача");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tīng yīn yuè");
        details.setDescriptionB("听音乐");
        details.setDescriptionC("Listen to music");
        details.setDescriptionD("Слушать музыку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài shàng ěr jī");
        details.setDescriptionB("戴上耳机");
        details.setDescriptionC("Put on headphones");
        details.setDescriptionD("Одеть наушники");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zòng héng zì mí");
        details.setDescriptionB("纵横字谜");
        details.setDescriptionC("Crossword");
        details.setDescriptionD("Кроссворд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dí si kē wǔ tīng");
        details.setDescriptionB("迪斯科舞厅");
        details.setDescriptionC("Disco");
        details.setDescriptionD("Дискотека");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào wǔ");
        details.setDescriptionB("跳舞");
        details.setDescriptionC("Dance");
        details.setDescriptionD("Танцевать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāng ná");
        details.setDescriptionB("桑拿");
        details.setDescriptionC("Sauna");
        details.setDescriptionD("Сауна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sàn bù");
        details.setDescriptionB("散步");
        details.setDescriptionC(" Take a walk ");
        details.setDescriptionD("Прогуливаться/ Гулять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu lǎn ");
        details.setDescriptionB("游览");
        details.setDescriptionC("Excursion");
        details.setDescriptionD(" Экскурсия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎo yóu");
        details.setDescriptionB("导游");
        details.setDescriptionC(" Guide ");
        details.setDescriptionD("Экскурсовод");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ xíng shū");
        details.setDescriptionB("旅行书");
        details.setDescriptionC("Guidebook/ Travel  book");
        details.setDescriptionD("Путеводитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ xíng");
        details.setDescriptionB("旅行");
        details.setDescriptionC("Travel");
        details.setDescriptionD("Путешествовать/ Туризм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liáo yǎng yuàn ");
        details.setDescriptionB("疗养院");
        details.setDescriptionC(" Sanatorium ");
        details.setDescriptionD("Санаторий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí zì xíng chē");
        details.setDescriptionB("骑自行车");
        details.setDescriptionC("Cycling");
        details.setDescriptionD("Кататься на велосипеде ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yě cān");
        details.setDescriptionB("野餐");
        details.setDescriptionC("Picnic");
        details.setDescriptionD("Пикник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě yíng ");
        details.setDescriptionB("野营");
        details.setDescriptionC("Camping site");
        details.setDescriptionD("Кемпинг/ Палаточный лагерь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shōu cáng");
        details.setDescriptionB("收藏");
        details.setDescriptionC("Сollect");
        details.setDescriptionD("Коллекционировать/Cобирать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shōucáng jiā");
        details.setDescriptionB("收藏家");
        details.setDescriptionC("Collector");
        details.setDescriptionD("Коллекционер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shōu cáng pǐn");
        details.setDescriptionB("收藏品");
        details.setDescriptionC("Collection");
        details.setDescriptionD("Коллекция");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu xì");
        details.setDescriptionB("游戏");
        details.setDescriptionC("Game/Play");
        details.setDescriptionD("Игра/Играть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mào xiǎn");
        details.setDescriptionB("冒险");
        details.setDescriptionC("Risk");
        details.setDescriptionD("Риск/ Рисковать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎi piào");
        details.setDescriptionB("彩票");
        details.setDescriptionC("Lottery ticket");
        details.setDescriptionD("Лотерейный билет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сān guān");
        details.setDescriptionB("参观");
        details.setDescriptionC("Visit ");
        details.setDescriptionD("Посетить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tàn qīn");
        details.setDescriptionB("探亲");
        details.setDescriptionC("Visit relatives");
        details.setDescriptionD("Посещать родственников");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huá chuán ");
        details.setDescriptionB("划船");
        details.setDescriptionC("Sail on a boat");
        details.setDescriptionD("Плавать на лодке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zài shā tān shàng shài tài yáng ");
        details.setDescriptionB("在沙滩上晒太阳");
        details.setDescriptionC(" Tan on the beach ");
        details.setDescriptionD("Загорать на пляже");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  shài tài yáng");
        details.setDescriptionB("晒太阳");
        details.setDescriptionC("Sunbathe ");
        details.setDescriptionD("Принимать солнечные ванны/ Загорать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qù gōng yuán");
        details.setDescriptionB("去公园");
        details.setDescriptionC("Go to park");
        details.setDescriptionD("Пойти в парк");
        detailsList.add(details);
    }
}
