package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C76 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("hóng lǜ dēng");
        details.setDescriptionB("红绿灯");
        details.setDescriptionC("Traffic light");
        details.setDescriptionD("Светофор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lù biāo");
        details.setDescriptionB("路标");
        details.setDescriptionC(" Road sign ");
        details.setDescriptionD("Дорожный знак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rén xíng héng dào");
        details.setDescriptionB("人行横道");
        details.setDescriptionC("Crosswalk");
        details.setDescriptionD("Пешеходный переход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xíng rén");
        details.setDescriptionB("行人");
        details.setDescriptionC("Pedestrian");
        details.setDescriptionD("Пешеход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rén xíng dào");
        details.setDescriptionB("人行道");
        details.setDescriptionC(" Sidewalk ");
        details.setDescriptionD("Тротуар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo jiē");
        details.setDescriptionB("小街");
        details.setDescriptionC("Alley");
        details.setDescriptionD("Аллея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiē dào");
        details.setDescriptionB("街道");
        details.setDescriptionC("Street");
        details.setDescriptionD("Улица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí zì lù kǒu");
        details.setDescriptionB("十字路口");
        details.setDescriptionC("Crossroad");
        details.setDescriptionD("Перекрёсток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiáo");
        details.setDescriptionB("桥");
        details.setDescriptionC("Bridge");
        details.setDescriptionD("Мост");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sī jī");
        details.setDescriptionB("司机");
        details.setDescriptionC("Driver");
        details.setDescriptionD("Водитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā chē");
        details.setDescriptionB("刹车");
        details.setDescriptionC("To brake");
        details.setDescriptionD("Тормозить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tíng chē");
        details.setDescriptionB("停车");
        details.setDescriptionC("To park");
        details.setDescriptionD("Парковаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("míng dí ");
        details.setDescriptionB("鸣笛");
        details.setDescriptionC("Honk/Beep");
        details.setDescriptionD("Сигналить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiāo tōng liú liàng ");
        details.setDescriptionB("交通流量");
        details.setDescriptionC("Traffic");
        details.setDescriptionD("Движение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā sù");
        details.setDescriptionB("加速");
        details.setDescriptionC("Increase speed");
        details.setDescriptionD("Увеличивать скорость");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn sù");
        details.setDescriptionB("限速");
        details.setDescriptionC("Speed limit ");
        details.setDescriptionD("Ограничение скорости");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā yóu zhàn");
        details.setDescriptionB("加油站");
        details.setDescriptionC("Gas station");
        details.setDescriptionD("Бензоколонка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì chē yóu xiāng ");
        details.setDescriptionB("汽车油箱");
        details.setDescriptionC("Car tank");
        details.setDescriptionD("Бак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi chē");
        details.setDescriptionB("开车");
        details.setDescriptionC("Drive a car");
        details.setDescriptionD("Водить машину");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tíng chē wèi");
        details.setDescriptionB("停车位");
        details.setDescriptionC("Parking space");
        details.setDescriptionD("Место для парковки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zuò wèi");
        details.setDescriptionB("座位");
        details.setDescriptionC("Seat");
        details.setDescriptionD("Место/Cидение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sī jī zuò yǐ");
        details.setDescriptionB("司机座椅");
        details.setDescriptionC("Driver seat");
        details.setDescriptionD("Сидение водителя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān quán dài ");
        details.setDescriptionB("安全带");
        details.setDescriptionC("Seat belt");
        details.setDescriptionD("Ремень безопасности");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hòu shì jìng");
        details.setDescriptionB("后视镜");
        details.setDescriptionC("Rear view mirror ");
        details.setDescriptionD("Зеркало заднего вида");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cè chē jìng");
        details.setDescriptionB("侧车镜");
        details.setDescriptionC("Side mirror");
        details.setDescriptionD(" Боковое зеркало");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chē mén ");
        details.setDescriptionB("车门");
        details.setDescriptionC("Car door ");
        details.setDescriptionD("Дверь машины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fāng xiàng pán ");
        details.setDescriptionB("方向盘");
        details.setDescriptionC("Steering wheel");
        details.setDescriptionD("Руль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎng fēng bō lí ");
        details.setDescriptionB("挡风玻璃");
        details.setDescriptionC("Windscreen ");
        details.setDescriptionD("Лобовое стекло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǔ shuā");
        details.setDescriptionB("雨刷");
        details.setDescriptionC("Wipers");
        details.setDescriptionD("Дворники/ Стеклоочистители");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chē lún");
        details.setDescriptionB("车轮");
        details.setDescriptionC("Wheel");
        details.setDescriptionD("Колесо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bào tāi ");
        details.setDescriptionB("爆胎");
        details.setDescriptionC("Flat tire");
        details.setDescriptionD("Спущенное колесо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chē tāi");
        details.setDescriptionB("车胎");
        details.setDescriptionC("Tire/Tyre");
        details.setDescriptionD("Шина/ Покрышка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hòu bèi xiāng");
        details.setDescriptionB("后备箱");
        details.setDescriptionC("Car trunk/Car boot");
        details.setDescriptionD("Багажник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē fā dòng jī zhào");
        details.setDescriptionB("汽车发动机罩");
        details.setDescriptionC("Car bonnet/Car hood ");
        details.setDescriptionD("Капот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fā dòng jī /mǎ dá");
        details.setDescriptionB("发动机/马达");
        details.setDescriptionC("Engine / Motor");
        details.setDescriptionD("Двигатель/Мотор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì chē líng jiàn ");
        details.setDescriptionB("汽车零件");
        details.setDescriptionC(" Repair parts /Spare parts");
        details.setDescriptionD("Запчасти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yí biǎo pán ");
        details.setDescriptionB("仪表盘");
        details.setDescriptionC("Dashboard");
        details.setDescriptionD("Приборная панель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biàn sù xiāng");
        details.setDescriptionB("变速箱");
        details.setDescriptionC("Gearbox");
        details.setDescriptionD("Коробка передач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu shā ");
        details.setDescriptionB("手刹");
        details.setDescriptionC(" Handbrake ");
        details.setDescriptionD("Cтояночный тормоз/Ручник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tà bǎn");
        details.setDescriptionB("踏板");
        details.setDescriptionC("Pedal");
        details.setDescriptionD("Педаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lí hé qì");
        details.setDescriptionB("离合器");
        details.setDescriptionC("Clutch");
        details.setDescriptionD("Сцепление");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu mén tà bǎn");
        details.setDescriptionB("油门踏板");
        details.setDescriptionC("Gas pedal");
        details.setDescriptionD("Педаль газа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā chē xì tǒng ");
        details.setDescriptionB("刹车系统");
        details.setDescriptionC("Brake system");
        details.setDescriptionD("Тормозная система");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rán liào");
        details.setDescriptionB("燃料");
        details.setDescriptionC("Fuel");
        details.setDescriptionD("Топливо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì yóu");
        details.setDescriptionB("汽油");
        details.setDescriptionC("Petrol/Gas");
        details.setDescriptionD(" Бензин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jìn guāng dēng ");
        details.setDescriptionB("近光灯");
        details.setDescriptionC("Low beams");
        details.setDescriptionD("Ближние фары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuǎn guāng dēng ");
        details.setDescriptionB("远光灯");
        details.setDescriptionC("High beams");
        details.setDescriptionD("Дальние фары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qián dēng");
        details.setDescriptionB("前灯");
        details.setDescriptionC("Headlights");
        details.setDescriptionD("Передние фары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wěi dēng ");
        details.setDescriptionB("  尾灯");
        details.setDescriptionC("Taillights");
        details.setDescriptionD("Задние фары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chē pái");
        details.setDescriptionB("车牌");
        details.setDescriptionC("Licence plate");
        details.setDescriptionD("Номерной знак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pái zhào hào mǎ ");
        details.setDescriptionB("牌照号码");
        details.setDescriptionC("Licence plate number");
        details.setDescriptionD("Номер автомобиля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì chē mó xíng ");
        details.setDescriptionB("汽车模型");
        details.setDescriptionC("Car model");
        details.setDescriptionD("Модель автомобиля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎo xiǎn gàng");
        details.setDescriptionB("保险杠");
        details.setDescriptionC("Bumper / Fender");
        details.setDescriptionD("Бампер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē lǜ qīng qì");
        details.setDescriptionB("汽车滤清器");
        details.setDescriptionC("Car filter");
        details.setDescriptionD("Автомобильный фильтр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huó sāi gǎn");
        details.setDescriptionB("活塞杆");
        details.setDescriptionC("Piston");
        details.setDescriptionD("Поршень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē fáng dào bào jǐng qì ");
        details.setDescriptionB("汽车防盗报警器");
        details.setDescriptionC("Car signaling");
        details.setDescriptionD("Сигнализация автомобиля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē bǎo xiǎn");
        details.setDescriptionB("汽车保险");
        details.setDescriptionC("Car insurance ");
        details.setDescriptionD("Страхование автомобиля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì wài/ shì gù");
        details.setDescriptionB("意外/事故");
        details.setDescriptionC("Accident");
        details.setDescriptionD("Авария");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhuàng chē ");
        details.setDescriptionB("撞车");
        details.setDescriptionC(" Crash ");
        details.setDescriptionD("Попадать в аварию");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhuǎn wān ");
        details.setDescriptionB("转弯");
        details.setDescriptionC("Turn");
        details.setDescriptionD("Поворачивать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chāo chē");
        details.setDescriptionB("超车");
        details.setDescriptionC(" Overtake ");
        details.setDescriptionD("Обгонять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rào xíng");
        details.setDescriptionB("绕行");
        details.setDescriptionC("Detour");
        details.setDescriptionD("Объезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dào zhá ");
        details.setDescriptionB("道闸");
        details.setDescriptionC("Barrier");
        details.setDescriptionD("Шлагбаум");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chū kǒu ");
        details.setDescriptionB("出口");
        details.setDescriptionC(" Exit ");
        details.setDescriptionD("Выезд");
        detailsList.add(details);
    }
}
