package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C8 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("mǎ ");
        details.setDescriptionB("马");
        details.setDescriptionC("Horse ");
        details.setDescriptionD("Лошадь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qí shǒu ");
        details.setDescriptionB("骑手");
        details.setDescriptionC("Rider");
        details.setDescriptionD("Всадник/Наездник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qí shǒu mào ");
        details.setDescriptionB("骑手帽");
        details.setDescriptionC("Riding hat");
        details.setDescriptionD(" Жокейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ xuē ");
        details.setDescriptionB("马靴");
        details.setDescriptionC("Riding boots ");
        details.setDescriptionD("Сапоги для верховой езды ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ jù");
        details.setDescriptionB("马具");
        details.setDescriptionC("Horse harness");
        details.setDescriptionD("Сбруя верховой лошади");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ lè");
        details.setDescriptionB("马勒");
        details.setDescriptionC("Bridle");
        details.setDescriptionD("Удила/Уздечка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuǐ tào ");
        details.setDescriptionB("嘴套");
        details.setDescriptionC("Muzzle");
        details.setDescriptionD("Намордник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāng shéng ");
        details.setDescriptionB("缰绳");
        details.setDescriptionC("Rein");
        details.setDescriptionD("Поводья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tí tiě ");
        details.setDescriptionB("马蹄铁");
        details.setDescriptionC("Horseshoe");
        details.setDescriptionD("Подкова");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ biān");
        details.setDescriptionB("马鞭");
        details.setDescriptionC("Riding crop");
        details.setDescriptionD("Хлыст");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ ān ");
        details.setDescriptionB("马鞍");
        details.setDescriptionC("Saddle");
        details.setDescriptionD("Седло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān");
        details.setDescriptionB("鞯");
        details.setDescriptionC(" Saddlecloth ");
        details.setDescriptionD("Вальтрап");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dù dài ");
        details.setDescriptionB("肚带");
        details.setDescriptionC("Belly-band");
        details.setDescriptionD("Подпруга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ dèng ");
        details.setDescriptionB("马镫");
        details.setDescriptionC(" Stirrup ");
        details.setDescriptionD("Стремя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ dèng dòng ");
        details.setDescriptionB("马镫洞");
        details.setDescriptionC("Stirrup hole");
        details.setDescriptionD("Отверстие стремени");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hù xiōng jiǎ ");
        details.setDescriptionB("护胸甲");
        details.setDescriptionC("Breastplate");
        details.setDescriptionD("Нагрудник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tǎn");
        details.setDescriptionB("马毯");
        details.setDescriptionC("Horsecloth");
        details.setDescriptionD("Попона");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bù ");
        details.setDescriptionB("步");
        details.setDescriptionC("Step");
        details.setDescriptionD("Шаг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" màn pǎo ");
        details.setDescriptionB("慢跑");
        details.setDescriptionC("Canter");
        details.setDescriptionD("Рысь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jí chí ");
        details.setDescriptionB("疾驰");
        details.setDescriptionC("Gallop");
        details.setDescriptionD("Галоп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhàng ài ");
        details.setDescriptionB("障碍");
        details.setDescriptionC("Barrier");
        details.setDescriptionD("Барьер/Препятствие");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ zhàng ");
        details.setDescriptionB("水障");
        details.setDescriptionC("Ditch");
        details.setDescriptionD("Канава");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhàng ài sài  ");
        details.setDescriptionB(" 障碍赛");
        details.setDescriptionC("Jump through the barrier");
        details.setDescriptionD("Преодоление препятствий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ qiú ");
        details.setDescriptionB("马球");
        details.setDescriptionC("Polo ");
        details.setDescriptionD("Поло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhàng ài sài mǎ ");
        details.setDescriptionB("障碍赛马");
        details.setDescriptionC("Steeplechase");
        details.setDescriptionD("Стипль-чез");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài mǎ");
        details.setDescriptionB("赛马");
        details.setDescriptionC("Horse racing");
        details.setDescriptionD("Скачки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuè zhàng ài sài ");
        details.setDescriptionB("越障碍赛");
        details.setDescriptionC("Show jumping");
        details.setDescriptionD("Конкур");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng jià chē sài ");
        details.setDescriptionB("轻驾车赛");
        details.setDescriptionC("Harness race");
        details.setDescriptionD("Гонка упряжек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ chē sài ");
        details.setDescriptionB("马车赛");
        details.setDescriptionC("Carriage race");
        details.setDescriptionD("Гонка карет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сháng tú lǚ xíng");
        details.setDescriptionB("长途旅行");
        details.setDescriptionC("Trekking");
        details.setDescriptionD("Поход ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā shì qí shù ");
        details.setDescriptionB("花式骑术");
        details.setDescriptionC("Dressage");
        details.setDescriptionD("Объездка лошадей");
        detailsList.add(details);
    }

}
