package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C80 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" dà bái shā ");
        details.setDescriptionB("大白鲨");
        details.setDescriptionC(" Great white shark ");
        details.setDescriptionD(" Белая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī shā ");
        details.setDescriptionB("丝鲨");
        details.setDescriptionC(" Silky Shark ");
        details.setDescriptionD("Шёлковая акула ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīng shā");
        details.setDescriptionB("鲸鲨");
        details.setDescriptionC("Whale shark");
        details.setDescriptionD("Китовая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǎo shā ");
        details.setDescriptionB("姥鲨");
        details.setDescriptionC("Basking Shark");
        details.setDescriptionD("Гиганская акула ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú shā ");
        details.setDescriptionB("牛鲨");
        details.setDescriptionC("Bull shark");
        details.setDescriptionD("Акула-бык/Тупорылая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jù kǒu shā ");
        details.setDescriptionB("巨口鲨");
        details.setDescriptionC("Megamouth shark ");
        details.setDescriptionD("Большеротая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā hǔ shā ");
        details.setDescriptionB("沙虎鲨");
        details.setDescriptionC("Sand tiger shark");
        details.setDescriptionD("Тигровая песчаная акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǔ shā");
        details.setDescriptionB("虎鲨");
        details.setDescriptionC("Tiger shark ");
        details.setDescriptionD("Тигровая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("níng méng shā ");
        details.setDescriptionB("柠檬鲨");
        details.setDescriptionC("Lemon shark");
        details.setDescriptionD("Лимонная акула ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà qīng shā ");
        details.setDescriptionB("大青鲨");
        details.setDescriptionC("Blue shark");
        details.setDescriptionD("Голубая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng jì shā ");
        details.setDescriptionB("双髻鲨");
        details.setDescriptionC(" Great Hammerhead shark ");
        details.setDescriptionD(" Гигантская акула-молот ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gé líng lán shuì shā ");
        details.setDescriptionB("格陵兰睡鲨");
        details.setDescriptionC("Greenland shark");
        details.setDescriptionD("Гренландская полярная акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo bān māo shā ");
        details.setDescriptionB("小斑猫鲨");
        details.setDescriptionC("Cat shark");
        details.setDescriptionD("Кошачья акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng wěi shā");
        details.setDescriptionB("长尾鲨");
        details.setDescriptionC("Thresher Shark");
        details.setDescriptionD("Лисья акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu shì jiān wěn jiāo ");
        details.setDescriptionB("欧氏尖吻鲛");
        details.setDescriptionC("Goblin shark ");
        details.setDescriptionD("Акула-домовой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī qīng shā ");
        details.setDescriptionB("灰鲭鲨 ");
        details.setDescriptionC("Mako shark ");
        details.setDescriptionD("Акула-мако");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bào wén shā ");
        details.setDescriptionB("豹纹鲨");
        details.setDescriptionC("Zebra shark");
        details.setDescriptionD("Зебровая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān diǎn xū shā ");
        details.setDescriptionB("斑点须鲨");
        details.setDescriptionC(" Spotted wobbegong ");
        details.setDescriptionD("Ковровая акула/ Пятнистый воббегонг ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hù shì shā ");
        details.setDescriptionB("护士鲨");
        details.setDescriptionC("Nurse shark ");
        details.setDescriptionD("Акула-нянька");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo shā ");
        details.setDescriptionB("角鲨");
        details.setDescriptionC("Dogfish Shark ");
        details.setDescriptionD("Акула катран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào dà lì yà hǔ shā ");
        details.setDescriptionB("澳大利亚虎鲨");
        details.setDescriptionC("Port Jackson Shark");
        details.setDescriptionD("Австралийская рогатая акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiān wěn qī sāi shā ");
        details.setDescriptionB("尖吻七鳃鲨");
        details.setDescriptionC(" Sharpnose Sevengill Shark");
        details.setDescriptionD("Семижаберная акула ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhòu sāi shā ");
        details.setDescriptionB("皱鳃鲨");
        details.setDescriptionC("Frilled Shark");
        details.setDescriptionD("Плащеносная акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biǎn shā ");
        details.setDescriptionB("扁鲨");
        details.setDescriptionC("Angelshark");
        details.setDescriptionD("Морской ангел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jù yáo ");
        details.setDescriptionB("锯鳐");
        details.setDescriptionC(" Sawfish ");
        details.setDescriptionD(" Пилорылый скат /Акула-пила ");
        detailsList.add(details);
    }
}
