package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C0 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details = new Details();
        details.setDescriptionA("先生");
        details.setDescriptionB("xiānshēng");
        details.setDescriptionC("Mr");
        details.setDescriptionD("Мистер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("太太");
        details.setDescriptionB("tài tai");
        details.setDescriptionC("Mrs");
        details.setDescriptionD("Миссис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("小姐");
        details.setDescriptionB("xiǎo jiě");
        details.setDescriptionC("Miss");
        details.setDescriptionD("Мисс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("亲戚");
        details.setDescriptionB("īn qin");
        details.setDescriptionC("Relatives");
        details.setDescriptionD("Родственники");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("父母");
        details.setDescriptionB("fù mǔ");
        details.setDescriptionC("Parents");
        details.setDescriptionD("Родители");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("老人");
        details.setDescriptionB("lǎo rén");
        details.setDescriptionC("Senior man");
        details.setDescriptionD("Пожилой мужчина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("男人");
        details.setDescriptionB("nán rén");
        details.setDescriptionC("Man");
        details.setDescriptionD("Мужчина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chéng nián rén/chéng rén");
        details.setDescriptionB("成年人/成人");
        details.setDescriptionC("Adult");
        details.setDescriptionD("Взрослый человек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("年轻人");
        details.setDescriptionB("nián qīng rén");
        details.setDescriptionC("Young man");
        details.setDescriptionD("Молодой человек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("青少年");
        details.setDescriptionB("qīng shào nián");
        details.setDescriptionC("Teenager");
        details.setDescriptionD("Юноша/ Подросток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("男孩");
        details.setDescriptionB("nán hái");
        details.setDescriptionC("Boy");
        details.setDescriptionD("Мальчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("孩子们");
        details.setDescriptionB("hái zi men");
        details.setDescriptionC("Children");
        details.setDescriptionD("Дети");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("宝宝/宝贝");
        details.setDescriptionB("bǎo bao/ bǎo bèi");
        details.setDescriptionC("Baby");
        details.setDescriptionD("Малыш");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("孩子");
        details.setDescriptionB("hái zi");
        details.setDescriptionC("Child");
        details.setDescriptionD("Ребёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér");
        details.setDescriptionB("婴儿");
        details.setDescriptionC("Newborn");
        details.setDescriptionD("Новорожденный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("双胞胎");
        details.setDescriptionB("shuāng bāo tāi");
        details.setDescriptionC("Twins");
        details.setDescriptionD("Близнецы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("老太太");
        details.setDescriptionB("lǎo tài tai");
        details.setDescriptionC("Senior lady");
        details.setDescriptionD("Пожилая женщина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("妇女/ 女人");
        details.setDescriptionB("fù nǚ/ nǚ rén");
        details.setDescriptionC("Woman");
        details.setDescriptionD("Женщина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("姑娘");
        details.setDescriptionB("gū niáng");
        details.setDescriptionC("Lady");
        details.setDescriptionD("Девушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("女孩");
        details.setDescriptionB("nǚ hái");
        details.setDescriptionC("Girl");
        details.setDescriptionD("Девочка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("爸爸");
        details.setDescriptionB("bà bà");
        details.setDescriptionC("Father");
        details.setDescriptionD("Папа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("妈妈");
        details.setDescriptionB("mā mā");
        details.setDescriptionC("Mother");
        details.setDescriptionD("Мама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("儿子");
        details.setDescriptionB("ér zi");
        details.setDescriptionC("Son");
        details.setDescriptionD("Сын");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("女儿");
        details.setDescriptionB("nǚ ér");
        details.setDescriptionC("Daughter");
        details.setDescriptionD("Дочь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("父 亲");
        details.setDescriptionB("fù qīn");
        details.setDescriptionC("Father");
        details.setDescriptionD("Отец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("母亲");
        details.setDescriptionB("mǔ qīn");
        details.setDescriptionC("Mother");
        details.setDescriptionD("Мать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("表兄弟");
        details.setDescriptionB("biǎo xiōng dì");
        details.setDescriptionC("Cousin");
        details.setDescriptionD("Двоюродный брат/Кузен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("表姐/表妹");
        details.setDescriptionB("biǎo jiě/biǎo mèi");
        details.setDescriptionC("Cousin");
        details.setDescriptionD("Двоюродная сестра/Кузина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("兄 弟");
        details.setDescriptionB("xiōng dì");
        details.setDescriptionC("Brother");
        details.setDescriptionD("Брат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("哥哥");
        details.setDescriptionB("gē ge");
        details.setDescriptionC("Elder brother");
        details.setDescriptionD("Старший брат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("弟弟");
        details.setDescriptionB("dì di");
        details.setDescriptionC("Younger brother");
        details.setDescriptionD("Младший брат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiě jie");
        details.setDescriptionB("姐姐");
        details.setDescriptionC("Elder sister");
        details.setDescriptionD("Старшая сестра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("妹妹");
        details.setDescriptionB("mèi mei");
        details.setDescriptionC("Younger sister");
        details.setDescriptionD("Младшая сестра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("外婆");
        details.setDescriptionB("wài pó");
        details.setDescriptionC("Maternal grandmother");
        details.setDescriptionD("Бабушка(по материнской линии)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("外公");
        details.setDescriptionB("wài gōng");
        details.setDescriptionC("Maternal grandfather");
        details.setDescriptionD("Дедушка( по материнской линии)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("祖母/奶奶");
        details.setDescriptionB("zǔ mǔ /nǎi nai");
        details.setDescriptionC("Grandmother");
        details.setDescriptionD("Бабушка ( по отцовской линии)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("祖父/爷爷");
        details.setDescriptionB("zǔ fù /yé ye");
        details.setDescriptionC("Grandfather");
        details.setDescriptionD("Дедушка (по отцовской линии)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("孙子");
        details.setDescriptionB("sūn zi");
        details.setDescriptionC("Grandson");
        details.setDescriptionD("Внук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("孙女");
        details.setDescriptionB("sūn nǚ");
        details.setDescriptionC("Granddaughter");
        details.setDescriptionD("Внучка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("夫妇");
        details.setDescriptionB("fū fù");
        details.setDescriptionC("Married couple");
        details.setDescriptionD("Cупруги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("爱人");
        details.setDescriptionB("ài ren");
        details.setDescriptionC("My love");
        details.setDescriptionD("Любимый/ Любимая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("配偶/伙伴");
        details.setDescriptionB("pèi ǒu/huǒ bàn");
        details.setDescriptionC("Partner");
        details.setDescriptionD("Партнёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("丈夫");
        details.setDescriptionB("zhàng fū");
        details.setDescriptionC("Husband");
        details.setDescriptionD("Муж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("妻子");
        details.setDescriptionB("qī zi");
        details.setDescriptionC("Wife");
        details.setDescriptionD("Жена");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("继母/后妈");
        details.setDescriptionB("jì mǔ/hòu mā");
        details.setDescriptionC("Stepmother");
        details.setDescriptionD("Мачеха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("继父");
        details.setDescriptionB("jì fù");
        details.setDescriptionC("Stepfather");
        details.setDescriptionD("Отчим");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("继女");
        details.setDescriptionB("jì nǚ");
        details.setDescriptionC("Stepdaughter");
        details.setDescriptionD("Падчерица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("继子");
        details.setDescriptionB("jì zǐ");
        details.setDescriptionC("Stepson");
        details.setDescriptionD("Пасынок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("公公");
        details.setDescriptionB("gōng gong");
        details.setDescriptionC("Husband's father");
        details.setDescriptionD("Свёкор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("婆婆");
        details.setDescriptionB("pó po");
        details.setDescriptionC("Husband's mother");
        details.setDescriptionD("Свекровь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("岳父");
        details.setDescriptionB("yuè fù");
        details.setDescriptionC("Father-in-law");
        details.setDescriptionD("Тесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("岳母");
        details.setDescriptionB("yuè mǔ");
        details.setDescriptionC("Mother-in-law");
        details.setDescriptionD("Тёща");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("未婚夫/新郎");
        details.setDescriptionB("wèi hūn fū/xīn láng");
        details.setDescriptionC("Bridegroom");
        details.setDescriptionD("Жених");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("未婚妻/ 新娘");
        details.setDescriptionB("wèi hūn qī/ xīn niáng");
        details.setDescriptionC("Bride");
        details.setDescriptionD("Невеста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("姐夫/妹夫");
        details.setDescriptionB("jiě fū/mèi fū");
        details.setDescriptionC("Brother-in-law");
        details.setDescriptionD("Шурин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("女婿");
        details.setDescriptionB("nǚ xù");
        details.setDescriptionC("Son-in-law");
        details.setDescriptionD("Зять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("儿媳妇");
        details.setDescriptionB("ér xí fù");
        details.setDescriptionC("Daughter-in-law");
        details.setDescriptionD("Невестка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("叔叔/伯伯");
        details.setDescriptionB("shū shu/ bó bo");
        details.setDescriptionC("Uncle");
        details.setDescriptionD("Дядя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("姑妈/姑母");
        details.setDescriptionB("gū mā /gū mǔ");
        details.setDescriptionC("Aunt");
        details.setDescriptionD("Тётя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("侄子/外甥");
        details.setDescriptionB("zhí zī/wài shēng");
        details.setDescriptionC("Nephew");
        details.setDescriptionD("Племянник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("侄女/外甥女");
        details.setDescriptionB("zhí nǚ / wài shēng nǚ");
        details.setDescriptionC("Niece");
        details.setDescriptionD("Племянница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("保姆");
        details.setDescriptionB("bǎo mǔ");
        details.setDescriptionC("Babysitter");
        details.setDescriptionD("Няня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("主人");
        details.setDescriptionB("zhǔ rén");
        details.setDescriptionC("Host");
        details.setDescriptionD("Хозяин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("主人");
        details.setDescriptionB("zhǔ rén");
        details.setDescriptionC("Hostess");
        details.setDescriptionD("Хозяйка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("客人");
        details.setDescriptionB("kè rén");
        details.setDescriptionC("Guest");
        details.setDescriptionD("Гость");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("世代");
        details.setDescriptionB("shì dài");
        details.setDescriptionC("Generation");
        details.setDescriptionD("Поколение");
        detailsList.add(details);
    }
}
