package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C34 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("yáng ròu ");
        details.setDescriptionB("羊肉");
        details.setDescriptionC("Mutton");
        details.setDescriptionD("Баранина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luò tuó ròu ");
        details.setDescriptionB("骆驼肉");
        details.setDescriptionC("Camel meat");
        details.setDescriptionD("Верблюжатина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" é ròu");
        details.setDescriptionB("鹅肉");
        details.setDescriptionC("Goose meat");
        details.setDescriptionD("Гусятина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  niú ròu");
        details.setDescriptionB("牛肉");
        details.setDescriptionC("Beef");
        details.setDescriptionD("Говядина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo niú ròu");
        details.setDescriptionB("小牛肉");
        details.setDescriptionC("Veal");
        details.setDescriptionD("Телятина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yě tù ròu ");
        details.setDescriptionB("野兔肉");
        details.setDescriptionC(" Hare meat");
        details.setDescriptionD("Зайчатина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān yáng ròu ");
        details.setDescriptionB("山羊肉");
        details.setDescriptionC(" Goat meat ");
        details.setDescriptionD("Козье мясо/ Козлятина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ ròu");
        details.setDescriptionB("马肉");
        details.setDescriptionC("Horsemeat");
        details.setDescriptionD("Конина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tù ròu");
        details.setDescriptionB("兔肉");
        details.setDescriptionC("Rabbit meat");
        details.setDescriptionD("Крольчатина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī ròu");
        details.setDescriptionB("鸡肉");
        details.setDescriptionC("Chicken");
        details.setDescriptionD("Куриное мясо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí lù ròu ");
        details.setDescriptionB("麋鹿肉");
        details.setDescriptionC("Moose meat");
        details.setDescriptionD("Лосина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ niú ròu ");
        details.setDescriptionB("水牛肉");
        details.setDescriptionC("Buffalo Ribeye ");
        details.setDescriptionD("Мясо буйвола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ān chún ròu");
        details.setDescriptionB("鹌鹑肉");
        details.setDescriptionC("Quail meat");
        details.setDescriptionD("Мясо перепелки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā ròu");
        details.setDescriptionB("鸭肉");
        details.setDescriptionC("Duck meat");
        details.setDescriptionD("Мясо утки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lù ròu");
        details.setDescriptionB("鹿肉");
        details.setDescriptionC("Deer meat");
        details.setDescriptionD("Оленина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū ròu");
        details.setDescriptionB("猪肉");
        details.setDescriptionC("Pork");
        details.setDescriptionD("Свинина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú ròu gān");
        details.setDescriptionB("牛肉干");
        details.setDescriptionC("Basturma");
        details.setDescriptionD("Бастурма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xūn ròu");
        details.setDescriptionB("熏肉");
        details.setDescriptionC("Bacon");
        details.setDescriptionD("Бекон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎo zhū ròu ");
        details.setDescriptionB("烤猪肉");
        details.setDescriptionC("Сold boiled pork");
        details.setDescriptionD("Буженина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ tuǐ");
        details.setDescriptionB("火腿");
        details.setDescriptionC("Ham");
        details.setDescriptionD("Ветчина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo xiāng cháng");
        details.setDescriptionB("小香肠");
        details.setDescriptionC("Sausages");
        details.setDescriptionD("Сосиски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cuì pí cháng ");
        details.setDescriptionB("脆皮肠");
        details.setDescriptionC("Fat sausages");
        details.setDescriptionD("Сардельки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng cháng");
        details.setDescriptionB("香肠");
        details.setDescriptionC(" Sausage ");
        details.setDescriptionD("Колбаса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("féi zhū ròu ");
        details.setDescriptionB("肥猪肉");
        details.setDescriptionC("Lard");
        details.setDescriptionD("Сало");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rén zào ròu");
        details.setDescriptionB("人造肉");
        details.setDescriptionC("Artificial meat");
        details.setDescriptionD("Искуственное мясо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū gān");
        details.setDescriptionB("猪肝");
        details.setDescriptionC("Pork liver");
        details.setDescriptionD("Свиная печень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū xīn");
        details.setDescriptionB("猪心");
        details.setDescriptionC("Pork heart");
        details.setDescriptionD("Сердце свиное");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī xīn ");
        details.setDescriptionB("鸡心");
        details.setDescriptionC(" Chicken heart ");
        details.setDescriptionD("Сердце куриное");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jī zhēn ");
        details.setDescriptionB("鸡胗");
        details.setDescriptionC("Chicken navel");
        details.setDescriptionD("Пупок куриный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ jī");
        details.setDescriptionB("火鸡");
        details.setDescriptionC("Turkey meat");
        details.setDescriptionD("Индейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng ròu xiàn ");
        details.setDescriptionB("羊肉馅");
        details.setDescriptionC("Minced mutton");
        details.setDescriptionD("Фарш бараний");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú ròu xiàn ");
        details.setDescriptionB("牛肉馅");
        details.setDescriptionC("Ground beef");
        details.setDescriptionD("Фарш говяжий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū ròu xiàn ");
        details.setDescriptionB("猪肉馅");
        details.setDescriptionC("Minced pork");
        details.setDescriptionD("Фарш свиной");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū shé");
        details.setDescriptionB("猪舌");
        details.setDescriptionC("Pork tongue");
        details.setDescriptionD(" Свиной язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú shé");
        details.setDescriptionB("牛舌");
        details.setDescriptionC("Beef tongue");
        details.setDescriptionD(" Говяжий язык");
        detailsList.add(details);

    }
}
