package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C35 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" páng xiè ");
        details.setDescriptionB("螃蟹");
        details.setDescriptionC("Crab");
        details.setDescriptionD("Краб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xiā ");
        details.setDescriptionB("大虾");
        details.setDescriptionC("King prawn ");
        details.setDescriptionD("Королевская креветка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiā ");
        details.setDescriptionB("虾");
        details.setDescriptionC("Shrimp");
        details.setDescriptionD("Креветка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín xiā  ");
        details.setDescriptionB("磷虾");
        details.setDescriptionC("Krill");
        details.setDescriptionD("Криль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lóng xiā ");
        details.setDescriptionB("龙虾");
        details.setDescriptionC("Lobster");
        details.setDescriptionD("Лобстер/ Омар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí cì lóng xiā ");
        details.setDescriptionB("棘刺龙虾");
        details.setDescriptionC("Spiny lobster/Langouste");
        details.setDescriptionD("Лангуст");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nuó wēi hǎi áo xiā");
        details.setDescriptionB("挪威海螯虾");
        details.setDescriptionC("Langoustine/ Norway lobster");
        details.setDescriptionD("Лангустин/Норвежский омар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo lóng xiā ");
        details.setDescriptionB("小龙虾");
        details.setDescriptionC("Crayfish");
        details.setDescriptionD("Рак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ lì/ háo ");
        details.setDescriptionB("牡蛎/ 蚝");
        details.setDescriptionC(" Oyster ");
        details.setDescriptionD("Устрица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yí bèi ");
        details.setDescriptionB("贻贝");
        details.setDescriptionC(" Mussel ");
        details.setDescriptionD("Мидия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shàn bèi");
        details.setDescriptionB("扇贝");
        details.setDescriptionC(" Scallop");
        details.setDescriptionD("Морской гребешок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhēng zi /zhú chēng ");
        details.setDescriptionB("蛏子/竹蛏");
        details.setDescriptionC(" Razor Clam ");
        details.setDescriptionD("Морской черенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yú");
        details.setDescriptionB("鱿鱼");
        details.setDescriptionC(" Squid ");
        details.setDescriptionD("Кальмар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhāng yú ");
        details.setDescriptionB("章鱼");
        details.setDescriptionC(" Octopus ");
        details.setDescriptionD("Осьминог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wū zéi ");
        details.setDescriptionB("乌贼");
        details.setDescriptionC(" Cuttlefish ");
        details.setDescriptionD("Каракатица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chéng sè zú hǎi shēn");
        details.setDescriptionB("橙色足海参");
        details.setDescriptionC("Orange sea cucumber");
        details.setDescriptionD("Кукумария  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi shēn");
        details.setDescriptionB("海参 ");
        details.setDescriptionC("Sea cucumber");
        details.setDescriptionD("Трепанг/Морской огурец ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǎo lèi");
        details.setDescriptionB("藻类");
        details.setDescriptionC("Algae");
        details.setDescriptionD("Водоросли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luó xuán zǎo ");
        details.setDescriptionB("螺旋藻");
        details.setDescriptionC("Spirulina");
        details.setDescriptionD("Спирулина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shòu sī ");
        details.setDescriptionB("寿司");
        details.setDescriptionC("Sushi");
        details.setDescriptionD("Суши");
        detailsList.add(details);
        

    }
}
