package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C40 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("wǎn lǐ fú");
        details.setDescriptionB("晚礼服");
        details.setDescriptionC("Evening dress");
        details.setDescriptionD("Вечернее платье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hūn shā lǐ fú ");
        details.setDescriptionB("婚纱礼服");
        details.setDescriptionC(" Wedding dress");
        details.setDescriptionD(" Свадебное платье ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lián yī qún ");
        details.setDescriptionB("连衣裙");
        details.setDescriptionC("Dress");
        details.setDescriptionD("Платье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǚ shì chèn shān");
        details.setDescriptionB("女式衬衫");
        details.setDescriptionC(" Women's   blouse ");
        details.setDescriptionD("Женская блузка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǐng zi");
        details.setDescriptionB("领子");
        details.setDescriptionC("Collar");
        details.setDescriptionD("Воротник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zhuāng shàng yī");
        details.setDescriptionB("西装上衣");
        details.setDescriptionC("Suit jacket ");
        details.setDescriptionD("Пиджак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kù zi ");
        details.setDescriptionB("裤子");
        details.setDescriptionC("Trousers");
        details.setDescriptionD("Брюки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí nǐ qún");
        details.setDescriptionB("迷你裙");
        details.setDescriptionC("Mini-skirt");
        details.setDescriptionD("Миниюбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qún zi");
        details.setDescriptionB("裙子");
        details.setDescriptionC("Skirt");
        details.setDescriptionD("Юбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo lǐng máo yī");
        details.setDescriptionB("高领毛衣");
        details.setDescriptionC("Turtleneck");
        details.setDescriptionD("Водолазка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lián kù wà");
        details.setDescriptionB("连裤袜");
        details.setDescriptionC("Tights");
        details.setDescriptionD("Колготки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sī wà");
        details.setDescriptionB("丝袜");
        details.setDescriptionC("Silk stockings");
        details.setDescriptionD("Шёлковые чулки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng tǒng wà ");
        details.setDescriptionB("长筒袜");
        details.setDescriptionC("Stockings");
        details.setDescriptionD("Чулки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diào wà dài ");
        details.setDescriptionB("吊袜带 ");
        details.setDescriptionC("Garters");
        details.setDescriptionD(" Подвязка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nèi yī ");
        details.setDescriptionB("内衣 ");
        details.setDescriptionC("Underwear");
        details.setDescriptionD("Нижнее белье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiōng zhào ");
        details.setDescriptionB("胸罩");
        details.setDescriptionC("Bra");
        details.setDescriptionD("Бюстгальтер/ Лифчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nèi kù ");
        details.setDescriptionB("内裤");
        details.setDescriptionC(" Underpant ");
        details.setDescriptionD("Трусы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dīng zì kù ");
        details.setDescriptionB("丁字裤");
        details.setDescriptionC("Strings");
        details.setDescriptionD("Стринги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ jī ní");
        details.setDescriptionB("比基尼");
        details.setDescriptionC("Bikini");
        details.setDescriptionD("Бикини");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǒng yī/yǒng zhuāng");
        details.setDescriptionB("泳衣/泳装");
        details.setDescriptionC("Swimsuit");
        details.setDescriptionD("Купальник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn dòng xiōng zhào ");
        details.setDescriptionB("运动胸罩");
        details.setDescriptionC("Sports bra");
        details.setDescriptionD("Спортивный бюстгальтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bèi xīn");
        details.setDescriptionB("背心");
        details.setDescriptionC("Vest");
        details.setDescriptionD("Майка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jǐn shēn kù ");
        details.setDescriptionB("紧身裤");
        details.setDescriptionC(" Tights ");
        details.setDescriptionD(" Тайтсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn dòng zhuāng");
        details.setDescriptionB("运动装");
        details.setDescriptionC("Sports suit");
        details.setDescriptionD("Спотривный костюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn wà  ");
        details.setDescriptionB("短袜");
        details.setDescriptionC("Socks");
        details.setDescriptionD("Носки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎo zhǐ wà /fēn zhǐ wà ");
        details.setDescriptionB("脚趾袜/分趾袜 ");
        details.setDescriptionC("Toe socks");
        details.setDescriptionD("Носки с пальцами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yāo dài");
        details.setDescriptionB("腰带");
        details.setDescriptionC("Belt");
        details.setDescriptionD("Пояс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú zǎi kù");
        details.setDescriptionB("牛仔裤");
        details.setDescriptionC("Jeans");
        details.setDescriptionD("Джинсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǒu dài");
        details.setDescriptionB("口袋");
        details.setDescriptionC("Pocket");
        details.setDescriptionD("Карман");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn kù");
        details.setDescriptionB("短裤");
        details.setDescriptionC("Shorts");
        details.setDescriptionD("Шорты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuìyī");
        details.setDescriptionB("睡衣");
        details.setDescriptionC(" Pajamas ");
        details.setDescriptionD("Пижама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chén yī");
        details.setDescriptionB("晨衣");
        details.setDescriptionC("Bathrobe");
        details.setDescriptionD("Халат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎo mào");
        details.setDescriptionB("草帽");
        details.setDescriptionC("Straw hat");
        details.setDescriptionD("Соломенная шляпка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mào zi");
        details.setDescriptionB("帽子");
        details.setDescriptionC("Hat");
        details.setDescriptionD("Шляпа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng róng wéi jīn");
        details.setDescriptionB("羊绒围巾");
        details.setDescriptionC("Cashmere scarf ");
        details.setDescriptionD("Кашемировый шарф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī jīn ");
        details.setDescriptionB("丝巾");
        details.setDescriptionC("Silk scarf  ");
        details.setDescriptionD("Шёлковый платок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā lì ");
        details.setDescriptionB("纱丽");
        details.setDescriptionC("Sari ");
        details.setDescriptionD("Сари");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiá kè");
        details.setDescriptionB("夹克");
        details.setDescriptionC("Jacket");
        details.setDescriptionD("Куртка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("waì tào / dà yī ");
        details.setDescriptionB("外套/大衣");
        details.setDescriptionC("Coat ");
        details.setDescriptionD("Пальто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn wàitào");
        details.setDescriptionB("短外套");
        details.setDescriptionC("Short coat");
        details.setDescriptionD("Полупальто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí jiá kè");
        details.setDescriptionB("皮夹克");
        details.setDescriptionC("Leather jacket");
        details.setDescriptionD("Кожаная куртка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diāo pí dàyī");
        details.setDescriptionB("貂皮大衣");
        details.setDescriptionC("Mink coat");
        details.setDescriptionD(" Норковая шуба");
        detailsList.add(details);

    }
}
