package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C49 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("lǐng dài ");
        details.setDescriptionB("领带");
        details.setDescriptionC("Tie");
        details.setDescriptionD("Галстук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǐng jié ");
        details.setDescriptionB("领结");
        details.setDescriptionC(" Bow-tie ");
        details.setDescriptionD("Галстук-бабочка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chèn shān ");
        details.setDescriptionB("衬衫");
        details.setDescriptionC("Shirt");
        details.setDescriptionD("Рубашка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī zhuāng ");
        details.setDescriptionB("西装");
        details.setDescriptionC("Business suit");
        details.setDescriptionD("Костюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎn lǐ fú ");
        details.setDescriptionB("晚礼服");
        details.setDescriptionC(" Dinner suit ");
        details.setDescriptionD("Смокинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zhuāng shàng yī");
        details.setDescriptionB("西装上衣");
        details.setDescriptionC("Suit jacket");
        details.setDescriptionD("Пиджак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ jiǎ ");
        details.setDescriptionB("马甲");
        details.setDescriptionC("Waistcoat");
        details.setDescriptionD("Жилет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiū xián shàng yī ");
        details.setDescriptionB("休闲上衣");
        details.setDescriptionC("Blazer");
        details.setDescriptionD("Блейзер/Клубный  пиджак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kù zǐ");
        details.setDescriptionB("裤子");
        details.setDescriptionC("Trousers");
        details.setDescriptionD("Брюки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiù zǐ ");
        details.setDescriptionB("袖子");
        details.setDescriptionC("Sleeve");
        details.setDescriptionD("Рукав");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo lǐng máo yī");
        details.setDescriptionB("高领毛衣");
        details.setDescriptionC(" Roll neck sweater");
        details.setDescriptionD("Водолазка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo yī ");
        details.setDescriptionB("毛衣");
        details.setDescriptionC("Sweater");
        details.setDescriptionD("Свитер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi jīn máo yī ");
        details.setDescriptionB("开襟毛衣");
        details.setDescriptionC(" Cardigan ");
        details.setDescriptionD("Кардиган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tào tóu máo yī ");
        details.setDescriptionB("套头毛衣");
        details.setDescriptionC("Pullover ");
        details.setDescriptionD("Пуловер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú xiù máo yī ");
        details.setDescriptionB("无袖毛衣");
        details.setDescriptionC(" Sweater vest");
        details.setDescriptionD("Безрукавка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng mào");
        details.setDescriptionB("风帽");
        details.setDescriptionC("Hood");
        details.setDescriptionD("Капюшон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lā liàn ");
        details.setDescriptionB("拉链");
        details.setDescriptionC("Zipper");
        details.setDescriptionD("Застёжка-молния");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niǔ kòu ");
        details.setDescriptionB("钮扣");
        details.setDescriptionC("Button");
        details.setDescriptionD("Пуговица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yāo dài ");
        details.setDescriptionB("腰带");
        details.setDescriptionC("Belt");
        details.setDescriptionD("Ремень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yāo dài kòu  ");
        details.setDescriptionB("腰带扣");
        details.setDescriptionC("Buckle ");
        details.setDescriptionD("Пряжка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú zǎi kù");
        details.setDescriptionB("牛仔裤");
        details.setDescriptionC("Jeans");
        details.setDescriptionD("Джинсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng xiù ");
        details.setDescriptionB("长袖");
        details.setDescriptionC("Long sleeve");
        details.setDescriptionD("Лонгслив");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Polo shān ");
        details.setDescriptionB("Polo衫");
        details.setDescriptionC(" Polo shirt ");
        details.setDescriptionD("Рубашка поло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎng qiú shān ");
        details.setDescriptionB("网球衫");
        details.setDescriptionC(" Tennis shirt ");
        details.setDescriptionD("Тенниска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bèi xīn");
        details.setDescriptionB("背心");
        details.setDescriptionC("Vest");
        details.setDescriptionD("Майка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("T xù shān");
        details.setDescriptionB("T恤衫");
        details.setDescriptionC("T-shirt");
        details.setDescriptionD("Футболка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kù zi ");
        details.setDescriptionB("裤子");
        details.setDescriptionC("Pants");
        details.setDescriptionD("Штаны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn kù");
        details.setDescriptionB("短裤");
        details.setDescriptionC("Shorts");
        details.setDescriptionD("Шорты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎi mù dà duǎn kù ");
        details.setDescriptionB("百慕大短裤");
        details.setDescriptionC(" Bermuda shorts  ");
        details.setDescriptionD("Бермуды (шорты)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qī fèn kù ");
        details.setDescriptionB("七分裤");
        details.setDescriptionC("Breeches ");
        details.setDescriptionD("Бриджи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǔ fèn kù/ kǎ pǔ lǐ kù");
        details.setDescriptionB("九分裤/ 卡普里裤");
        details.setDescriptionC("Capri Pants");
        details.setDescriptionD("Капри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xié wén mián bù kù ");
        details.setDescriptionB("斜纹棉布裤");
        details.setDescriptionC("Chinos");
        details.setDescriptionD("Брюки-чинос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng zhuāng kù");
        details.setDescriptionB("工装裤");
        details.setDescriptionC(" Сargo pants ");
        details.setDescriptionD("Брюки-карго ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biàn kù ");
        details.setDescriptionB("便裤");
        details.setDescriptionC("Slacks");
        details.setDescriptionD("Слаксы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ kù ");
        details.setDescriptionB("马裤");
        details.setDescriptionC("Riding breeches");
        details.setDescriptionD("Галифе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng zhuāng lián yī kù ");
        details.setDescriptionB("工装连衣裤");
        details.setDescriptionC("Overalls");
        details.setDescriptionD("Комбинезон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá xuě shān");
        details.setDescriptionB("滑雪衫");
        details.setDescriptionC("Anorak");
        details.setDescriptionD("Анорак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi xíng yuán jiá kè ");
        details.setDescriptionB("飞行员夹克");
        details.setDescriptionC("Bomber jacket/ Flight jacket");
        details.setDescriptionD("Бомбер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bàng qiú jiá kè ");
        details.setDescriptionB("棒球夹克");
        details.setDescriptionC("Baseball jacket");
        details.setDescriptionD("Бейсбольная куртка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā kè");
        details.setDescriptionB("夹克");
        details.setDescriptionC("Jacket");
        details.setDescriptionD("Жакет/ Куртка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ róng mǎ jiǎ ");
        details.setDescriptionB("羽绒马甲");
        details.setDescriptionC(" Quilted vest ");
        details.setDescriptionD("Стёганый жилет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī chē jiá kè ");
        details.setDescriptionB("机车夹克");
        details.setDescriptionC("Biker jacket ");
        details.setDescriptionD("Косуха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng yī ");
        details.setDescriptionB("风衣");
        details.setDescriptionC("Dust coat");
        details.setDescriptionD("Пыльник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ yī");
        details.setDescriptionB("雨衣");
        details.setDescriptionC("Raincoat");
        details.setDescriptionD("Дождевик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhàn háo fēng yī ");
        details.setDescriptionB("战壕风衣");
        details.setDescriptionC(" Trench coat ");
        details.setDescriptionD("Тренч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi jūn ní duǎn dà yī ");
        details.setDescriptionB("海军呢短大衣");
        details.setDescriptionC(" Pea coat");
        details.setDescriptionD("Бушлат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú jiǎo kòu dà yī ");
        details.setDescriptionB("牛角扣大衣");
        details.setDescriptionC("Duffle coat");
        details.setDescriptionD("Дафлкот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wài tào ");
        details.setDescriptionB("外套");
        details.setDescriptionC("Coat");
        details.setDescriptionD("Пальто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duǎn wài tào");
        details.setDescriptionB("短外套");
        details.setDescriptionC("Short coat ");
        details.setDescriptionD("Полупальто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiē sī tè fēi ěr dé dà yī / xī zhuāng shì dà yī ");
        details.setDescriptionB("切斯特菲尔德大衣/西装式大衣");
        details.setDescriptionC("Chesterfield Coat");
        details.setDescriptionD("Пальто Честерфилд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fú lún qí shì shàng yī ");
        details.setDescriptionB("弗伦奇式上衣");
        details.setDescriptionC("French jacket");
        details.setDescriptionD("Френч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ róng fú ");
        details.setDescriptionB("羽绒服");
        details.setDescriptionC(" Padded coat ");
        details.setDescriptionD("Пуховик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("páng qiáo dǒu péng");
        details.setDescriptionB("庞乔斗篷");
        details.setDescriptionC("Poncho");
        details.setDescriptionD("Пончо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng pí dà yī ");
        details.setDescriptionB("羊皮大衣");
        details.setDescriptionC("Sheepskin coat");
        details.setDescriptionD("Дублёнка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pài kè dà yī ");
        details.setDescriptionB("派克大衣");
        details.setDescriptionC("Parka");
        details.setDescriptionD("Парка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn diāo pí yī ");
        details.setDescriptionB("短貂皮衣");
        details.setDescriptionC(" Short mint coat ");
        details.setDescriptionD("Норковый полушубок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diāo pí dàyī");
        details.setDescriptionB("貂皮大衣");
        details.setDescriptionC("Mink coat");
        details.setDescriptionD("Норковая шуба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng yī ");
        details.setDescriptionB("风衣");
        details.setDescriptionC("Windcheater");
        details.setDescriptionD("Ветровка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pī jiān ");
        details.setDescriptionB("披肩");
        details.setDescriptionC("Mantle");
        details.setDescriptionD("Накидка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qián shuǐ fú ");
        details.setDescriptionB("潜水服");
        details.setDescriptionC("Diving suit");
        details.setDescriptionD("Гидрокостюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèi yī ");
        details.setDescriptionB("卫衣");
        details.setDescriptionC("Tolstoy shirt ");
        details.setDescriptionD("Толстовка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jǐn shēn kù ");
        details.setDescriptionB("紧身裤");
        details.setDescriptionC("Tights");
        details.setDescriptionD("Тайтсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng zhuāng");
        details.setDescriptionB("运动装");
        details.setDescriptionC("Sports suit");
        details.setDescriptionD("Спортивный костюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn dòng jiá kè shān ");
        details.setDescriptionB("运动夹克衫");
        details.setDescriptionC(" Sports jacket ");
        details.setDescriptionD("Мастерка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng kù ");
        details.setDescriptionB("运动裤");
        details.setDescriptionC("Sweatpants");
        details.setDescriptionD("Спортивные штаны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng shān ");
        details.setDescriptionB("运动衫");
        details.setDescriptionC("Sweatshirt");
        details.setDescriptionD("Свитшот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lián mào shān");
        details.setDescriptionB("连帽衫");
        details.setDescriptionC("Hoodie");
        details.setDescriptionD("Худи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wū kè lán chuán tǒng mín zú fú zhuāng ");
        details.setDescriptionB("乌克兰传统民族服装");
        details.setDescriptionC("Vyshivanka");
        details.setDescriptionD("Вышиванка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dēng lóng kù ");
        details.setDescriptionB("灯笼裤");
        details.setDescriptionC("Wide trousers");
        details.setDescriptionD("Шаровары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo lǐng cháng wài tào ");
        details.setDescriptionB("高领长外套");
        details.setDescriptionC("Sherwani");
        details.setDescriptionD("Шервани");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guǒ qún ");
        details.setDescriptionB("裹裙");
        details.setDescriptionC("Dhoti");
        details.setDescriptionD("Дхоти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hán fú ");
        details.setDescriptionB("韩服");
        details.setDescriptionC("Hanbok");
        details.setDescriptionD("Ханбок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kù ěr tǎ zhǎng shān ");
        details.setDescriptionB("库尔塔长衫");
        details.setDescriptionC(" Kurta ");
        details.setDescriptionD("Курта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hàn fú ");
        details.setDescriptionB("汉服");
        details.setDescriptionC("Hanfu");
        details.setDescriptionD("Ханьфу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hé fú ");
        details.setDescriptionB("和服");
        details.setDescriptionC("Kimono");
        details.setDescriptionD("Кимоно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nèi kù ");
        details.setDescriptionB("内裤");
        details.setDescriptionC("Underpant");
        details.setDescriptionD("Трусы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǎo nuǎn nèi yī");
        details.setDescriptionB("保暖内衣");
        details.setDescriptionC("Thermal underwear");
        details.setDescriptionD("Термобельё");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuì yī");
        details.setDescriptionB("睡衣");
        details.setDescriptionC("Pyjamas  ");
        details.setDescriptionD("Пижама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chén yī ");
        details.setDescriptionB("晨衣");
        details.setDescriptionC("Dressing gown");
        details.setDescriptionD("Халат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ tōng lián tǐ yī ");
        details.setDescriptionB("卡通连体衣");
        details.setDescriptionC("Kigurumi");
        details.setDescriptionD("Кигуруми");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wà zi ");
        details.setDescriptionB("袜子");
        details.setDescriptionC("Socks");
        details.setDescriptionD("Носки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng wà");
        details.setDescriptionB("长袜");
        details.setDescriptionC("Knee socks");
        details.setDescriptionD(" Гольфы ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xū jīn ");
        details.setDescriptionB("虚襟");
        details.setDescriptionC("Shirt-front");
        details.setDescriptionD("Манишка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā shé mào ");
        details.setDescriptionB("鸭舌帽");
        details.setDescriptionC("Cap");
        details.setDescriptionD("Кепка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng mào ");
        details.setDescriptionB("运动帽");
        details.setDescriptionC(" Sports cap ");
        details.setDescriptionD("Бейсболка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mào zǐ");
        details.setDescriptionB("帽子");
        details.setDescriptionC("Hat");
        details.setDescriptionD("Шапка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi jīn");
        details.setDescriptionB("围巾");
        details.setDescriptionC("Scarf");
        details.setDescriptionD("Шарф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu tào ");
        details.setDescriptionB("手套");
        details.setDescriptionC("Gloves");
        details.setDescriptionD("Перчатки");
        detailsList.add(details);
    }
}
