package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C54 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("zhù chǎn shì");
        details.setDescriptionB("助产士");
        details.setDescriptionC("Midwife");
        details.setDescriptionD("Акушерка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Xīn shēng yīng ér");
        details.setDescriptionB("新生婴儿");
        details.setDescriptionC("Newborn baby");
        details.setDescriptionD("Новорожденный ребенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù yīng xiāng");
        details.setDescriptionB("育婴箱");
        details.setDescriptionC("Incubator");
        details.setDescriptionD("Инкубатор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhū shēng shí tǐ zhòng");
        details.setDescriptionB("出生时体重");
        details.setDescriptionC("Birth weight");
        details.setDescriptionD(" Вес при рождении");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér chèng");
        details.setDescriptionB("婴儿秤");
        details.setDescriptionC("Scales");
        details.setDescriptionD("Весы для новорожденных");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān tīng qì/jiān hù yí");
        details.setDescriptionB("监听器/监护仪");
        details.setDescriptionC("Monitor");
        details.setDescriptionD("Монитор (фетальный)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū yè");
        details.setDescriptionB("输液");
        details.setDescriptionC("Drip");
        details.setDescriptionD("Капать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎo guǎn");
        details.setDescriptionB("导管");
        details.setDescriptionC("Catheter");
        details.setDescriptionD("Катетер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chǎn qián");
        details.setDescriptionB("产钳");
        details.setDescriptionC("Forceps");
        details.setDescriptionD("Акушерские щипцы ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pōu fù chǎn ");
        details.setDescriptionB("剖腹产");
        details.setDescriptionC(" Cesarean section ");
        details.setDescriptionD("Кесарево сечение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tāi ér ");
        details.setDescriptionB("胎儿");
        details.setDescriptionC(" Fetus ");
        details.setDescriptionD("Плод");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēn fèn biāo qiān ");
        details.setDescriptionB("身份标签");
        details.setDescriptionC("Identity tag");
        details.setDescriptionD("Идентификационный браслет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǔ rǔ / wèi mǔ rǔ ");
        details.setDescriptionB("哺乳/喂母乳");
        details.setDescriptionC("Nursing/ Breast-feeding ");
        details.setDescriptionD("Кормление грудью");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǔ rǔ xiōng zhào");
        details.setDescriptionB("哺乳胸罩");
        details.setDescriptionC("Nursing bra");
        details.setDescriptionD("Бюстгальтер для кормления");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī nǎi qì");
        details.setDescriptionB("吸奶器");
        details.setDescriptionC("Breast pump");
        details.setDescriptionD("Молокоотсос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rǔ diàn");
        details.setDescriptionB("乳垫");
        details.setDescriptionC(" Nursing pads");
        details.setDescriptionD("Подушечки");
        detailsList.add(details);
    }
}
