package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C59 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("shù qín");
        details.setDescriptionB("竖琴");
        details.setDescriptionC("Harp");
        details.setDescriptionD("Арфа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu fēng qín");
        details.setDescriptionB("手风琴");
        details.setDescriptionC("Accordion");
        details.setDescriptionD("Аккордеон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ");
        details.setDescriptionB("鼓");
        details.setDescriptionC("Drum");
        details.setDescriptionD("Барабан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā lā láikǎ");
        details.setDescriptionB("巴拉莱卡");
        details.setDescriptionC("Balalaika");
        details.setDescriptionD("Балалайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā yáng ");
        details.setDescriptionB("巴扬");
        details.setDescriptionC("Bayan");
        details.setDescriptionD("Баян");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà gǔ");
        details.setDescriptionB("大鼓");
        details.setDescriptionC("Big drum");
        details.setDescriptionD("Большой барабан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān zhuō qín ");
        details.setDescriptionB("班卓琴");
        details.setDescriptionC("Banjo");
        details.setDescriptionD("Банджо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bāng gē gǔ");
        details.setDescriptionB("邦戈鼓");
        details.setDescriptionC("Bongos");
        details.setDescriptionD("Бонго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu gǔ");
        details.setDescriptionB("手鼓");
        details.setDescriptionC("Tambourine");
        details.setDescriptionD("Бубен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu yáo líng ");
        details.setDescriptionB("手摇铃");
        details.setDescriptionC(" Handbell ");
        details.setDescriptionD("Бубенцы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuán hào ");
        details.setDescriptionB("圆号");
        details.setDescriptionC(" French Horn ");
        details.setDescriptionD("Валторна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà tí qín");
        details.setDescriptionB("大提琴");
        details.setDescriptionC("Violoncello");
        details.setDescriptionD("Виолончель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng dí");
        details.setDescriptionB("风笛");
        details.setDescriptionC("Bagpipes");
        details.setDescriptionD("Волынка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí tā");
        details.setDescriptionB("吉他");
        details.setDescriptionC("Guitar");
        details.setDescriptionD("Гитара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng huáng guǎn");
        details.setDescriptionB("双簧管");
        details.setDescriptionC("Oboe");
        details.setDescriptionD("Гобой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luó");
        details.setDescriptionB("锣");
        details.setDescriptionC("Gong");
        details.setDescriptionD("Гонг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǒu qín ");
        details.setDescriptionB("口琴");
        details.setDescriptionC("Harmonica ");
        details.setDescriptionD("Губная гармоника");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ sī lǐ qín");
        details.setDescriptionB("古斯里琴");
        details.setDescriptionC("Gusli");
        details.setDescriptionD("Гусли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ zhēng");
        details.setDescriptionB("古筝");
        details.setDescriptionC("Chinese Zither");
        details.setDescriptionD("Гучжэн/Китайская цитра ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dí zi ");
        details.setDescriptionB("笛子");
        details.setDescriptionC("Flute");
        details.setDescriptionD("Дудка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān huáng guǎn/ hēi guǎn ");
        details.setDescriptionB("单簧管/黑管");
        details.setDescriptionC("Clarinet");
        details.setDescriptionD("Кларнет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ zǔ dí");
        details.setDescriptionB("卡祖笛");
        details.setDescriptionC("Kazoo");
        details.setDescriptionD("Казу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāng jiā gǔ");
        details.setDescriptionB("康加鼓");
        details.setDescriptionC("Conga");
        details.setDescriptionD("Конга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dī yīn tí qín");
        details.setDescriptionB("低音提琴");
        details.setDescriptionC("Double-bass");
        details.setDescriptionD("Контрабас");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù qín");
        details.setDescriptionB("木琴");
        details.setDescriptionC("Xylophone");
        details.setDescriptionD("Ксилофон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎng bǎn");
        details.setDescriptionB("响板");
        details.setDescriptionC("Castanets");
        details.setDescriptionD("Кастаньеты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā chuí/mǎ lā kǎ sī");
        details.setDescriptionB("砂槌/马拉卡斯");
        details.setDescriptionC("Maracas");
        details.setDescriptionD("Маракасы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng qín");
        details.setDescriptionB("风琴");
        details.setDescriptionC("Organ");
        details.setDescriptionD("Орган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāng qín");
        details.setDescriptionB("钢琴");
        details.setDescriptionC("Piano ");
        details.setDescriptionD("Пианино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí pá");
        details.setDescriptionB("琵琶");
        details.setDescriptionC("Lute");
        details.setDescriptionD("Лютня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sà kè sī guǎn ");
        details.setDescriptionB("萨克斯管");
        details.setDescriptionC(" Saxophone ");
        details.setDescriptionD("Саксофон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tí qín ");
        details.setDescriptionB("提琴");
        details.setDescriptionC(" Violin ");
        details.setDescriptionD("Скрипка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn zǐ qín ");
        details.setDescriptionB("电子琴");
        details.setDescriptionC(" Synthesizer ");
        details.setDescriptionD(" Синтезатор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bó/náo bó ");
        details.setDescriptionB("钹/铙钹");
        details.setDescriptionC("Сymbals");
        details.setDescriptionD("Тарелки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān jiǎo tiě");
        details.setDescriptionB("三角铁");
        details.setDescriptionC("Triangle");
        details.setDescriptionD("Треугольник（музыкальный）");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo hào/lǎ bā");
        details.setDescriptionB("小号/喇叭");
        details.setDescriptionC("Trumpet");
        details.setDescriptionD("Труба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng hào ");
        details.setDescriptionB("长号");
        details.setDescriptionC("Trombone ");
        details.setDescriptionD("Тромбон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà hào");
        details.setDescriptionB("大号");
        details.setDescriptionC("Tuba");
        details.setDescriptionD("Туба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jià zi gǔ");
        details.setDescriptionB("架子鼓");
        details.setDescriptionC("Drum kit/ Jazz Drum set ");
        details.setDescriptionD("Ударная установка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng dí");
        details.setDescriptionB("长笛");
        details.setDescriptionC("Flute");
        details.setDescriptionD("Флейта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gāng qín ");
        details.setDescriptionB("钢琴");
        details.setDescriptionC("Piano");
        details.setDescriptionD("Фортепиано/Рояль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn jí tā ");
        details.setDescriptionB("电吉他");
        details.setDescriptionC(" Electric guitar ");
        details.setDescriptionD("Электрогитара");
        detailsList.add(details);
    }
}
