package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C65 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("lán diào yīn yuè");
        details.setDescriptionB("蓝调音乐");
        details.setDescriptionC("Blues");
        details.setDescriptionD("Блюз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jué shì yuè");
        details.setDescriptionB("爵士乐");
        details.setDescriptionC("Jazz");
        details.setDescriptionD("Джаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ diǎn yīn yuè");
        details.setDescriptionB("古典音乐");
        details.setDescriptionC("Classical music");
        details.setDescriptionD("Классическая музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuè tuán/yuè duì");
        details.setDescriptionB("乐团/乐队");
        details.setDescriptionC("Orchestra");
        details.setDescriptionD("Оркестр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng cūn yīn yuè");
        details.setDescriptionB("乡村音乐");
        details.setDescriptionC("Country music");
        details.setDescriptionD("Музыка кантри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mín jiān yīn yuè");
        details.setDescriptionB("民间音乐");
        details.setDescriptionC("Folk music");
        details.setDescriptionD("Народная музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("péng kè yīn yuè ");
        details.setDescriptionB("朋克音乐");
        details.setDescriptionC("Punk");
        details.setDescriptionD("Панк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liú xíng yīn yuè");
        details.setDescriptionB("流行音乐");
        details.setDescriptionC("Pop music");
        details.setDescriptionD("Поп-музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("léi guǐ yīn yuè");
        details.setDescriptionB("雷鬼音乐");
        details.setDescriptionC("Reggae");
        details.setDescriptionD(" Регги /Рэгги ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuō chàng yīn yuè");
        details.setDescriptionB("说唱音乐");
        details.setDescriptionC("Rap");
        details.setDescriptionD("Рэп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáo gǔn yuè");
        details.setDescriptionB("摇滚乐");
        details.setDescriptionC("Rock music");
        details.setDescriptionD("Рок музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ qǔ");
        details.setDescriptionB("舞曲");
        details.setDescriptionC("Dance music");
        details.setDescriptionD("Танцевальная музыка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhòng jīn shǔ yīn yuè");
        details.setDescriptionB("重金属音乐");
        details.setDescriptionC("Heavy metal");
        details.setDescriptionD("Хеви-метал/ Тяжёлый рок металл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gē qǔ");
        details.setDescriptionB("歌曲");
        details.setDescriptionC("Song");
        details.setDescriptionD("Песня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qǔ diào");
        details.setDescriptionB("曲调");
        details.setDescriptionC("Melody");
        details.setDescriptionD("Мелодия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gē cí");
        details.setDescriptionB("歌词");
        details.setDescriptionC("Lyrics");
        details.setDescriptionD("Текст песни");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuè pǔ");
        details.setDescriptionB("乐谱");
        details.setDescriptionC(" Sheet music");
        details.setDescriptionD("Ноты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tīng yīn yuè");
        details.setDescriptionB("听音乐");
        details.setDescriptionC("Listen to music");
        details.setDescriptionD("Слушать музыку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chàng piàn qí shī ");
        details.setDescriptionB("DJ/唱片骑师");
        details.setDescriptionC("DJ/ Disc Jockey");
        details.setDescriptionD("Диджей");
        detailsList.add(details);
    }
}
