package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C78 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("chún cǎi");
        details.setDescriptionB("唇彩");
        details.setDescriptionC("Lip gloss");
        details.setDescriptionD("Блеск для губ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǒu hóng");
        details.setDescriptionB("口红");
        details.setDescriptionC("Lipstick");
        details.setDescriptionD("Помада");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāi hóng");
        details.setDescriptionB("腮红");
        details.setDescriptionC("Blush");
        details.setDescriptionD("Румяна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jié máo gāo");
        details.setDescriptionB("睫毛膏");
        details.setDescriptionC("Mascara");
        details.setDescriptionD("Тушь для ресниц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn yǐng");
        details.setDescriptionB("眼影");
        details.setDescriptionC("Eye shadow");
        details.setDescriptionD("Тени для век");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mián qiān");
        details.setDescriptionB("棉签");
        details.setDescriptionC(" Cotton swab ");
        details.setDescriptionD(" Ватные  палочки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǎn xiàn bǐ");
        details.setDescriptionB("眼线笔");
        details.setDescriptionC("Eyeliner");
        details.setDescriptionD("Подводка для глаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("méi bǐ");
        details.setDescriptionB("眉笔");
        details.setDescriptionC("Eyebrow pencil");
        details.setDescriptionD("Карандаш для бровей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sǎn fěn");
        details.setDescriptionB("散粉");
        details.setDescriptionC("Loose powder");
        details.setDescriptionD("Рассыпчатая пудра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fěn bǐng");
        details.setDescriptionB("粉饼");
        details.setDescriptionC("Pressed powder");
        details.setDescriptionD("Компактная пудра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà zhuāng jìng");
        details.setDescriptionB("化妆镜");
        details.setDescriptionC("Makeup mirror ");
        details.setDescriptionD("Зеркальце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fěn dǐ");
        details.setDescriptionB("粉底");
        details.setDescriptionC(" Foundation ");
        details.setDescriptionD("Тональный крем");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn shuāng");
        details.setDescriptionB("面霜");
        details.setDescriptionC(" Face cream ");
        details.setDescriptionD("Крем для лица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà zhuāng shuǐ");
        details.setDescriptionB("化妝水");
        details.setDescriptionC("Face tonic");
        details.setDescriptionD("Тоник для лица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xǐ miàn nǎi ");
        details.setDescriptionB("洗面奶");
        details.setDescriptionC(" Face cleanser ");
        details.setDescriptionD("Очищающее молочко для лица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hù shǒu shuāng ");
        details.setDescriptionB("护手霜");
        details.setDescriptionC(" Hand cream ");
        details.setDescriptionD("Крем для рук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rùn fū shuāng ");
        details.setDescriptionB("润肤霜");
        details.setDescriptionC(" Moisture lotion ");
        details.setDescriptionD("Увлажняющий лосьон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rùn fū lù");
        details.setDescriptionB("润肤露");
        details.setDescriptionC("Body lotion");
        details.setDescriptionD("Лосьон для тела");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó shā gāo");
        details.setDescriptionB("磨砂膏");
        details.setDescriptionC(" Scrub ");
        details.setDescriptionD(" Cкраб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shēn céng qīng jié ");
        details.setDescriptionB("深层清洁");
        details.setDescriptionC(" Deep cleaning ");
        details.setDescriptionD("Cредство для глубокой очистки кожи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ jia yóu");
        details.setDescriptionB("指甲油");
        details.setDescriptionC("Nail polish ");
        details.setDescriptionD("Лак для ногтей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn mó");
        details.setDescriptionB("面膜");
        details.setDescriptionC("Face mask");
        details.setDescriptionD(" Маска для лица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huà zhuāng bāo");
        details.setDescriptionB("化妆包");
        details.setDescriptionC(" Cosmetic bag ");
        details.setDescriptionD(" Косметичка");
        detailsList.add(details);
    }
}
