package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C79 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("hǎi");
        details.setDescriptionB("海");
        details.setDescriptionC("Sea");
        details.setDescriptionD("Море");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ jī ní");
        details.setDescriptionB("比基尼");
        details.setDescriptionC("Bikini");
        details.setDescriptionD("Бикини/Раздельный купальник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lián tǐ yǒng yī ");
        details.setDescriptionB("连体泳衣");
        details.setDescriptionC("One-piece swimsuit");
        details.setDescriptionD("Слитный купальник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yǒng yī ");
        details.setDescriptionB("游泳衣");
        details.setDescriptionC("Swimwear");
        details.setDescriptionD("Купальник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǒng kù ");
        details.setDescriptionB("泳裤");
        details.setDescriptionC("Swimming trunks");
        details.setDescriptionD("Плавки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yǒng mào ");
        details.setDescriptionB("游泳帽");
        details.setDescriptionC("Swimming cap ");
        details.setDescriptionD("Шапочка для плаванья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qián shuǐ jìng");
        details.setDescriptionB("潜水镜");
        details.setDescriptionC(" Diving goggles ");
        details.setDescriptionD("Очки для ныряния");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qián shuǐ miàn zhào");
        details.setDescriptionB("潜水面罩");
        details.setDescriptionC("Diving mask");
        details.setDescriptionD("Маска для дайвинга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qián shuǐ hū xī guǎn");
        details.setDescriptionB("潜水呼吸管");
        details.setDescriptionC("Snorkel ");
        details.setDescriptionD("Дыхательная трубка для подводного плавания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yǒng jiǎo pǔ ");
        details.setDescriptionB("游泳脚蹼");
        details.setDescriptionC(" Swim fins ");
        details.setDescriptionD("Плавательные ласты ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yǒng quān");
        details.setDescriptionB("游泳圈");
        details.setDescriptionC("Rubber ring ");
        details.setDescriptionD("Круг для плавания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bì quān");
        details.setDescriptionB("臂圈");
        details.setDescriptionC("Armbands");
        details.setDescriptionD(" Нарукавники для плавания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài yáng mào");
        details.setDescriptionB("太阳帽");
        details.setDescriptionC("Sun hat ");
        details.setDescriptionD("Шляпа от солнца ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng shài mào zi ");
        details.setDescriptionB("防晒帽子");
        details.setDescriptionC("Sun cap");
        details.setDescriptionD("Кепка от солнца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rén zì tuō ");
        details.setDescriptionB("人字拖");
        details.setDescriptionC("Flip-flops");
        details.setDescriptionD("Шлепанцы/Вьетнамки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mò jìng ");
        details.setDescriptionB("墨镜");
        details.setDescriptionC("Sunglasses");
        details.setDescriptionD("Cолнцезащитные очки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng shài rǔ yè ");
        details.setDescriptionB("防晒乳液");
        details.setDescriptionC("Sunscreen lotion");
        details.setDescriptionD("Cолнцезащитный лосьон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā tān jīn ");
        details.setDescriptionB("沙滩巾");
        details.setDescriptionC("Beach towel");
        details.setDescriptionD("Пляжное полотенце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("沙滩垫");
        details.setDescriptionB("shā tān diàn ");
        details.setDescriptionC("Beach mat");
        details.setDescriptionD("Пляжный коврик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā tān qiú ");
        details.setDescriptionB("沙滩球");
        details.setDescriptionC(" Beach ball  ");
        details.setDescriptionD("Пляжный мяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu yǒng diàn");
        details.setDescriptionB("游泳垫");
        details.setDescriptionC("Swimming mattress");
        details.setDescriptionD("Надувной матрас");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chōng làng bǎn ");
        details.setDescriptionB("冲浪板");
        details.setDescriptionC("Surfboard ");
        details.setDescriptionD(" Доска для сёрфинга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhōng làng zhě");
        details.setDescriptionB("冲浪者");
        details.setDescriptionC("Surfer");
        details.setDescriptionD(" Сёрфингист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō làng ");
        details.setDescriptionB("波浪");
        details.setDescriptionC("Waves");
        details.setDescriptionD(" Волны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ qiāng");
        details.setDescriptionB("水枪");
        details.setDescriptionC("Water pistol");
        details.setDescriptionD("Водный пистолет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā tān sǎn");
        details.setDescriptionB("沙滩伞");
        details.setDescriptionC("Beach umbrella");
        details.setDescriptionD("Пляжный зонт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi àn");
        details.setDescriptionB("海岸");
        details.setDescriptionC("Coast");
        details.setDescriptionD("Побережье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā zi ");
        details.setDescriptionB("沙子");
        details.setDescriptionC(" Sand ");
        details.setDescriptionD("Песок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā bǎo ");
        details.setDescriptionB("沙堡");
        details.setDescriptionC("Sand castle ");
        details.setDescriptionD("Песочный замок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhē yáng péng ");
        details.setDescriptionB("遮阳篷");
        details.setDescriptionC("Sunshade");
        details.setDescriptionD("Навес от солнца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("日光躺椅");
        details.setDescriptionB(" rì guāng tǎng yǐ ");
        details.setDescriptionC("Sun lounger /Beach chair");
        details.setDescriptionD("Шезлонг-лежак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ tóu ");
        details.setDescriptionB("码头");
        details.setDescriptionC("Quay/ Dock");
        details.setDescriptionD("Причал для лодок и кораблей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiào tái ");
        details.setDescriptionB("跳台");
        details.setDescriptionC("Pier for jumping");
        details.setDescriptionD("Пирс для прыжков");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huàn yī jiān ");
        details.setDescriptionB("换衣间");
        details.setDescriptionC("Changing cubicle");
        details.setDescriptionD("Кабинка для переодевания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wèi shēng jiān ");
        details.setDescriptionB("卫生间");
        details.setDescriptionC("Toilet/ WC");
        details.setDescriptionD("Туалет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín yù jiān");
        details.setDescriptionB("淋浴间");
        details.setDescriptionC("Shower stall");
        details.setDescriptionD("Душевая кабина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīn shuǐ qū");
        details.setDescriptionB("滨水区");
        details.setDescriptionC("Waterfront");
        details.setDescriptionD("Набережная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi tān");
        details.setDescriptionB("海滩");
        details.setDescriptionC("Beach");
        details.setDescriptionD("Пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā tān ");
        details.setDescriptionB("沙滩");
        details.setDescriptionC("Sandy beach");
        details.setDescriptionD("Песчаный пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái shā ");
        details.setDescriptionB("白沙");
        details.setDescriptionC("White sand");
        details.setDescriptionD(" Белый песок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi huǒ shān shā tān");
        details.setDescriptionB("黑火山沙滩");
        details.setDescriptionC("Black volcanic sand beach");
        details.setDescriptionD(" Пляж с вулканическим чёрным песком");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ruǎn shā");
        details.setDescriptionB("软沙");
        details.setDescriptionC("Soft/Silky sand");
        details.setDescriptionD(" Мягкий песок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luǎn shí tān");
        details.setDescriptionB("卵石滩");
        details.setDescriptionC("Pebble beach");
        details.setDescriptionD("Галечный пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě shēng hǎi tān ");
        details.setDescriptionB("野生海滩");
        details.setDescriptionC("Wild beach");
        details.setDescriptionD("Дикий пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī rén hǎi tān");
        details.setDescriptionB("私人海滩");
        details.setDescriptionC("Private beach");
        details.setDescriptionD("Частный пляж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēn shuǐ wān");
        details.setDescriptionB("深水湾");
        details.setDescriptionC("Deep water bay");
        details.setDescriptionD("Глубоководный залив/Бухта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng chè de shuǐ");
        details.setDescriptionB("清澈的水");
        details.setDescriptionC("Crystal clear water");
        details.setDescriptionD("Кристально чистая вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hún shuǐ");
        details.setDescriptionB("浑水");
        details.setDescriptionC("Muddy water ");
        details.setDescriptionD("Грязная вода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" làng huā ");
        details.setDescriptionB("浪花");
        details.setDescriptionC("White horses on the sea");
        details.setDescriptionD("Барашки на море");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yán shí hǎi àn ");
        details.setDescriptionB("岩石海岸");
        details.setDescriptionC(" Rocky coast");
        details.setDescriptionD("Скалистый берег");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiāo shí");
        details.setDescriptionB("礁石");
        details.setDescriptionC("Reef");
        details.setDescriptionD("Риф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi zǎo");
        details.setDescriptionB("海藻");
        details.setDescriptionC("Seaweed");
        details.setDescriptionD("Водоросли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shān hú");
        details.setDescriptionB("珊瑚");
        details.setDescriptionC(" Coral");
        details.setDescriptionD("Коралл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi ōu ");
        details.setDescriptionB("海鸥");
        details.setDescriptionC("Seagull");
        details.setDescriptionD("Чайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi guī ");
        details.setDescriptionB("海龟");
        details.setDescriptionC("Sea turtle");
        details.setDescriptionD("Морская черепаха");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  yáo yú ");
        details.setDescriptionB("鳐鱼");
        details.setDescriptionC("Ray");
        details.setDescriptionD("Скат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rè dài yú ");
        details.setDescriptionB("热带鱼");
        details.setDescriptionC("Tropical fish");
        details.setDescriptionD("Тропическая рыбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi xīng ");
        details.setDescriptionB("海星");
        details.setDescriptionC("Starfish");
        details.setDescriptionD("Морская звезда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi mǎ");
        details.setDescriptionB("海马");
        details.setDescriptionC("Sea horse");
        details.setDescriptionD("Морской конёк ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("海蜇");
        details.setDescriptionB("hǎi zhé ");
        details.setDescriptionC("Jellyfish");
        details.setDescriptionD("Медуза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fú qiǎn");
        details.setDescriptionB("浮潜");
        details.setDescriptionC("Snorkeling");
        details.setDescriptionD(" Сноркелинг/ Подводное плавание с дыхательной трубкой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huá xiáng yì");
        details.setDescriptionB("滑翔翼");
        details.setDescriptionC("Hang gliding");
        details.setDescriptionD(" Полёт на дельтаплане");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diào yú chuán");
        details.setDescriptionB("钓鱼船");
        details.setDescriptionC("Fishing boat ");
        details.setDescriptionD("Рыболовецкая лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì tǐng ");
        details.setDescriptionB("汽艇");
        details.setDescriptionC("Motorboat");
        details.setDescriptionD(" Моторная лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ qiāo");
        details.setDescriptionB("水橇");
        details.setDescriptionC(" Water ski ");
        details.setDescriptionD("Водные лыжи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ shàng mó tuō tǐng ");
        details.setDescriptionB("水上摩托艇");
        details.setDescriptionC("Wave runner/ Jet Ski");
        details.setDescriptionD(" Водный мотоцикл/ Гидроцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān chuán yùn dòng");
        details.setDescriptionB("帆船运动");
        details.setDescriptionC("Sailing");
        details.setDescriptionD("  Парусный спорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi shàng lǚ xíng ");
        details.setDescriptionB("海上旅行");
        details.setDescriptionC("Sea voyage/Sea trip");
        details.setDescriptionD(" Морская прогулка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ shā tān pái qiú");
        details.setDescriptionB("打沙滩排球");
        details.setDescriptionC("Play beach volleyball");
        details.setDescriptionD(" Играть в пляжный волейбол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zài hǎi lǐ yóu yǒng ");
        details.setDescriptionB("在海里游泳");
        details.setDescriptionC("Swim in the sea");
        details.setDescriptionD(" Плавать в море");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  tiào shuǐ ");
        details.setDescriptionB("跳水");
        details.setDescriptionC("Dive");
        details.setDescriptionD("Прыгать в воду/Нырять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cóng xuán yá shàng tiào xià lái ");
        details.setDescriptionB("从悬崖上跳下来");
        details.setDescriptionC("Jump from cliff ");
        details.setDescriptionD("Прыгать с утёса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàn zào shā bǎo ");
        details.setDescriptionB("建造沙堡");
        details.setDescriptionC(" Build sand castles ");
        details.setDescriptionD("Cтроить песочные замки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎn qǐ bèi ké ");
        details.setDescriptionB("捡起贝壳");
        details.setDescriptionC("Gather seashells ");
        details.setDescriptionD("Cобирать ракушки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zuò bèi ké xiàng liàn");
        details.setDescriptionB("做贝壳项链");
        details.setDescriptionC(" Make a shell necklace ");
        details.setDescriptionD("Cделать ожерелье из ракушек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎ yǔ máo qiú");
        details.setDescriptionB("打羽毛球");
        details.setDescriptionC(" Play badminton ");
        details.setDescriptionD("Играть в бадминтон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fàng fēng zhēng ");
        details.setDescriptionB("放风筝");
        details.setDescriptionC("Fly a kite ");
        details.setDescriptionD("Запускать воздушного змея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ pái");
        details.setDescriptionB("打牌");
        details.setDescriptionC("Play cards ");
        details.setDescriptionD("Играть в карты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zài shuǐ shàng lè yuán wán ");
        details.setDescriptionB("在水上乐园玩");
        details.setDescriptionC("Have fun in the water park");
        details.setDescriptionD("Веселиться в аквапарке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yán zhe hǎi tān sàn bù");
        details.setDescriptionB("沿着海滩散步");
        details.setDescriptionC("Walk along the beach  ");
        details.setDescriptionD("Прогуливаться вдоль пляжа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǐ xǐ huān qù hǎi tān ma ");
        details.setDescriptionB("你喜欢去海滩吗？");
        details.setDescriptionC("Do you like to go to the beach? ");
        details.setDescriptionD(" Вам нравится ходить на пляж?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔn xǔ chǒng wù rù nèi ");
        details.setDescriptionB("允许宠物入内");
        details.setDescriptionC("Are pets allowed?");
        details.setDescriptionD("Можно ли с животными?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ xiǎng zhǎo ān jìng de dì fāng ");
        details.setDescriptionB("我想找安静的地方");
        details.setDescriptionC("I would like to find some peaceful spot");
        details.setDescriptionD("Я бы хотел найти спокойное место");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ zěn me qù hǎi tān ");
        details.setDescriptionB("我怎么去海滩?");
        details.setDescriptionC("How can I get to the beach?");
        details.setDescriptionD("Как я могу добраться до пляжа?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhè lǐ de shēn dù shì duō shǎo ");
        details.setDescriptionB("这里的深度是多少");
        details.setDescriptionC("What is the depth of the water here?");
        details.setDescriptionD("Какая здесь глубина?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhè lǐ de shuǐ shēn hái shì qiǎn ");
        details.setDescriptionB("这里的水深还是浅?");
        details.setDescriptionC("Is the water here deep or shallow?");
        details.setDescriptionD("Здесь глубоко или мелко?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ de tuǐ chōu jīn ");
        details.setDescriptionB("我的腿抽筋");
        details.setDescriptionC("My leg is cramped");
        details.setDescriptionD(" Мою ногу свела судорога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shài tài yáng");
        details.setDescriptionB("晒太阳");
        details.setDescriptionC("Tan");
        details.setDescriptionD("Загорать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ bèi yán zhòng shài shāng");
        details.setDescriptionB("我被严重晒伤");
        details.setDescriptionC("I got a severe sunburn ");
        details.setDescriptionD("Я сильно обгорел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shí wù cān chē ");
        details.setDescriptionB("食物餐车");
        details.setDescriptionC("Food truck");
        details.setDescriptionD("Фудтрак/Автокафе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo chī tíng");
        details.setDescriptionB("小吃亭");
        details.setDescriptionC(" Snack kiosk ");
        details.setDescriptionD("Киоск со снеками");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zǒu zhe chī ");
        details.setDescriptionB("走着吃");
        details.setDescriptionC("Grab-and-go food");
        details.setDescriptionD("Еда на ходу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yú cān tīng ");
        details.setDescriptionB("鱼餐厅");
        details.setDescriptionC("Fish restaurant");
        details.setDescriptionD("Рыбный ресторан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zài hǎi biān de yī jiā cān tīng yòng cān ");
        details.setDescriptionB("在海边的一家餐厅用餐");
        details.setDescriptionC("Have lunch at an oceanside restaurant");
        details.setDescriptionD(" Пообедать в ресторане на берегу океана");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng liáng yǐn liào");
        details.setDescriptionB("清凉饮料");
        details.setDescriptionC("Cooler");
        details.setDescriptionD("Прохладительный напиток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng bàng");
        details.setDescriptionB("冰棒");
        details.setDescriptionC(" Ice lolly / Popsicle ");
        details.setDescriptionD(" Фруктовое мороженое на палочке");
        detailsList.add(details);
    }
}
