package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C82 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("xiāo pí");
        details.setDescriptionB("削皮");
        details.setDescriptionC("Peel");
        details.setDescriptionD("Чистить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiē piàn");
        details.setDescriptionB("切片");
        details.setDescriptionC("Slice");
        details.setDescriptionD("Резать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cā suì");
        details.setDescriptionB("擦碎");
        details.setDescriptionC("Grate/Rub");
        details.setDescriptionD("Тереть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dào");
        details.setDescriptionB("倒");
        details.setDescriptionC("Pour");
        details.setDescriptionD("Лить/Наливать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo bàn ");
        details.setDescriptionB("搅拌");
        details.setDescriptionC("Mix");
        details.setDescriptionD("Мешать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo dǎ ");
        details.setDescriptionB("搅打");
        details.setDescriptionC("Whisk");
        details.setDescriptionD("Взбивать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǔ");
        details.setDescriptionB("煮");
        details.setDescriptionC("Boil");
        details.setDescriptionD("Варить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chǎo ");
        details.setDescriptionB("炒");
        details.setDescriptionC("Fry");
        details.setDescriptionD("Жарить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhá/yóu zhá ");
        details.setDescriptionB("炸/油炸");
        details.setDescriptionC("Deep-fry");
        details.setDescriptionD("Жарить во фритюре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dùn/wēi ");
        details.setDescriptionB("炖/煨");
        details.setDescriptionC("Simmer");
        details.setDescriptionD("Тушить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǎn ");
        details.setDescriptionB("擀");
        details.setDescriptionC("Roll");
        details.setDescriptionD("Катать/Раскатывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo / jiǎo bàn ");
        details.setDescriptionB("搅/搅拌");
        details.setDescriptionC("Stir");
        details.setDescriptionD("Мешать/Помешивать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hōng kǎo ");
        details.setDescriptionB("烘烤");
        details.setDescriptionC("Bake");
        details.setDescriptionD("Испечь/Выпекать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo");
        details.setDescriptionB("烤");
        details.setDescriptionC("Roast");
        details.setDescriptionD("Жарить/Обжигать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shāo kǎo ");
        details.setDescriptionB("烧烤");
        details.setDescriptionC("Grill");
        details.setDescriptionD("Гриль/Жарить на гриле");
        detailsList.add(details);
    }
}
