package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C85 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("gōng niú");
        details.setDescriptionB("公牛");
        details.setDescriptionC("Bull");
        details.setDescriptionD("Бык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǎi niú");
        details.setDescriptionB("奶牛");
        details.setDescriptionC("Milk cow");
        details.setDescriptionD("Корова");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo niú ");
        details.setDescriptionB("小牛");
        details.setDescriptionC("Calf");
        details.setDescriptionD("Телёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ");
        details.setDescriptionB("zhōng guó shuǐ niú ");
        details.setDescriptionC("中国水牛");
        details.setDescriptionD("Chinese buffalo ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo niú");
        details.setDescriptionB("牦牛");
        details.setDescriptionC(" Yak ");
        details.setDescriptionD("Як");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà é niú");
        details.setDescriptionB("大额牛");
        details.setDescriptionC("Gayal");
        details.setDescriptionD("Гаял");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǎo wā yě niú ");
        details.setDescriptionB("爪哇野牛");
        details.setDescriptionC("Banteng");
        details.setDescriptionD("Бантенг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuó yáng  ");
        details.setDescriptionB("驼羊");
        details.setDescriptionC("Llama ");
        details.setDescriptionD("Лама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng tuó ");
        details.setDescriptionB("羊驼");
        details.setDescriptionC("Alpaca ");
        details.setDescriptionD("Альпака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ");
        details.setDescriptionB("马");
        details.setDescriptionC("Horse");
        details.setDescriptionD("Конь/Лошадь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ mǎ");
        details.setDescriptionB("母马");
        details.setDescriptionC("Mare");
        details.setDescriptionD("Кобыла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo mǎ");
        details.setDescriptionB("小马");
        details.setDescriptionC("Foal");
        details.setDescriptionD("Жеребёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ǎi zhǒng mǎ");
        details.setDescriptionB("矮种马");
        details.setDescriptionC("Pony");
        details.setDescriptionD("Пони");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǘ ");
        details.setDescriptionB("驴");
        details.setDescriptionC("Donkey");
        details.setDescriptionD("Осёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ luó");
        details.setDescriptionB("马骡");
        details.setDescriptionC("Mule");
        details.setDescriptionD("Мул");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shān yáng");
        details.setDescriptionB("山羊");
        details.setDescriptionC("Goat ");
        details.setDescriptionD("Козёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ shān yáng");
        details.setDescriptionB("母山羊");
        details.setDescriptionC("Mother Goat");
        details.setDescriptionD("Коза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo shān yáng ");
        details.setDescriptionB("小山羊");
        details.setDescriptionC(" Little goat ");
        details.setDescriptionD("Козочка/козлик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng yáng ");
        details.setDescriptionB("公羊");
        details.setDescriptionC("Ram");
        details.setDescriptionD("Баран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mián yáng ");
        details.setDescriptionB("绵羊");
        details.setDescriptionC("Sheep");
        details.setDescriptionD("Овца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo yáng");
        details.setDescriptionB("小羊");
        details.setDescriptionC("Lamb");
        details.setDescriptionD(" Ягнёнок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhū");
        details.setDescriptionB("猪");
        details.setDescriptionC("Pig");
        details.setDescriptionD("Свинья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo zhū");
        details.setDescriptionB("小猪");
        details.setDescriptionC("Piglet/piggy");
        details.setDescriptionD("Поросенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gē zi ");
        details.setDescriptionB("鸽子");
        details.setDescriptionC("Dove");
        details.setDescriptionD("Голубь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā zi");
        details.setDescriptionB("鸭子");
        details.setDescriptionC("Duck");
        details.setDescriptionD("Утка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo yā");
        details.setDescriptionB("小鸭");
        details.setDescriptionC("Duckling");
        details.setDescriptionD("Утёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn zhū jī");
        details.setDescriptionB("珍珠鸡");
        details.setDescriptionC("Guinea fowl");
        details.setDescriptionD("Цесарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhì jī ");
        details.setDescriptionB(" 雉鸡");
        details.setDescriptionC("Pheasant ");
        details.setDescriptionD("Фазан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xióng é ");
        details.setDescriptionB("雄鹅");
        details.setDescriptionC("Goose  (male)");
        details.setDescriptionD("Гусь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cí é ");
        details.setDescriptionB("雌鹅");
        details.setDescriptionC("Goose （Female）");
        details.setDescriptionD("Гусыня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" é miáo");
        details.setDescriptionB("鹅苗 ");
        details.setDescriptionC(" Gosling ");
        details.setDescriptionD("Гусёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ jī ");
        details.setDescriptionB("火鸡");
        details.setDescriptionC("Turkey");
        details.setDescriptionD("Индюк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huǒ jī ");
        details.setDescriptionB("火鸡");
        details.setDescriptionC("Turkey ");
        details.setDescriptionD("Индейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ jī miáo ");
        details.setDescriptionB("火鸡苗");
        details.setDescriptionC(" Turkey-poult ");
        details.setDescriptionD("Индюшонок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng jī ");
        details.setDescriptionB("公鸡");
        details.setDescriptionC(" Cock ");
        details.setDescriptionD("Петух");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǔ jī ");
        details.setDescriptionB("母鸡");
        details.setDescriptionC("Hen");
        details.setDescriptionD("Курица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo jī ");
        details.setDescriptionB("小鸡");
        details.setDescriptionC("Chick");
        details.setDescriptionD(" Цыплёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng wǔ ");
        details.setDescriptionB("鹦鹉");
        details.setDescriptionC("Parrot");
        details.setDescriptionD("Попугай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cāng  tóu yàn què");
        details.setDescriptionB("苍头燕雀");
        details.setDescriptionC("Chaffinch");
        details.setDescriptionD("Зяблик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn sī què ");
        details.setDescriptionB("金丝雀");
        details.setDescriptionC("Canary -bird");
        details.setDescriptionD("Канарейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("māo ");
        details.setDescriptionB("猫");
        details.setDescriptionC("Cat");
        details.setDescriptionD("Кот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo māo ");
        details.setDescriptionB("小猫");
        details.setDescriptionC(" Kitty ");
        details.setDescriptionD(" Котёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǒu ");
        details.setDescriptionB("狗");
        details.setDescriptionC("Dog");
        details.setDescriptionD("Собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo gǒu ");
        details.setDescriptionB("小狗");
        details.setDescriptionC("Puppy");
        details.setDescriptionD("Щенок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tù zǐ ");
        details.setDescriptionB("兔子");
        details.setDescriptionC("Rabbit");
        details.setDescriptionD("Кролик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo tù zǐ ");
        details.setDescriptionB("小兔子");
        details.setDescriptionC("Bunny");
        details.setDescriptionD("Крольчонок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сāng shǔ ");
        details.setDescriptionB("仓鼠");
        details.setDescriptionC(" Hamster");
        details.setDescriptionD("Хомяк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tún shǔ");
        details.setDescriptionB("豚鼠");
        details.setDescriptionC("Guinea Pig");
        details.setDescriptionD("Морская свинка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái shǔ ");
        details.setDescriptionB("白鼠");
        details.setDescriptionC("White rat");
        details.setDescriptionD("Белая крыса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diāo ");
        details.setDescriptionB("貂");
        details.setDescriptionC("Mink");
        details.setDescriptionD("Норка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhǒng wù diāo ");
        details.setDescriptionB("宠物貂");
        details.setDescriptionC(" Ferret ");
        details.setDescriptionD("Фретка/ Домашний хорек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cì wèi ");
        details.setDescriptionB("刺猬");
        details.setDescriptionC(" Hedgehog");
        details.setDescriptionD(" Ёж ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chǒng wù hú lí ");
        details.setDescriptionB("宠物狐狸");
        details.setDescriptionC(" Pet fox ");
        details.setDescriptionD("Домашняя лиса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn yú ");
        details.setDescriptionB("金鱼");
        details.setDescriptionC("Goldfish");
        details.setDescriptionD("Золотая рыбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cán");
        details.setDescriptionB("蚕");
        details.setDescriptionC("Silkworm");
        details.setDescriptionD("Шелкопряд  тутовый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng fēng luò tuó");
        details.setDescriptionB("双峰骆驼");
        details.setDescriptionC(" Bactrian camel ");
        details.setDescriptionD("Двугорбый верблюд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān fēng luò tuó ");
        details.setDescriptionB("单峰骆驼");
        details.setDescriptionC(" Arabian Camel (Dromedary) ");
        details.setDescriptionD("Одногорбый верблюд");
        detailsList.add(details);
    }
}
