package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C1 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("kè hù");
        details.setDescriptionB("客户");
        details.setDescriptionC("Client");
        details.setDescriptionD("Клиент");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhuāng kǒu");
        details.setDescriptionB("窗口");
        details.setDescriptionC("Window");
        details.setDescriptionD("Окно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guì tái");
        details.setDescriptionB("柜台");
        details.setDescriptionC("Counter");
        details.setDescriptionD("Стойка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhū nà chù ");
        details.setDescriptionB("出纳处");
        details.setDescriptionC("Cash desk");
        details.setDescriptionD("Касса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chū nà yuán");
        details.setDescriptionB("出纳员");
        details.setDescriptionC("Cashier");
        details.setDescriptionD("Кассир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín háng jīng lǐ");
        details.setDescriptionB("银行经理");
        details.setDescriptionC("Bank manager");
        details.setDescriptionD("Банковский менеджер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuài jì shī");
        details.setDescriptionB("会计师");
        details.setDescriptionC("Accountant");
        details.setDescriptionD("Бухгалтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jǐng wèi");
        details.setDescriptionB("警卫");
        details.setDescriptionC(" Security guard");
        details.setDescriptionD("Охранник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhuán dān");
        details.setDescriptionB("传单");
        details.setDescriptionC("Leaflets");
        details.setDescriptionD("Листовки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wài bì");
        details.setDescriptionB("外币");
        details.setDescriptionC("Foreign currency");
        details.setDescriptionD("Иностранная валюта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huì lǜ");
        details.setDescriptionB("汇率");
        details.setDescriptionC("Exchange rate");
        details.setDescriptionD("Курс обмена валют");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wài bì duì huàn chù ");
        details.setDescriptionB("外币兑换处");
        details.setDescriptionC("Exchange office");
        details.setDescriptionD("Обменный пункт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xìn yòng kǎ ");
        details.setDescriptionB("信用卡");
        details.setDescriptionC("Credit card");
        details.setDescriptionD("Кредитная карта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chǔ xù kǎ");
        details.setDescriptionB("储蓄卡");
        details.setDescriptionC("Debit card");
        details.setDescriptionD(" Дебетовая карта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhàng hào");
        details.setDescriptionB("帐号");
        details.setDescriptionC("Account number");
        details.setDescriptionD("Номер счета");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhī piào");
        details.setDescriptionB("支票");
        details.setDescriptionC("Check");
        details.setDescriptionD("Чек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn é");
        details.setDescriptionB("金额");
        details.setDescriptionC("Amount");
        details.setDescriptionD("Сумма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiān míng");
        details.setDescriptionB("签名");
        details.setDescriptionC("Signature");
        details.setDescriptionD("Подпись");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn jīn / qián");
        details.setDescriptionB(" 现金/钱");
        details.setDescriptionC("Cash/Money");
        details.setDescriptionD("Наличные/Деньги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǐ bì");
        details.setDescriptionB("纸币");
        details.setDescriptionC("Paper money");
        details.setDescriptionD("Бумажные деньги/Банкноты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yìng bì");
        details.setDescriptionB("硬币");
        details.setDescriptionC("Coins");
        details.setDescriptionD("Монеты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàn jīn cún kuǎn jī");
        details.setDescriptionB("现金存款机");
        details.setDescriptionC("Cash Deposit Machine");
        details.setDescriptionD("Депозитный автомат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì zhù fú wù zhōng duān");
        details.setDescriptionB("自助服务终端");
        details.setDescriptionC("Self-service terminal");
        details.setDescriptionD("Терминал самообслуживания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiàn jīn qǔ kuǎn jī");
        details.setDescriptionB("现金取款机");
        details.setDescriptionC("Cash machine");
        details.setDescriptionD("Банкомат ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì dòng qǔ kuǎn jī");
        details.setDescriptionB("自动取款机");
        details.setDescriptionC("ATM (Automated teller machine)");
        details.setDescriptionD("Банкомат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng mù");
        details.setDescriptionB("屏幕");
        details.setDescriptionC("Screen");
        details.setDescriptionD("Экран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" àn jiàn qū");
        details.setDescriptionB("按键区");
        details.setDescriptionC("Key pad");
        details.setDescriptionD("Клавиатура");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mì mǎ");
        details.setDescriptionB("密码");
        details.setDescriptionC("Pin code");
        details.setDescriptionD("Пин-код");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chā kǎ kǒu");
        details.setDescriptionB("插卡口");
        details.setDescriptionC("Card slot");
        details.setDescriptionD("Слот для карты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēi shì kǎ ");
        details.setDescriptionB("威士卡");
        details.setDescriptionC("Visa card");
        details.setDescriptionD("Карта Visa");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wàn shì dá ");
        details.setDescriptionB("万事达");
        details.setDescriptionC("MasterCard International");
        details.setDescriptionD("Карта MasterCard ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín lián");
        details.setDescriptionB("银联");
        details.setDescriptionC(" China UnionPay(CUP) ");
        details.setDescriptionD("Китайская платежная карта CUP");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn róng");
        details.setDescriptionB("金融");
        details.setDescriptionC("Finance");
        details.setDescriptionD("Финансы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhèng quàn jiāo yì suǒ");
        details.setDescriptionB("证券交易所");
        details.setDescriptionC("Stock exchange");
        details.setDescriptionD("Фондовая биржа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ piào jīng jì rén");
        details.setDescriptionB("股票经纪人");
        details.setDescriptionC("Stockbroker ");
        details.setDescriptionD("Биржевой брокер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóu zī gù wèn");
        details.setDescriptionB("投资顾问");
        details.setDescriptionC("Financial advisor");
        details.setDescriptionD("Финансовый консультант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhèng quàn");
        details.setDescriptionB("证券");
        details.setDescriptionC("Securities");
        details.setDescriptionD("Ценные бумаги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guó zhài ");
        details.setDescriptionB("国债");
        details.setDescriptionC("Government bond");
        details.setDescriptionD("Государственная облигация");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ fèn");
        details.setDescriptionB("股份");
        details.setDescriptionC("Shares");
        details.setDescriptionD("Акции");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ piào jià gé");
        details.setDescriptionB("股票价格");
        details.setDescriptionC("Share price");
        details.setDescriptionD("Цена акций");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ xí");
        details.setDescriptionB("股息");
        details.setDescriptionC("Dividends");
        details.setDescriptionD("Дивиденды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yōng jīn");
        details.setDescriptionB("佣金");
        details.setDescriptionC("Commission");
        details.setDescriptionD("Комиссия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuì");
        details.setDescriptionB("税");
        details.setDescriptionC("Tax");
        details.setDescriptionD("Налог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài kuǎn");
        details.setDescriptionB("贷款");
        details.setDescriptionC("Loan");
        details.setDescriptionD("Кредит");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chú xù");
        details.setDescriptionB("储蓄");
        details.setDescriptionC("Savings");
        details.setDescriptionD("Cбережения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chǔ xù zhàng hù");
        details.setDescriptionB("储蓄账户");
        details.setDescriptionC("Savings account");
        details.setDescriptionD("Сберегательный счет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huó qí cún kuǎn zhàng hù");
        details.setDescriptionB("活期存款账户");
        details.setDescriptionC("Current account");
        details.setDescriptionD("Текущий счет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cún rù xiàn jīn ");
        details.setDescriptionB("存入现金");
        details.setDescriptionC("Pay in");
        details.setDescriptionD("Вкладывать деньги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fù kuǎn");
        details.setDescriptionB("付款");
        details.setDescriptionC("Payment");
        details.setDescriptionD("Оплата");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qǔ kuǎn dān");
        details.setDescriptionB("取款单");
        details.setDescriptionC(" Transaction slip ");
        details.setDescriptionD("Чек банкомата");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tòu zhī");
        details.setDescriptionB("透支");
        details.setDescriptionC("Overdraft");
        details.setDescriptionD("Овердрафт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lì lǜ");
        details.setDescriptionB("利率");
        details.setDescriptionC("Interest rate");
        details.setDescriptionD("Процентная ставка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǐ yā dài kuǎn");
        details.setDescriptionB("抵押贷款");
        details.setDescriptionC(" Mortgage ");
        details.setDescriptionD(" Ипотечный кредит");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhuǎn zhàng zhī fù");
        details.setDescriptionB("转账支付");
        details.setDescriptionC("Bank payment");
        details.setDescriptionD("Банковский платеж ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín háng zhuǎn zhàng");
        details.setDescriptionB("银行转帐");
        details.setDescriptionC("Bank transfer");
        details.setDescriptionD(" Банковский перевод ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín háng shǒu xù fèi");
        details.setDescriptionB("银行手续费");
        details.setDescriptionC("Bank charge");
        details.setDescriptionD("Банковская комиссия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhōng jiè yín háng");
        details.setDescriptionB("中介银行");
        details.setDescriptionC("Intermediary Bank");
        details.setDescriptionD(" Банк-посредник");
        detailsList.add(details);
    }

}
