package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C11 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("马");
        details.setDescriptionB("mǎ");
        details.setDescriptionC("Horse");
        details.setDescriptionD("Лошадь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("野马");
        details.setDescriptionB("yě mǎ");
        details.setDescriptionC("Wild horse");
        details.setDescriptionD("Мустанг/ Дикая лошадь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("斑马");
        details.setDescriptionB("bān mǎ");
        details.setDescriptionC("Zebra");
        details.setDescriptionD("Зебра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大象");
        details.setDescriptionB("dà xiàng");
        details.setDescriptionC("Elephant");
        details.setDescriptionD("Слон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("犀牛");
        details.setDescriptionB("xī niú");
        details.setDescriptionC("Rhinoceros");
        details.setDescriptionD("Носорог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("牦牛");
        details.setDescriptionB("máo niú");
        details.setDescriptionC("Yak");
        details.setDescriptionD("Як");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("麝牛");
        details.setDescriptionB("shè niú");
        details.setDescriptionC("Musk ox");
        details.setDescriptionD("Овцебык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("野牛");
        details.setDescriptionB("yě niú");
        details.setDescriptionC("Bison");
        details.setDescriptionD("Бизон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("羚牛");
        details.setDescriptionB("líng niú");
        details.setDescriptionC("Takin");
        details.setDescriptionD("Такин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("河马");
        details.setDescriptionB("hé mǎ");
        details.setDescriptionC("Hippo");
        details.setDescriptionD("Гиппопотам/Бегемот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("非洲野猪");
        details.setDescriptionB("fēi zhōu yě zhū");
        details.setDescriptionC("African wild boar");
        details.setDescriptionD("Африканский кабан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鬣狗");
        details.setDescriptionB("liè gǒu");
        details.setDescriptionC("Hyena");
        details.setDescriptionD("Гиена");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("长颈鹿");
        details.setDescriptionB("сháng jǐng lù");
        details.setDescriptionC("Giraffe");
        details.setDescriptionD("Жираф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("驼鹿");
        details.setDescriptionB("tuó lù");
        details.setDescriptionC("Moose");
        details.setDescriptionD("Лось");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("羚羊");
        details.setDescriptionB("líng yáng");
        details.setDescriptionC("Antelope");
        details.setDescriptionD("Антилопа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("羚羊");
        details.setDescriptionB("líng yáng");
        details.setDescriptionC("Antelope");
        details.setDescriptionD("Антилопа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("瞪羚");
        details.setDescriptionB("dèng líng");
        details.setDescriptionC("Gazelle");
        details.setDescriptionD("Газель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狍子");
        details.setDescriptionB("páo zǐ");
        details.setDescriptionC("Roe deer");
        details.setDescriptionD("Косуля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鹿");
        details.setDescriptionB("lù");
        details.setDescriptionC("Deer");
        details.setDescriptionD("Олень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黄斑鹿");
        details.setDescriptionB("huáng bān lù");
        details.setDescriptionC("Fallow Deer");
        details.setDescriptionD("Лань");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("小鹿");
        details.setDescriptionB("xiǎo lù");
        details.setDescriptionC("Fallow Deer Fawn");
        details.setDescriptionD("Оленёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("岩羚羊");
        details.setDescriptionB("yán líng yáng");
        details.setDescriptionC("Chamois");
        details.setDescriptionD("Серна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("角马");
        details.setDescriptionB("jiǎo mǎ");
        details.setDescriptionC("Wildebeest");
        details.setDescriptionD("Гну");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("捻角山羊");
        details.setDescriptionB("niǎn jiǎo shān yáng");
        details.setDescriptionC("Markhor");
        details.setDescriptionD("Винторогий козёл/Мархур");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北山羊");
        details.setDescriptionB("běi shān yáng");
        details.setDescriptionC("Northern goat");
        details.setDescriptionD("Горный козёл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大角羊");
        details.setDescriptionB("dà jiǎo yáng");
        details.setDescriptionC("Mountain Sheep /Bighorn sheep");
        details.setDescriptionD("Горный баран/Толсторог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("羱羊");
        details.setDescriptionB("yuán yáng");
        details.setDescriptionC("Alpine ibex");
        details.setDescriptionD("Ибекс/Козерог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猴子");
        details.setDescriptionB("hóu zi");
        details.setDescriptionC("Monkey");
        details.setDescriptionD("Oбезьянa");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑猩猩");
        details.setDescriptionB("hēi xīng xīng");
        details.setDescriptionC("Сhimpanzee");
        details.setDescriptionD("Шимпанзе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大猩猩");
        details.setDescriptionB("dà xīng xīng");
        details.setDescriptionC("Gorilla");
        details.setDescriptionD("Горилла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("红猩猩");
        details.setDescriptionB("hóng xīng xīng");
        details.setDescriptionC("Orangutan");
        details.setDescriptionD("Орангутанг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狒狒");
        details.setDescriptionB("fèi fèi");
        details.setDescriptionC("Baboon");
        details.setDescriptionD("Бабуин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("长臂猿");
        details.setDescriptionB("сháng bì yuán");
        details.setDescriptionC("Gibbon");
        details.setDescriptionD("Гиббон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猕猴");
        details.setDescriptionB("mí hóu");
        details.setDescriptionC("Macaque");
        details.setDescriptionD("Макака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狨猴");
        details.setDescriptionB("róng hóu");
        details.setDescriptionC("Marmoset monkey/ Zaris");
        details.setDescriptionD("Мармозетка/Миниатюрная мартышка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("豺");
        details.setDescriptionB("chái");
        details.setDescriptionC("Jackal");
        details.setDescriptionD("Шакал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("美洲狮");
        details.setDescriptionB("měi zhōu shī");
        details.setDescriptionC("Puma /Cougar");
        details.setDescriptionD("Пума");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猎豹");
        details.setDescriptionB("liè bào");
        details.setDescriptionC("Сheetah");
        details.setDescriptionD("Гепард");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("美洲虎");
        details.setDescriptionB("měi zhōu hǔ");
        details.setDescriptionC("Jaguar");
        details.setDescriptionD("Ягуар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("豹子");
        details.setDescriptionB("bào zi");
        details.setDescriptionC("Leopard");
        details.setDescriptionD("Леопард");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("云豹");
        details.setDescriptionB("yún bào");
        details.setDescriptionC("Clouded Leopard");
        details.setDescriptionD("Дымчатый леопард");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑豹");
        details.setDescriptionB("hēi bào");
        details.setDescriptionC("Black Panther");
        details.setDescriptionD("Чёрная пантера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("薮猫");
        details.setDescriptionB("sǒu māo");
        details.setDescriptionC("Serval");
        details.setDescriptionD("Сервал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狮子");
        details.setDescriptionB("shī zi");
        details.setDescriptionC("Lion");
        details.setDescriptionD("Лев");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("母狮");
        details.setDescriptionB("mǔ shī");
        details.setDescriptionC("Lioness");
        details.setDescriptionD("Львица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("老虎");
        details.setDescriptionB("lǎo hǔ");
        details.setDescriptionC("Tiger");
        details.setDescriptionD("Тигр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狼");
        details.setDescriptionB("láng");
        details.setDescriptionC("Wolf");
        details.setDescriptionD("Волк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("郊狼");
        details.setDescriptionB("jiāo láng");
        details.setDescriptionC("Coyote");
        details.setDescriptionD("Койот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猞猁");
        details.setDescriptionB("shē lì");
        details.setDescriptionC("Lynx");
        details.setDescriptionD("Обыкновенная рысь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("加拿大猞猁");
        details.setDescriptionB("jiā ná dà shē lì");
        details.setDescriptionC("Canadian Lynx");
        details.setDescriptionD("Канадская рысь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狞猫");
        details.setDescriptionB("níng māo");
        details.setDescriptionC("Caracal сat");
        details.setDescriptionD("Каракал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狐狸");
        details.setDescriptionB("hú lí");
        details.setDescriptionC("Fox");
        details.setDescriptionD("Лиса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北极狐");
        details.setDescriptionB("běi jí hú");
        details.setDescriptionC("Arctic fox");
        details.setDescriptionD("Полярная лисица/Песец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北极熊");
        details.setDescriptionB("běi jí xióng");
        details.setDescriptionC("Polar bear");
        details.setDescriptionD("Полярный медведь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("驯鹿");
        details.setDescriptionB("xùn lù");
        details.setDescriptionC("Reindeer");
        details.setDescriptionD("Северный олень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("棕熊");
        details.setDescriptionB("zōng xióng");
        details.setDescriptionC("Brown bear");
        details.setDescriptionD("Бурый медведь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑熊");
        details.setDescriptionB("hēi xióng");
        details.setDescriptionC("Black bear");
        details.setDescriptionD("Чёрный медведь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("袋鼠");
        details.setDescriptionB("dài shǔ");
        details.setDescriptionC("Kangaroo");
        details.setDescriptionD("Кенгуру");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("驼羊");
        details.setDescriptionB("tuó yáng");
        details.setDescriptionC("Llama");
        details.setDescriptionD("Лама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("原驼");
        details.setDescriptionB("yuán tuó");
        details.setDescriptionC("Guanaco");
        details.setDescriptionD("Гуанако");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("骆马");
        details.setDescriptionB("luò mǎ");
        details.setDescriptionC("Vicuna");
        details.setDescriptionD("Викунья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("单峰骆驼");
        details.setDescriptionB("dān fēng luò tuó");
        details.setDescriptionC("Arabian Camel (Dromedary)");
        details.setDescriptionD("Одногорбый верблюд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("双峰骆驼");
        details.setDescriptionB("shuāng fēng luò tuó");
        details.setDescriptionC("Bactrian camel");
        details.setDescriptionD("Двугорбый верблюд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("熊猫");
        details.setDescriptionB("xióng māo");
        details.setDescriptionC("Panda");
        details.setDescriptionD("Панда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("树袋熊");
        details.setDescriptionB("shù dài xióng");
        details.setDescriptionC("Koala");
        details.setDescriptionD("Коала");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("小熊猫");
        details.setDescriptionB("xiǎo xióng māo");
        details.setDescriptionC("Red panda /Lesser panda");
        details.setDescriptionD("Красная панда/ Малая панда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("浣熊");
        details.setDescriptionB("huàn xióng");
        details.setDescriptionC("Raccoon");
        details.setDescriptionD("Енот-полоскун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("刺猬");
        details.setDescriptionB("cì wèi");
        details.setDescriptionC("Hedgehog");
        details.setDescriptionD("Еж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("野兔");
        details.setDescriptionB("yě tù");
        details.setDescriptionC("Hare");
        details.setDescriptionD("Заяц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("松鼠");
        details.setDescriptionB("sōng shǔ");
        details.setDescriptionC("Squirrel");
        details.setDescriptionD("Белка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("花栗鼠");
        details.setDescriptionB("huā lì shǔ");
        details.setDescriptionC("Сhipmunk");
        details.setDescriptionD("Бурундук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("仓鼠");
        details.setDescriptionB("сāng shǔ");
        details.setDescriptionC("Hamster");
        details.setDescriptionD("Хомяк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白鼠");
        details.setDescriptionB("bái shǔ");
        details.setDescriptionC("White rat");
        details.setDescriptionD("Белая крыса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蝙蝠");
        details.setDescriptionB("biān fú");
        details.setDescriptionC("Bat");
        details.setDescriptionD("Летучая мышь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("旅鼠");
        details.setDescriptionB("lǚ shǔ");
        details.setDescriptionC("Lemming");
        details.setDescriptionD("Копытный лемминг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("俄罗斯麝鼹");
        details.setDescriptionB("é luó sī shè yǎn");
        details.setDescriptionC("Russian desman");
        details.setDescriptionD("Выхухоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("麝鼠");
        details.setDescriptionB("shè shǔ");
        details.setDescriptionC("Muskrat");
        details.setDescriptionD("Ондатра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("海狸鼠");
        details.setDescriptionB("hǎi lí shǔ");
        details.setDescriptionC("Coypu");
        details.setDescriptionD("Нутрия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("河狸");
        details.setDescriptionB("hé lí");
        details.setDescriptionC("Eurasian beaver");
        details.setDescriptionD("Европейский бобр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("水獭");
        details.setDescriptionB("shuǐ tǎ");
        details.setDescriptionC("Eurasian River Otter");
        details.setDescriptionD("Выдра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鼹鼠");
        details.setDescriptionB("yǎn shǔ");
        details.setDescriptionC("Mole");
        details.setDescriptionD("Крот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("树懒");
        details.setDescriptionB("shù lǎn");
        details.setDescriptionC("Sloth");
        details.setDescriptionD("Ленивец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("狐獴");
        details.setDescriptionB("hú měng");
        details.setDescriptionC("Suricate");
        details.setDescriptionD("Сурикат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猫鼬");
        details.setDescriptionB("māo yòu");
        details.setDescriptionC("Мongoose");
        details.setDescriptionD("Мангуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("旱獭");
        details.setDescriptionB("hàn tǎ");
        details.setDescriptionC("Marmot");
        details.setDescriptionD("Сурок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鸭嘴兽");
        details.setDescriptionB("yā zuǐ shòu");
        details.setDescriptionC("Duck-billed Platypus");
        details.setDescriptionD("Утконос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("獾");
        details.setDescriptionB("huān");
        details.setDescriptionC("Badger");
        details.setDescriptionD("Барсук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("猪獾");
        details.setDescriptionB("Hog-badger");
        details.setDescriptionC("zhū huān");
        details.setDescriptionD("Теледу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("毛鼻袋熊");
        details.setDescriptionB("máo bí dài xióng");
        details.setDescriptionC("Wombat");
        details.setDescriptionD("Вомбат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("穿山甲");
        details.setDescriptionB("chuān shān jiǎ");
        details.setDescriptionC("Chinese Pangolin");
        details.setDescriptionD("Китайский ящер/панголин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蜜獾");
        details.setDescriptionB("mì huān");
        details.setDescriptionC("Honey badger");
        details.setDescriptionD("Медоед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("貂熊");
        details.setDescriptionB("diāo xióng");
        details.setDescriptionC("Wolverine");
        details.setDescriptionD("Росомаха");
        detailsList.add(details);

    }
}
