package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C12 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("hēi mài ");
        details.setDescriptionB("黑麦");
        details.setDescriptionC("Rye");
        details.setDescriptionD("Рожь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà mài ");
        details.setDescriptionB("大麦");
        details.setDescriptionC("Barley");
        details.setDescriptionD("Ячмень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo mài ");
        details.setDescriptionB("小麦");
        details.setDescriptionC(" Wheat ");
        details.setDescriptionD("Пшеница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiáo mài ");
        details.setDescriptionB("荞麦");
        details.setDescriptionC("Buckwheat");
        details.setDescriptionD("Гречиха/ гречка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yàn mài ");
        details.setDescriptionB("燕麦");
        details.setDescriptionC("Oats");
        details.setDescriptionD("Овёс ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yàn mài piàn ");
        details.setDescriptionB("燕麦片");
        details.setDescriptionC(" Oatmeal");
        details.setDescriptionD("Овсяные хлопья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà mǐ ");
        details.setDescriptionB("大米");
        details.setDescriptionC("Rice");
        details.setDescriptionD("Рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng mǐ ");
        details.setDescriptionB("长米");
        details.setDescriptionC("Long grain rice");
        details.setDescriptionD("Длиннозёрный рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuán mǐ ");
        details.setDescriptionB("圆米");
        details.setDescriptionC("Round grain rice");
        details.setDescriptionD("Круглозёрный рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīng mǐ ");
        details.setDescriptionB("精米");
        details.setDescriptionC("Polished rice ");
        details.setDescriptionD(" Полированный рис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cū mǐ ");
        details.setDescriptionB("粗米 ");
        details.setDescriptionC("Half polished rice ");
        details.setDescriptionD("Полуполированный рис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cāo mǐ ");
        details.setDescriptionB(" 糙米");
        details.setDescriptionC("  Brown rice ");
        details.setDescriptionD("Неочищенный рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yě mǐ ");
        details.setDescriptionB("野米");
        details.setDescriptionC("Wild rice");
        details.setDescriptionD("Дикий рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái mǐ ");
        details.setDescriptionB("白米");
        details.setDescriptionC("White rice");
        details.setDescriptionD("Белый рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng mǐ");
        details.setDescriptionB("红米");
        details.setDescriptionC("Red rice");
        details.setDescriptionD("Красный рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi mǐ");
        details.setDescriptionB("黑米");
        details.setDescriptionC("Black rice");
        details.setDescriptionD("Чёрный рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ mǐ ");
        details.setDescriptionB("紫米");
        details.setDescriptionC(" Purple rice ");
        details.setDescriptionD(" Фиолетовый рис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nuò mǐ");
        details.setDescriptionB("糯米");
        details.setDescriptionC(" Glutinous rice ");
        details.setDescriptionD(" Клейкий рис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo mǐ ");
        details.setDescriptionB("小米");
        details.setDescriptionC("Millet");
        details.setDescriptionD("Просо/пшено");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì rén ");
        details.setDescriptionB("薏仁");
        details.setDescriptionC("Coix seed ");
        details.setDescriptionD(" Зёрна коикса/ бусенник  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lí mài/kuí nú yà lí ");
        details.setDescriptionB("藜麦/奎奴亚藜");
        details.setDescriptionC("Quinoa");
        details.setDescriptionD("Киноа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù mǐ ");
        details.setDescriptionB("玉米");
        details.setDescriptionC("Corn");
        details.setDescriptionD("Кукуруза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī mǐ /shā gǔ mǐ ");
        details.setDescriptionB("西米/沙谷米");
        details.setDescriptionC("Sago");
        details.setDescriptionD("Саго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo liáng ");
        details.setDescriptionB("高粱");
        details.setDescriptionC(" Sorghum ");
        details.setDescriptionD("Сорго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi ");
        details.setDescriptionB("咖啡");
        details.setDescriptionC("Сoffee ");
        details.setDescriptionD("Кофе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kě kě ");
        details.setDescriptionB("可可");
        details.setDescriptionC("Cocoa");
        details.setDescriptionD("Какао");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cū lì xiǎo mài fěn");
        details.setDescriptionB("粗粒小麦粉");
        details.setDescriptionC("Semolina");
        details.setDescriptionD("Манная крупа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēng cū mài fěn ");
        details.setDescriptionB("蒸粗麦粉");
        details.setDescriptionC("Couscous");
        details.setDescriptionD("Кускус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mài fū ");
        details.setDescriptionB("麦麸");
        details.setDescriptionC("Bran");
        details.setDescriptionD("Отруби");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" suì lì xiǎo mài ");
        details.setDescriptionB("碎粒小麦");
        details.setDescriptionC("Cracked wheat");
        details.setDescriptionD("Пшеничная крупа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wān dòu ");
        details.setDescriptionB("豌豆");
        details.setDescriptionC("Garden pea");
        details.setDescriptionD("Горох");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòu ");
        details.setDescriptionB("豆");
        details.setDescriptionC("Bean");
        details.setDescriptionD("Фасоль/ Боб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng dòu ");
        details.setDescriptionB("黄豆");
        details.setDescriptionC("Soya beans");
        details.setDescriptionD("Соя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng dòu ");
        details.setDescriptionB("青豆");
        details.setDescriptionC("Green pea");
        details.setDescriptionD(" Зелёный горошек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mián dòu");
        details.setDescriptionB("棉豆");
        details.setDescriptionC(" Lima bean/ butter bean");
        details.setDescriptionD("Лимская фасоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng zuǐ dòu");
        details.setDescriptionB("鹰嘴豆");
        details.setDescriptionC("Chickpeas");
        details.setDescriptionD("Нут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái yún dòu ");
        details.setDescriptionB("白芸豆");
        details.setDescriptionC(" White kidney beans ");
        details.setDescriptionD("Белая фасоль чали");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo lì cài dòu ");
        details.setDescriptionB("小粒菜豆");
        details.setDescriptionC("Flageolet beans");
        details.setDescriptionD("Фасоль флажоле");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chì xiǎo dòu ");
        details.setDescriptionB("赤小豆");
        details.setDescriptionC("Aduki beans ");
        details.setDescriptionD("Бобы адзуки ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi dòu");
        details.setDescriptionB("黑豆");
        details.setDescriptionC("Black beans");
        details.setDescriptionD("Чёрная фасоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ dòu ");
        details.setDescriptionB("绿豆");
        details.setDescriptionC("Mung beans");
        details.setDescriptionD("Маш/ бобы мунг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi xiǎo dòu");
        details.setDescriptionB("黑小豆");
        details.setDescriptionC("Black gram");
        details.setDescriptionD("Чёрный маш/ Урд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng sè xiǎo biǎn dòu ");
        details.setDescriptionB("红色小扁豆");
        details.setDescriptionC("Red lentils");
        details.setDescriptionD("Красная чечевица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zōng sè xiǎo biǎn dòu ");
        details.setDescriptionB("棕色小扁豆");
        details.setDescriptionC("Brown lentils");
        details.setDescriptionD("Коричневая чечевица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng sè xiǎo biǎn dòu ");
        details.setDescriptionB("黄色小扁豆");
        details.setDescriptionC(" Yellow lentils ");
        details.setDescriptionD("Жёлтая чечевица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ sè xiǎo biǎn dòu");
        details.setDescriptionB("绿色小扁豆");
        details.setDescriptionC(" Green lentils ");
        details.setDescriptionD("Зелёная чечевица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi sè xiǎo biǎn dòu ");
        details.setDescriptionB("黑色小扁豆");
        details.setDescriptionC("Black lentils ");
        details.setDescriptionD("Чёрная чечевица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cài dòu ");
        details.setDescriptionB("菜豆 ");
        details.setDescriptionC("Navy beans ");
        details.setDescriptionD("Фасоль нэви ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cán dòu ");
        details.setDescriptionB("蚕豆");
        details.setDescriptionC(" Broad beans");
        details.setDescriptionD("Конские бобы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng yún dòu ");
        details.setDescriptionB("红芸豆");
        details.setDescriptionC("Red kidney beans");
        details.setDescriptionD("Фасоль кидни");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān dòu ");
        details.setDescriptionB("斑豆");
        details.setDescriptionC("Pinto beans");
        details.setDescriptionD("Пинто /пёстрая фасоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi yǎn dòu/ mǐ dòu ");
        details.setDescriptionB("黑眼豆/米豆");
        details.setDescriptionC("Black-eyed beans");
        details.setDescriptionD("Фасоль чёрный глаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ā nà sà qí dòu ");
        details.setDescriptionB("阿纳萨齐豆");
        details.setDescriptionC("Anasazi beans");
        details.setDescriptionD("Фасоль анасази");
        detailsList.add(details);
        

    }
}
