package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C15 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("日出");
        details.setDescriptionB("dōng tiān");
        details.setDescriptionC("Sunrise");
        details.setDescriptionD("Восход солнца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("日落");
        details.setDescriptionB("rì luò");
        details.setDescriptionC("Sunset");
        details.setDescriptionD("Закат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("火山");
        details.setDescriptionB("huǒ shān");
        details.setDescriptionC("Volcano");
        details.setDescriptionD("Вулкан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("瀑布");
        details.setDescriptionB("pù  bù");
        details.setDescriptionC("Waterfall");
        details.setDescriptionD("Водопад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("冰雹");
        details.setDescriptionB("bīng báo");
        details.setDescriptionC("Hail");
        details.setDescriptionD("Град");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大雨");
        details.setDescriptionB("dà yǔ");
        details.setDescriptionC("Downpour");
        details.setDescriptionD("Ливень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("彩虹");
        details.setDescriptionB("cǎi hóng");
        details.setDescriptionC("Rainbow");
        details.setDescriptionD("Радуга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("月亮");
        details.setDescriptionB("yuè liàng");
        details.setDescriptionC("Moon");
        details.setDescriptionD("Луна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("落叶");
        details.setDescriptionB("luò yè");
        details.setDescriptionC("Leaf fall");
        details.setDescriptionD("Листопад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("暴风雪");
        details.setDescriptionB("bào fēng xuě");
        details.setDescriptionC("Snowstorm");
        details.setDescriptionD("Метель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("月光");
        details.setDescriptionB("yuè guāng");
        details.setDescriptionC("Moonlight");
        details.setDescriptionD("Лунная дорожка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("闪电");
        details.setDescriptionB("shǎn diàn");
        details.setDescriptionC("Lightning");
        details.setDescriptionD("Молния");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("雷电");
        details.setDescriptionB("léi diàn");
        details.setDescriptionC("Thunder and Lightning");
        details.setDescriptionD("Гром и молния");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("大海");
        details.setDescriptionB("dà hǎi");
        details.setDescriptionC("Sea");
        details.setDescriptionD("Море");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("岛");
        details.setDescriptionB("dǎo");
        details.setDescriptionC("Island");
        details.setDescriptionD("Остров");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("湖");
        details.setDescriptionB("hú");
        details.setDescriptionC("Lake");
        details.setDescriptionD("Озеро");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("北极光");
        details.setDescriptionB("běi jí guāng");
        details.setDescriptionC("Northern lights");
        details.setDescriptionD("Северное сияние");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("日蚀/日环食");
        details.setDescriptionB("rì shí /rì huán shí");
        details.setDescriptionC("Solar eclipse");
        details.setDescriptionD("Солнечное затмение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("露珠");
        details.setDescriptionB("lù zhū");
        details.setDescriptionC("Dew");
        details.setDescriptionD("Роса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("江/ 河");
        details.setDescriptionB("jiāng /hé");
        details.setDescriptionC("River");
        details.setDescriptionD("Река");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("太阳");
        details.setDescriptionB("tài yáng");
        details.setDescriptionC("Sun");
        details.setDescriptionD("Солнце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("阳光");
        details.setDescriptionB("yáng guāng");
        details.setDescriptionC("Sunshine");
        details.setDescriptionD("Солнечный свет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("冰柱");
        details.setDescriptionB("bīng zhù");
        details.setDescriptionC("Icicles");
        details.setDescriptionD("Сосульки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("结冰");
        details.setDescriptionB("jié bīng");
        details.setDescriptionC("Freeze");
        details.setDescriptionD("Замерзать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("季风");
        details.setDescriptionB("jì fēng");
        details.setDescriptionC("Monsoon");
        details.setDescriptionD("Муссон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("龙卷风");
        details.setDescriptionB("lóng juàn fēng");
        details.setDescriptionC("Tornado");
        details.setDescriptionD("Торнадо/ Смерч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("飓风");
        details.setDescriptionB("jù fēng");
        details.setDescriptionC("Hurricane");
        details.setDescriptionD("Ураган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("暴风雨");
        details.setDescriptionB("bào fēng yǔ");
        details.setDescriptionC("Storm");
        details.setDescriptionD("Шторм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("海啸");
        details.setDescriptionB("hǎi xiào");
        details.setDescriptionC("Tsunami");
        details.setDescriptionD("Цунами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("洪水");
        details.setDescriptionB("hóng shuǐ");
        details.setDescriptionC("Flood");
        details.setDescriptionD("Наводнение");
        detailsList.add(details);

    }
}
