package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C25 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("bái tóu yìng wěi yā");
        details.setDescriptionB("白头硬尾鸭");
        details.setDescriptionC("White-headed duck");
        details.setDescriptionD("Белоголовая савка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái yǎn qián yā ");
        details.setDescriptionB("白眼潜鸭");
        details.setDescriptionC(" White-eyed Pochard /Ferruginous duck");
        details.setDescriptionD("Белоглазый нырок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pǔ tōng qiū shā yā ");
        details.setDescriptionB("普通秋沙鸭");
        details.setDescriptionC(" Common merganser /Goosander");
        details.setDescriptionD("Большой крохаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dòu yàn ");
        details.setDescriptionB("豆雁");
        details.setDescriptionC("Bean goose");
        details.setDescriptionD(" Гусь-гуменник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng tóu qián yā ");
        details.setDescriptionB("红头潜鸭");
        details.setDescriptionC(" Common Pochard /Pochard");
        details.setDescriptionD("Красноголовый нырок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("赤嘴潜鸭");
        details.setDescriptionB(" chì zuǐ qián yā ");
        details.setDescriptionC("Red-crested pochard");
        details.setDescriptionD("Красноносый нырок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ tóu yā ");
        details.setDescriptionB("绿头鸭");
        details.setDescriptionC("Mallard");
        details.setDescriptionD("Кряква");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào zhōu huī yàn ");
        details.setDescriptionB("澳洲灰雁");
        details.setDescriptionC("  Cape Barren Goose ");
        details.setDescriptionD("Куриный гусь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà tiān é ");
        details.setDescriptionB("大天鹅");
        details.setDescriptionC("Whooper Swan");
        details.setDescriptionD("Лебедь-кликун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu bí tiān é ");
        details.setDescriptionB("疣鼻天鹅");
        details.setDescriptionC("Mute swan");
        details.setDescriptionD("Лебедь-шипун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi zuǐ tiān é ");
        details.setDescriptionB("黑嘴天鹅");
        details.setDescriptionC(" Trumpeter Swan  ");
        details.setDescriptionD("Лебедь-трубач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi tiān é");
        details.setDescriptionB("黑天鹅");
        details.setDescriptionC("Black swan ");
        details.setDescriptionD("Чёрный лебедь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi jǐng tiān é ");
        details.setDescriptionB(" 黑颈天鹅");
        details.setDescriptionC(" Black-necked Swan ");
        details.setDescriptionD("Черношейный лебедь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo tiān'é/táiyuán tiān é ");
        details.setDescriptionB("小天鹅/苔原天鹅");
        details.setDescriptionC(" Tundra swan");
        details.setDescriptionD("Американский лебедь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuān yāng ");
        details.setDescriptionB("鸳鸯");
        details.setDescriptionC(" Mandarin duck ");
        details.setDescriptionD("Утка мандаринка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng wěi yā ");
        details.setDescriptionB("长尾鸭 ");
        details.setDescriptionC("Long-tailed duck");
        details.setDescriptionD(" Морянка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu bí qī yā ");
        details.setDescriptionB("疣鼻栖鸭 ");
        details.setDescriptionC("Muscovy Duck ");
        details.setDescriptionD("Мускусная утка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu róng yā ");
        details.setDescriptionB(" 欧绒鸭");
        details.setDescriptionC("Eider/ Common Eider ");
        details.setDescriptionD(" Обыкновенная гага");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" què yā ");
        details.setDescriptionB("鹊鸭");
        details.setDescriptionC("Goldeneye");
        details.setDescriptionD(" Обыкновенный гоголь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiào bí má yā ");
        details.setDescriptionB("翘鼻麻鸭");
        details.setDescriptionC("Shelduck");
        details.setDescriptionD("Пеганка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chì jǐng yā ");
        details.setDescriptionB("赤颈鸭");
        details.setDescriptionC("Wigeon/ Eurasian Wigeon ");
        details.setDescriptionD("Свиязь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chì bǎng yā ");
        details.setDescriptionB("赤膀鸭");
        details.setDescriptionC("Gadwall");
        details.setDescriptionD("Серая утка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huī yàn ");
        details.setDescriptionB("灰雁");
        details.setDescriptionC("Greylag goose");
        details.setDescriptionD("Серый гусь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi fān yā ");
        details.setDescriptionB("海番鸭");
        details.setDescriptionC(" Common scoter ");
        details.setDescriptionD("Синьга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fèng tóu qián yā ");
        details.setDescriptionB("凤头潜鸭");
        details.setDescriptionC("Tufted duck");
        details.setDescriptionD("Хохлатая чернеть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ chì yā ");
        details.setDescriptionB("绿翅鸭 ");
        details.setDescriptionC("Eurasian Teal ");
        details.setDescriptionD("Чирок-свистунок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái méi yā ");
        details.setDescriptionB("白眉鸭");
        details.setDescriptionC("Garganey ");
        details.setDescriptionD("Чирок-трескунок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhēn wěi yā ");
        details.setDescriptionB("针尾鸭");
        details.setDescriptionC("Pintail / Northern Pintail ");
        details.setDescriptionD(" Шилохвость");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pí zuǐ yā ");
        details.setDescriptionB("琵嘴鸭");
        details.setDescriptionC("Shoveler ");
        details.setDescriptionD(" Широконоска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng huá qiū shā yā ");
        details.setDescriptionB("中华秋沙鸭 ");
        details.setDescriptionC("Chinese Merganser / Scaly-sided Merganser  ");
        details.setDescriptionD("Чешуйчатый крохаль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hè qiū shā yā ");
        details.setDescriptionB("褐秋沙鸭");
        details.setDescriptionC(" Brazilian Merganser ");
        details.setDescriptionD("Бразильский крохаль");
        detailsList.add(details);
        

    }
}
