package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C29 {

    public List<Details> detailsList = new ArrayList<>();

    {

        Details details = new Details();
        details.setDescriptionA("nǐ hǎo");
        details.setDescriptionB("你好！");
        details.setDescriptionC("Hello!");
        details.setDescriptionD("Привет!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nín hǎo");
        details.setDescriptionB("您好!");
        details.setDescriptionC("Hello!");
        details.setDescriptionD("Здравствуйте!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǎo shàng hǎo");
        details.setDescriptionB("早上好!");
        details.setDescriptionC("Good morning!");
        details.setDescriptionD("Доброе утро!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xià wǔ hǎo ");
        details.setDescriptionB("下午好!");
        details.setDescriptionC("Good afternoon!");
        details.setDescriptionD("Добрый день!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎn shàng hǎo");
        details.setDescriptionB("晚上好!");
        details.setDescriptionC("Good evening!");
        details.setDescriptionD("Добрый вечер! ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǎn ān ");
        details.setDescriptionB("晚安!");
        details.setDescriptionC("Good night!");
        details.setDescriptionD("Спокойной ночи!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎo jiǔ bú jiàn ");
        details.setDescriptionB("好久不见!");
        details.setDescriptionC("Long time no see you!");
        details.setDescriptionD("Давно не виделись!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǐ hǎo ma/ nǐ zěn me yàng ");
        details.setDescriptionB("你好吗?/ 你怎么样？");
        details.setDescriptionC(" How are you?");
        details.setDescriptionD("Как дела?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ hěn hǎo! ");
        details.setDescriptionB("我很好！ ");
        details.setDescriptionC("I am fine!");
        details.setDescriptionD("У меня все прекрасно!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiè xiè");
        details.setDescriptionB("谢谢");
        details.setDescriptionC("Thank you");
        details.setDescriptionD("Спасибо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù kè qì!");
        details.setDescriptionB("不客气!");
        details.setDescriptionC("You are welcome!");
        details.setDescriptionD("Пожалуйста!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎo ");
        details.setDescriptionB("好");
        details.setDescriptionC("Good");
        details.setDescriptionD("Хорошо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù hǎo ");
        details.setDescriptionB("不好");
        details.setDescriptionC("Bad/Not so good");
        details.setDescriptionD("Плохо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huān yíng");
        details.setDescriptionB("欢迎!");
        details.setDescriptionC("Welcome!");
        details.setDescriptionD("Добро пожаловать!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǐ jiào shén me míng zì ");
        details.setDescriptionB("你叫什么名字?");
        details.setDescriptionC("What’s your name?");
        details.setDescriptionD("Как вас зовут?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ jiào");
        details.setDescriptionB("我叫...");
        details.setDescriptionC("My name is…");
        details.setDescriptionD("Меня зовут...");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hěn gāo xìng  jiàn dào nǐ  ");
        details.setDescriptionB("很高兴见到你!");
        details.setDescriptionC("Nice to meet you!");
        details.setDescriptionD("Рад с вами познакомиться!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duì bù qǐ");
        details.setDescriptionB("对不起");
        details.setDescriptionC("I am sorry");
        details.setDescriptionD("Простите");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" méi guān xì ");
        details.setDescriptionB("没关系!");
        details.setDescriptionC("Never mind!");
        details.setDescriptionD("Это пустяки!/ Ничего!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zài jiàn/ bái ");
        details.setDescriptionB("再见! 拜！");
        details.setDescriptionC("Goodbye!/ Bye!");
        details.setDescriptionD("До свидания!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zài jiàn ");
        details.setDescriptionB("再见!");
        details.setDescriptionC("See you!");
        details.setDescriptionD("До встречи! ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhù nǐ yī qiè shùn lì ");
        details.setDescriptionB("祝你一切顺利!");
        details.setDescriptionC("All the best!");
        details.setDescriptionD("Всего хорошего!");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhù nǐ hǎo yùn ");
        details.setDescriptionB("祝你好运!");
        details.setDescriptionC(" Good luck !");
        details.setDescriptionD("Удачи!");
        detailsList.add(details);


    }
}
