package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C45 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("qì chē");
        details.setDescriptionB("汽车");
        details.setDescriptionC(" Car ");
        details.setDescriptionD("Автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǎo chē");
        details.setDescriptionB("跑车");
        details.setDescriptionC("Sports car");
        details.setDescriptionD("Cпортивный автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāo fáng chē ");
        details.setDescriptionB("消防车");
        details.setDescriptionC("Fire engine");
        details.setDescriptionD("Пожарная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiù hù chē ");
        details.setDescriptionB("救护车");
        details.setDescriptionC("Ambulance");
        details.setDescriptionD("Cкорая помощь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rán qì yìng jí jiù yuán chē ");
        details.setDescriptionB("燃气应急救援车");
        details.setDescriptionC("Gas emergency service");
        details.setDescriptionD("Аварийная служба газа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn chāo chē ");
        details.setDescriptionB("运钞车");
        details.setDescriptionC(" Armored cash car ");
        details.setDescriptionD("Инкассаторская машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jǐng chē");
        details.setDescriptionB("警车");
        details.setDescriptionC("Police car");
        details.setDescriptionD("Полицейская машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu zhèng chē ");
        details.setDescriptionB("邮政车");
        details.setDescriptionC("Postal car");
        details.setDescriptionD("Почтовый автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chū zū chē");
        details.setDescriptionB("出租车");
        details.setDescriptionC("Тaxi");
        details.setDescriptionD("Такси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí pǔ chē ");
        details.setDescriptionB("吉普车");
        details.setDescriptionC("Jeep");
        details.setDescriptionD("Джип");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sài chē ");
        details.setDescriptionB("赛车");
        details.setDescriptionC("Racing car");
        details.setDescriptionD("Гоночный автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng qì chē ");
        details.setDescriptionB("电动汽车");
        details.setDescriptionC(" Electric car ");
        details.setDescriptionD("Электроавтомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chǎng péng chē ");
        details.setDescriptionB("敞篷车");
        details.setDescriptionC("Open car");
        details.setDescriptionD("Кабриолет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǎo yé chē");
        details.setDescriptionB("老爷车");
        details.setDescriptionC("Vintage car");
        details.setDescriptionD("Классический автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn bāo chē ");
        details.setDescriptionB("面包车");
        details.setDescriptionC("Minibus");
        details.setDescriptionD("Микроавтобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pí kǎ chē ");
        details.setDescriptionB("皮卡车");
        details.setDescriptionC(" Pickup truck");
        details.setDescriptionD("Пикап");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shāng wù chē");
        details.setDescriptionB("商务车");
        details.setDescriptionC("Minivan");
        details.setDescriptionD("Минивэн");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huǒ jiàn qì chē ");
        details.setDescriptionB("火箭汽车");
        details.setDescriptionC("Rocket car");
        details.setDescriptionD("Ракетомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi xíng qì chē ");
        details.setDescriptionB("飞行汽车");
        details.setDescriptionC("Flying car");
        details.setDescriptionD("Летающий автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wú rén jià shǐ qì chē ");
        details.setDescriptionB("无人驾驶汽车");
        details.setDescriptionC("Driverless cars ");
        details.setDescriptionD("Беспилотный автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú rén jià shǐ bā shì ");
        details.setDescriptionB("无人驾驶巴士");
        details.setDescriptionC(" Driverless bus");
        details.setDescriptionD("Беспилотный автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāo huáng zhuān chē ");
        details.setDescriptionB("教皇专车");
        details.setDescriptionC("Popemobile");
        details.setDescriptionD("Папамобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" biān fú chē ");
        details.setDescriptionB("蝙蝠车 ");
        details.setDescriptionC("Batmobile");
        details.setDescriptionD("Бэтмобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā cháng lín kěn ");
        details.setDescriptionB("加长林肯");
        details.setDescriptionC("Limousine");
        details.setDescriptionD("Лимузин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fáng chē ");
        details.setDescriptionB("房车");
        details.setDescriptionC("Recreational vehicle/Trailer");
        details.setDescriptionD("Автодом/ Трейлер  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ chē ");
        details.setDescriptionB("马车");
        details.setDescriptionC("Сarriage");
        details.setDescriptionD("Карета");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn huò mǎ chē");
        details.setDescriptionB("运货马车");
        details.setDescriptionC("Cart");
        details.setDescriptionD("Телега");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ xuě qiāo ");
        details.setDescriptionB(" 马雪橇");
        details.setDescriptionC("Horse Sleigh");
        details.setDescriptionD("Конные сани");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě qiāo ");
        details.setDescriptionB("雪橇");
        details.setDescriptionC("Sledge ");
        details.setDescriptionD("Сани");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rè qì qiú ");
        details.setDescriptionB("热气球");
        details.setDescriptionC(" Hot air balloon ");
        details.setDescriptionD("Воздушный шар/Аэростат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo kōng qì qiú ");
        details.setDescriptionB("高空气球");
        details.setDescriptionC("High-altitude balloon");
        details.setDescriptionD("Стратостат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tàn kōng qì qiú ");
        details.setDescriptionB("探空气球");
        details.setDescriptionC("Weather balloon");
        details.setDescriptionD("Метеозонд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiàng luò sǎn");
        details.setDescriptionB("降落伞");
        details.setDescriptionC("Parachute");
        details.setDescriptionD("Парашют");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi tǐng ");
        details.setDescriptionB("飞艇");
        details.setDescriptionC("Airship ");
        details.setDescriptionD("Дирижабль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pēn qì bèi bāo ");
        details.setDescriptionB("喷气背包");
        details.setDescriptionC("Jet pack ");
        details.setDescriptionD("Реактивный ранец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuán guà shì huá xiáng jī");
        details.setDescriptionB("悬挂式滑翔机");
        details.setDescriptionC("Hang glider");
        details.setDescriptionD("Дельтаплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mín yòng fēi jī ");
        details.setDescriptionB("民用飞机");
        details.setDescriptionC("Civil aircraft");
        details.setDescriptionD("Гражданский самолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jūn yòng fēi jī ");
        details.setDescriptionB("军用飞机");
        details.setDescriptionC("Military aircraft");
        details.setDescriptionD("Военный самолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huò jī ");
        details.setDescriptionB("货机");
        details.setDescriptionC("Cargo aircraft");
        details.setDescriptionD("Грузовой самолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāo liàn jī ");
        details.setDescriptionB("教练机");
        details.setDescriptionC("Trainer (aircraft)");
        details.setDescriptionD(" Учебно-тренировочный самолёт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi jī");
        details.setDescriptionB("飞机");
        details.setDescriptionC("Airplane");
        details.setDescriptionD("Cамолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kōng zhōng jiā yóu jī ");
        details.setDescriptionB("空中加油机");
        details.setDescriptionC("Aerial tanker");
        details.setDescriptionD("Самолёт-заправщик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ shàng fēi jī ");
        details.setDescriptionB("水上飞机");
        details.setDescriptionC("Seaplane");
        details.setDescriptionD("Гидросамолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú rén jià shǐ fēi jī");
        details.setDescriptionB("无人驾驶飞机");
        details.setDescriptionC("Pilotless aircraft");
        details.setDescriptionD("Беспилотник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiáng jī jī ");
        details.setDescriptionB("强击机");
        details.setDescriptionC("Attack aircraft");
        details.setDescriptionD("Штурмовик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān jī jī ");
        details.setDescriptionB("歼击机");
        details.setDescriptionC("Fighter plane");
        details.setDescriptionD("Истребитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hōng zhà jī");
        details.setDescriptionB("轰炸机 ");
        details.setDescriptionC("Bomber plane");
        details.setDescriptionD("  Бомбардировщик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn chá jī");
        details.setDescriptionB("侦察机");
        details.setDescriptionC("Spy plane");
        details.setDescriptionD("Самолёт-разведчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tài kōng fēi jī ");
        details.setDescriptionB("太空飞机");
        details.setDescriptionC("Spaceplane");
        details.setDescriptionD("Космоплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá xiáng jī");
        details.setDescriptionB("滑翔机");
        details.setDescriptionC("Glider");
        details.setDescriptionD("Планер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fù yì fēi jī ");
        details.setDescriptionB("复翼飞机");
        details.setDescriptionC("Biplane");
        details.setDescriptionD("Биплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhí shēng fēi jī");
        details.setDescriptionB("直升飞机");
        details.setDescriptionC(" Helicopter");
        details.setDescriptionD("Вертолёт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuāng xuán yì jiāo chā shì zhí shēng jī ");
        details.setDescriptionB("双旋翼交叉式直升机");
        details.setDescriptionC("Synchropter");
        details.setDescriptionD("Синхроптер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng fā kě biàn yì zhí shēng jī");
        details.setDescriptionB("双发可变翼直升机");
        details.setDescriptionC("Convertiplane");
        details.setDescriptionD("Конвертоплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì zhuǎn xuán yì jī ");
        details.setDescriptionB("自转旋翼机");
        details.setDescriptionC(" Autogyro/ Gyroplane ");
        details.setDescriptionD("Автожир/ Гироплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dì xiào fēi xíng qì ");
        details.setDescriptionB("地效飞行器");
        details.setDescriptionC("Ekranoplan ");
        details.setDescriptionD("Экраноплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ jiàn fēi jī ");
        details.setDescriptionB("火箭飞机");
        details.setDescriptionC(" Rocketplane");
        details.setDescriptionD("Ракетоплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòng lì huá xiáng sǎn ");
        details.setDescriptionB("动力滑翔伞");
        details.setDescriptionC("Motoparaplane");
        details.setDescriptionD("Мотопараплан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zì xíng chē/ jiǎo tà chē ");
        details.setDescriptionB("自行车/脚踏车");
        details.setDescriptionC("Bicycle");
        details.setDescriptionD("Велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shān dì zì xíng chē");
        details.setDescriptionB("山地自行车");
        details.setDescriptionC("Mountain bike");
        details.setDescriptionD("Горный велобайк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng gòng zì xíng chē ");
        details.setDescriptionB("公共自行车");
        details.setDescriptionC("Public bike");
        details.setDescriptionD("Общественный велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duō rén zì xíng chē ");
        details.setDescriptionB("多人自行车");
        details.setDescriptionC("Tandem bicycle");
        details.setDescriptionD("Тандем-велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pàng chē ");
        details.setDescriptionB("胖车");
        details.setDescriptionC(" Fatbike ");
        details.setDescriptionD("Фэтбайк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biàn sù zì xíng chē ");
        details.setDescriptionB("变速自行车");
        details.setDescriptionC("Sport racing bike");
        details.setDescriptionD("Спортивный велобайк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gōng lù zì xíng chē ");
        details.setDescriptionB("公路自行车");
        details.setDescriptionC("Road bike");
        details.setDescriptionD("Шоссейный байк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiě sān chē ");
        details.setDescriptionB("铁三车");
        details.setDescriptionC("Triathlon Bike");
        details.setDescriptionD("Байк для занятий триатлоном");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" BMX xiǎo lún chē ");
        details.setDescriptionB(" BMX小轮车");
        details.setDescriptionC("  BMX bike");
        details.setDescriptionD("Спортивный байк для триала и фристайла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ xíng zì xíng chē ");
        details.setDescriptionB("旅行自行车");
        details.setDescriptionC("Touring bike");
        details.setDescriptionD("Туринговый велобайк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhé dié zì xíng chē ");
        details.setDescriptionB("折叠自行车");
        details.setDescriptionC("Folding bicycle  ");
        details.setDescriptionD("Складной велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sǐ fēi dān chē ");
        details.setDescriptionB("死飞单车");
        details.setDescriptionC("Fixed gear bike");
        details.setDescriptionD("Фикс велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng zì xíng chē ");
        details.setDescriptionB("电动自行车");
        details.setDescriptionC("Electrobike");
        details.setDescriptionD("Электровелосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuán fú zì xíng chē ");
        details.setDescriptionB("悬浮自行车");
        details.setDescriptionC(" Hover bike ");
        details.setDescriptionD(" Ховербайк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" 3 lún tǎng chē ");
        details.setDescriptionB(" 3轮躺车");
        details.setDescriptionC("Liegerad");
        details.setDescriptionD("Трехколёсный лигерад");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" èr lún tǎng chē ");
        details.setDescriptionB("2轮躺车");
        details.setDescriptionC("Two-wheels liegerad ");
        details.setDescriptionD("Двухколёсный лигерад  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhì néng zì xíng chē ");
        details.setDescriptionB("智能自行车");
        details.setDescriptionC(" Smart bicycle ");
        details.setDescriptionD("«Умный» велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér tóng zì xíng chē ");
        details.setDescriptionB("儿童自行车");
        details.setDescriptionC("Child bike");
        details.setDescriptionD("Детский велосипед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  píng héng chē ");
        details.setDescriptionB("平衡车");
        details.setDescriptionC(" Balance bike ");
        details.setDescriptionD("Беговел");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huá bǎn chē ");
        details.setDescriptionB("滑板车");
        details.setDescriptionC("Scooter");
        details.setDescriptionD("Самокат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng huá bǎn chē ");
        details.setDescriptionB("电动滑板车");
        details.setDescriptionC(" Electric scooter");
        details.setDescriptionD("Электросамокат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà lún tāi diàn dòng huá bǎn chē ");
        details.setDescriptionB("大轮胎电动滑板车");
        details.setDescriptionC("Big wheel electric scooter");
        details.setDescriptionD("Электросамокат на больших колёсах");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huá bǎn ");
        details.setDescriptionB("滑板");
        details.setDescriptionC("Skateboard");
        details.setDescriptionD(" Cкейтборд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng huá bǎn ");
        details.setDescriptionB("电动滑板");
        details.setDescriptionC("Electric Skateboard");
        details.setDescriptionD("Электроскейт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng dú lún huá bǎn ");
        details.setDescriptionB("电动独轮滑板");
        details.setDescriptionC("Hoverboard");
        details.setDescriptionD("Ховерборд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhì néng píng héng chē ");
        details.setDescriptionB("智能平衡车");
        details.setDescriptionC(" Giroskuter ");
        details.setDescriptionD(" Гироскутер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("悬浮滑板");
        details.setDescriptionB(" xuán fú huá bǎn ");
        details.setDescriptionC("Flyboard Air");
        details.setDescriptionD("Воздушный флайборд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ shàng fēi bǎn ");
        details.setDescriptionB("水上飞板");
        details.setDescriptionC("Flyboard");
        details.setDescriptionD("Флайборд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng huá xíng chē");
        details.setDescriptionB("儿童滑行车");
        details.setDescriptionC("Children's scooter");
        details.setDescriptionD("Детский скутер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng diàn dòng chē ");
        details.setDescriptionB("儿童电动车");
        details.setDescriptionC(" Children's electric car ");
        details.setDescriptionD("Детский электроавтомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǔ hào píng héng chē kǎ dīng gǎi zhuāng tào jiàn ");
        details.setDescriptionB("九号平衡车卡丁改装套件");
        details.setDescriptionC(" Ninebot GoKart Kit ");
        details.setDescriptionD("Электрокарт Найнбот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī wéi chē/ píng héng chē ");
        details.setDescriptionB("思维车/平衡车");
        details.setDescriptionC("Segway");
        details.setDescriptionD("Сегвей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huá dào ");
        details.setDescriptionB("滑道");
        details.setDescriptionC("Toboggan run");
        details.setDescriptionD("Табогган ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō lā jī ");
        details.setDescriptionB("拖拉机");
        details.setDescriptionC(" Tractor");
        details.setDescriptionD(" Tрактор ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("汽车拖拉机");
        details.setDescriptionB(" qì chē tuō lā jī ");
        details.setDescriptionC("Auto tractor");
        details.setDescriptionD("Автотрактор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuō lā jī yǔ tuō chē ");
        details.setDescriptionB("拖拉机与拖车");
        details.setDescriptionC(" Тractor with trailer ");
        details.setDescriptionD("Трактор с прицепом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shōu gē jī ");
        details.setDescriptionB("收割机");
        details.setDescriptionC("Combine harvester ");
        details.setDescriptionD("Комбайн");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gāo tiě ");
        details.setDescriptionB("高铁");
        details.setDescriptionC("High-speed rail train");
        details.setDescriptionD("Cкоростной поезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shàng hǎi cí xuán fú liè chē ");
        details.setDescriptionB("上海磁悬浮列车");
        details.setDescriptionC("Shanghai Maglev train ");
        details.setDescriptionD("Шанхайский Маглев");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gè rén kuài sù jiāo tōng ");
        details.setDescriptionB("个人快速交通");
        details.setDescriptionC("Personal Rapid Transit");
        details.setDescriptionD("Персональный автоматический транспорт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huǒ chē ");
        details.setDescriptionB("火车");
        details.setDescriptionC("Train");
        details.setDescriptionD("Поезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ chē tóu");
        details.setDescriptionB("火车头");
        details.setDescriptionC("Locomotive");
        details.setDescriptionD("Паровоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn lì huǒ chē");
        details.setDescriptionB("电力火车");
        details.setDescriptionC("Electric train");
        details.setDescriptionD("Электричка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān guǐ liè chē ");
        details.setDescriptionB("单轨列车");
        details.setDescriptionC("Monorail");
        details.setDescriptionD("Монорельс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuán guà shì dān guǐ tiě lù ");
        details.setDescriptionB("悬挂式单轨铁路");
        details.setDescriptionC(" Suspended monorail railway ");
        details.setDescriptionD("Подвесная монорельсовая дорога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dì tiě ");
        details.setDescriptionB("地铁");
        details.setDescriptionC(" Underground");
        details.setDescriptionD("Метро");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhú huǒ chē ");
        details.setDescriptionB("竹火车");
        details.setDescriptionC("Bamboo train ");
        details.setDescriptionD("Бамбуковый поезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bīng qí lín kǎ chē");
        details.setDescriptionB("冰淇淋卡车");
        details.setDescriptionC("Ice-cream truck");
        details.setDescriptionD("Фургон с мороженным");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wū bǎo ào kè ěr chāo jí bā shì ");
        details.setDescriptionB("乌宝奥克尔超级巴士");
        details.setDescriptionC("Wubbo Ockels Superbus");
        details.setDescriptionD("Супер-автобус  Вуббо Оккельс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng gòng qì chē ");
        details.setDescriptionB("公共汽车");
        details.setDescriptionC("Bus");
        details.setDescriptionD("Автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng céng bā shì");
        details.setDescriptionB("双层巴士 ");
        details.setDescriptionC("Double decker bus");
        details.setDescriptionD(" Двухэтажный автобус ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guó jì bā shì");
        details.setDescriptionB("国际巴士");
        details.setDescriptionC("International bus");
        details.setDescriptionD("Международный автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guān guāng bā shì ");
        details.setDescriptionB("观光巴士");
        details.setDescriptionC(" Sightseeing bus ");
        details.setDescriptionD("Экскурсионный автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī chǎng bā shì");
        details.setDescriptionB("机场巴士");
        details.setDescriptionC("Airport bus");
        details.setDescriptionD("Экспресс -автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiào chē ");
        details.setDescriptionB("校车");
        details.setDescriptionC("School bus");
        details.setDescriptionD("Школьный автобус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn dòng guān guāng chē");
        details.setDescriptionB("电动观光车");
        details.setDescriptionC("Electric sightseeing bus ");
        details.setDescriptionD(" Электрический экскурсионный автобус ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú guǐ diàn chē ");
        details.setDescriptionB("无轨电车");
        details.setDescriptionC(" Trolleybus");
        details.setDescriptionD(" Tроллейбус ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǒu guǐ diàn chē ");
        details.setDescriptionB("有轨电车");
        details.setDescriptionC("Tram");
        details.setDescriptionD(" Tрамвай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě dì chē ");
        details.setDescriptionB("雪地车");
        details.setDescriptionC("Snowmobile");
        details.setDescriptionD("Cнегоход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě jī chē ");
        details.setDescriptionB("雪机车");
        details.setDescriptionC("Snow machine ");
        details.setDescriptionD("Cнегоуборочная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sǎ shuǐ chē ");
        details.setDescriptionB("洒水车");
        details.setDescriptionC("Watering car");
        details.setDescriptionD("Поливомоечная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sǎo lù chē");
        details.setDescriptionB("扫路车");
        details.setDescriptionC("Road sweeper ");
        details.setDescriptionD(" Подметально-уборочная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo bàn chē ");
        details.setDescriptionB("搅拌车");
        details.setDescriptionC("Сoncrete mixer");
        details.setDescriptionD("Бетономешалка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ ní yùn shū chē ");
        details.setDescriptionB("水泥运输车");
        details.setDescriptionC(" Cement truck ");
        details.setDescriptionD("Авторастворовоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhuāng zǎi jī ");
        details.setDescriptionB("装载机");
        details.setDescriptionC("Wheel loader");
        details.setDescriptionD("Автопогрузчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí nǐ zhuāng zǎi jī ");
        details.setDescriptionB("迷你装载机");
        details.setDescriptionC(" Mini wheel loader ");
        details.setDescriptionD("Мини-погрузчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wā jué jī ");
        details.setDescriptionB("挖掘机");
        details.setDescriptionC("Excavator ");
        details.setDescriptionD("Экскаватор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zì xiè kǎ chē ");
        details.setDescriptionB("自卸卡车");
        details.setDescriptionC("Dump truck");
        details.setDescriptionD("Самосвал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuī tǔ jī ");
        details.setDescriptionB("推土机");
        details.setDescriptionC("Bulldozer ");
        details.setDescriptionD("Бульдозер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chā chē ");
        details.setDescriptionB("叉车");
        details.setDescriptionC("Forklift");
        details.setDescriptionD("Грузоподъемник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǎ shì qǐ zhòng jī");
        details.setDescriptionB("塔式起重机");
        details.setDescriptionC("Tower crane");
        details.setDescriptionD(" Подъемный кран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǚ dài qǐ zhòng jī ");
        details.setDescriptionB("履带起重机");
        details.setDescriptionC(" Crawler crane ");
        details.setDescriptionD("Трубоукладчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì chē qǐ zhòng jī");
        details.setDescriptionB("汽车起重机");
        details.setDescriptionC("Truck crane ");
        details.setDescriptionD("Автокран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo kōng zuò yè chē ");
        details.setDescriptionB("高空作业车");
        details.setDescriptionC(" Aerial work truck");
        details.setDescriptionD("Автовышка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hùn níng tǔ bèng chē ");
        details.setDescriptionB("混凝土泵车");
        details.setDescriptionC(" Concrete pump truck ");
        details.setDescriptionD("Бетононасос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuō chē ");
        details.setDescriptionB("拖车");
        details.setDescriptionC("Tow truck ");
        details.setDescriptionD("Эвакуатор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō guà chē");
        details.setDescriptionB("拖挂车");
        details.setDescriptionC("Lorry tractor ");
        details.setDescriptionD("Тягач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huò chē ");
        details.setDescriptionB("货车");
        details.setDescriptionC("Lorry ");
        details.setDescriptionD("Грузовик /Фура");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng bǎn tuō chē");
        details.setDescriptionB("平板拖车");
        details.setDescriptionC("Flatbed trailer");
        details.setDescriptionD("Бортовой прицеп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nóng yòng tuō chē");
        details.setDescriptionB("农用拖车");
        details.setDescriptionC("Agricultural trailer");
        details.setDescriptionD("Сельскохозяйственный прицеп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo xíng huò chē ");
        details.setDescriptionB("小型货车");
        details.setDescriptionC("Van");
        details.setDescriptionD("Фургон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lěng cáng chē ");
        details.setDescriptionB("冷藏车");
        details.setDescriptionC(" Refrigerated truck");
        details.setDescriptionD("Авторефрижератор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo kǎ chē ");
        details.setDescriptionB("小卡车");
        details.setDescriptionC(" Small truck ");
        details.setDescriptionD("Малый грузовик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gē cǎo jī");
        details.setDescriptionB("割草机");
        details.setDescriptionC(" Grass cutter ");
        details.setDescriptionD("Газонокосилка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yè yā pò suì chuí ");
        details.setDescriptionB("液压破碎锤");
        details.setDescriptionC("Hydraulic hammer");
        details.setDescriptionD("Гидромолот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā lù jī ");
        details.setDescriptionB("压路机");
        details.setDescriptionC("Road roller");
        details.setDescriptionD("Дорожный каток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chǎn yùn jī");
        details.setDescriptionB("铲运机");
        details.setDescriptionC("Scraper");
        details.setDescriptionD("Скрепер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" píng dì jī ");
        details.setDescriptionB("平地机");
        details.setDescriptionC(" Grader ");
        details.setDescriptionD("Грейдер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kāi gōu jī ");
        details.setDescriptionB("开沟机");
        details.setDescriptionC("Trencher machine");
        details.setDescriptionD("Траншеекопатель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yè huà qì guàn chē ");
        details.setDescriptionB("液化气罐车");
        details.setDescriptionC("Liquified gas tanker");
        details.setDescriptionD("Автомобиль-газовоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuō guàn chē ");
        details.setDescriptionB("拖罐车");
        details.setDescriptionC("Tank wagon");
        details.setDescriptionD("Вагон-цистерна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu guàn chē ");
        details.setDescriptionB("油罐车");
        details.setDescriptionC("Tanker truck ");
        details.setDescriptionD("Бензовоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì chē yùn shū chē ");
        details.setDescriptionB("汽车运输车");
        details.setDescriptionC(" Car carrier ");
        details.setDescriptionD("Автовоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù cái yùn shū chē");
        details.setDescriptionB("木材运输车");
        details.setDescriptionC("Timber carrier");
        details.setDescriptionD("Форвардер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lā jī chē ");
        details.setDescriptionB("垃圾车");
        details.setDescriptionC("Garbage truck");
        details.setDescriptionD("Mусоровоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǎi guàn chē");
        details.setDescriptionB("奶罐车");
        details.setDescriptionC("Milk tanker");
        details.setDescriptionD("Молоковоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn fěn yùn shū chē ");
        details.setDescriptionB("面粉运输车");
        details.setDescriptionC(" Flour truck ");
        details.setDescriptionD("Муковоз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí zhuāng xiāng chē ");
        details.setDescriptionB("集装箱车");
        details.setDescriptionC("Container truck");
        details.setDescriptionD("Автоконтейнеровоз ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huò chē liè chē ");
        details.setDescriptionB("货车列车");
        details.setDescriptionC(" Road train ");
        details.setDescriptionD("Автопоезд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǎn kè ");
        details.setDescriptionB("坦克");
        details.setDescriptionC("Tank");
        details.setDescriptionD("Танк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huǒ jiàn");
        details.setDescriptionB("火箭");
        details.setDescriptionC("Rocket");
        details.setDescriptionD("Ракета");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wèi xīng");
        details.setDescriptionB("卫星");
        details.setDescriptionC("Satellite");
        details.setDescriptionD("Спутник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǔ zhòu fēi chuán ");
        details.setDescriptionB("宇宙飞船");
        details.setDescriptionC("Spaceship");
        details.setDescriptionD(" Космический корабль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuè qiú chē ");
        details.setDescriptionB("月球车");
        details.setDescriptionC("Moon car");
        details.setDescriptionD("Лунный автомобиль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi dié");
        details.setDescriptionB("飞碟");
        details.setDescriptionC("UFO");
        details.setDescriptionD("НЛО");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng biàn mó tuō chē ");
        details.setDescriptionB("轻便摩托车");
        details.setDescriptionC("Motor scooter");
        details.setDescriptionD("Мотороллер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mó tuō chē ");
        details.setDescriptionB("摩托车");
        details.setDescriptionC("Motorcycle");
        details.setDescriptionD("Мотоцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn dòng tà bǎn chē ");
        details.setDescriptionB("电动踏板车");
        details.setDescriptionC(" Electric scooter ");
        details.setDescriptionD("Электроскутер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("MonoTracer mó tuō chē ");
        details.setDescriptionB("MonoTracer摩托车");
        details.setDescriptionC(" Ecomobile /MonoTracer Мотоцикл MonoTracer ");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng huò yùn sān lún chē ");
        details.setDescriptionB("电动货运三轮车");
        details.setDescriptionC("Electric cargo tricycle ");
        details.setDescriptionD(" Трехколёсный грузовой мотоцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sān lún mó tuō chē ");
        details.setDescriptionB("三轮摩托车");
        details.setDescriptionC(" Three-wheels motorcycle ");
        details.setDescriptionD("Трехколёсный скутер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cán jí rén diàn dòng chē ");
        details.setDescriptionB(" 残疾人电动车");
        details.setDescriptionC("Scooter for disabled");
        details.setDescriptionD("Скутер для инвалидов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér tóng diàn dòng tà bǎn chē ");
        details.setDescriptionB("儿童电动踏板车");
        details.setDescriptionC(" Children's electric scooter ");
        details.setDescriptionD("Детский электроскутер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dān lún diàn dòng tà bǎn chē ");
        details.setDescriptionB("单轮电动踏板车");
        details.setDescriptionC("One wheel electric scooter");
        details.setDescriptionD("Одноколёсный электроскутер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng dú lún chē ");
        details.setDescriptionB("电动独轮车");
        details.setDescriptionC("Solowheel ");
        details.setDescriptionD("Моноколесо Solowheel ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dú lún jiǎo tà chē");
        details.setDescriptionB("独轮脚踏车");
        details.setDescriptionC("Unicycle");
        details.setDescriptionD("Уницикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dān lún mó tuō chē ");
        details.setDescriptionB("单轮摩托车");
        details.setDescriptionC(" Monocycle");
        details.setDescriptionD("Интроцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sì lún mó tuō chē ");
        details.setDescriptionB("四轮摩托车");
        details.setDescriptionC("Quad bike");
        details.setDescriptionD("Квадроцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér tóng sì lún mó tuō chē ");
        details.setDescriptionB("儿童四轮摩托车");
        details.setDescriptionC(" Children's quad bike ");
        details.setDescriptionD("Детский квадроцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo ěr fū qiú chē ");
        details.setDescriptionB("高尔夫球车");
        details.setDescriptionC("Golf car");
        details.setDescriptionD("Гольф-кар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǎn chē");
        details.setDescriptionB("缆车");
        details.setDescriptionC("Cable car");
        details.setDescriptionD("Канатная дорога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dēng shān tiě dào");
        details.setDescriptionB("登山铁道");
        details.setDescriptionC("Funicular railway");
        details.setDescriptionD("Фуникулёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiào zǐ ");
        details.setDescriptionB("轿子");
        details.setDescriptionC("Palanquin");
        details.setDescriptionD("Паланкин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng bāo chē");
        details.setDescriptionB("黄包车");
        details.setDescriptionC("Rickshaw");
        details.setDescriptionD("Рикша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kè yùn sān lún chē ");
        details.setDescriptionB("客运三轮车");
        details.setDescriptionC(" Trishaw ");
        details.setDescriptionD("Велорикша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhuán");
        details.setDescriptionB("船 ");
        details.setDescriptionC("Ship");
        details.setDescriptionD("Корабль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ lù yuè yě chē ");
        details.setDescriptionB(" 水陆越野车");
        details.setDescriptionC("Amphibious Vehicle");
        details.setDescriptionD("Грузовик-амфибия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ lù liǎng yòng chē ");
        details.setDescriptionB(" 水陆两用车");
        details.setDescriptionC(" Amphibian automobile ");
        details.setDescriptionD("Амфибия-вседорожник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ lù liǎng qī fáng chē ");
        details.setDescriptionB("水陆两栖房车");
        details.setDescriptionC("Sealander Amphibious");
        details.setDescriptionD("Кемпинг трейлер-амфибия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā yú qián tǐng");
        details.setDescriptionB("鲨鱼潜艇");
        details.setDescriptionC("Shark submarine");
        details.setDescriptionD("Подводная лодка Акула");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qián tǐng ");
        details.setDescriptionB("潜艇");
        details.setDescriptionC("Submarine");
        details.setDescriptionD("Подводная лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ xià háng mǔ ");
        details.setDescriptionB("水下航母");
        details.setDescriptionC("Underwater carrier");
        details.setDescriptionD("Подводный авианосец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" háng kōng mǔ jiàn ");
        details.setDescriptionB("航空母舰");
        details.setDescriptionC("Carrier ship");
        details.setDescriptionD("Авианосец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qū zhú jiàn");
        details.setDescriptionB("驱逐舰");
        details.setDescriptionC("Destroyer ship");
        details.setDescriptionD("Эскадрённый миноносец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhàn jiàn ");
        details.setDescriptionB("战舰");
        details.setDescriptionC(" Warship ");
        details.setDescriptionD("Военный корабль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhàn liè jiàn ");
        details.setDescriptionB("战列舰");
        details.setDescriptionC("Battleship ");
        details.setDescriptionD("Линкор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wā ní chuán ");
        details.setDescriptionB("挖泥船");
        details.setDescriptionC("Dredger");
        details.setDescriptionD("Дноуглубительное судно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ yì chuán ");
        details.setDescriptionB("水翼船");
        details.setDescriptionC("Hydrofoil");
        details.setDescriptionD("Судно на подводных крыльях");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pò bīng chuán ");
        details.setDescriptionB("破冰船");
        details.setDescriptionC("Icebreaker");
        details.setDescriptionD("Ледокол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qì lún chuán ");
        details.setDescriptionB("汽轮船");
        details.setDescriptionC("Steamship");
        details.setDescriptionD("Пароход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kè lún chuán");
        details.setDescriptionB("客轮船");
        details.setDescriptionC("Passenger ship");
        details.setDescriptionD("Пассажирский теплоход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān chuán ");
        details.setDescriptionB("班船");
        details.setDescriptionC("Liner");
        details.setDescriptionD("Лайнер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dù chuán ");
        details.setDescriptionB("渡船");
        details.setDescriptionC("Ferry");
        details.setDescriptionD("Паром");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu lǎn chuán");
        details.setDescriptionB("游览船");
        details.setDescriptionC("Excursion vessel");
        details.setDescriptionD("Экскурсионное судно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu tǐng ");
        details.setDescriptionB("游艇");
        details.setDescriptionC("Yacht");
        details.setDescriptionD("Яхта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mó tuō tǐng ");
        details.setDescriptionB("摩托艇");
        details.setDescriptionC(" Hydrocycle ");
        details.setDescriptionD("Водный мотоцикл/Гидроцикл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo chuán ");
        details.setDescriptionB("小船");
        details.setDescriptionC("Boat");
        details.setDescriptionD("Лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fá");
        details.setDescriptionB("筏");
        details.setDescriptionC("Raft");
        details.setDescriptionD("Плот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chōng qì chuán");
        details.setDescriptionB(" 充气船");
        details.setDescriptionC(" Inflatable boat ");
        details.setDescriptionD(" Надувная резиновая лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qì tǐng ");
        details.setDescriptionB("汽艇");
        details.setDescriptionC("Motorboat");
        details.setDescriptionD("Моторная лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí tǐng");
        details.setDescriptionB("皮艇");
        details.setDescriptionC("Kayak");
        details.setDescriptionD("Байдарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiù shēng chuán");
        details.setDescriptionB("救生船 ");
        details.setDescriptionC("Lifeboat");
        details.setDescriptionD("Спасательная лодка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō chuán ");
        details.setDescriptionB("拖船");
        details.setDescriptionC("Tugboat");
        details.setDescriptionD("Буксир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tuō wǎng yú chuán ");
        details.setDescriptionB("拖网渔船");
        details.setDescriptionC("Trawler");
        details.setDescriptionD("Промысловое судно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuāng tǐ chuán ");
        details.setDescriptionB("双体船");
        details.setDescriptionC(" Catamaran ");
        details.setDescriptionD("Катамаран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn dòng shuāng tǐ chuán ");
        details.setDescriptionB("电动双体船");
        details.setDescriptionC(" Electric-solar catamaran ");
        details.setDescriptionD("Электрокатамаран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuāng tǐ fān chuán ");
        details.setDescriptionB("双体帆船");
        details.setDescriptionC(" Sailing catamaran ");
        details.setDescriptionD("Парусно-моторный катамаран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān chuán ");
        details.setDescriptionB("帆船");
        details.setDescriptionC("Sailing ship");
        details.setDescriptionD("Парусник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu chuán ");
        details.setDescriptionB("油船");
        details.setDescriptionC("Oil tanker");
        details.setDescriptionD("Танкер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bó chuán");
        details.setDescriptionB("驳船");
        details.setDescriptionC("Barge");
        details.setDescriptionD("Баржа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jí zhuāng xiāng chuán ");
        details.setDescriptionB("集装箱船");
        details.setDescriptionC("Container Ship");
        details.setDescriptionD("Контейнеровоз ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ shàng chū zū chē ");
        details.setDescriptionB(" 水上出租车");
        details.setDescriptionC("Water taxi ");
        details.setDescriptionD("Водное такси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zì dòng fú tī ");
        details.setDescriptionB("自动扶梯");
        details.setDescriptionC("Escalator");
        details.setDescriptionD("Эскалатор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn tī ");
        details.setDescriptionB("电梯");
        details.setDescriptionC(" Lift/ Elevator ");
        details.setDescriptionD("Лифт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng biàn mó tuō chē ");
        details.setDescriptionB("轻便摩托车");
        details.setDescriptionC("Moped");
        details.setDescriptionD("Мопед");
        detailsList.add(details);
    }
}
