package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C46 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("ā bǐ xī ní yǎ māo ");
        details.setDescriptionB("阿比西尼亚猫");
        details.setDescriptionC(" Abyssinian cat ");
        details.setDescriptionD("Абиссинская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ào dà lì yà wù māo ");
        details.setDescriptionB("澳大利亚雾猫");
        details.setDescriptionC(" Australian Mist cat ");
        details.setDescriptionD("Австралийский мист");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yà zhōu hǔ bān māo ");
        details.setDescriptionB("亚洲虎斑猫");
        details.setDescriptionC(" Asian-Tabby");
        details.setDescriptionD("Азиатская табби");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi guó duǎn máo māo ");
        details.setDescriptionB("美国短毛猫");
        details.setDescriptionC(" American shorthair cat ");
        details.setDescriptionD("Американская короткошёрстная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó yìng máo māo");
        details.setDescriptionB("美国硬毛猫");
        details.setDescriptionC(" American Wirehair cat");
        details.setDescriptionD("Американская жесткошёрстная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó duǎn wěi māo( duǎn máo )");
        details.setDescriptionB("美国短尾猫(短毛）");
        details.setDescriptionC(" American Bobtail  Shorthair cat ");
        details.setDescriptionD("Американский бобтейл короткошёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" měi guó duǎn wěi māo(сháng máo)");
        details.setDescriptionB("美国短尾猫(长毛) ");
        details.setDescriptionC(" American Bobtail Longhair cat");
        details.setDescriptionD("Американский бобтейл длинношёрстный ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó juǎn ěr māo ( duǎn máo ) ");
        details.setDescriptionB("美国卷耳猫(短毛 ) ");
        details.setDescriptionC(" American Curl  shorthair");
        details.setDescriptionD("Американский кёрл короткошёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó juǎn ěr māo (сháng máo) ");
        details.setDescriptionB("美国卷耳猫(长毛) ");
        details.setDescriptionC(" American Curl  longhair");
        details.setDescriptionD("Американский кёрл длиношёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bā lí māo ");
        details.setDescriptionB("巴厘猫");
        details.setDescriptionC(" Balinese");
        details.setDescriptionD("Балинезийская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā qiū māo ā lā bó yà zhǒng");
        details.setDescriptionB("沙丘猫阿拉伯亚种");
        details.setDescriptionC("Sand Dune Cat");
        details.setDescriptionD("Барханный кот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mèng jiā lā bào māo ");
        details.setDescriptionB("孟加拉豹猫");
        details.setDescriptionC("Bengal cat");
        details.setDescriptionD("Бенгальская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mèng mǎi māo");
        details.setDescriptionB("孟买猫");
        details.setDescriptionC("Bombay cat");
        details.setDescriptionD("Бомбейская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā xī duǎn máo māo ");
        details.setDescriptionB("巴西短毛猫");
        details.setDescriptionC("Brazilian Shorthair");
        details.setDescriptionD("Бразильская короткошёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng guó cháng máo māo ");
        details.setDescriptionB("英国长毛猫");
        details.setDescriptionC(" British Longhair cat");
        details.setDescriptionD("Британская длинношёрстная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng guó duǎn máo māo");
        details.setDescriptionB("英国短毛猫");
        details.setDescriptionC(" British Shorthair cat ");
        details.setDescriptionD("Британская короткошёрстная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miǎn diàn māo ");
        details.setDescriptionB("缅甸猫");
        details.setDescriptionC("Burmese cat");
        details.setDescriptionD(" Бурманская кошка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bō mǐ lā māo ");
        details.setDescriptionB("波米拉猫");
        details.setDescriptionC("Burmilla shorthair cat ");
        details.setDescriptionD("Бурмилла короткошёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hā wǎ nà zōng māo ");
        details.setDescriptionB("哈瓦那棕猫");
        details.setDescriptionC(" Havana Brown cat");
        details.setDescriptionD("Кошка Гавана браун ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ mǎ lā yǎ māo");
        details.setDescriptionB("喜玛拉雅猫");
        details.setDescriptionC("Himalayan Longhair cat");
        details.setDescriptionD("Гималайская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé wén juǎn máo māo");
        details.setDescriptionB("德文卷毛猫");
        details.setDescriptionC(" Devon Rex cat");
        details.setDescriptionD("Девон рекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng sī fēn kè sī māo ");
        details.setDescriptionB("唐斯芬克斯猫");
        details.setDescriptionC("Donskoy cat/ Don Sphynx cat");
        details.setDescriptionD("Донской сфинкс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" āi jí māo");
        details.setDescriptionB("埃及猫");
        details.setDescriptionC("Egyptian Mau");
        details.setDescriptionD("Египетский мау");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuē kè māo ");
        details.setDescriptionB("约克猫");
        details.setDescriptionC("York cat");
        details.setDescriptionD("Йоркская шоколадная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tài guó yù māo");
        details.setDescriptionB("泰国御猫");
        details.setDescriptionC("Khao Manee");
        details.setDescriptionD("Као-ма́ни");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā zhōu shǎn liàng māo ");
        details.setDescriptionB("加州闪亮猫 ");
        details.setDescriptionC("California Spangled ");
        details.setDescriptionD("Калифорнийская сияющая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu duǎn máo māo");
        details.setDescriptionB("欧洲短毛猫");
        details.setDescriptionC(" European Shorthair ");
        details.setDescriptionD("Европейская короткошёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kē lā tè māo/ hē lè māo ");
        details.setDescriptionB("科拉特猫/呵叻猫");
        details.setDescriptionC(" Korat ");
        details.setDescriptionD("Корат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎ nà ní māo ");
        details.setDescriptionB("卡纳尼猫");
        details.setDescriptionC("Kanaani  ");
        details.setDescriptionD("Канаани");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎ lèi lì ā duǎn wěi ");
        details.setDescriptionB("卡累利阿短尾");
        details.setDescriptionC(" Karelian bobtail ");
        details.setDescriptionD("Карельский бобтейл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng guó lí huā māo");
        details.setDescriptionB("中国狸花猫");
        details.setDescriptionC("Chinese Li Hua ");
        details.setDescriptionD("Китайская Ли Хуа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēi ěr shì māo");
        details.setDescriptionB("威尔士猫");
        details.setDescriptionC("Cymric cat");
        details.setDescriptionD("Кимрик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kē ní sī juǎn máo māo");
        details.setDescriptionB("柯尼斯卷毛猫");
        details.setDescriptionC("Cornish Rex cat");
        details.setDescriptionD(" Корниш-Рекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiān dǎo duǎn wěi māo ");
        details.setDescriptionB("千岛短尾猫");
        details.setDescriptionC(" Kurilian Bobtail");
        details.setDescriptionD("Курильский бобтейл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lā bō juǎn máo māo ");
        details.setDescriptionB("拉波卷毛猫");
        details.setDescriptionC(" LaPerm ");
        details.setDescriptionD("Лаперм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("màn chì kěn māo/ duǎn tuǐ māo ");
        details.setDescriptionB("曼赤肯猫/短腿猫");
        details.setDescriptionC("Munchkin cat");
        details.setDescriptionD("Манчкин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("màn chì kěn māo/ duǎn tuǐ māo (сháng máo) ");
        details.setDescriptionB("曼赤肯猫/短腿猫 (长毛)");
        details.setDescriptionC("Munchkin cat longhair");
        details.setDescriptionD("Манчкин длиношёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miǎn yīn kù");
        details.setDescriptionB("缅因库");
        details.setDescriptionC("Maine Coon");
        details.setDescriptionD("Мейн Кун");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" méi gōng hé duǎn wěi māo ");
        details.setDescriptionB("湄公河短尾猫");
        details.setDescriptionC(" Mekong Bobtail");
        details.setDescriptionD(" Меконгский бобтейл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("míng sī kè māo ");
        details.setDescriptionB("明斯克猫");
        details.setDescriptionC("Minskin ");
        details.setDescriptionD("Минскин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" màn qí kǎn māo/ mǎ ēn dǎo māo ");
        details.setDescriptionB("曼奇坎猫/ 马恩岛猫");
        details.setDescriptionC("Manx cat");
        details.setDescriptionD("Мэнкс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ná pò lún māo");
        details.setDescriptionB("拿破仑猫");
        details.setDescriptionC("Napoleon");
        details.setDescriptionD("Наполеон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dé guó juǎn máo māo ");
        details.setDescriptionB("德国卷毛猫");
        details.setDescriptionC(" German Rex ");
        details.setDescriptionD("Немецкий рекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nèi huá dá māo / ní bǐ lóng māo ");
        details.setDescriptionB("内华达猫 /尼比龙猫");
        details.setDescriptionC("Nebelung ");
        details.setDescriptionD("Нибелунг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nuó wēi sēn lín māo");
        details.setDescriptionB("挪威森林猫");
        details.setDescriptionC("Norwegian Forest Cat");
        details.setDescriptionD("Норвежская лесная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Neva Masquerade ");
        details.setDescriptionB("Невская маскарадная");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" é lēi gāng léi kè sī māo");
        details.setDescriptionB("俄勒冈雷克斯猫");
        details.setDescriptionC("Oregon Rex");
        details.setDescriptionD("Орегон-рекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dōng fāng cháng máo māo ");
        details.setDescriptionB("东方长毛猫");
        details.setDescriptionC(" Oriental Longhair ");
        details.setDescriptionD("Ориентальная длинношёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dōng fāng duǎn máo māo ");
        details.setDescriptionB("东方短毛猫");
        details.setDescriptionC(" Oriental Shorthair ");
        details.setDescriptionD("Ориентальная короткошёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ōu sī yà shǐ liè sī māo duǎn máo");
        details.setDescriptionB("欧斯亚史烈斯猫短毛 ");
        details.setDescriptionC(" Ojos Azules ");
        details.setDescriptionD("Охос Азулес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ōu xī māo");
        details.setDescriptionB("欧西猫");
        details.setDescriptionC("Ocicat");
        details.setDescriptionD("Оцикет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō sī māo");
        details.setDescriptionB("波斯猫");
        details.setDescriptionC("Persian cat");
        details.setDescriptionD("Персидская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ dé tū māo");
        details.setDescriptionB("彼得秃猫");
        details.setDescriptionC("Peterbald");
        details.setDescriptionD("Петерболд /Петербургский сфинкс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" běi měi zhōu duǎn máo māo ");
        details.setDescriptionB("北美洲短毛猫");
        details.setDescriptionC(" Pixiebob ");
        details.setDescriptionD("Пиксибоб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán lǚ māo ");
        details.setDescriptionB("褴褛猫");
        details.setDescriptionC(" Ragamuffin");
        details.setDescriptionD("Рагамаффин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù ǒu māo");
        details.setDescriptionB("布偶猫");
        details.setDescriptionC(" Ragdoll  cat");
        details.setDescriptionD("Рэгдолл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" é luó sī lán māo ");
        details.setDescriptionB("俄罗斯蓝猫");
        details.setDescriptionC(" Russian Blue ");
        details.setDescriptionD(" Русская голубая кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sà fán nà/ cǎoyuán māo ");
        details.setDescriptionB("萨凡娜/草原猫");
        details.setDescriptionC(" Savannah");
        details.setDescriptionD("Саванна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bó màn māo ");
        details.setDescriptionB("伯曼猫");
        details.setDescriptionC(" Sacred Birman");
        details.setDescriptionD("Священная бирманская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāi shé ěr māo duǎn máo");
        details.setDescriptionB("塞舌尔猫短毛");
        details.setDescriptionC("Seychellois  shorthair");
        details.setDescriptionD("Сейшельская короткошёрстная ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāi shé ěr māo cháng máo ");
        details.setDescriptionB("塞舌尔猫长毛");
        details.setDescriptionC("Seychellois longhair ");
        details.setDescriptionD("Сейшельская длинношёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài ěr kǎi kè juǎn máo māo duǎn máo ");
        details.setDescriptionB("塞尔凯克卷毛猫短毛");
        details.setDescriptionC("Selkirk Rex shorthair ");
        details.setDescriptionD("Селкирк рекс короткошёрстная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sài ěr kǎi kè juǎn máo māo ");
        details.setDescriptionB("塞尔凯克卷毛猫");
        details.setDescriptionC("Selkirk Rex longhair");
        details.setDescriptionD("Селкирк рекс длинношёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sāi lún gài dì māo ");
        details.setDescriptionB(" 塞伦盖蒂猫");
        details.setDescriptionC("Serengeti cat ");
        details.setDescriptionD("Серенгети");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiān luó māo");
        details.setDescriptionB("暹罗猫");
        details.setDescriptionC("Siamese cat");
        details.setDescriptionD("Сиамская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī bó lì yǎ māo ");
        details.setDescriptionB("西伯利亚猫");
        details.setDescriptionC(" Siberian cat");
        details.setDescriptionD("Сибирская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" Toybob(中文) ");
        details.setDescriptionB(" Toybob/ Skif-Thai-Don ");
        details.setDescriptionC(" Той-боб /Скиф-тай-дон");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīn jiā pō māo");
        details.setDescriptionB("新加坡猫");
        details.setDescriptionC("Singapura cat");
        details.setDescriptionD("Сингапурская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū gé lán zhé ěr māo ");
        details.setDescriptionB("苏格兰折耳猫");
        details.setDescriptionC("Scottish Fold ");
        details.setDescriptionD("  Скоттиш-фолд/ Шотландская вислоухая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū gé lán lì ěr māo ");
        details.setDescriptionB("苏格兰立耳猫");
        details.setDescriptionC(" Scottish Straight ");
        details.setDescriptionD("Скоттиш страйт /Шотландская прямоухая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě xié māo ");
        details.setDescriptionB("雪鞋猫");
        details.setDescriptionC(" Snowshoe ");
        details.setDescriptionD("Сноу-Шу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kěn ní yǎ māo ");
        details.setDescriptionB("肯尼亚猫");
        details.setDescriptionC("Sokoke");
        details.setDescriptionD("Сококе ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suǒ mǎ lǐ māo");
        details.setDescriptionB("索马里猫");
        details.setDescriptionC(" Somali  cat");
        details.setDescriptionD("Сомали");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("Jiā ná dà wú máo māo");
        details.setDescriptionB("加拿大无毛猫");
        details.setDescriptionC("Canadian Hairless cat");
        details.setDescriptionD(" Сфинкс канадский");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tài guó māo");
        details.setDescriptionB("泰国猫");
        details.setDescriptionC("Thai cat");
        details.setDescriptionD("Тайская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wán jù hǔmāo ");
        details.setDescriptionB("玩具虎猫");
        details.setDescriptionC("Toyger Cat");
        details.setDescriptionD("Тойгер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dōng qí ní māo ");
        details.setDescriptionB("东奇尼猫");
        details.setDescriptionC("Tonkinese саt");
        details.setDescriptionD("Тонкинская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǔ ěr qí ān gē lā māo ");
        details.setDescriptionB("土耳其安哥拉猫");
        details.setDescriptionC("Turkish Angora");
        details.setDescriptionD("Турецкая ангора");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǔ ěr qí fàn māo ");
        details.setDescriptionB("土耳其梵猫");
        details.setDescriptionC(" Turkish Van");
        details.setDescriptionD("Турецкий ван");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wū kè lán lēi fū kē yī māo");
        details.setDescriptionB("乌克兰勒夫科伊猫");
        details.setDescriptionC("Ukrainian Levkoy");
        details.setDescriptionD("Украинский левкой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wū lā ěr léi kè sī ");
        details.setDescriptionB("乌拉尔雷克斯");
        details.setDescriptionC(" Ural Rex ");
        details.setDescriptionD("Уральский рекс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yì guó duǎn máo bái māo");
        details.setDescriptionB("异国短毛白猫  ");
        details.setDescriptionC("Foreign White");
        details.setDescriptionD("Форин Вайт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gāo dì zhé ěr māo ");
        details.setDescriptionB("高地折耳猫");
        details.setDescriptionC("Highland Fold");
        details.setDescriptionD("Хайленд фолд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi zhōu shī zi māo ");
        details.setDescriptionB("非洲狮子猫");
        details.setDescriptionC("Chausie ");
        details.setDescriptionD("Хауси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī lán māo ");
        details.setDescriptionB("锡兰猫");
        details.setDescriptionC(" Ceylon cat");
        details.setDescriptionD("Цейлонская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi zú māo");
        details.setDescriptionB("黑足猫");
        details.setDescriptionC("Black-footed cat");
        details.setDescriptionD("Черноногая кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xià tè ěr māo/shā tè ěr māo");
        details.setDescriptionB("夏特尔猫/沙特尔猫");
        details.setDescriptionC("Chartreux");
        details.setDescriptionD("Шартрез");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dì fán ní māo ");
        details.setDescriptionB("蒂凡尼猫");
        details.setDescriptionC(" Chantilly-Tiffany ");
        details.setDescriptionD("Шантильи Тиффани");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yì guó duǎn máo māo ");
        details.setDescriptionB("异国短毛猫");
        details.setDescriptionC("Exotic Shorthair Cat");
        details.setDescriptionD("Экзотическая короткошёрстная кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǎo wā māo ");
        details.setDescriptionB("爪哇猫 ");
        details.setDescriptionC("Javanese ");
        details.setDescriptionD("Яванез /Яванская кошка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rì běn duǎn wěi māo");
        details.setDescriptionB("日本短尾猫");
        details.setDescriptionC("Japanese Bobtail");
        details.setDescriptionD("Японский бобтейл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhòng diǎn sè duǎn máo māo ");
        details.setDescriptionB("重点色短毛猫");
        details.setDescriptionC("Colorpoint Shorthair ");
        details.setDescriptionD(" Колорпойнт короткошёрстный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhá bēi bō sī māo ");
        details.setDescriptionB("茶杯波斯猫");
        details.setDescriptionC("Teacup Persian cat");
        details.setDescriptionD("Персидский котенок ");
        detailsList.add(details);
    }
}
