package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C56 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("huàn zhě/bìng rén");
        details.setDescriptionB("患者/病人");
        details.setDescriptionC("Patient");
        details.setDescriptionD("Пациент/Больной");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hù shì");
        details.setDescriptionB("护士");
        details.setDescriptionC("Nurse");
        details.setDescriptionD("Медсестра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yī shēng");
        details.setDescriptionB("医生");
        details.setDescriptionC("Doctor");
        details.setDescriptionD("Доктор/Врач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǒ xū yào kàn yī shēng");
        details.setDescriptionB("我需要看医生");
        details.setDescriptionC("I need to see a doctor");
        details.setDescriptionD("Мне нужен врач");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhè er tòng ");
        details.setDescriptionB("这儿痛");
        details.setDescriptionC("It hurts here");
        details.setDescriptionD("Здесь больно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hòu zhěn shì ");
        details.setDescriptionB("候诊室");
        details.setDescriptionC("Waiting room");
        details.setDescriptionD("Зал ожидания");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuè yā ");
        details.setDescriptionB("血压");
        details.setDescriptionC("Blood pressure ");
        details.setDescriptionD("Кровяное давление");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tīng zhěn qì");
        details.setDescriptionB("听诊器");
        details.setDescriptionC("Stethoscope");
        details.setDescriptionD("Стетоскоп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēn gāo chǐ/shēn gāo jì ");
        details.setDescriptionB("身高尺/身高计");
        details.setDescriptionC("Height bar ");
        details.setDescriptionD("Ростомер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ zhòng jì");
        details.setDescriptionB("体重计");
        details.setDescriptionC("Scales");
        details.setDescriptionD("Весы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ wēn jì");
        details.setDescriptionB("体温计");
        details.setDescriptionC("Thermometer");
        details.setDescriptionD("Градусник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiē zhǒng");
        details.setDescriptionB("接种");
        details.setDescriptionC("Inoculation/ Vaccinate ");
        details.setDescriptionD("Делать прививку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǐ jiǎn");
        details.setDescriptionB("体检");
        details.setDescriptionC("Medical examination");
        details.setDescriptionD("Медицинский осмотр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chǔ fāng/ yào fāng ");
        details.setDescriptionB("处方/药方");
        details.setDescriptionC("Prescription ");
        details.setDescriptionD("Рецепт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guò mǐn");
        details.setDescriptionB("过敏");
        details.setDescriptionC("Allergy");
        details.setDescriptionD("Аллергия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bìng dú");
        details.setDescriptionB("病毒");
        details.setDescriptionC("Virus");
        details.setDescriptionD("Вирус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn rǎn");
        details.setDescriptionB("感染");
        details.setDescriptionC("Infection");
        details.setDescriptionD("Инфекция");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fā shāo ");
        details.setDescriptionB("发烧");
        details.setDescriptionC("Fever");
        details.setDescriptionD("Жар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóu tòng");
        details.setDescriptionB("头痛");
        details.setDescriptionC("Headache");
        details.setDescriptionD("Головная боль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèi tòng");
        details.setDescriptionB("胃痛");
        details.setDescriptionC("Stomach ache");
        details.setDescriptionD("Боль в желудке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bí xiě");
        details.setDescriptionB("鼻血");
        details.setDescriptionC("Nosebleed ");
        details.setDescriptionD("Носовое кровотечение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ké sòu");
        details.setDescriptionB("咳嗽");
        details.setDescriptionC("Cough");
        details.setDescriptionD("Кашель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pēn tì");
        details.setDescriptionB("喷嚏");
        details.setDescriptionC("Sneeze ");
        details.setDescriptionD("Чихать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǎn mào");
        details.setDescriptionB("感冒");
        details.setDescriptionC("Cold");
        details.setDescriptionD("Простуда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liú gǎn");
        details.setDescriptionB("流感");
        details.setDescriptionC("Flu ");
        details.setDescriptionD("Грипп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāo chuǎn");
        details.setDescriptionB("哮喘");
        details.setDescriptionC("Asthma");
        details.setDescriptionD("Астма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhōu jīn");
        details.setDescriptionB("抽筋");
        details.setDescriptionC("Cramp ");
        details.setDescriptionD("Судорога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ě xīn");
        details.setDescriptionB("恶心");
        details.setDescriptionC("Nausea");
        details.setDescriptionD("Тошнота");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ dòu");
        details.setDescriptionB("水痘");
        details.setDescriptionC("Chickenpox");
        details.setDescriptionD("Ветряная оспа/Ветрянка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pí zhěn");
        details.setDescriptionB("皮疹");
        details.setDescriptionC("Rash");
        details.setDescriptionD("Сыпь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi yào");
        details.setDescriptionB("开药");
        details.setDescriptionC("Prescribe medicine");
        details.setDescriptionD("Выписать лекарство");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táng niào bìng");
        details.setDescriptionB("糖尿病");
        details.setDescriptionC("Diabetes");
        details.setDescriptionD("Диабет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shī zhěn");
        details.setDescriptionB("湿疹");
        details.setDescriptionC("Eczema");
        details.setDescriptionD("Экзема");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ǒu tù");
        details.setDescriptionB("呕吐");
        details.setDescriptionC("Vomit");
        details.setDescriptionD("Рвота");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fù xiè");
        details.setDescriptionB("腹泻");
        details.setDescriptionC("Diarrhoea");
        details.setDescriptionD("Диарея/Понос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diān xián");
        details.setDescriptionB("癫痫");
        details.setDescriptionC("Epilepsy");
        details.setDescriptionD("Эпилепсия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("má zhěn");
        details.setDescriptionB("麻疹");
        details.setDescriptionC("Measles");
        details.setDescriptionD("Корь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīn zàng bìng fā zuò");
        details.setDescriptionB("心脏病发作");
        details.setDescriptionC("Heart attack");
        details.setDescriptionD("Сердечный приступ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hūn jué");
        details.setDescriptionB("昏厥");
        details.setDescriptionC("Faint");
        details.setDescriptionD("Обморок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" piān tóu tòng");
        details.setDescriptionB("偏头痛");
        details.setDescriptionC("Migraine");
        details.setDescriptionD("Мигрень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sāi xiàn yán");
        details.setDescriptionB("腮腺炎");
        details.setDescriptionC("Mumps");
        details.setDescriptionD("Свинка");
        detailsList.add(details);
    }
}
