package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C57 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("cái féng diàn");
        details.setDescriptionB("裁缝店");
        details.setDescriptionC("Tailor shop");
        details.setDescriptionD("Ателье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn bāo diàn ");
        details.setDescriptionB("面包店");
        details.setDescriptionC("Baker’s ");
        details.setDescriptionD("Булочная ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dàn gāo diàn");
        details.setDescriptionB("蛋糕店");
        details.setDescriptionC("Cake shop");
        details.setDescriptionD("Кондитерская");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi fà tīng");
        details.setDescriptionB("美发厅");
        details.setDescriptionC("Hairdresser’s");
        details.setDescriptionD("Парикмахерская");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ròu pù");
        details.setDescriptionB("肉铺");
        details.setDescriptionC(" Butcher shop ");
        details.setDescriptionD("Мясной магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yú pù");
        details.setDescriptionB("鱼铺");
        details.setDescriptionC("Fish shop");
        details.setDescriptionD("Рыбный магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū cài shuǐ guǒ diàn ");
        details.setDescriptionB("蔬菜水果店");
        details.setDescriptionC("Greengrocer’s");
        details.setDescriptionD("Магазин овощей и фруктов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuán yì diàn");
        details.setDescriptionB("园艺店");
        details.setDescriptionC("Garden shop");
        details.setDescriptionD("Садовый магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chǒng wù shāng diàn");
        details.setDescriptionB("宠物商店");
        details.setDescriptionC("Pet shop");
        details.setDescriptionD("Зоомагазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xié diàn");
        details.setDescriptionB("鞋店");
        details.setDescriptionC("Shoe shop");
        details.setDescriptionD("Магазин обуви");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǔ jīn diàn");
        details.setDescriptionB("五金店");
        details.setDescriptionC("Hardware shop");
        details.setDescriptionD("Магазин хозяйственных товаров");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǐ pǐn diàn");
        details.setDescriptionB("礼品店");
        details.setDescriptionC("Gift shop");
        details.setDescriptionD("Магазин подарков");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā jù diàn");
        details.setDescriptionB("家具店");
        details.setDescriptionC("Furniture shop");
        details.setDescriptionD("Магазин мебели");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuè qì diàn ");
        details.setDescriptionB("乐器店");
        details.setDescriptionC(" Musical instrument store ");
        details.setDescriptionD("Магазин музыкальных инструментов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǔ dǒng diàn");
        details.setDescriptionB("古董店");
        details.setDescriptionC("Antiques shop");
        details.setDescriptionD("Антикварный магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu shì diàn");
        details.setDescriptionB("首饰店");
        details.setDescriptionC("Jewellery shop");
        details.setDescriptionD("Ювелирный магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū diàn");
        details.setDescriptionB("书店");
        details.setDescriptionC("Book shop");
        details.setDescriptionD("Книжный магазин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì shù pǐn shāng diàn");
        details.setDescriptionB("艺术品商店");
        details.setDescriptionC("Art shop");
        details.setDescriptionD("Художественный салон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí pǐn zá huò diàn");
        details.setDescriptionB("食品杂货店");
        details.setDescriptionC("Grocer’s ");
        details.setDescriptionD("Бакалейная лавка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí zhuāng diàn");
        details.setDescriptionB("时装店");
        details.setDescriptionC("Boutique");
        details.setDescriptionD("Бутик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gān xǐ diàn");
        details.setDescriptionB("干洗店");
        details.setDescriptionC("Dry cleaner’s");
        details.setDescriptionD("Химчистка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ xíng shè");
        details.setDescriptionB("旅行社");
        details.setDescriptionC("Travel agency");
        details.setDescriptionD("Туристическое агенство");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng chǎn zhōng jiè ");
        details.setDescriptionB("房产中介");
        details.setDescriptionC("Estate agency");
        details.setDescriptionD("Агентство недвижимости");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("èr shǒu huò shāng diàn");
        details.setDescriptionB("二手货商店");
        details.setDescriptionC("Second-hand shop");
        details.setDescriptionD("Секонд-хенд");
        detailsList.add(details);
    }
}
