package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C61 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("wèi shēng jiān");
        details.setDescriptionB("卫生间");
        details.setDescriptionC("Toilet");
        details.setDescriptionD("Туалет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ shǒu chí");
        details.setDescriptionB("洗手池");
        details.setDescriptionC("Washbasin");
        details.setDescriptionD("Раковина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù gāng");
        details.setDescriptionB("浴缸");
        details.setDescriptionC("Bathtub");
        details.setDescriptionD("Ванна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ zǎo");
        details.setDescriptionB("洗澡");
        details.setDescriptionC("Take a bath");
        details.setDescriptionD("Принимать ванну");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín yù  ");
        details.setDescriptionB("淋浴");
        details.setDescriptionC("Shower");
        details.setDescriptionD("Душ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ lín yù");
        details.setDescriptionB("洗淋浴");
        details.setDescriptionC("Take a shower");
        details.setDescriptionD("Принять душ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lín yù mén");
        details.setDescriptionB("淋浴门");
        details.setDescriptionC("Shower door");
        details.setDescriptionD("Душевая дверь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lín yù pēn tóu ");
        details.setDescriptionB("淋浴喷头");
        details.setDescriptionC("Shower head");
        details.setDescriptionD("Насадка для душа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pái shuǐ guǎn");
        details.setDescriptionB("排水管");
        details.setDescriptionC("Drain");
        details.setDescriptionD("Слив/Водосток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lěng shuǐ lóng tóu");
        details.setDescriptionB("冷水龙头");
        details.setDescriptionC("Cold tap");
        details.setDescriptionD(" Кран для холодной воды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rè shuǐ lóng tóu ");
        details.setDescriptionB("热水龙头");
        details.setDescriptionC("Hot tap");
        details.setDescriptionD(" Кран для горячей воды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo jīn jià");
        details.setDescriptionB("毛巾架");
        details.setDescriptionC("Towel rail");
        details.setDescriptionD("Вешалка для полотенца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn rè máo jīn jià");
        details.setDescriptionB("电热毛巾架");
        details.setDescriptionC("Heated towel rail");
        details.setDescriptionD("Полотенцесушитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" máo jīn ");
        details.setDescriptionB("毛巾");
        details.setDescriptionC("Towel");
        details.setDescriptionD("Полотенце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu jīn");
        details.setDescriptionB("手巾");
        details.setDescriptionC("Hand towel");
        details.setDescriptionD("Полотенце для рук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yù jīn ");
        details.setDescriptionB("浴巾 ");
        details.setDescriptionC("Bath towel");
        details.setDescriptionD("Полотенце для душа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù yī/yù páo");
        details.setDescriptionB("浴衣/浴袍");
        details.setDescriptionC("Bathrobe");
        details.setDescriptionD("Халат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" féi zào ");
        details.setDescriptionB("肥皂");
        details.setDescriptionC("Soap");
        details.setDescriptionD("Мыло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("féi zào hé ");
        details.setDescriptionB("肥皂盒");
        details.setDescriptionC("Soap dish");
        details.setDescriptionD(" Мыльница ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi mián");
        details.setDescriptionB("海绵");
        details.setDescriptionC("Sponge");
        details.setDescriptionD("Губка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bèi shuā");
        details.setDescriptionB("背刷");
        details.setDescriptionC("Back brush");
        details.setDescriptionD("Банная щётка для спины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fú shí");
        details.setDescriptionB("浮石");
        details.setDescriptionC("Pumice stone");
        details.setDescriptionD("Пемза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pào mò yù yè");
        details.setDescriptionB("泡沫浴液");
        details.setDescriptionC("Bubble bath");
        details.setDescriptionD("Пена для ванны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù yù rǔ");
        details.setDescriptionB("沐浴乳");
        details.setDescriptionC("Shower gel");
        details.setDescriptionD("Гель для душа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rùn fū lù ");
        details.setDescriptionB("润肤露");
        details.setDescriptionC("Body lotion");
        details.setDescriptionD("Лосьон для тела");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("爽身粉");
        details.setDescriptionB(" shuǎng shēn fěn ");
        details.setDescriptionC("Talcum powder");
        details.setDescriptionD("Тальк для тела");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chú chòu jì");
        details.setDescriptionB("除臭剂");
        details.setDescriptionC("Deodorant");
        details.setDescriptionD("Дезодорант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn dòng tì xū dāo");
        details.setDescriptionB("电动剃须刀");
        details.setDescriptionC("Electric razor");
        details.setDescriptionD("Электробритва");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yá gāo");
        details.setDescriptionB("牙膏");
        details.setDescriptionC("Toothpaste");
        details.setDescriptionD("Зубная паста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yá shuā");
        details.setDescriptionB("牙刷");
        details.setDescriptionC("Toothbrush");
        details.setDescriptionD("Зубная щётка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shù kǒu yè ");
        details.setDescriptionB("漱口液");
        details.setDescriptionC("Mouthwash");
        details.setDescriptionD(" Зубной эликсир ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yá xiàn");
        details.setDescriptionB("牙线");
        details.setDescriptionC("Dental floss");
        details.setDescriptionD("Зубная нить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" miàn shuāng ");
        details.setDescriptionB("面霜");
        details.setDescriptionC("Face cream");
        details.setDescriptionD("Крем для лица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tǒng ");
        details.setDescriptionB("马桶");
        details.setDescriptionC("Toilet");
        details.setDescriptionD("Унитаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuò yù pén ");
        details.setDescriptionB("坐浴盆");
        details.setDescriptionC("Bidet");
        details.setDescriptionD("Биде");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tǒng zuò");
        details.setDescriptionB("马桶座");
        details.setDescriptionC("Toilet seat");
        details.setDescriptionD("Сиденье для унитаза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ tǒng shuā");
        details.setDescriptionB("马桶刷");
        details.setDescriptionC("Toilet brush");
        details.setDescriptionD("Щетка для унитаза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèi shēng zhǐ");
        details.setDescriptionB("卫生纸");
        details.setDescriptionC("Toilet roll");
        details.setDescriptionD("Туалетная бумага");
        detailsList.add(details);
    }
}
