package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C73 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("dà xué");
        details.setDescriptionB("大学");
        details.setDescriptionC(" University ");
        details.setDescriptionD("Университет/ ВУЗ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xué yuàn");
        details.setDescriptionB(" 学院");
        details.setDescriptionC("Institute ");
        details.setDescriptionD("Институт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xué yuàn");
        details.setDescriptionB(" 学院");
        details.setDescriptionC("Academy ");
        details.setDescriptionD("Академия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sù shè");
        details.setDescriptionB("宿舍");
        details.setDescriptionC(" Dormitory ");
        details.setDescriptionD("Общежитие");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tú shū guǎn");
        details.setDescriptionB("图书馆");
        details.setDescriptionC("Library");
        details.setDescriptionD("Библиотека");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuè dú shì");
        details.setDescriptionB("阅读室");
        details.setDescriptionC("Reading room");
        details.setDescriptionD("Читальный зал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí táng");
        details.setDescriptionB("食堂");
        details.setDescriptionC("Dining hall/ Canteen ");
        details.setDescriptionD("Столовая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎng táng");
        details.setDescriptionB("讲堂");
        details.setDescriptionC(" Lecture hall ");
        details.setDescriptionD(" Лекционный зал/ Аудитория");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí yàn shì");
        details.setDescriptionB("实验室");
        details.setDescriptionC(" Laboratory ");
        details.setDescriptionD(" Лаборатория");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bān");
        details.setDescriptionB("班");
        details.setDescriptionC(" Class ");
        details.setDescriptionD("Группа/ Класс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎng kè");
        details.setDescriptionB("讲课 ");
        details.setDescriptionC(" Lecture/ Give a lesson ");
        details.setDescriptionD("Преподавать/Читать лекции");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bì yè");
        details.setDescriptionB("毕业");
        details.setDescriptionC(" Graduate");
        details.setDescriptionD("Закончить курс/ Окончить учебное заведение");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bì yè shēng");
        details.setDescriptionB("毕业生");
        details.setDescriptionC("the graduate ");
        details.setDescriptionD("Выпускник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bì yè zhèng");
        details.setDescriptionB("毕业证 ");
        details.setDescriptionC(" Graduation certificate ");
        details.setDescriptionD("Диплом об окончании учебного заведения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǎo shī ");
        details.setDescriptionB("老师");
        details.setDescriptionC(" Teacher ");
        details.setDescriptionD("Учитель/ Преподаватель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān zhǔ rèn ");
        details.setDescriptionB("班主任");
        details.setDescriptionC(" Class teacher");
        details.setDescriptionD("Классный учитель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān zhí jiào shī");
        details.setDescriptionB("兼职教师");
        details.setDescriptionC(" Part-time teacher ");
        details.setDescriptionD("Учитель по совместительству");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā jiào");
        details.setDescriptionB("家教");
        details.setDescriptionC(" Tutor ");
        details.setDescriptionD("Репетитор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóng xué ");
        details.setDescriptionB("同学");
        details.setDescriptionC(" Classmate ");
        details.setDescriptionD("Одноклассник/Одногруппник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xué shēng");
        details.setDescriptionB("大学生");
        details.setDescriptionC("Student ");
        details.setDescriptionD("Студент");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎng xué jīn");
        details.setDescriptionB("奖学金");
        details.setDescriptionC(" Scholarship ");
        details.setDescriptionD(" Стипендия");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xué wèi lùn wén ");
        details.setDescriptionB("学位论文");
        details.setDescriptionC(" Dissertation");
        details.setDescriptionD("Диссертация");
        detailsList.add(details);
    }
}
