package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C74 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("rù kǒu");
        details.setDescriptionB("入口");
        details.setDescriptionC("Entrance");
        details.setDescriptionD("Вход");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gòu wù chē ");
        details.setDescriptionB("购物车");
        details.setDescriptionC(" Shopping cart");
        details.setDescriptionD("Тележка для покупок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gòu wù lán ");
        details.setDescriptionB("购物篮");
        details.setDescriptionC(" Shopping basket ");
        details.setDescriptionD("Корзина (для покупок)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ dài ");
        details.setDescriptionB("纸袋");
        details.setDescriptionC(" Paper bag ");
        details.setDescriptionD("Пакет бумажный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dài zi");
        details.setDescriptionB("袋子");
        details.setDescriptionC("Packet");
        details.setDescriptionD("Пакет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ròu lèi hé jiā qín lèi");
        details.setDescriptionB("肉类和家禽类");
        details.setDescriptionC(" Meat and poultry ");
        details.setDescriptionD("Мясо и птица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi xiān");
        details.setDescriptionB("海鲜");
        details.setDescriptionC("Seafood");
        details.setDescriptionD("Морепродукты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rǔ zhì pǐn");
        details.setDescriptionB("乳制品");
        details.setDescriptionC("Milk products");
        details.setDescriptionD("Молочные продукты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shū cài hé shuǐ guǒ");
        details.setDescriptionB("蔬菜和水果");
        details.setDescriptionC("Vegetables and fruits");
        details.setDescriptionD("Овощи и фрукты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo chī");
        details.setDescriptionB("小吃");
        details.setDescriptionC("Snacks");
        details.setDescriptionD("Закуски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guàn tóu shí pǐn");
        details.setDescriptionB("罐头食品");
        details.setDescriptionC("Canned food");
        details.setDescriptionD("Консервы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǔ lèi yǐn pǐn");
        details.setDescriptionB("酒类饮品");
        details.setDescriptionC("Alcoholic drinks");
        details.setDescriptionD("Алкогольные напитки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǐn liào ");
        details.setDescriptionB("饮料");
        details.setDescriptionC("Drinks");
        details.setDescriptionD("Напитки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jū jiā yòng pǐn");
        details.setDescriptionB("居家用品");
        details.setDescriptionC("Household goods");
        details.setDescriptionD("Хозяйственные товары");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lěng dòng shí pǐn");
        details.setDescriptionB("冷冻食品");
        details.setDescriptionC("Frozen foods");
        details.setDescriptionD("Замороженные пищевые продукты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuǎn gòu");
        details.setDescriptionB("选购");
        details.setDescriptionC("To choose");
        details.setDescriptionD("Выбирать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huò wù jiāo huàn");
        details.setDescriptionB("货物交换");
        details.setDescriptionC("Exchange of goods ");
        details.setDescriptionD("Обмен товара");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuì huò ");
        details.setDescriptionB("退货");
        details.setDescriptionC("Return of goods");
        details.setDescriptionD("Возвратить товар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ xiǎng tuì huò");
        details.setDescriptionB("我想退货");
        details.setDescriptionC("I would like to return the goods");
        details.setDescriptionD("Я хотел бы вернуть товар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎn jià");
        details.setDescriptionB("减价");
        details.setDescriptionC("Sell-out");
        details.setDescriptionD("Распродажа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duō shǎo qián ");
        details.setDescriptionB("多少钱?");
        details.setDescriptionC(" How much is it?");
        details.setDescriptionD("Сколько это стоит?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hěn guì");
        details.setDescriptionB("很贵!");
        details.setDescriptionC("It is very expensive");
        details.setDescriptionD("Это очень дорого");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pián yí");
        details.setDescriptionB("便宜");
        details.setDescriptionC(" Cheap ");
        details.setDescriptionD("Дешёвый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shōu yín tái");
        details.setDescriptionB("收银台");
        details.setDescriptionC("Cash desk");
        details.setDescriptionD("Касса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nín yòng xiàn jīn hái shì xìn yòng kǎ fù kuǎn");
        details.setDescriptionB("您用现金还是信用卡付款？");
        details.setDescriptionC("Will you pay in cash or by credit card?");
        details.setDescriptionD("Вы будете платить наличными или кредитной картой?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xìn yòng kǎ");
        details.setDescriptionB(" 信用卡");
        details.setDescriptionC(" Credit card ");
        details.setDescriptionD("Кредитная карта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn jīn");
        details.setDescriptionB("现金");
        details.setDescriptionC("Cash");
        details.setDescriptionD("Наличные");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ná shōu jù ");
        details.setDescriptionB("拿收据");
        details.setDescriptionC("Take a check");
        details.setDescriptionD("Взять чек");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǎo qián");
        details.setDescriptionB("找钱");
        details.setDescriptionC("Take the change");
        details.setDescriptionD("Взять сдачу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi xiān qū zài nǎ er ");
        details.setDescriptionB("海鲜区在哪儿？");
        details.setDescriptionC(" Where is the seafood area here ?");
        details.setDescriptionD("Где здесь отдел морепродуктов?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ròu lèi shí pǐn qū zài nǎ er ");
        details.setDescriptionB("肉类食品区在哪儿？");
        details.setDescriptionC(" Where is the meat area here ?");
        details.setDescriptionD("Где здесь мясной отдел?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zài nà biān");
        details.setDescriptionB("在那边");
        details.setDescriptionC("There");
        details.setDescriptionD("Вон там");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chū kǒu");
        details.setDescriptionB("出口");
        details.setDescriptionC("Exit");
        details.setDescriptionD("Выход");
        detailsList.add(details);
    }
}
