package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C75 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("mǎ kè bēi");
        details.setDescriptionB("马克杯");
        details.setDescriptionC("Mug");
        details.setDescriptionD("Кружка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhá bēi");
        details.setDescriptionB("茶杯");
        details.setDescriptionC("Teacup");
        details.setDescriptionD("Чайная кружка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō lí bēi");
        details.setDescriptionB("玻璃杯");
        details.setDescriptionC("Glass");
        details.setDescriptionD("Стакан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kuài zi");
        details.setDescriptionB("筷子");
        details.setDescriptionC("Сhopsticks");
        details.setDescriptionD("Палочки для еды");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chā zi");
        details.setDescriptionB("叉子");
        details.setDescriptionC("Fork");
        details.setDescriptionD("Вилка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yú chā");
        details.setDescriptionB("鱼叉");
        details.setDescriptionC("Fish fork");
        details.setDescriptionD("Рыбная вилка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sháo zi ");
        details.setDescriptionB("勺子");
        details.setDescriptionC("Spoon");
        details.setDescriptionD("Ложка (столовая)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiē cài bǎn");
        details.setDescriptionB("切菜板");
        details.setDescriptionC("Chopping board");
        details.setDescriptionD("Разделочная доска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō pán");
        details.setDescriptionB("托盘");
        details.setDescriptionC("Tray");
        details.setDescriptionD("Поднос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guō gài ");
        details.setDescriptionB("锅盖");
        details.setDescriptionC("Lid");
        details.setDescriptionD("Крышка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tāng guō ");
        details.setDescriptionB("汤锅");
        details.setDescriptionC("Pot");
        details.setDescriptionD("Кастрюля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("píng dǐ guō");
        details.setDescriptionB("平底锅");
        details.setDescriptionC(" Saucepan");
        details.setDescriptionD("Сотейник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo yā guō");
        details.setDescriptionB("高压锅");
        details.setDescriptionC("Pressure cooker");
        details.setDescriptionD("Скороварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǔ guō");
        details.setDescriptionB("煮锅");
        details.setDescriptionC("Cooking pot ");
        details.setDescriptionD("Котелок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhǎo guō");
        details.setDescriptionB("炒锅");
        details.setDescriptionC("Wok");
        details.setDescriptionD("Вок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎo jià pán ");
        details.setDescriptionB("烤架盘");
        details.setDescriptionC("Grill pan ");
        details.setDescriptionD("Сковорода-гриль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān guō");
        details.setDescriptionB("煎锅");
        details.setDescriptionC("Frying pan");
        details.setDescriptionD("Сковорода");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guō bǎ");
        details.setDescriptionB("锅把");
        details.setDescriptionC(" Pan handle ");
        details.setDescriptionD("Ручка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàng sháo ");
        details.setDescriptionB("酱勺");
        details.setDescriptionC(" Sauce spoon ");
        details.setDescriptionD("Соусная ложка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tāng sháo/cháng bǐng sháo ");
        details.setDescriptionB("汤勺/长柄勺");
        details.setDescriptionC("Ladle");
        details.setDescriptionD("Половник/Черпак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guō chǎn");
        details.setDescriptionB("锅铲");
        details.setDescriptionC(" Spatula ");
        details.setDescriptionD("Лопатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" guā chǎn ");
        details.setDescriptionB("刮铲");
        details.setDescriptionC(" Spatula ");
        details.setDescriptionD(" Силиконовая лопатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dàn gāo chǎn");
        details.setDescriptionB("蛋糕铲");
        details.setDescriptionC(" Cake scoop ");
        details.setDescriptionD("Лопатка для торта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lòu sháo");
        details.setDescriptionB("漏勺");
        details.setDescriptionC("Сolander");
        details.setDescriptionD("Дуршлаг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎn");
        details.setDescriptionB("碗");
        details.setDescriptionC("Bowl");
        details.setDescriptionD("Пиала");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pán zi ");
        details.setDescriptionB("盘子");
        details.setDescriptionC("Plate");
        details.setDescriptionD("Тарелка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dāo ");
        details.setDescriptionB("刀");
        details.setDescriptionC("Knife");
        details.setDescriptionD("Нож");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng yóu dāo");
        details.setDescriptionB("黄油刀");
        details.setDescriptionC("Butter knife");
        details.setDescriptionD("Нож для масла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("miàn bāo dāo");
        details.setDescriptionB("面包刀");
        details.setDescriptionC("Bread knife");
        details.setDescriptionD("Нож для хлеба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú pái dāo");
        details.setDescriptionB("牛排刀");
        details.setDescriptionC("Steak knife");
        details.setDescriptionD("Нож для стейка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiē ròu dāo ");
        details.setDescriptionB("切肉刀");
        details.setDescriptionC(" Cleaver ");
        details.setDescriptionD("Разделочный нож");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("táo cí dāo");
        details.setDescriptionB("陶瓷刀");
        details.setDescriptionC("Ceramic knife");
        details.setDescriptionD("Керамический нож");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi guàn qì");
        details.setDescriptionB("开罐器");
        details.setDescriptionC("Can opener");
        details.setDescriptionD("Консервный нож");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāo pí dāo ");
        details.setDescriptionB("削皮刀");
        details.setDescriptionC("Peeler");
        details.setDescriptionD("Нож для чистки картофеля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mó dāo qì");
        details.setDescriptionB("磨刀器");
        details.setDescriptionC("Knife sharpener");
        details.setDescriptionD("Точилка для ножа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi píng qì");
        details.setDescriptionB("开瓶器");
        details.setDescriptionC("Bottle opener");
        details.setDescriptionD("Открывалка для бутылок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi píng qì");
        details.setDescriptionB("开瓶器");
        details.setDescriptionC("Сorkscrew");
        details.setDescriptionD("Штопор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǜ chá qì");
        details.setDescriptionB("滤茶器");
        details.setDescriptionC("Tea strainer");
        details.setDescriptionD("Чайное ситечко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chá chí");
        details.setDescriptionB("茶匙");
        details.setDescriptionC("Tea spoon");
        details.setDescriptionD("Чайная ложка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mù sháo");
        details.setDescriptionB("木勺");
        details.setDescriptionC("Wooden spoon");
        details.setDescriptionD("Деревянная ложка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gǎn miàn zhàng");
        details.setDescriptionB("擀面杖");
        details.setDescriptionC("Rolling pin");
        details.setDescriptionD("Скалка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎo ní qì");
        details.setDescriptionB("捣泥器");
        details.setDescriptionC("Masher");
        details.setDescriptionD("Толкушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chuàn ròu qiān ");
        details.setDescriptionB("串肉扦");
        details.setDescriptionC("Skewer");
        details.setDescriptionD("Шампур");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  lòu sháo ");
        details.setDescriptionB("漏勺");
        details.setDescriptionC("Slotted spoon");
        details.setDescriptionD("Шумовка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǜ wǎng");
        details.setDescriptionB("滤网");
        details.setDescriptionC("Sieve");
        details.setDescriptionD("Сито");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhú fáng qián ");
        details.setDescriptionB("厨房钳");
        details.setDescriptionC(" Kitchen tongs ");
        details.setDescriptionD(" Кухонные щипцы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiān guǒ qián");
        details.setDescriptionB("坚果钳");
        details.setDescriptionC("Nutcracker");
        details.setDescriptionD("Щипцы для орехов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chú fáng jiǎn dāo");
        details.setDescriptionB("厨房剪刀");
        details.setDescriptionC("Kitchen scissors");
        details.setDescriptionD("Кухонные ножницы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhú chèng");
        details.setDescriptionB("厨秤");
        details.setDescriptionC("Kitchen scales");
        details.setDescriptionD("Кухонные весы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biǎo huā qì");
        details.setDescriptionB("裱花器");
        details.setDescriptionC(" Pastry bag ");
        details.setDescriptionD("Кондитерский шприц ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biǎo huā dài");
        details.setDescriptionB("裱花袋");
        details.setDescriptionC(" Piping bag ");
        details.setDescriptionD("Кондитерский мешок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dǎ dàn qì ");
        details.setDescriptionB("打蛋器");
        details.setDescriptionC("Whisk");
        details.setDescriptionD("Венчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiè dàn qì ");
        details.setDescriptionB("切蛋器");
        details.setDescriptionC(" Egg cutter ");
        details.setDescriptionD("Яйцерезка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chā cài bǎn ");
        details.setDescriptionB("插菜板");
        details.setDescriptionC("Grater");
        details.setDescriptionD("Тёрка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā suàn qì");
        details.setDescriptionB("压蒜器");
        details.setDescriptionC("Garlic press ");
        details.setDescriptionD(" Пресс для чеснока / Чесночница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ròu chuí");
        details.setDescriptionB("肉锤");
        details.setDescriptionC("Meat hammer");
        details.setDescriptionD("Молоток для отбивания мяса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàn bǐng kǎo mó");
        details.setDescriptionB("馅饼烤模");
        details.setDescriptionC(" Pie mold ");
        details.setDescriptionD("Форма для пирога");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dàn gāo mó");
        details.setDescriptionB("蛋糕模");
        details.setDescriptionC(" Cake mold ");
        details.setDescriptionD("Форма для торта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sōng bǐng kǎo pán");
        details.setDescriptionB("松饼烤盘");
        details.setDescriptionC("Muffin tray");
        details.setDescriptionD("Форма для кексов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo pán");
        details.setDescriptionB("烤盘");
        details.setDescriptionC("Baking tray");
        details.setDescriptionD("Противень");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ  hú");
        details.setDescriptionB("水壶");
        details.setDescriptionC("Kettle");
        details.setDescriptionD("Чайник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lěng què jià");
        details.setDescriptionB("冷却架");
        details.setDescriptionC("Cooling rack ");
        details.setDescriptionD("Охладительная решетка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hù shǒu diàn");
        details.setDescriptionB("护手垫");
        details.setDescriptionC("Potholder");
        details.setDescriptionD("Прихватка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo xiāng shǒu tào");
        details.setDescriptionB("烤箱手套");
        details.setDescriptionC("Oven glove");
        details.setDescriptionD("Кухонная рукавица");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi qún");
        details.setDescriptionB("围裙");
        details.setDescriptionC("Apron");
        details.setDescriptionD("Фартук");
        detailsList.add(details);
    }
}
