package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C84 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("yīng ér ");
        details.setDescriptionB("婴儿");
        details.setDescriptionC("Baby");
        details.setDescriptionD(" Младенец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér tóng ");
        details.setDescriptionB("儿童");
        details.setDescriptionC("Child");
        details.setDescriptionD(" Ребёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bèi xīn");
        details.setDescriptionB("背心");
        details.setDescriptionC("Vest");
        details.setDescriptionD("Майка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér lián jiǎo yī");
        details.setDescriptionB("婴儿连脚衣");
        details.setDescriptionC("Bodysuit");
        details.setDescriptionD("Ясельный комбинезон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér shuì yī");
        details.setDescriptionB("婴儿睡衣");
        details.setDescriptionC("Baby sleepsuit");
        details.setDescriptionD("Пижама для младенца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lián shēn yī");
        details.setDescriptionB("连身衣");
        details.setDescriptionC("Romper suit");
        details.setDescriptionD("Ромпер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng gāo yāo kù");
        details.setDescriptionB("儿童高腰裤");
        details.setDescriptionC(" Сrawlers   ");
        details.setDescriptionD("Ползунки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér fáng xuě zhuāng");
        details.setDescriptionB("婴儿防雪装");
        details.setDescriptionC(" Wintersuit");
        details.setDescriptionD("Зимний комбинезон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi jīn");
        details.setDescriptionB("围巾");
        details.setDescriptionC("Scarf");
        details.setDescriptionD("Шарф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér shǒu tào");
        details.setDescriptionB("婴儿手套");
        details.setDescriptionC("Mittens");
        details.setDescriptionD("Варежки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǐ niào kù ");
        details.setDescriptionB("纸尿裤");
        details.setDescriptionC("Disposable nappy/Diaper");
        details.setDescriptionD("Одноразовый подгузник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bù niào kù ");
        details.setDescriptionB("布尿裤");
        details.setDescriptionC(" Reusable nappy/ Cloth Diaper ");
        details.setDescriptionD("Многоразовый подгузник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi  zuǐ");
        details.setDescriptionB("围嘴");
        details.setDescriptionC("Bib");
        details.setDescriptionD("Нагрудник/ Слюнявчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wéi dōu");
        details.setDescriptionB("围兜");
        details.setDescriptionC("Apron");
        details.setDescriptionD("Передник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("T xù shān");
        details.setDescriptionB("T恤衫");
        details.setDescriptionC("T-shirt");
        details.setDescriptionD("Футболка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn kù");
        details.setDescriptionB("短裤");
        details.setDescriptionC("Shorts");
        details.setDescriptionD("Шорты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chèn shān");
        details.setDescriptionB("衬衫");
        details.setDescriptionC("Blouse/Shirt");
        details.setDescriptionD("Блузка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qún zi");
        details.setDescriptionB("裙子");
        details.setDescriptionC("Skirt");
        details.setDescriptionD("Юбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǒng qún ");
        details.setDescriptionB("筒裙");
        details.setDescriptionC(" Straight skirt ");
        details.setDescriptionD("Прямая юбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qún kù");
        details.setDescriptionB("裙裤");
        details.setDescriptionC("Skirt leggings");
        details.setDescriptionD(" Леггинсы-юбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng lián yī qún ");
        details.setDescriptionB("儿童连衣裙");
        details.setDescriptionC("Baby dress");
        details.setDescriptionD("Детское платье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bēi dài kù");
        details.setDescriptionB("背带裤");
        details.setDescriptionC("Dungarees");
        details.setDescriptionD("Детский комбинезон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú zǎi kù");
        details.setDescriptionB("牛仔裤");
        details.setDescriptionC("Jeans");
        details.setDescriptionD("Джинсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zhuāng ");
        details.setDescriptionB("西装");
        details.setDescriptionC("Suit");
        details.setDescriptionD("Костюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kù zi");
        details.setDescriptionB("裤子");
        details.setDescriptionC("Trousers");
        details.setDescriptionD("Брюки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiū xián kù");
        details.setDescriptionB("休闲裤");
        details.setDescriptionC("Pants");
        details.setDescriptionD("Штаны");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" máo yī ");
        details.setDescriptionB("毛衣");
        details.setDescriptionC("Sweater");
        details.setDescriptionD("Свитер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ yī");
        details.setDescriptionB("雨衣");
        details.setDescriptionC("Raincoat");
        details.setDescriptionD("Плащ-дождевик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǔ róng fú ");
        details.setDescriptionB("羽绒服");
        details.setDescriptionC(" Padded coat ");
        details.setDescriptionD("Пуховик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú jiǎo kòu dà yī");
        details.setDescriptionB("牛角扣大衣");
        details.setDescriptionC("Duffle coat");
        details.setDescriptionD("Дафлкот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi shān");
        details.setDescriptionB("开衫");
        details.setDescriptionC("Cardigan");
        details.setDescriptionD("Кардиган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiā kè");
        details.setDescriptionB("夹克");
        details.setDescriptionC("Jacket");
        details.setDescriptionD("Жакет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zhuāng shàng yī");
        details.setDescriptionB("西装上衣");
        details.setDescriptionC("Suit jacket");
        details.setDescriptionD("Пиджак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng shān ");
        details.setDescriptionB("运动衫");
        details.setDescriptionC(" Sweatshirt ");
        details.setDescriptionD("Свитшот/Пайта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zú qiú qiú yī");
        details.setDescriptionB("足球球衣");
        details.setDescriptionC("Football strip");
        details.setDescriptionD("Футбольная форма");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn dòng zhuāng");
        details.setDescriptionB("运动装");
        details.setDescriptionC("Sports suit");
        details.setDescriptionD("Спотривный костюм");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ér tóng shuì yī");
        details.setDescriptionB("儿童睡衣");
        details.setDescriptionC("Children's pajamas");
        details.setDescriptionD("Детская пижама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuì yī ");
        details.setDescriptionB("睡衣");
        details.setDescriptionC("Nightie/Nightgown");
        details.setDescriptionD("Ночнушка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chén yī");
        details.setDescriptionB("晨衣");
        details.setDescriptionC("Bathrobe");
        details.setDescriptionD("Халат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jǐn shēn kù ");
        details.setDescriptionB("紧身裤");
        details.setDescriptionC("Leggings");
        details.setDescriptionD("Лосины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhē yáng mào  ");
        details.setDescriptionB("遮阳帽");
        details.setDescriptionC("Sun hat");
        details.setDescriptionD("Панама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yā shé mào ");
        details.setDescriptionB("鸭舌帽");
        details.setDescriptionC("Cap");
        details.setDescriptionD("Кепка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yùn dòng mào ");
        details.setDescriptionB("运动帽");
        details.setDescriptionC(" Sports cap ");
        details.setDescriptionD("Бейсболка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ér tóng lián wà kù");
        details.setDescriptionB("儿童连袜裤");
        details.setDescriptionC("Baby tights");
        details.setDescriptionD("Детские колготки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng wà zi ");
        details.setDescriptionB("长袜子");
        details.setDescriptionC(" Knee socks ");
        details.setDescriptionD("Гольфы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wà zi ");
        details.setDescriptionB("袜子");
        details.setDescriptionC("Socks");
        details.setDescriptionD("Носки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng ér xié ");
        details.setDescriptionB("婴儿鞋");
        details.setDescriptionC(" Baby booties ");
        details.setDescriptionD("Детские пинетки ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō xié");
        details.setDescriptionB("拖鞋");
        details.setDescriptionC("Slippers");
        details.setDescriptionD("Домашние тапочки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liáng xié");
        details.setDescriptionB("凉鞋");
        details.setDescriptionC("Sandals");
        details.setDescriptionD("Сандали");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yùn dòng xié ");
        details.setDescriptionB("运动鞋");
        details.setDescriptionC("Trainers");
        details.setDescriptionD("Кросовки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǔ xuē ");
        details.setDescriptionB("雨靴");
        details.setDescriptionC("Rain boots");
        details.setDescriptionD("Резиновые сапоги");
        detailsList.add(details);
    }
}
