package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C10 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("牛肝菌");
        details.setDescriptionB("niú gān jùn");
        details.setDescriptionC("Porcini mushroom");
        details.setDescriptionD("Белый гриб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("褐疣柄牛肝菌");
        details.setDescriptionB("hè yóu bǐng niú gān jùn");
        details.setDescriptionC("Birch bolete");
        details.setDescriptionD("Подберёзовик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("平菇/侧耳");
        details.setDescriptionB("píng gū /cè ěr");
        details.setDescriptionC("Oyster mushroom");
        details.setDescriptionD("Вёшенка / Устричный гриб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鸡油菌");
        details.setDescriptionB("jī yóu jùn");
        details.setDescriptionC("Golden chanterelle");
        details.setDescriptionD("Лисички");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("卷边乳菇");
        details.setDescriptionB("juǎn biān rǔ gū");
        details.setDescriptionC("Milk agaric");
        details.setDescriptionD("Груздь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("乳牛肝菌");
        details.setDescriptionB("rǔ niú gān jùn");
        details.setDescriptionC("Slippery jack mushroom");
        details.setDescriptionD("Маслёнок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("厚环乳牛肝菌");
        details.setDescriptionB("hòu huán rǔ niú gān jùn");
        details.setDescriptionC("Greville's bolete");
        details.setDescriptionD("Маслёнок лиственничный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("毒蝇伞");
        details.setDescriptionB("dú yíng sǎn");
        details.setDescriptionC("Fly agaric");
        details.setDescriptionD("Мухомор красный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("毛柄库恩菌");
        details.setDescriptionB("máo bǐng kù ēn jùn");
        details.setDescriptionC("Sheathed woodtuft mushroom");
        details.setDescriptionD("Опёнок летний");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("蜜环菌");
        details.setDescriptionB("mì huán jùn");
        details.setDescriptionC("Honey mushroom");
        details.setDescriptionD("Опёнок осенний");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("松乳菇/松菌");
        details.setDescriptionB("sōng rǔ gū /sōng jùn");
        details.setDescriptionC("Red pine mushroom");
        details.setDescriptionD("Рыжик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("羊肚菌");
        details.setDescriptionB("yáng dù jùn");
        details.setDescriptionC("Morel / Sponge morel");
        details.setDescriptionD("Сморчок съедобный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("菱红菇");
        details.setDescriptionB("líng hóng gū");
        details.setDescriptionC("Bare-toothed russula");
        details.setDescriptionD("Сыроежка пищевая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("绿菇");
        details.setDescriptionB("lǜ gū");
        details.setDescriptionC("Green russula");
        details.setDescriptionD("Сыроежка зеленоватая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("亮黄红菇");
        details.setDescriptionB("liàng huáng hóng gū");
        details.setDescriptionC("Yellow swamp russula");
        details.setDescriptionD("Сыроежка светло-жёлтая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("松露");
        details.setDescriptionB("sōng lù");
        details.setDescriptionC("Truffle");
        details.setDescriptionD("Трюфель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("双孢蘑菇/ 洋蘑菇");
        details.setDescriptionB("shuāng bāo mó gū / yáng mó gū");
        details.setDescriptionC("Button mushroom");
        details.setDescriptionD("Шампиньон двуспоровый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("香菇");
        details.setDescriptionB("xiāng gū");
        details.setDescriptionC("Shiitake");
        details.setDescriptionD("Шиитаке/ Японский лесной гриб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("金针菇");
        details.setDescriptionB("jīn zhēn gū");
        details.setDescriptionC("Enoki Mushroom/ Enokitake");
        details.setDescriptionD("Грибы Эноки/ Энокитаке");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("黑木耳");
        details.setDescriptionB("hēi mù ěr");
        details.setDescriptionC("Wood ear/ Jew's ear");
        details.setDescriptionD("Древесные грибы/ Иудины уши");
        detailsList.add(details);
    }
}
