package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C2 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("皮肤");
        details.setDescriptionB("pí fū");
        details.setDescriptionC("Skin");
        details.setDescriptionD("Кожа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("前额/额头");
        details.setDescriptionB("qián é /é tóu");
        details.setDescriptionC("Forehead");
        details.setDescriptionD("Лоб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("眉毛");
        details.setDescriptionB("méi máo");
        details.setDescriptionC("Eyebrow");
        details.setDescriptionD("Бровь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("睫毛");
        details.setDescriptionB("jié máo");
        details.setDescriptionC("Eyelash");
        details.setDescriptionD("Ресница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("眼睛");
        details.setDescriptionB("yǎn jīng");
        details.setDescriptionC("Eye");
        details.setDescriptionD("Глаз");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鼻孔");
        details.setDescriptionB("bí kǒng");
        details.setDescriptionC("Nostrils");
        details.setDescriptionD("Ноздри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鼻子");
        details.setDescriptionB("bí zi");
        details.setDescriptionC("Nose");
        details.setDescriptionD("Нос");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("嘴");
        details.setDescriptionB("zuǐ");
        details.setDescriptionC("Mouth");
        details.setDescriptionD("Рот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("牙齿");
        details.setDescriptionB("yá chǐ");
        details.setDescriptionC("Tooth");
        details.setDescriptionD("Зуб");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("嘴唇");
        details.setDescriptionB("zuǐ chún");
        details.setDescriptionC("Lips");
        details.setDescriptionD("Губы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("脸颊");
        details.setDescriptionB("liǎn jiá");
        details.setDescriptionC("Cheek");
        details.setDescriptionD("Щека");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("舌头");
        details.setDescriptionB("shé tóu");
        details.setDescriptionC("Tongue");
        details.setDescriptionD("Язык");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("下颚");
        details.setDescriptionB("xià è");
        details.setDescriptionC("Jaw");
        details.setDescriptionD("Челюсть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("下巴");
        details.setDescriptionB("xià bā");
        details.setDescriptionC("Chin");
        details.setDescriptionD("Подбородок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("脖子");
        details.setDescriptionB("bó zi");
        details.setDescriptionC("Neck");
        details.setDescriptionD("Шея");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("耳朵");
        details.setDescriptionB("ěr duo");
        details.setDescriptionC("Ear");
        details.setDescriptionD("Ухо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("头发");
        details.setDescriptionB("tóu fā");
        details.setDescriptionC("Hair");
        details.setDescriptionD("Волосы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("痣");
        details.setDescriptionB("zhì");
        details.setDescriptionC("Mole");
        details.setDescriptionD("Родинка");
        detailsList.add(details);
    }

}
