package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C3 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("一");
        details.setDescriptionB("yī");
        details.setDescriptionC("One");
        details.setDescriptionD("Один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("èr");
        details.setDescriptionB("二");
        details.setDescriptionC("Two");
        details.setDescriptionD("Два");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三");
        details.setDescriptionB("sān");
        details.setDescriptionC("Three");
        details.setDescriptionD("Три");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四");
        details.setDescriptionB("sì");
        details.setDescriptionC("Four");
        details.setDescriptionD("Четыре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("五");
        details.setDescriptionB("wǔ");
        details.setDescriptionC("Five");
        details.setDescriptionD("Пять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("六");
        details.setDescriptionB("liù");
        details.setDescriptionC("Six");
        details.setDescriptionD("Шесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("七");
        details.setDescriptionB("qī");
        details.setDescriptionC("Seven");
        details.setDescriptionD("Семь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("八");
        details.setDescriptionB("bā");
        details.setDescriptionC("Eight");
        details.setDescriptionD("Восемь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("九");
        details.setDescriptionB("jiǔ");
        details.setDescriptionC("Nine");
        details.setDescriptionD("Девять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十");
        details.setDescriptionB("shí");
        details.setDescriptionC("Ten");
        details.setDescriptionD("Десять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十一");
        details.setDescriptionB("shí yī");
        details.setDescriptionC("Eleven");
        details.setDescriptionD("Одиннадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十二");
        details.setDescriptionB("shí èr");
        details.setDescriptionC("Twelve");
        details.setDescriptionD("Двенадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十三");
        details.setDescriptionB("shí sān");
        details.setDescriptionC("Thirteen");
        details.setDescriptionD("Тринадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十四");
        details.setDescriptionB("shí sì");
        details.setDescriptionC("Fourteen");
        details.setDescriptionD("Четырнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十五");
        details.setDescriptionB("shí wǔ");
        details.setDescriptionC("Fifteen");
        details.setDescriptionD("Пятнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十六");
        details.setDescriptionB("shí liù");
        details.setDescriptionC("Sixteen");
        details.setDescriptionD("Шестнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十七");
        details.setDescriptionB("shí qī");
        details.setDescriptionC("Seventeen");
        details.setDescriptionD("Семнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十八");
        details.setDescriptionB("shí bā");
        details.setDescriptionC("Eighteen");
        details.setDescriptionD("Восемнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十九");
        details.setDescriptionB("shí jiǔ");
        details.setDescriptionC("Nineteen");
        details.setDescriptionD("Девятнадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十");
        details.setDescriptionB("èr shí");
        details.setDescriptionC("Twenty");
        details.setDescriptionD("Двадцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十一");
        details.setDescriptionB("èr shí yī");
        details.setDescriptionC("Twenty-one");
        details.setDescriptionD("Двадцать один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十二");
        details.setDescriptionB("èr shí èr");
        details.setDescriptionC("Twenty- two");
        details.setDescriptionD("Двадцать два");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十三");
        details.setDescriptionB("èr shí sān");
        details.setDescriptionC("Twenty- three");
        details.setDescriptionD("Двадцать три");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十四");
        details.setDescriptionB("èr shí sì");
        details.setDescriptionC("Twenty-four");
        details.setDescriptionD("Двадцать четыре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十五");
        details.setDescriptionB("èr shí wǔ");
        details.setDescriptionC("Twenty -five");
        details.setDescriptionD("Двадцать пять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十六");
        details.setDescriptionB("èr shí liù");
        details.setDescriptionC("Twenty-six");
        details.setDescriptionD("Двадцать шесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十七");
        details.setDescriptionB("èr shí qī");
        details.setDescriptionC("Twenty-seven");
        details.setDescriptionD("Двадцать семь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十八");
        details.setDescriptionB("èr shí bā");
        details.setDescriptionC("Twenty-eight");
        details.setDescriptionD("Двадцать восемь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二十九");
        details.setDescriptionB("èr shí jiǔ");
        details.setDescriptionC("Twenty-nine");
        details.setDescriptionD("Двадцать девять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十");
        details.setDescriptionB("sān shí");
        details.setDescriptionC("Thirty");
        details.setDescriptionD("Тридцать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十一");
        details.setDescriptionB("sān shí yī");
        details.setDescriptionC("Thirty-one");
        details.setDescriptionD("Тридцать один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十二");
        details.setDescriptionB("sān shí èr");
        details.setDescriptionC("Thirty-two");
        details.setDescriptionD("Тридцать два");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十三");
        details.setDescriptionB("sān shí sān");
        details.setDescriptionC("Thirty-three");
        details.setDescriptionD("Тридцать три");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十四");
        details.setDescriptionB("sān shí sì");
        details.setDescriptionC("Thirty-four");
        details.setDescriptionD("Тридцать четыре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十五");
        details.setDescriptionB("sān shí wǔ");
        details.setDescriptionC("Thirty-five");
        details.setDescriptionD("Тридцать пять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十六");
        details.setDescriptionB("sān shí liù");
        details.setDescriptionC("Thirty-six");
        details.setDescriptionD("Тридцать шесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十七");
        details.setDescriptionB("sān shí qī");
        details.setDescriptionC("Thirty-seven");
        details.setDescriptionD("Тридцать семь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十八");
        details.setDescriptionB("sān shí bā");
        details.setDescriptionC("Thirty-eight");
        details.setDescriptionD("Тридцать восемь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三十九");
        details.setDescriptionB("sān shí jiǔ");
        details.setDescriptionC("Thirty-nine");
        details.setDescriptionD("Тридцать девять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十");
        details.setDescriptionB("sì shí");
        details.setDescriptionC("Forty");
        details.setDescriptionD("Сорок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十一");
        details.setDescriptionB("sì shí yī ");
        details.setDescriptionC("Forty-one");
        details.setDescriptionD("Сорок  один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十二");
        details.setDescriptionB("sì shí èr");
        details.setDescriptionC("Forty-two");
        details.setDescriptionD("Сорок два");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十三");
        details.setDescriptionB("sì shí sān");
        details.setDescriptionC("Forty-three");
        details.setDescriptionD("Сорок три");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十四");
        details.setDescriptionB("sì shí sì");
        details.setDescriptionC("Forty-four");
        details.setDescriptionD("Сорок четыре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十五");
        details.setDescriptionB("sì shí wǔ");
        details.setDescriptionC("Forty-five");
        details.setDescriptionD("Сорок пять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十六");
        details.setDescriptionB("sì shí liù");
        details.setDescriptionC("Forty-six");
        details.setDescriptionD("Сорок шесть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十七");
        details.setDescriptionB("sì shí qī");
        details.setDescriptionC("Forty-seven");
        details.setDescriptionD("Сорок семь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十八");
        details.setDescriptionB("sì shí bā");
        details.setDescriptionC("Forty-eight");
        details.setDescriptionD("Сорок восемь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四十九");
        details.setDescriptionB("sì shí jiǔ");
        details.setDescriptionC("Forty-nine");
        details.setDescriptionD("Сорок девять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("五十");
        details.setDescriptionB("wǔ shí");
        details.setDescriptionC("Fifty");
        details.setDescriptionD("Пятьдесят");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("六十");
        details.setDescriptionB("liù shí");
        details.setDescriptionC("Sixty");
        details.setDescriptionD("Шестьдесят");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("七十");
        details.setDescriptionB("qī shí");
        details.setDescriptionC("Seventy");
        details.setDescriptionD("Семьдесят");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("八十");
        details.setDescriptionB("bā shí");
        details.setDescriptionC("Eighty");
        details.setDescriptionD("Восемьдесят");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("九十");
        details.setDescriptionB("jiǔ shí");
        details.setDescriptionC("Ninety");
        details.setDescriptionD("Девяносто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一百");
        details.setDescriptionB("yī bǎi");
        details.setDescriptionC("One hundred");
        details.setDescriptionD("Сто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一百一十");
        details.setDescriptionB("yī bǎi yī shí");
        details.setDescriptionC("One hundred and ten");
        details.setDescriptionD("Сто десять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("二百");
        details.setDescriptionB("èr bǎi");
        details.setDescriptionC("Two hundred");
        details.setDescriptionD("Двести");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("三百");
        details.setDescriptionB("sān bǎi");
        details.setDescriptionC("Three hundred");
        details.setDescriptionD("Триста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("四百");
        details.setDescriptionB("sì bǎi");
        details.setDescriptionC("Four hundred");
        details.setDescriptionD("Четыреста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("五百");
        details.setDescriptionB("wǔ bǎi");
        details.setDescriptionC("Five hundred");
        details.setDescriptionD("Пятьсот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("六百");
        details.setDescriptionB("liù bǎi");
        details.setDescriptionC("Six hundred");
        details.setDescriptionD("Шестьсот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("七百");
        details.setDescriptionB("qī bǎi");
        details.setDescriptionC("Seven hundred");
        details.setDescriptionD("Семьсот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("八百");
        details.setDescriptionB("bā bǎi");
        details.setDescriptionC("Eight hundred");
        details.setDescriptionD("Восемьсот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("九百");
        details.setDescriptionB("jiǔ  bǎi");
        details.setDescriptionC("Nine hundred");
        details.setDescriptionD("Девятьсот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一千");
        details.setDescriptionB("yī qiān");
        details.setDescriptionC("One thousand");
        details.setDescriptionD("Тысяча");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一千零一");
        details.setDescriptionB("yī qiān líng yī");
        details.setDescriptionC("One thousand and one");
        details.setDescriptionD("Тысяча один");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一千零一十");
        details.setDescriptionB("yī qiān líng yī shí");
        details.setDescriptionC("One thousand and ten");
        details.setDescriptionD("Тысяча десять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一千一百");
        details.setDescriptionB("yī qiān yī  bǎi");
        details.setDescriptionC("One thousand and hundred");
        details.setDescriptionD("Тысяча сто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一万");
        details.setDescriptionB("yī wàn");
        details.setDescriptionC("Ten thousand");
        details.setDescriptionD("Десять тысяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("五万");
        details.setDescriptionB("wǔ wàn");
        details.setDescriptionC("Fifty thousand");
        details.setDescriptionD("Пятьдесят тысяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十万");
        details.setDescriptionB("shí wàn");
        details.setDescriptionC("One hundred thousand");
        details.setDescriptionD("Сто тысяч");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一百万");
        details.setDescriptionB("yī bǎi wàn");
        details.setDescriptionC("Million");
        details.setDescriptionD("Миллион");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("一亿");
        details.setDescriptionB("yī yì");
        details.setDescriptionC("One hundred million");
        details.setDescriptionD("Сто миллионов");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("十亿");
        details.setDescriptionB("shí yì");
        details.setDescriptionC("Billion");
        details.setDescriptionD("Миллиард");
        detailsList.add(details);
    }

}
