package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C31 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" yáng jì ");
        details.setDescriptionB("洋蓟");
        details.setDescriptionC(" Artichoke ");
        details.setDescriptionD("Артишок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" juǎn xīn cài / bāo xīn cài ");
        details.setDescriptionB("卷心菜/ 包心菜");
        details.setDescriptionC("Cabbage");
        details.setDescriptionD("Белокочанная капуста ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zǐ gān lán ");
        details.setDescriptionB("紫甘蓝");
        details.setDescriptionC("  Red cabbage ");
        details.setDescriptionD("Красночанная капуста ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhòu yè gān lán ");
        details.setDescriptionB("皱叶甘蓝");
        details.setDescriptionC(" Savoy cabbage ");
        details.setDescriptionD("Савойская капуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yǔ yī gān lán ");
        details.setDescriptionB("羽衣甘蓝");
        details.setDescriptionC(" Kale ");
        details.setDescriptionD("Декоративная капуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huā cài/ yē cài huā ");
        details.setDescriptionB(" 花菜/椰菜花");
        details.setDescriptionC("Cauliflower ");
        details.setDescriptionD("Цветная капуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bào zǐ gān lán ");
        details.setDescriptionB("抱子甘蓝");
        details.setDescriptionC(" Brussels sprout");
        details.setDescriptionD("Брюссельская капуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà báicài ");
        details.setDescriptionB("大白菜");
        details.setDescriptionC(" Chinese cabbage ");
        details.setDescriptionD("Пекинская капуста");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wá wá cài");
        details.setDescriptionB("娃娃菜");
        details.setDescriptionC("Baby Chinese Cabbage");
        details.setDescriptionD("Маленькая пекинская капуста ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiú jīng gān lán");
        details.setDescriptionB("球茎甘蓝");
        details.setDescriptionC("Kohlrabi");
        details.setDescriptionD("Кольраби");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luó mǎ huā yē cài");
        details.setDescriptionB("罗马花椰菜");
        details.setDescriptionC("Romanesco broccoli ");
        details.setDescriptionD("Романеско");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī lán huā");
        details.setDescriptionB("西兰花");
        details.setDescriptionC("Broccoli");
        details.setDescriptionD("Брокколи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo bái cài ");
        details.setDescriptionB("小白菜");
        details.setDescriptionC("Bok choy");
        details.setDescriptionD("Китайский капустный лист/ Бок-чой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhú sǔn ");
        details.setDescriptionB("竹笋");
        details.setDescriptionC(" Bamboo shoots ");
        details.setDescriptionD("Бамбуковые побеги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hú luó bo");
        details.setDescriptionB("胡萝卜");
        details.setDescriptionC("Carrot");
        details.setDescriptionD("Морковь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī hú lu");
        details.setDescriptionB("西葫芦");
        details.setDescriptionC("Marrow/ Zucchini ");
        details.setDescriptionD("Кабачок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cháng qié zi ");
        details.setDescriptionB("长茄子");
        details.setDescriptionC("Long eggplant ");
        details.setDescriptionD("Длинный баклажан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuán qié zi");
        details.setDescriptionB("圆茄子");
        details.setDescriptionC("Round eggplant");
        details.setDescriptionD("Круглый баклажан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shì zi jiāo/ tián jiāo ");
        details.setDescriptionB("柿子椒/ 甜椒");
        details.setDescriptionC(" Bell pepper ");
        details.setDescriptionD("Болгарский перец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng jiāo ");
        details.setDescriptionB("青椒");
        details.setDescriptionC("Green Pepper ");
        details.setDescriptionD("Зелёный перец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng tián jiāo ");
        details.setDescriptionB("红甜椒");
        details.setDescriptionC("Red bell pepper");
        details.setDescriptionD("Красный сладкий перец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("là jiāo ");
        details.setDescriptionB("辣椒");
        details.setDescriptionC(" Hot pepper/ Chilli ");
        details.setDescriptionD("Перец чили");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng sè xiǎo fān qié ");
        details.setDescriptionB("黄色小番茄");
        details.setDescriptionC("Yellow cherry tomato");
        details.setDescriptionD("Томат черри желтый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shèng nǚ guǒ ");
        details.setDescriptionB("圣女果");
        details.setDescriptionC("Cherry tomato");
        details.setDescriptionD("Томат черри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xī hóng shì /fān qié ");
        details.setDescriptionB("西红柿/番茄");
        details.setDescriptionC(" Tomato ");
        details.setDescriptionD("Помидор/ Томат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǔ dòu /mǎ líng shǔ");
        details.setDescriptionB("土豆/马铃薯");
        details.setDescriptionC("Potato");
        details.setDescriptionD("Картофель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng shǔ/ fān shǔ ");
        details.setDescriptionB("红薯/ 蕃薯");
        details.setDescriptionC(" Sweet potato ");
        details.setDescriptionD("Батат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǐ shǔ");
        details.setDescriptionB("紫薯");
        details.setDescriptionC(" Purple sweet potato ");
        details.setDescriptionD("Фиолетовый батат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà suàn");
        details.setDescriptionB("大蒜");
        details.setDescriptionC("Garlic ");
        details.setDescriptionD("Чеснок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suàn tái ");
        details.setDescriptionB("蒜苔 ");
        details.setDescriptionC("Garlic shoot");
        details.setDescriptionD(" Побеги чеснока ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng cōng");
        details.setDescriptionB("洋葱");
        details.setDescriptionC("Onion");
        details.setDescriptionD("Лук репчатый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng yáng cōng");
        details.setDescriptionB("红洋葱");
        details.setDescriptionC("Red onion ");
        details.setDescriptionD("Красный лук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái yáng cōng");
        details.setDescriptionB("白洋葱");
        details.setDescriptionC("White onion");
        details.setDescriptionD("Лук белый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà cōng");
        details.setDescriptionB("大葱");
        details.setDescriptionC(" Bunching Onion / Leek");
        details.setDescriptionD("Лук-порей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng cōng ");
        details.setDescriptionB("香葱");
        details.setDescriptionC("Spring onion ");
        details.setDescriptionD("Зеленый лук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qín cài ");
        details.setDescriptionB(" 芹菜");
        details.setDescriptionC("Celery");
        details.setDescriptionD("Сельдерей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng chūn ");
        details.setDescriptionB("香椿");
        details.setDescriptionC(" Chinese toon/ Red toon ");
        details.setDescriptionD("Цедрела китайская/ Красная Туна");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lián péng ");
        details.setDescriptionB("莲蓬");
        details.setDescriptionC("Fresh Lotus seeds ");
        details.setDescriptionD("Семена лотоса (свежие) ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lián zǐ ");
        details.setDescriptionB("莲子");
        details.setDescriptionC("Dry Lotus seeds ");
        details.setDescriptionD("Семена лотоса( сухие)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ǒu/ lián ǒu ");
        details.setDescriptionB("藕/莲藕");
        details.setDescriptionC("Lotus root");
        details.setDescriptionD("Корень лотоса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shān yào");
        details.setDescriptionB("山药");
        details.setDescriptionC("  Yam rhizome ");
        details.setDescriptionD("Ямс (корни)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bì lǔ hú luó bo");
        details.setDescriptionB("秘鲁胡萝卜");
        details.setDescriptionC("Arracacha");
        details.setDescriptionD("Арракача");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kuài jīng cù jiāng cǎo ");
        details.setDescriptionB("块茎酢浆草");
        details.setDescriptionC("Оса");
        details.setDescriptionD("(Кислица клубненосная)Ока");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi pó luó mén shēn ");
        details.setDescriptionB("黑婆罗门参");
        details.setDescriptionC(" Spanish salsify /Black salsify");
        details.setDescriptionD("Козелец испанский(Скорцонера испанская)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pó luó mén shēn ");
        details.setDescriptionB("婆罗门参");
        details.setDescriptionC(" Purple salsify ");
        details.setDescriptionD("(Козлобородник пореелистный) Сальсифи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wū lú kù shǔ ");
        details.setDescriptionB("乌卢库薯");
        details.setDescriptionC("Olluco");
        details.setDescriptionD("Уллюко клубненосный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luò kuí");
        details.setDescriptionB("落葵");
        details.setDescriptionC("Malabar Spinach");
        details.setDescriptionD("Базелла/Малабарский шпинат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō cài ");
        details.setDescriptionB("菠菜");
        details.setDescriptionC("Spinach");
        details.setDescriptionD(" Шпинат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèng cài ");
        details.setDescriptionB("蕹菜");
        details.setDescriptionC("Water-spinach");
        details.setDescriptionD("Водяной шпинат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pú gōng yīng/pó po dīng ");
        details.setDescriptionB("蒲公英/婆婆丁");
        details.setDescriptionC(" Dandelion");
        details.setDescriptionD(" Одуванчик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dú huó cǎo");
        details.setDescriptionB("独活草");
        details.setDescriptionC("Lovage");
        details.setDescriptionD("Любисток");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu mài cài");
        details.setDescriptionB("油麦菜");
        details.setDescriptionC(" Romaine lettuce");
        details.setDescriptionD(" Салат-ромен /Римский салат ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān mó");
        details.setDescriptionB("酸模");
        details.setDescriptionC("Sorrel");
        details.setDescriptionD("Щавель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòu bàn cài");
        details.setDescriptionB("豆瓣菜");
        details.setDescriptionC("Watercress");
        details.setDescriptionD("Водяной кресс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shēng cài ");
        details.setDescriptionB("生菜");
        details.setDescriptionC(" Lettuce  ");
        details.setDescriptionD("Салат латук листовой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiú shēng cài/yuán shēng cài ");
        details.setDescriptionB("球生菜/圆生菜");
        details.setDescriptionC("Iceberg ");
        details.setDescriptionD("Салат Айсберг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhī ma cài ");
        details.setDescriptionB("芝麻菜");
        details.setDescriptionC(" Eruca/ Rucola ");
        details.setDescriptionD("Эрука/Руккола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǔ jú ");
        details.setDescriptionB("苦菊");
        details.setDescriptionC(" Frisee Lettuce/  Endive ");
        details.setDescriptionD(" Cалат Фризе / Эндивий курчавый ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiān suì gǔ/zǐ lì xiàn ");
        details.setDescriptionB("千穗谷/籽粒苋");
        details.setDescriptionC(" Amaranth");
        details.setDescriptionD("Амарант");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiānɡ huánɡ ");
        details.setDescriptionB("姜黄");
        details.setDescriptionC(" Curcuma");
        details.setDescriptionD("Куркума");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiānɡ ");
        details.setDescriptionB("姜");
        details.setDescriptionC("Ginger");
        details.setDescriptionD("Имбирь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("là gēn");
        details.setDescriptionB("辣根");
        details.setDescriptionC(" Horseradish ");
        details.setDescriptionD("Хрен ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lú sǔn");
        details.setDescriptionB("芦笋");
        details.setDescriptionC("Sparrow grass/Asparagus");
        details.setDescriptionD("Спаржа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi dié guā ");
        details.setDescriptionB("飞碟瓜");
        details.setDescriptionC("Patisson");
        details.setDescriptionD("Патиссон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fó shǒu guā ");
        details.setDescriptionB("佛手瓜");
        details.setDescriptionC(" Chayote ");
        details.setDescriptionD("Чайот /Мексиканский огурец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǔ guā");
        details.setDescriptionB("苦瓜");
        details.setDescriptionC("Balsam-pear/Bitter melon");
        details.setDescriptionD("Момордика/ Горький огурец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dōng guā ");
        details.setDescriptionB("冬瓜");
        details.setDescriptionC(" Wax gourd /Winter melon ");
        details.setDescriptionD("Восковая тыква");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nán guā ");
        details.setDescriptionB("南瓜");
        details.setDescriptionC(" Pumpkin ");
        details.setDescriptionD("Тыква");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hú lu ");
        details.setDescriptionB("葫芦");
        details.setDescriptionC(" Bottle Gourd ");
        details.setDescriptionD("Лагенария/ Горлянка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiū kuí");
        details.setDescriptionB("秋葵");
        details.setDescriptionC(" Okra ");
        details.setDescriptionD("(Абельмош съедобный) Окра ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pēn guā");
        details.setDescriptionB("喷瓜");
        details.setDescriptionC("Squirting cucumber");
        details.setDescriptionD("Бешеный огурец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng guā");
        details.setDescriptionB("黄瓜");
        details.setDescriptionC("Cucumber ");
        details.setDescriptionD("Огурец посевной");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǔ zhǐ xī guā");
        details.setDescriptionB("拇指西瓜");
        details.setDescriptionC(" Cucamelon /Mexican miniature watermelon ");
        details.setDescriptionD("Мелотрия шершавая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo què guā ");
        details.setDescriptionB("小雀瓜 ");
        details.setDescriptionC("  Achuqcha ");
        details.setDescriptionD("Огурец ачохча");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sī guā ");
        details.setDescriptionB("丝瓜");
        details.setDescriptionC("Luffa ");
        details.setDescriptionD("Люффа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guā yè guā lóu");
        details.setDescriptionB("瓜叶栝楼");
        details.setDescriptionC("Snake gourd");
        details.setDescriptionD("Огурец змеевидный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cì jiǎo guā ");
        details.setDescriptionB("刺角瓜 ");
        details.setDescriptionC("Kiwano ");
        details.setDescriptionD("Кивано/ Арбузный огурец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chì páo ");
        details.setDescriptionB("赤瓟");
        details.setDescriptionC(" Manchurian tuber gourd ");
        details.setDescriptionD("Красный огурец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cì shān gān");
        details.setDescriptionB("刺山柑");
        details.setDescriptionC("Capers");
        details.setDescriptionD("Каперсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi gǎn lǎn");
        details.setDescriptionB("黑橄榄");
        details.setDescriptionC("Black olives");
        details.setDescriptionD("Маслины");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng gǎn lǎn");
        details.setDescriptionB("青橄榄");
        details.setDescriptionC("Green olives");
        details.setDescriptionD("Оливки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biǎn dòu");
        details.setDescriptionB("扁豆");
        details.setDescriptionC("Hyacinth beans");
        details.setDescriptionD("Гиацинтовые бобы (Долихоз)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng jiāng dòu ");
        details.setDescriptionB("长豇豆");
        details.setDescriptionC(" Asparagus bean/ Chinese long beans ");
        details.setDescriptionD("Китайская длинная фасоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dòu jiǎo");
        details.setDescriptionB("豆角");
        details.setDescriptionC(" Asparagus bean");
        details.setDescriptionD("Спаржевая фасоль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu shā dòu/ hǔ jiān guǒ ");
        details.setDescriptionB("油莎豆/虎坚果");
        details.setDescriptionC("Chufa sedge/Earth almond");
        details.setDescriptionD("Чуфа/ Земляной миндаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng sù ");
        details.setDescriptionB("罂粟");
        details.setDescriptionC("Poppy");
        details.setDescriptionD("Мак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yīng táo luó bo ");
        details.setDescriptionB("樱桃萝卜");
        details.setDescriptionC("Radish ");
        details.setDescriptionD("Редис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián cài");
        details.setDescriptionB("甜菜");
        details.setDescriptionC("Beetroot");
        details.setDescriptionD("Свёкла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" táng luó bo ");
        details.setDescriptionB("糖萝卜");
        details.setDescriptionC(" Sugar Beet ");
        details.setDescriptionD(" Сахарная свёкла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú jīng");
        details.setDescriptionB("芜菁");
        details.setDescriptionC("Turnip");
        details.setDescriptionD("Репа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīn lǐ měi / hóng xīn luó bo ");
        details.setDescriptionB("(心里美) 红心萝卜");
        details.setDescriptionC(" Watermelon radish ");
        details.setDescriptionD(" Арбузная редька");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  bái luó bo ");
        details.setDescriptionB("白萝卜");
        details.setDescriptionC("White Radish Daikon ");
        details.setDescriptionD(" Белый редис  Дайкон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi luó bo ");
        details.setDescriptionB("黑萝卜");
        details.setDescriptionC(" Black radish ");
        details.setDescriptionD(" Чёрная редька");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hóng pí luó bo ");
        details.setDescriptionB("红皮萝卜");
        details.setDescriptionC("Red radish");
        details.setDescriptionD(" Красный редис ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng luó bo ");
        details.setDescriptionB("青萝卜");
        details.setDescriptionC("Green turnip ");
        details.setDescriptionD("Зелёная репа ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wú jīng gān lán/yáng dà tóu cài ");
        details.setDescriptionB("芜菁甘蓝/洋大头菜");
        details.setDescriptionC("Swede ");
        details.setDescriptionD("Брюква");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ōu fáng fēng gēn ");
        details.setDescriptionB("欧防风根");
        details.setDescriptionC("Parsnip");
        details.setDescriptionD("Пастернак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòu shǔ/ dì guā ");
        details.setDescriptionB("豆薯/地瓜");
        details.setDescriptionC("Jicama");
        details.setDescriptionD("Хикама");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jú yù");
        details.setDescriptionB("菊芋");
        details.setDescriptionC("Jerusalem artichoke/Sunroot");
        details.setDescriptionD("Топинамбур");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jú shǔ ");
        details.setDescriptionB("菊薯");
        details.setDescriptionC("Yacon");
        details.setDescriptionD("Якон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yù tou");
        details.setDescriptionB("芋头");
        details.setDescriptionC("Taro roots");
        details.setDescriptionD("Таро");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bí qi");
        details.setDescriptionB("荸荠");
        details.setDescriptionC(" Chinese water chestnut ");
        details.setDescriptionD("Болотница сладкая ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù shǔ ");
        details.setDescriptionB("木薯");
        details.setDescriptionC(" Cassava ");
        details.setDescriptionD(" Маниок/Кассава ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēng dòu cài ");
        details.setDescriptionB("蜂斗菜");
        details.setDescriptionC("Burdock");
        details.setDescriptionD("Белокопытник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  di huán/luó sī cài ");
        details.setDescriptionB("地环/螺丝菜");
        details.setDescriptionC(" Marsh woundwort ");
        details.setDescriptionD("Стахис/ Чистец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yào xī guā ");
        details.setDescriptionB("药西瓜");
        details.setDescriptionC("Wild desert gourd/Colocynth ");
        details.setDescriptionD("Колоцинт ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yù mǐ ");
        details.setDescriptionB("玉米");
        details.setDescriptionC("Corn");
        details.setDescriptionD("Кукуруза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái yù mǐ");
        details.setDescriptionB("白玉米");
        details.setDescriptionC("White corn");
        details.setDescriptionD("Белая кукуруза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi yù mǐ");
        details.setDescriptionB("黑玉米");
        details.setDescriptionC("Black corn");
        details.setDescriptionD("Чёрная кукуруза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎo méi yù mǐ");
        details.setDescriptionB("草莓玉米");
        details.setDescriptionC(" Strawberry corn ");
        details.setDescriptionD("Кукуруза земляничная");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ guǒ yù mǐ ");
        details.setDescriptionB("水果玉米");
        details.setDescriptionC(" Fruit corn ");
        details.setDescriptionD("Фруктовая кукуруза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("cǎi sè yù mǐ");
        details.setDescriptionB("彩色玉米");
        details.setDescriptionC(" Multicolored corn ");
        details.setDescriptionD(" Цветная кукуруза ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bō lí bǎo shí yù mǐ ");
        details.setDescriptionB("玻璃宝石玉米");
        details.setDescriptionC("Corn Glass Gem/ Blue corn");
        details.setDescriptionD(" Цветная кукуруза  Стеклянная Гемма");
        detailsList.add(details);
        

    }
}
