package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C36 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("niú nǎi");
        details.setDescriptionB("牛奶");
        details.setDescriptionC("Cow’s milk");
        details.setDescriptionD("Коровье молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ nǎi ");
        details.setDescriptionB("马奶");
        details.setDescriptionC("Mare's milk");
        details.setDescriptionD("Кобылье молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" luò tuó nǎi ");
        details.setDescriptionB("骆驼奶");
        details.setDescriptionC("Camel’s milk ");
        details.setDescriptionD("Верблюжье молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shān yáng nǎi");
        details.setDescriptionB("山羊奶");
        details.setDescriptionC("Goat’s milk");
        details.setDescriptionD("Козье молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yáng nǎi");
        details.setDescriptionB("羊奶");
        details.setDescriptionC("Ewe's milk");
        details.setDescriptionD("Овечье молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān nǎi ");
        details.setDescriptionB("酸奶");
        details.setDescriptionC("Yoghurt");
        details.setDescriptionD("Йогурт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kāi fēi ěr ");
        details.setDescriptionB("开菲尔");
        details.setDescriptionC("Kefir");
        details.setDescriptionD("Кефир");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān niú nǎi / suān rǔ ");
        details.setDescriptionB("酸牛奶/ 酸乳");
        details.setDescriptionC("Sour milk/ Clabber ");
        details.setDescriptionD("Простокваша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tǔ ěr qí xián suān nǎi ");
        details.setDescriptionB("土耳其咸酸奶");
        details.setDescriptionC("Ayran");
        details.setDescriptionD("Айран");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liàn rǔ");
        details.setDescriptionB("炼乳");
        details.setDescriptionC("Condensed milk");
        details.setDescriptionD("Сгущенное молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān nǎi yóu");
        details.setDescriptionB("酸奶油");
        details.setDescriptionC("Sour cream");
        details.setDescriptionD("Сметана");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nóng jiā nǎi lào");
        details.setDescriptionB("农家奶酪");
        details.setDescriptionC("(Curd) Cottage cheese");
        details.setDescriptionD("Творог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiā tíng zì zhì nǎi lào ");
        details.setDescriptionB("家庭自制奶酪 ");
        details.setDescriptionC(" Homemade cheese ");
        details.setDescriptionD("Домашний сыр брынза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo sān jiǎo nǎi lào");
        details.setDescriptionB("小三角奶酪");
        details.setDescriptionC("Soft cheese");
        details.setDescriptionD("Плавленный сыр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǎi lào");
        details.setDescriptionB("奶酪");
        details.setDescriptionC("Cheese");
        details.setDescriptionD("Сыр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái tuō niú nǎi");
        details.setDescriptionB("白脱牛奶");
        details.setDescriptionC(" Buttermilk  ");
        details.setDescriptionD("Пахта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō zhī niú nǎi");
        details.setDescriptionB("脱脂牛奶");
        details.setDescriptionC("Milk low fat /Skimmed milk");
        details.setDescriptionD("Обезжиренное молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" suān luò tuó nǎi ");
        details.setDescriptionB("酸骆驼奶");
        details.setDescriptionC(" Shubat  /Chal  (fermented camel milk)");
        details.setDescriptionD("Шубат/ Чал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ nǎi jiǔ");
        details.setDescriptionB("马奶酒");
        details.setDescriptionC("Kumis");
        details.setDescriptionD("Кумыс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎo niú nǎi ");
        details.setDescriptionB("烤牛奶");
        details.setDescriptionC(" Baked milk");
        details.setDescriptionD("Топленое молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rǔ qīng");
        details.setDescriptionB("乳清");
        details.setDescriptionC("Whey");
        details.setDescriptionD("Сыворотка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng yóu");
        details.setDescriptionB("黄油");
        details.setDescriptionC("Butter");
        details.setDescriptionD("Сливочное масло");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě gāo / bīng qí lín ");
        details.setDescriptionB("雪糕/ 冰淇淋");
        details.setDescriptionC("Ice cream");
        details.setDescriptionD("Мороженое");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dàn nǎi yóu");
        details.setDescriptionB("淡奶油");
        details.setDescriptionC(" Whipped  cream ");
        details.setDescriptionD("Взбитые сливки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎi yóu ");
        details.setDescriptionB("奶油");
        details.setDescriptionC(" Сream");
        details.setDescriptionD("Сливки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rǔ qīng fěn");
        details.setDescriptionB("乳清粉");
        details.setDescriptionC("Whey protein");
        details.setDescriptionD("Сывороточный порошок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎi fěn ");
        details.setDescriptionB("奶粉");
        details.setDescriptionC("Powdered milk ");
        details.setDescriptionD("Сухое молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tuō zhī rǔ fěn ");
        details.setDescriptionB("脱脂乳粉 ");
        details.setDescriptionC("Skim milk powder");
        details.setDescriptionD("Обезжиренное сухое молоко");
        detailsList.add(details);
        

    }
}
