package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C39 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" xiàng liàn ");
        details.setDescriptionB("项链");
        details.setDescriptionC("Necklace");
        details.setDescriptionD("Колье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiōng zhēn ");
        details.setDescriptionB("胸针");
        details.setDescriptionC("Brooch");
        details.setDescriptionD("Брошь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiàng liàn zhuì  ");
        details.setDescriptionB("项链坠");
        details.setDescriptionC("Pendant ");
        details.setDescriptionD("Кулон/ Подвеска");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liàn zi ");
        details.setDescriptionB("链子");
        details.setDescriptionC("Chain");
        details.setDescriptionD("Цепочка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liàn kòu ");
        details.setDescriptionB("链扣");
        details.setDescriptionC("Clasp");
        details.setDescriptionD("Застежка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu zhuó");
        details.setDescriptionB("手镯");
        details.setDescriptionC("Bracelet");
        details.setDescriptionD("Браслет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fěi cuì shǒu zhuó");
        details.setDescriptionB("翡翠手镯");
        details.setDescriptionC("Jade bracelet");
        details.setDescriptionD(" Нефритовый браслет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn zhū shǒu zhuó ");
        details.setDescriptionB("珍珠手镯");
        details.setDescriptionC("Pearl bracelet ");
        details.setDescriptionD("Жемчужный браслет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhēn zhū xiàng liàn ");
        details.setDescriptionB("珍珠项链");
        details.setDescriptionC("Pearl necklace");
        details.setDescriptionD("Жемчужное ожерелье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiè zhǐ");
        details.setDescriptionB("戒指");
        details.setDescriptionC("Ring");
        details.setDescriptionD("Кольцо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jié hūn jiè zhǐ ");
        details.setDescriptionB("结婚戒指");
        details.setDescriptionC("Wedding rings");
        details.setDescriptionD("Обручальные кольца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zuàn shí jiè zhǐ ");
        details.setDescriptionB("钻石戒指");
        details.setDescriptionC(" Ring with diamonds ");
        details.setDescriptionD("Кольцо с бриллиантами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bǎo shí ");
        details.setDescriptionB("宝石");
        details.setDescriptionC("Gemstone");
        details.setDescriptionD("Драгоценный камень ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ěr huán ");
        details.setDescriptionB("耳环");
        details.setDescriptionC("Earrings");
        details.setDescriptionD("Серьги");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ěr dīng ");
        details.setDescriptionB("耳钉");
        details.setDescriptionC("Stud earrings");
        details.setDescriptionD("Серьги-гвоздики");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diào huán ěr huán ");
        details.setDescriptionB("吊环耳环");
        details.setDescriptionC("Dangle earrings");
        details.setDescriptionD("Висячие серьги ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà quān ěr huán ");
        details.setDescriptionB("大圈耳环");
        details.setDescriptionC("Hoop earrings");
        details.setDescriptionD("Серьги-кольца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ěr jiá ");
        details.setDescriptionB("耳夹");
        details.setDescriptionC("Clips");
        details.setDescriptionD("Клипсы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǐng dài jiá ");
        details.setDescriptionB("领带夹");
        details.setDescriptionC("Tiepin");
        details.setDescriptionD("Булавка для галстука");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiù kòu ");
        details.setDescriptionB("袖扣");
        details.setDescriptionC("Cufflinks");
        details.setDescriptionD("Запонки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǒu biǎo ");
        details.setDescriptionB("手表");
        details.setDescriptionC("Watch");
        details.setDescriptionD("Часы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǒu shì hé");
        details.setDescriptionB("首饰盒");
        details.setDescriptionC("Jewellery box");
        details.setDescriptionD("Шкатулка для драгоценностей");
        detailsList.add(details);
        

    }
}
