package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C42 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("wǒ ");
        details.setDescriptionB("我");
        details.setDescriptionC("I");
        details.setDescriptionD("Я");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǐ");
        details.setDescriptionB("你");
        details.setDescriptionC("You");
        details.setDescriptionD("Ты");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nín");
        details.setDescriptionB("您");
        details.setDescriptionC("You");
        details.setDescriptionD("Вы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ men ");
        details.setDescriptionB("我们");
        details.setDescriptionC("We");
        details.setDescriptionD("Мы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā");
        details.setDescriptionB("他");
        details.setDescriptionC("He");
        details.setDescriptionD("Он");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā");
        details.setDescriptionB("她");
        details.setDescriptionC("She");
        details.setDescriptionD("Она");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā");
        details.setDescriptionB("它");
        details.setDescriptionC("It");
        details.setDescriptionD("Оно");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā men");
        details.setDescriptionB("他们");
        details.setDescriptionC("They");
        details.setDescriptionD("Они");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā men");
        details.setDescriptionB("她们(女)");
        details.setDescriptionC("They ");
        details.setDescriptionD("Они");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhè");
        details.setDescriptionB("这");
        details.setDescriptionC("This");
        details.setDescriptionD("Это/Этот/Эта");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhè xiē");
        details.setDescriptionB("这些");
        details.setDescriptionC("These");
        details.setDescriptionD("Эти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suǒ yǒu");
        details.setDescriptionB("所有");
        details.setDescriptionC("All/Every");
        details.setDescriptionD("Все");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ de");
        details.setDescriptionB("我的");
        details.setDescriptionC("My/Mine");
        details.setDescriptionD("Мой/Моя/ Моё");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nǐ de");
        details.setDescriptionB("你的");
        details.setDescriptionC("Your");
        details.setDescriptionD("Твой");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ men de");
        details.setDescriptionB("我们的");
        details.setDescriptionC("Our/Ours");
        details.setDescriptionD("Наш/Наша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nín de");
        details.setDescriptionB("您的");
        details.setDescriptionC("Your/Yours");
        details.setDescriptionD("Ваш/Ваше");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā de");
        details.setDescriptionB("他的");
        details.setDescriptionC("His");
        details.setDescriptionD("Его");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tā de ");
        details.setDescriptionB("她的");
        details.setDescriptionC("Her");
        details.setDescriptionD("Её");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā men de");
        details.setDescriptionB("他们的");
        details.setDescriptionC("Their");
        details.setDescriptionD("Их");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tā");
        details.setDescriptionB("他");
        details.setDescriptionC("Him");
        details.setDescriptionD("Ему");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tā ");
        details.setDescriptionB("她");
        details.setDescriptionC("Her");
        details.setDescriptionD("Ей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shéi");
        details.setDescriptionB("谁?");
        details.setDescriptionC("Who?");
        details.setDescriptionD("Кто?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shén me");
        details.setDescriptionB("什么?");
        details.setDescriptionC("What?");
        details.setDescriptionD("Что?");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǎ /nǎ yī gè?");
        details.setDescriptionB("哪/ 哪一个？");
        details.setDescriptionC("Which?");
        details.setDescriptionD("Какой? /Который？");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shì shéi de");
        details.setDescriptionB("是谁的?");
        details.setDescriptionC("Whose?");
        details.setDescriptionD("Чей？");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duō shǎo");
        details.setDescriptionB("多少?");
        details.setDescriptionC("How many?/How much?");
        details.setDescriptionD("Сколько？");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shéi yě bù ");
        details.setDescriptionB("谁也不");
        details.setDescriptionC("Nobody");
        details.setDescriptionD("Никто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shén me yě bù/ shén me yě méi yǒu ");
        details.setDescriptionB("什么也不/ 什么也没有");
        details.setDescriptionC("Nothing");
        details.setDescriptionD("Ничто");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wú zhǔ de ");
        details.setDescriptionB("无主的");
        details.setDescriptionC("Nobody's");
        details.setDescriptionD("Ничей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi/měi yīgè/gè");
        details.setDescriptionB("每/每一个/各");
        details.setDescriptionC("Each/ Every");
        details.setDescriptionD("Каждый");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zì jǐ ");
        details.setDescriptionB("自己");
        details.setDescriptionC(" Oneself ");
        details.setDescriptionD("Сам");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǒ de");
        details.setDescriptionB("我的");
        details.setDescriptionC("Me");
        details.setDescriptionD("Мне");
        detailsList.add(details);
    }
}
