package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C43 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("shèng bó nà quǎn");
        details.setDescriptionB("圣伯纳犬");
        details.setDescriptionC("Saint Bernard");
        details.setDescriptionD("Сенбернар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kē lì quǎn");
        details.setDescriptionB("柯利犬");
        details.setDescriptionC("Collie");
        details.setDescriptionD("Колли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn máo mù yáng quǎn");
        details.setDescriptionB("短毛牧羊犬");
        details.setDescriptionC("Smooth Collie");
        details.setDescriptionD("Короткошёрстный колли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("biān jìng mù yáng quǎn");
        details.setDescriptionB("边境牧羊犬");
        details.setDescriptionC("Border Collie");
        details.setDescriptionD("Бордер-колли");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ lè dì");
        details.setDescriptionB("喜乐蒂");
        details.setDescriptionC("Shetland Sheepdog");
        details.setDescriptionD("Шелти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé guó mù yáng quǎn");
        details.setDescriptionB("德国牧羊犬");
        details.setDescriptionC("German Shepherd");
        details.setDescriptionD("Немецкая овчарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ lì shí mù yáng quǎn");
        details.setDescriptionB("比利时牧羊犬");
        details.setDescriptionC("Belgian Shepherd Dog");
        details.setDescriptionD("Бельгийская овчарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gāo jiā suǒ quǎn");
        details.setDescriptionB("高加索犬");
        details.setDescriptionC("Caucasian dog");
        details.setDescriptionD("Кавказская овчарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ān nà tuō lì yǎ mù yáng quǎn/ kǎn gāo quǎn");
        details.setDescriptionB("安纳托利亚牧羊犬/ 坎高犬");
        details.setDescriptionC("Anatolian Shepherd Dog/ Kangal");
        details.setDescriptionD("Анатолийская овчарка/ Кангал");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lán bō gé quǎn");
        details.setDescriptionB("兰波格犬");
        details.setDescriptionC("Leonberger");
        details.setDescriptionD("Леонбергер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dá ěr mǎ tí yà gǒu/ dà mài tīng quǎn");
        details.setDescriptionB("达尔马提亚狗/ 大麦町犬");
        details.setDescriptionC("Dalmatian dog");
        details.setDescriptionD("Далматский дог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào dá liè quǎn");
        details.setDescriptionB("奥达猎犬");
        details.setDescriptionC("Otterhound");
        details.setDescriptionD("Оттерхаунд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà dān quǎn");
        details.setDescriptionB("大丹犬");
        details.setDescriptionC("Great Dane");
        details.setDescriptionD("Немецкий дог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dù bīn quǎn");
        details.setDescriptionB("杜宾犬");
        details.setDescriptionC("Doberman Pinscher");
        details.setDescriptionD("Доберман-пинчер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niǔ fēn lán quǎn");
        details.setDescriptionB("纽芬兰犬");
        details.setDescriptionC("Newfoundland dog");
        details.setDescriptionD("Ньюфаундленд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn máo xún huí quǎn");
        details.setDescriptionB("金毛寻回犬");
        details.setDescriptionC("Golden Retriever");
        details.setDescriptionD("Золотистый ретривер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lā bù lā duō");
        details.setDescriptionB("拉布拉多");
        details.setDescriptionC("Labrador");
        details.setDescriptionD("Лабрадор");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bān yá áo quǎn");
        details.setDescriptionB("西班牙獒犬");
        details.setDescriptionC("Spanish Mastiff");
        details.setDescriptionD("Испанский мастиф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nà bù lè sī áo quǎn");
        details.setDescriptionB("那不勒斯獒犬");
        details.setDescriptionC("Neapolitan Mastiff");
        details.setDescriptionD("Неаполитанский мастиф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fǎ guó áo quǎn");
        details.setDescriptionB("法国獒犬");
        details.setDescriptionC("French Mastiff");
        details.setDescriptionD("Французский мастиф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì dà lì kǎ sī luó quǎn");
        details.setDescriptionB("意大利卡斯罗犬");
        details.setDescriptionC("Сane Corso");
        details.setDescriptionD("Кане-корсо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ lèi lìā xióng gǒu");
        details.setDescriptionB("卡累利阿熊狗");
        details.setDescriptionC("Karelian Bear Dog");
        details.setDescriptionD("Карельская медвежья лайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dōng xī bó lì yà lái kǎ quǎn");
        details.setDescriptionB("东西伯利亚莱卡犬");
        details.setDescriptionC("East Siberian Laika");
        details.setDescriptionD("Восточно-сибирская лайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú tóu gěng");
        details.setDescriptionB("牛头梗");
        details.setDescriptionC("Bull Terrier");
        details.setDescriptionD("Бультерьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fǎ guó dòu niú quǎn");
        details.setDescriptionB("法国斗牛犬");
        details.setDescriptionC("French Bulldog");
        details.setDescriptionD("Французский бульдог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bān yá dòu niú quǎn");
        details.setDescriptionB("西班牙斗牛犬");
        details.setDescriptionC("Spanish Alano/Spanish Bulldog");
        details.setDescriptionD("Испанский Алано/Испанский бульдог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòu niú quǎn");
        details.setDescriptionB("斗牛犬");
        details.setDescriptionC("Bulldog");
        details.setDescriptionD("Английский бульдог");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó è bà quǎn");
        details.setDescriptionB("美国恶霸犬");
        details.setDescriptionC("American Pit bull terrier");
        details.setDescriptionD("Американский питбуль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě nà ruì quǎn");
        details.setDescriptionB("雪纳瑞犬");
        details.setDescriptionC("Schnauzer");
        details.setDescriptionD("Шнауцер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jù xíng xuě nà ruì");
        details.setDescriptionB("巨型雪纳瑞");
        details.setDescriptionC("Giant Schnauzer");
        details.setDescriptionD("Ризеншнауцер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí nǐ xíng xuě nà ruì");
        details.setDescriptionB("迷你型雪纳瑞");
        details.setDescriptionC("Miniature Schnauzer");
        details.setDescriptionD("Миниатюрный шнауцер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā pí quǎn");
        details.setDescriptionB("沙皮犬");
        details.setDescriptionC("Chinese Shar- Pei");
        details.setDescriptionD("Китайский шарпей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("luō wēi nà quǎn");
        details.setDescriptionB("罗威纳犬");
        details.setDescriptionC("Rottweiler");
        details.setDescriptionD("Ротвейлер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng yà mù yáng quǎn");
        details.setDescriptionB("中亚牧羊犬");
        details.setDescriptionC("Centralasian Sheepdog");
        details.setDescriptionD("Среднеазиатская овчарка/Алабай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò sī kē hù wèi quǎn");
        details.setDescriptionB("莫斯科护卫犬");
        details.setDescriptionC("Moscow Watchdog");
        details.setDescriptionD("Московская сторожевая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é luó sī nán bù mù yáng quǎn");
        details.setDescriptionB("俄罗斯南部牧羊犬");
        details.setDescriptionC("South Russian Sheepdog");
        details.setDescriptionD("Южнорусская овчарка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng guó gǔ dài mù yáng quǎn");
        details.setDescriptionB("英国古代牧羊犬");
        details.setDescriptionC("Old English Sheepdog/Bobtail");
        details.setDescriptionD("Староанглийская овчарка/Бобтейл");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě áo");
        details.setDescriptionB("雪獒");
        details.setDescriptionC("Snow Mastiff");
        details.setDescriptionD("Тибетский мастиф снежный лев");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zàng áo");
        details.setDescriptionB("藏獒");
        details.setDescriptionC("Tibetan Mastiff");
        details.setDescriptionD("Тибетский мастиф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("quán shī quǎn");
        details.setDescriptionB("拳师犬");
        details.setDescriptionC("Boxer");
        details.setDescriptionD("Боксёр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēi ěr shì kē jī quǎn");
        details.setDescriptionB("威尔士柯基犬");
        details.setDescriptionC("Welsh Corgi Pembroke");
        details.setDescriptionD("Вельш корги пемброк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèi mǎ liè quǎn");
        details.setDescriptionB("魏玛猎犬");
        details.setDescriptionC("Weimaraner");
        details.setDescriptionD("Веймаранер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng guó zhǐ shì quǎn");
        details.setDescriptionB("英国指示犬");
        details.setDescriptionC("English Pointer");
        details.setDescriptionD("Английский пойнтер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé guó gāng máo zhǐ shì quǎn");
        details.setDescriptionB("德国刚毛指示犬");
        details.setDescriptionC("Deutsch Drahthaar dog");
        details.setDescriptionD("Немецкий драхтаар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé guó duǎn máo zhǐ shì quǎn");
        details.setDescriptionB("德国短毛指示犬");
        details.setDescriptionC("German Shorthaired Pointer");
        details.setDescriptionD("Немецкий курцхаар");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng guó guān máo quǎn");
        details.setDescriptionB("中国冠毛犬");
        details.setDescriptionC("Chinese Crested Dog(Powderpuff)");
        details.setDescriptionD("Китайская хохлатая собака (Пуховая)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōng guó guān máo quǎn");
        details.setDescriptionB("中国冠毛犬");
        details.setDescriptionC("Chinese Crested Dog(Hairless)");
        details.setDescriptionD("Китайская хохлатая собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī zàng liè quǎn /xiù gǒu");
        details.setDescriptionB("西藏猎犬/袖狗");
        details.setDescriptionC("Tibetan Spaniel");
        details.setDescriptionD("Тибетский спаниель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chá lǐ wáng xiǎo liè quǎn");
        details.setDescriptionB("查理王小猎犬");
        details.setDescriptionC("Cavalier King Charles Spaniel");
        details.setDescriptionD("Кавалер-кинг-чарльз-спаниель ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó shuǐ liè quǎn");
        details.setDescriptionB("美国水猎犬");
        details.setDescriptionC("American Water Spaniel");
        details.setDescriptionD("Американский водяной спаниель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng guó kě kǎ quǎn");
        details.setDescriptionB("英国可卡犬");
        details.setDescriptionC("English Cocker Spaniel");
        details.setDescriptionD("Английский кокер-спаниель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó kě kǎ quǎn");
        details.setDescriptionB("美国可卡犬");
        details.setDescriptionC("American Cocker Spaniel");
        details.setDescriptionD("Американский кокер-спаниель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mí nǐ dù bīn quǎn");
        details.setDescriptionB("迷你杜宾犬");
        details.setDescriptionC("Miniature Pinscher");
        details.setDescriptionD("Карликовый пинчер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuē kè xià quǎn");
        details.setDescriptionB("约克夏犬");
        details.setDescriptionC("Yorkshire Terrier");
        details.setDescriptionD("Йоркширский терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sī máo gěng");
        details.setDescriptionB("丝毛梗");
        details.setDescriptionC("Australian Silky Terrier");
        details.setDescriptionD("Австралийский шелковистый терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jié kè luó sù gěng");
        details.setDescriptionB("杰克罗素梗");
        details.setDescriptionC("Jack Russell Terrier");
        details.setDescriptionD("Джек-рассел-терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎi lì lán gěng");
        details.setDescriptionB("凯利蓝梗");
        details.setDescriptionC("Kerry Blue Terrier");
        details.setDescriptionD("Келли-блю терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("liè hú gěng");
        details.setDescriptionB("猎狐梗");
        details.setDescriptionC("Foxterrier");
        details.setDescriptionD("Фокстерьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("nuò fú kè gěng");
        details.setDescriptionB("诺福克梗");
        details.setDescriptionC("Norfolk Terrier");
        details.setDescriptionD("Норфолк-терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé guó liè gěng");
        details.setDescriptionB("德国猎梗");
        details.setDescriptionC("German Hunting Terrier");
        details.setDescriptionD("Немецкий ягдтерьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jié kè gěng");
        details.setDescriptionB("捷克梗");
        details.setDescriptionC("Czech terrier /Cesky terrier");
        details.setDescriptionD("Чешский терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū gé lán gěng");
        details.setDescriptionB("苏格兰梗");
        details.setDescriptionC("Scottish Terrier");
        details.setDescriptionD("Шотландский терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào dà lì yà gěng");
        details.setDescriptionB("澳大利亚梗");
        details.setDescriptionC("AustralianTerrier");
        details.setDescriptionD("Австралийский терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ài ěr lán gěng");
        details.setDescriptionB("爱尔兰梗");
        details.setDescriptionC("Irish Terrier");
        details.setDescriptionD("Ирландский терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bèi líng dùn gěng");
        details.setDescriptionB("贝灵顿梗");
        details.setDescriptionC(" Bedlington Terrier");
        details.setDescriptionD("Бедлингтон-терьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pú táo yá shuǐ quǎn");
        details.setDescriptionB("葡萄牙水犬");
        details.setDescriptionC(" Portuguese Water Dog");
        details.setDescriptionD("Португальская водяная собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bān yá shuǐ quǎn");
        details.setDescriptionB("西班牙水犬");
        details.setDescriptionC("Spanish Water Dog");
        details.setDescriptionD("Испанская водяная собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiōng yá lì bō lì quǎn");
        details.setDescriptionB("匈牙利波利犬");
        details.setDescriptionC("Hungarian Puli");
        details.setDescriptionD(" Венгерская овчарка пули");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo xíng pú táo yá bō dēng kě quǎn");
        details.setDescriptionB("小型葡萄牙波登可犬");
        details.setDescriptionC("Portuguese Podengo");
        details.setDescriptionD("Португальский поденг у");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("duǎn máo liè hú gěng");
        details.setDescriptionB("短毛猎狐梗");
        details.setDescriptionC("Smooth Fox Terrier");
        details.setDescriptionD("Американский той фокстерьер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é luó sī wán jù quǎn");
        details.setDescriptionB("俄罗斯玩具犬");
        details.setDescriptionC("Russian Toy");
        details.setDescriptionD("Русский той");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā jí dù quǎn");
        details.setDescriptionB("巴吉度犬");
        details.setDescriptionC("Basset Hound");
        details.setDescriptionD("Бассет-хаунд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā gē");
        details.setDescriptionB("巴哥");
        details.setDescriptionC("Pug");
        details.setDescriptionD("Мопс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ gé /xiǎo liè quǎn");
        details.setDescriptionB("比格/小猎犬");
        details.setDescriptionC("Beagle");
        details.setDescriptionD("Бигль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("哈巴小猎犬");
        details.setDescriptionB("hǎ bā xiǎo liè quǎn");
        details.setDescriptionC("Puggle");
        details.setDescriptionD("Пагль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎo shī zi gǒu");
        details.setDescriptionB("小狮子狗");
        details.setDescriptionC("Pekingese");
        details.setDescriptionD("Пекинес");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("là cháng quǎn");
        details.setDescriptionB("腊肠犬");
        details.setDescriptionC("Dachshund");
        details.setDescriptionD("Такса");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sà lù jī liè quǎn");
        details.setDescriptionB("萨路基猎犬");
        details.setDescriptionC("Saluki");
        details.setDescriptionD("Салюки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ā fù hàn liè quǎn");
        details.setDescriptionB("阿富汗猎犬");
        details.setDescriptionC("Afghan Hound");
        details.setDescriptionD("Афганская борзая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bān yá huī gǒu");
        details.setDescriptionB("西班牙灰狗");
        details.setDescriptionC("Spanish galgo / Spanish greyhound");
        details.setDescriptionD("Испанский гальго");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huì bǐ tè quǎn");
        details.setDescriptionB("惠比特犬");
        details.setDescriptionC("Whippet");
        details.setDescriptionD("Уиппет");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yì dà lì huī gǒu");
        details.setDescriptionB("意大利灰狗");
        details.setDescriptionC("Italian Greyhound");
        details.setDescriptionD("Итальянский грейхаунд/Левретка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ zhá ěr quǎn/xiōng yá lì líng tí quǎn");
        details.setDescriptionB("马扎尔犬/匈牙利灵缇犬");
        details.setDescriptionC("Magyar agár/Hungarian Greyhound");
        details.setDescriptionD("Мадьяр Агар/Венгерская борзая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gé lì quǎn/huī gǒu");
        details.setDescriptionB("格力犬/灰狗");
        details.setDescriptionC("Greyhound");
        details.setDescriptionD("Английская борзая/Грейхаунд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é luó sī liè láng quǎn");
        details.setDescriptionB("俄罗斯猎狼犬");
        details.setDescriptionC("Russian Wolfhound");
        details.setDescriptionD("Русская борзая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sū gé lán liè lù quǎn");
        details.setDescriptionB("苏格兰猎鹿犬");
        details.setDescriptionC("Scottish Deerhound");
        details.setDescriptionD("Шотландский дирхаунд ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ā shā wǎ kè quǎn");
        details.setDescriptionB("阿沙瓦克犬");
        details.setDescriptionC("Azawakh");
        details.setDescriptionD("Азавак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bō lán líng tí");
        details.setDescriptionB("波兰灵缇");
        details.setDescriptionC("Polish Greyhound");
        details.setDescriptionD("Польский харт /Польская борзая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pǔ luō tè liè quǎn");
        details.setDescriptionB("普罗特猎犬");
        details.setDescriptionC("Plott Hound");
        details.setDescriptionD("Плотт-хаунд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ào dà lì yà mù niú quǎn");
        details.setDescriptionB("澳大利亚牧牛犬");
        details.setDescriptionC("Australian Cattle Dog");
        details.setDescriptionD("Австралийская пастушья собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chuān dōng liè quǎn");
        details.setDescriptionB("川东猎犬");
        details.setDescriptionC("Chinese Chongqing Dog");
        details.setDescriptionD("Китайская гончая/ Чунцин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎ ài quǎn");
        details.setDescriptionB("卡爱犬");
        details.setDescriptionC("Kai Dog/Tora (Tiger) Dog");
        details.setDescriptionD("Кай-кен");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yīng guó sāi tè zhǒng liè gǒu");
        details.setDescriptionB("英国塞特种猎狗");
        details.setDescriptionC("English Setter");
        details.setDescriptionD("Английский сеттер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ài ěr lán xuě dá quǎn");
        details.setDescriptionB("爱尔兰雪达犬");
        details.setDescriptionC("Irish Setter");
        details.setDescriptionD("Ирландский сеттер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ài ěr lán liè láng quǎn");
        details.setDescriptionB("爱尔兰猎狼犬");
        details.setDescriptionC("Irish Wolfhound");
        details.setDescriptionD("Ирландский волкодав");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guì bīn quǎn/ tài dí quǎn");
        details.setDescriptionB("贵宾犬/泰迪犬");
        details.setDescriptionC("Poodle");
        details.setDescriptionD("Пудель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bó luò ní yǎ quǎn");
        details.setDescriptionB("博洛尼亚犬");
        details.setDescriptionC("Bolognese");
        details.setDescriptionD("Болоньез");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ xióng quǎn");
        details.setDescriptionB("比熊犬");
        details.setDescriptionC("Bichon Frise");
        details.setDescriptionD("Бишон фризе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mǎ ěr jì sī quǎn");
        details.setDescriptionB("马尔济斯犬");
        details.setDescriptionC("Maltese Dog");
        details.setDescriptionD("Мальтийская болонка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hú dié quǎn");
        details.setDescriptionB("蝴蝶犬");
        details.setDescriptionC("Papillon");
        details.setDescriptionD(" Папильон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bù lǔ sài'ěr gé lǐ fēn");
        details.setDescriptionB("布鲁塞尔格里芬");
        details.setDescriptionC("Brussels Griffon");
        details.setDescriptionD("Брюссельский гриффон");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī shī quǎn/shī zi quǎn");
        details.setDescriptionB("西施犬/狮子犬");
        details.setDescriptionC("Shih Tzu");
        details.setDescriptionD("Ши-тцу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sōng shī quǎn");
        details.setDescriptionB("松狮犬");
        details.setDescriptionC("Chow Chow");
        details.setDescriptionD("Чау-чау");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("měi guó ài sī jī mó quǎn");
        details.setDescriptionB("美国爱斯基摩犬");
        details.setDescriptionC("American Eskimo dog");
        details.setDescriptionD("Американский эскимосский шпиц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī bó lì yǎ xuě qiāo quǎn / hà shi qí");
        details.setDescriptionB("西伯利亚雪橇犬/哈士奇");
        details.setDescriptionC("Siberian Husky");
        details.setDescriptionD("Сибирский хаски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ā lā sī jiā  xuě qiāo quǎn");
        details.setDescriptionB("阿拉斯加雪橇犬");
        details.setDescriptionC("Alaskan Malamute");
        details.setDescriptionD("Аляскинский маламут");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sà mó yé");
        details.setDescriptionB("萨摩耶");
        details.setDescriptionC("Samoyed");
        details.setDescriptionD("Самоедская лайка/Самоед");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēn lán hú lí quǎn");
        details.setDescriptionB("芬兰狐狸犬");
        details.setDescriptionC(" Finnish Spitz");
        details.setDescriptionD("Финский шпиц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiū tián quǎn");
        details.setDescriptionB("秋田犬");
        details.setDescriptionC("Japanese Akita");
        details.setDescriptionD("Акита-ину");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chái quǎn");
        details.setDescriptionB("柴犬");
        details.setDescriptionC("Shiba Inu");
        details.setDescriptionD("Сиба-ину/Шиба- Ину");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dé yì zhì zhōng xíng hú lí quǎn");
        details.setDescriptionB("德意志中型狐狸犬");
        details.setDescriptionC("German Spitz Mittel");
        details.setDescriptionD("Немецкий шпиц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bó měi");
        details.setDescriptionB("博美");
        details.setDescriptionC("Pomeranian");
        details.setDescriptionD("Померанский шпиц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rì běn zhòng quǎn");
        details.setDescriptionB("日本狆犬");
        details.setDescriptionC("Japanese Chin");
        details.setDescriptionD("Японский хин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí nǔ kè quǎn");
        details.setDescriptionB("奇努克犬");
        details.setDescriptionC("Chinook");
        details.setDescriptionD("Чинук");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā xiān jí quǎn");
        details.setDescriptionB("巴仙吉犬");
        details.setDescriptionC("Basenji");
        details.setDescriptionD("Басенджи");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mò xī gē wú máo quǎn");
        details.setDescriptionB("墨西哥无毛犬");
        details.setDescriptionC("Mexican Hairless dog");
        details.setDescriptionD("Голая мексиканская собака");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí wǎ wǎ");
        details.setDescriptionB("奇瓦瓦");
        details.setDescriptionC("Chihuahua");
        details.setDescriptionD("Чихуахуа");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhá bēi quǎn");
        details.setDescriptionB("茶杯犬");
        details.setDescriptionC("Teacup Poodles");
        details.setDescriptionD("Ти кап пудель");
        detailsList.add(details);
    }
}
