package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C67 {

    public List<Details> detailsList = new ArrayList<>();

    {
       Details details = new Details();
        details.setDescriptionA("zhuō zi");
        details.setDescriptionB("桌子");
        details.setDescriptionC("Table");
        details.setDescriptionD("Стол");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yǐ zi");
        details.setDescriptionB("椅子");
        details.setDescriptionC("Chair");
        details.setDescriptionD("Стул");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn lú");
        details.setDescriptionB("电炉");
        details.setDescriptionC("Cooker/Stove");
        details.setDescriptionD("Электроплита");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xī yóu yān jī ");
        details.setDescriptionB("吸油烟机");
        details.setDescriptionC("Kitchen hood");
        details.setDescriptionD("Вытяжка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kǎo xiāng");
        details.setDescriptionB("烤箱");
        details.setDescriptionC("Oven");
        details.setDescriptionD("Духовка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ wǎn jī ");
        details.setDescriptionB("洗碗机");
        details.setDescriptionC("Dishwasher");
        details.setDescriptionD("Посудомоечная машина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng xiāng");
        details.setDescriptionB("冰箱");
        details.setDescriptionC("Fridge ");
        details.setDescriptionD("Холодильник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xǐ wǎn chí ");
        details.setDescriptionB("洗碗池");
        details.setDescriptionC("Sink");
        details.setDescriptionD("Раковина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuǐ lóng tóu ");
        details.setDescriptionB("水龙头");
        details.setDescriptionC("Water tap");
        details.setDescriptionD("Кран/ Смеситель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("diàn shuǐ hú ");
        details.setDescriptionB("电水壶");
        details.setDescriptionC("Electric kettle");
        details.setDescriptionD("Электрочайник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diàn mó kā fēi jī ");
        details.setDescriptionB("电磨咖啡机");
        details.setDescriptionC("Electric coffee grinder");
        details.setDescriptionD("Электрокофемолка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kā fēi jī ");
        details.setDescriptionB("咖啡机");
        details.setDescriptionC("Coffee machine");
        details.setDescriptionD("Кофеварка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tái miàn");
        details.setDescriptionB("台面");
        details.setDescriptionC("Tabletop");
        details.setDescriptionD("Столешница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhú guì");
        details.setDescriptionB("厨柜");
        details.setDescriptionC("Kitchen сabinet ");
        details.setDescriptionD("Кухонный шкаф");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jià zi ");
        details.setDescriptionB("架子");
        details.setDescriptionC("Shelf");
        details.setDescriptionD("Полка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сhōu tì");
        details.setDescriptionB("抽屉");
        details.setDescriptionC("Drawer");
        details.setDescriptionD("Выдвижной ящик");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lā jī tǒng");
        details.setDescriptionB("垃圾桶");
        details.setDescriptionC("Rubbish bin");
        details.setDescriptionD("Мусорное ведро");
        detailsList.add(details);
    }
}
