package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C7 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("葡萄酒");
        details.setDescriptionB("pú táo jiǔ");
        details.setDescriptionC("Wine");
        details.setDescriptionD("Вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白葡萄酒");
        details.setDescriptionB("bái pú táo jiǔ");
        details.setDescriptionC("White wine");
        details.setDescriptionD("Белое вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("红葡萄酒");
        details.setDescriptionB("hóng pú táo jiǔ");
        details.setDescriptionC("Red wine");
        details.setDescriptionD("Красное вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("玫瑰红葡萄酒");
        details.setDescriptionB("méi guī hóng pú táo jiǔ");
        details.setDescriptionC("Rose wine");
        details.setDescriptionD("Розовое вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("无糖分的葡萄酒");
        details.setDescriptionB("wú táng fèn de pú táo jiǔ");
        details.setDescriptionC("Dry wine");
        details.setDescriptionD("Cухое вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("米酒");
        details.setDescriptionB("mǐ jiǔ");
        details.setDescriptionC("Rice wine");
        details.setDescriptionD("Рисовое вино");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("啤酒");
        details.setDescriptionB("pí jiǔ");
        details.setDescriptionC("Beer");
        details.setDescriptionD("Пиво");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("伏特加");
        details.setDescriptionB("fú tè jiā");
        details.setDescriptionC("Vodka");
        details.setDescriptionD("Водка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("威士忌");
        details.setDescriptionB("wēi shì jì");
        details.setDescriptionC("Whisky");
        details.setDescriptionD("Виски");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("杜松子酒");
        details.setDescriptionB("dù sōng zǐ jiǔ");
        details.setDescriptionC("Gin");
        details.setDescriptionD("Джин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("白兰地");
        details.setDescriptionB("bái lán dì");
        details.setDescriptionC("Brandy");
        details.setDescriptionD("Бренди");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("科尼亚克白兰地酒");
        details.setDescriptionB("kē ní yà kè bái lán dì jiǔ");
        details.setDescriptionC("Cognac");
        details.setDescriptionD("Коньяк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("香槟");
        details.setDescriptionB("xiāng bīn");
        details.setDescriptionC("Champagne");
        details.setDescriptionD("Шампанское");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("朗姆");
        details.setDescriptionB("lǎng mǔ");
        details.setDescriptionC("Rum");
        details.setDescriptionD("Ром");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("鸡尾酒");
        details.setDescriptionB("jī wěi jiǔ");
        details.setDescriptionC("Сocktail");
        details.setDescriptionD("Коктейль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("苹果酒");
        details.setDescriptionB("píng guǒ jiǔ");
        details.setDescriptionC("Cider");
        details.setDescriptionD("Сидр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("雪利酒");
        details.setDescriptionB("xuě lì jiǔ");
        details.setDescriptionC("Sherry");
        details.setDescriptionD("Херес/ Шерри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("马天尼");
        details.setDescriptionB("mǎ tiān ní");
        details.setDescriptionC("Martini");
        details.setDescriptionD("Мартини");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("金巴利");
        details.setDescriptionB("jīn bā lì");
        details.setDescriptionC("Campari");
        details.setDescriptionD("Кампари");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("百利甜酒");
        details.setDescriptionB("bǎi lì tián jiǔ");
        details.setDescriptionC("Baileys");
        details.setDescriptionD("Бейлис");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("轩尼诗");
        details.setDescriptionB("xuān ní shī");
        details.setDescriptionC("Hennessy");
        details.setDescriptionD("Хеннесси");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("茅台");
        details.setDescriptionB("máo tái");
        details.setDescriptionC("Moutai");
        details.setDescriptionD("Маотай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("null");
        details.setDescriptionB("null");
        details.setDescriptionC("null");
        details.setDescriptionD("null");
        detailsList.add(details);

    }

}
