package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C77 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("zhù");
        details.setDescriptionB("住");
        details.setDescriptionC("Live ");
        details.setDescriptionD("Жить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dòng ");
        details.setDescriptionB("动");
        details.setDescriptionC("Move ");
        details.setDescriptionD("Двигаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhàn /lì");
        details.setDescriptionB("站/立");
        details.setDescriptionC("Stand");
        details.setDescriptionD("Стоять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuò");
        details.setDescriptionB("坐");
        details.setDescriptionC("Sit");
        details.setDescriptionD("Сидеть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zǒu");
        details.setDescriptionB("走");
        details.setDescriptionC("Go");
        details.setDescriptionD("Идти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qù");
        details.setDescriptionB("去（乘交通工具）");
        details.setDescriptionC("Go by");
        details.setDescriptionD("Ехать ( на транспорте)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jià shǐ");
        details.setDescriptionB("驾驶");
        details.setDescriptionC("Drive");
        details.setDescriptionD("Водить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" pǎo");
        details.setDescriptionB("跑");
        details.setDescriptionC("Run ");
        details.setDescriptionD("Бежать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiào");
        details.setDescriptionB("跳");
        details.setDescriptionC("Jump");
        details.setDescriptionD("Прыгать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zēng zhǎng");
        details.setDescriptionB("增长");
        details.setDescriptionC("Grow ");
        details.setDescriptionD("Расти");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiāng xìn");
        details.setDescriptionB("相信");
        details.setDescriptionC("Believe ");
        details.setDescriptionD("Верить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xǐ huān");
        details.setDescriptionB("喜欢");
        details.setDescriptionC("Like");
        details.setDescriptionD("Нравится");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ài");
        details.setDescriptionB("爱");
        details.setDescriptionC("Love");
        details.setDescriptionD("Любить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gǎn xiè");
        details.setDescriptionB("感谢");
        details.setDescriptionC("Thank");
        details.setDescriptionD("Благодарить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǎ diàn huà");
        details.setDescriptionB("打电话");
        details.setDescriptionC("Call ");
        details.setDescriptionD("Звонить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎng /sī kǎo ");
        details.setDescriptionB("想/思考");
        details.setDescriptionC("Think ");
        details.setDescriptionD("Думать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhī dào ");
        details.setDescriptionB("知道");
        details.setDescriptionC("Know");
        details.setDescriptionD(" Знать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wán ");
        details.setDescriptionB("玩");
        details.setDescriptionC("Play");
        details.setDescriptionD("Играть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("gěi");
        details.setDescriptionB("给");
        details.setDescriptionC("Give");
        details.setDescriptionD("Давать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kāi");
        details.setDescriptionB("开");
        details.setDescriptionC("Open");
        details.setDescriptionD("Открывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("guān");
        details.setDescriptionB("关");
        details.setDescriptionC(" Close ");
        details.setDescriptionD("Закрывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gōng zuò");
        details.setDescriptionB("工作");
        details.setDescriptionC("Work");
        details.setDescriptionD("Работать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuò");
        details.setDescriptionB("做");
        details.setDescriptionC("Do ");
        details.setDescriptionD("Делать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wēi xiào");
        details.setDescriptionB("微笑");
        details.setDescriptionC("Smile");
        details.setDescriptionD("Улыбаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiào");
        details.setDescriptionB("笑");
        details.setDescriptionC("Laugh");
        details.setDescriptionD("Смеяться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kū");
        details.setDescriptionB("哭");
        details.setDescriptionC("Cry");
        details.setDescriptionD("Плакать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dìng gòu ");
        details.setDescriptionB("订购");
        details.setDescriptionC("Order");
        details.setDescriptionD("Заказывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bān");
        details.setDescriptionB("搬");
        details.setDescriptionC("Carry ");
        details.setDescriptionD("Нести");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǚ xíng");
        details.setDescriptionB("旅行");
        details.setDescriptionC("Travel");
        details.setDescriptionD("Путешествовать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi");
        details.setDescriptionB("飞");
        details.setDescriptionC("Fly");
        details.setDescriptionD("Летать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("pá");
        details.setDescriptionB("爬");
        details.setDescriptionC("Climb");
        details.setDescriptionD("Лезть/ Залазить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiǎng yào ");
        details.setDescriptionB("想要");
        details.setDescriptionC("Want");
        details.setDescriptionD(" Хотеть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xún zhǎo ");
        details.setDescriptionB("寻找");
        details.setDescriptionC("Search");
        details.setDescriptionD("Искать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhǎo dào");
        details.setDescriptionB("找到");
        details.setDescriptionC("Find ");
        details.setDescriptionD("Находить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dài lái");
        details.setDescriptionB("带来");
        details.setDescriptionC("Bring ");
        details.setDescriptionD("Приносить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sòng gěi");
        details.setDescriptionB("送给");
        details.setDescriptionC("Give/Present");
        details.setDescriptionD("Дарить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hē");
        details.setDescriptionB("喝");
        details.setDescriptionC("Drink");
        details.setDescriptionD("Пить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сhī");
        details.setDescriptionB("吃");
        details.setDescriptionC("Eat");
        details.setDescriptionD("Кушать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zuò fàn");
        details.setDescriptionB("做饭");
        details.setDescriptionC("Cook");
        details.setDescriptionD("Готовить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuō huà ");
        details.setDescriptionB("说话");
        details.setDescriptionC("Speak");
        details.setDescriptionD(" Говорить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎn ");
        details.setDescriptionB("喊");
        details.setDescriptionC("Shout");
        details.setDescriptionD("Кричать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tōng zhī");
        details.setDescriptionB(" 通知");
        details.setDescriptionC("Notice");
        details.setDescriptionD(" Уведомлять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎng");
        details.setDescriptionB("讲");
        details.setDescriptionC("Tell");
        details.setDescriptionD("Рассказывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dú");
        details.setDescriptionB("读");
        details.setDescriptionC("Read");
        details.setDescriptionD("Читать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huà");
        details.setDescriptionB("画");
        details.setDescriptionC("Draw");
        details.setDescriptionD("Рисовать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiě");
        details.setDescriptionB("写");
        details.setDescriptionC("Write");
        details.setDescriptionD("Писать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kàn");
        details.setDescriptionB("看");
        details.setDescriptionC("Watch");
        details.setDescriptionD("Cмотреть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kàn jiàn");
        details.setDescriptionB("看见");
        details.setDescriptionC("See");
        details.setDescriptionD("Видеть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tīng jiàn");
        details.setDescriptionB("听见");
        details.setDescriptionC("Hear");
        details.setDescriptionD("Слышать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wén");
        details.setDescriptionB("闻");
        details.setDescriptionC("Smell");
        details.setDescriptionD("Нюхать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("chàng");
        details.setDescriptionB("唱");
        details.setDescriptionC("Sing");
        details.setDescriptionD("Петь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tīng");
        details.setDescriptionB("听");
        details.setDescriptionC(" Listen ");
        details.setDescriptionD("Слушать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jì ");
        details.setDescriptionB("记");
        details.setDescriptionC("Remember ");
        details.setDescriptionD("Помнить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dǒng ");
        details.setDescriptionB("懂");
        details.setDescriptionC("Understand");
        details.setDescriptionD("Понимать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wèn ");
        details.setDescriptionB("问");
        details.setDescriptionC("Ask ");
        details.setDescriptionD("Спрашивать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huí dá");
        details.setDescriptionB("回答");
        details.setDescriptionC("Answer");
        details.setDescriptionD("Отвечать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhǎn shì");
        details.setDescriptionB("展示");
        details.setDescriptionC("Show");
        details.setDescriptionD(" Показывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāo ");
        details.setDescriptionB("教");
        details.setDescriptionC("Teach");
        details.setDescriptionD(" Учить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiǎng jiě");
        details.setDescriptionB("讲解");
        details.setDescriptionC("Explain ");
        details.setDescriptionD("Объяснять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fān yì");
        details.setDescriptionB("翻译");
        details.setDescriptionC("Translate");
        details.setDescriptionD("Переводить ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cháng shì ");
        details.setDescriptionB("尝试");
        details.setDescriptionC("Try ");
        details.setDescriptionD("Пытаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bāng zhù ");
        details.setDescriptionB("帮助");
        details.setDescriptionC("Help ");
        details.setDescriptionD("Помогать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kāi shǐ ");
        details.setDescriptionB("开始");
        details.setDescriptionC("Begin ");
        details.setDescriptionD("Начинать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎn fà");
        details.setDescriptionB("剪发");
        details.setDescriptionC("Сut hair");
        details.setDescriptionD("Стричь волосы");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chuàng zào");
        details.setDescriptionB("创造");
        details.setDescriptionC("Create");
        details.setDescriptionD(" Создавать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gēn suí");
        details.setDescriptionB("跟随");
        details.setDescriptionC("Follow ");
        details.setDescriptionD("Следовать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tíng");
        details.setDescriptionB("停");
        details.setDescriptionC("Stop ");
        details.setDescriptionD("Останавливать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huàn ");
        details.setDescriptionB("换");
        details.setDescriptionC("Сhange");
        details.setDescriptionD(" Менять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fàng");
        details.setDescriptionB("放");
        details.setDescriptionC("Put ");
        details.setDescriptionD("Класть / Ставить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng jié");
        details.setDescriptionB("清洁");
        details.setDescriptionC("Clean");
        details.setDescriptionD("Чистить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xǐ");
        details.setDescriptionB("洗");
        details.setDescriptionC("Wash");
        details.setDescriptionD("Мыть");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xǐ");
        details.setDescriptionB("洗");
        details.setDescriptionC("Wash");
        details.setDescriptionD("Стирать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tiào wǔ");
        details.setDescriptionB("跳舞");
        details.setDescriptionC("Dance");
        details.setDescriptionD("Танцевать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yóu yǒng");
        details.setDescriptionB("游泳");
        details.setDescriptionC("Swim");
        details.setDescriptionD("Плавать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuǎn zé ");
        details.setDescriptionB("选择");
        details.setDescriptionC("Choose");
        details.setDescriptionD(" Выбирать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiàn zào ");
        details.setDescriptionB("建造");
        details.setDescriptionC("Build");
        details.setDescriptionD("Строить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nòng huài");
        details.setDescriptionB("弄坏");
        details.setDescriptionC("Break");
        details.setDescriptionD(" Ломать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tái");
        details.setDescriptionB("抬");
        details.setDescriptionC("Lift");
        details.setDescriptionD("Поднимать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhuā zhù ");
        details.setDescriptionB("抓住");
        details.setDescriptionC("Catch ");
        details.setDescriptionD("Ловить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yíng");
        details.setDescriptionB("赢");
        details.setDescriptionC("Win ");
        details.setDescriptionD("Побеждать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yóu jì ");
        details.setDescriptionB("邮寄(信)");
        details.setDescriptionC("Send (letter)");
        details.setDescriptionD("Посылать (письмо)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" gài ");
        details.setDescriptionB("盖");
        details.setDescriptionC("Cover");
        details.setDescriptionD(" Покрывать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jí zhòng ");
        details.setDescriptionB("击中");
        details.setDescriptionC("Hit ");
        details.setDescriptionD("Ударять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tóng yì");
        details.setDescriptionB("同意");
        details.setDescriptionC("Agree ");
        details.setDescriptionD("Соглашаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiē shōu/ shōu dào ");
        details.setDescriptionB("接收/收到");
        details.setDescriptionC("Receive ");
        details.setDescriptionD("Получать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mài");
        details.setDescriptionB("卖");
        details.setDescriptionC("Sell ");
        details.setDescriptionD("Продавать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎi");
        details.setDescriptionB("买");
        details.setDescriptionC("Buy");
        details.setDescriptionD("Покупать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fù ");
        details.setDescriptionB("付");
        details.setDescriptionC("Pay ");
        details.setDescriptionD("Платить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā fèi");
        details.setDescriptionB("花费");
        details.setDescriptionC("Spend ");
        details.setDescriptionD("Тратить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yù jiàn ");
        details.setDescriptionB("遇见");
        details.setDescriptionC("Meet ");
        details.setDescriptionD("Встречать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liú xià");
        details.setDescriptionB("留下");
        details.setDescriptionC("Stay");
        details.setDescriptionD(" Оставаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lí kāi");
        details.setDescriptionB("离开");
        details.setDescriptionC("Leave ");
        details.setDescriptionD("Уходить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lái");
        details.setDescriptionB("来");
        details.setDescriptionC("Сome ");
        details.setDescriptionD("Приходить");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fǎn huí ");
        details.setDescriptionB("返回");
        details.setDescriptionC("Return ");
        details.setDescriptionD("Возвращаться");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dié dǎo");
        details.setDescriptionB("跌倒");
        details.setDescriptionC("Fall ");
        details.setDescriptionD("Падать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" diū shī ");
        details.setDescriptionB("丢失");
        details.setDescriptionC("Lose ");
        details.setDescriptionD("Терять");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā");
        details.setDescriptionB("杀");
        details.setDescriptionC("Kill");
        details.setDescriptionD(" Убивать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sǐ");
        details.setDescriptionB("死");
        details.setDescriptionC("Die ");
        details.setDescriptionD("Умирать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhěng jiù");
        details.setDescriptionB("拯救");
        details.setDescriptionC("Save");
        details.setDescriptionD("Спасать");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wán bì");
        details.setDescriptionB("完毕");
        details.setDescriptionC("Finish");
        details.setDescriptionD("Заканчивать");
        detailsList.add(details);
    }
}
