package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C81 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("mó guǐ yú ");
        details.setDescriptionB("魔鬼鱼");
        details.setDescriptionC("Manta ray");
        details.setDescriptionD("Скат манта / Морской дьявол ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lán wén gōng ");
        details.setDescriptionB("蓝纹魟");
        details.setDescriptionC("Common stingray");
        details.setDescriptionD("Скат хвостокол/Морской кот");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bèi jí yáo ");
        details.setDescriptionB("背棘鳐");
        details.setDescriptionC(" Thornback Ray ");
        details.setDescriptionD(" Морская лисица/ Колючий скат ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xuě huā yā zuǐ yàn ");
        details.setDescriptionB("雪花鸭嘴燕");
        details.setDescriptionC(" Spotted eagle ray ");
        details.setDescriptionD(" Пятнистый орляк ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huáng diāo yú yòu zǎi");
        details.setDescriptionB("黄貂鱼幼崽");
        details.setDescriptionC("Stingray Cubs");
        details.setDescriptionD("Детёныши ската");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo wěi yú/qiāng jí yú");
        details.setDescriptionB("矛尾鱼/腔棘鱼");
        details.setDescriptionC("Coelacanth");
        details.setDescriptionD("Латимерия/Целакант ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí qiū");
        details.setDescriptionB("鲯鳅");
        details.setDescriptionC(" Dolphin Fish/ Mahi Mahi  ");
        details.setDescriptionD(" Корифена ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān chē yú");
        details.setDescriptionB("翻车鱼");
        details.setDescriptionC("Ocean sunfish");
        details.setDescriptionD("Луна-рыба/Рыба-солнце");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bā lā jīn suō yú ");
        details.setDescriptionB("巴拉金梭鱼");
        details.setDescriptionC("Great barracuda ");
        details.setDescriptionD("Барракуда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shí tou yú ");
        details.setDescriptionB("石头鱼");
        details.setDescriptionC("Stonefish");
        details.setDescriptionD("Рыба-камень/Бородавчатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" сì tún ");
        details.setDescriptionB("刺豚");
        details.setDescriptionC(" Porcupine Puffer Fish ");
        details.setDescriptionD("Рыба-ёж");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hé tún ");
        details.setDescriptionB("河豚");
        details.setDescriptionC("Takifugu/ Fugu ");
        details.setDescriptionD("Такифугу/ Фугу");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán dào diào");
        details.setDescriptionB("蓝倒吊");
        details.setDescriptionC(" Blue Surgeonfish/ Regal Blue Tang ");
        details.setDescriptionD("Рыба-хирург/Голубой хирург");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo chǒu yú ");
        details.setDescriptionB("小丑鱼");
        details.setDescriptionC(" Clownfish /Amphiprion");
        details.setDescriptionD("Рыба-клоун /Амфиприон ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhāo cái yú ");
        details.setDescriptionB("招财鱼");
        details.setDescriptionC("Giant gourami  ");
        details.setDescriptionD("Гигантский гурами");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wěn lú ");
        details.setDescriptionB("吻鲈");
        details.setDescriptionC(" Kissing gourami ");
        details.setDescriptionD(" Гурами целующийся  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" liù jiǎo lóng yú ");
        details.setDescriptionB("六角龙鱼");
        details.setDescriptionC(" Mexican walking fish ");
        details.setDescriptionD(" Аксолотль ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qīng wā yú ");
        details.setDescriptionB("青蛙鱼");
        details.setDescriptionC("Mandarinfish ");
        details.setDescriptionD(" Мандаринка (рыба)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" niú jiǎo yú ");
        details.setDescriptionB("牛角鱼");
        details.setDescriptionC("Thornback Cowfish");
        details.setDescriptionD(" Рогатый трехиглый кузовок ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shī zi yú ");
        details.setDescriptionB("狮子鱼  ");
        details.setDescriptionC(" Red lionfish ");
        details.setDescriptionD("Крылатка-зебра");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yè hǎi lóng");
        details.setDescriptionB("叶海龙");
        details.setDescriptionC("  Leafy Sea Dragon  ");
        details.setDescriptionD("Морской конёк-тряпичник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi mǎ");
        details.setDescriptionB("海马");
        details.setDescriptionC("Sea Horse");
        details.setDescriptionD("Морской конёк");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng fú ");
        details.setDescriptionB("鲂鮄");
        details.setDescriptionC(" Sea robin ");
        details.setDescriptionD("Морской петух ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái jīn lóng yú ");
        details.setDescriptionB("白金龙鱼 ");
        details.setDescriptionC("White dragon/ Platinum Arowana");
        details.setDescriptionD(" Платиновая арована");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yī diǎn hú lí yú ");
        details.setDescriptionB("一点狐狸鱼");
        details.setDescriptionC("Blotched foxface");
        details.setDescriptionD("Рыба-кролик/Однопятнистый сиган");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēi yú");
        details.setDescriptionB("飞鱼");
        details.setDescriptionC("Flying fish");
        details.setDescriptionD("Летучая рыба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuǐ dī yú");
        details.setDescriptionB("水滴鱼");
        details.setDescriptionC("Blobfish");
        details.setDescriptionD("Рыба-капля");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qiú shì è tóu bīng yú ");
        details.setDescriptionB("裘氏鳄头冰鱼");
        details.setDescriptionC(" Mackerel icefish ");
        details.setDescriptionD("Ледяная рыба ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ān kāng yú ");
        details.setDescriptionB("鮟鱇鱼");
        details.setDescriptionC(" Angler fish ");
        details.setDescriptionD("Морской чёрт");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" duō bǎo yú ");
        details.setDescriptionB("多宝鱼");
        details.setDescriptionC(" Turbot  ");
        details.setDescriptionD(" Тюрбо ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xī yáng yōng dié ");
        details.setDescriptionB("大西洋庸鲽");
        details.setDescriptionC("Atlantic halibut ");
        details.setDescriptionD("Палтус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu dié");
        details.setDescriptionB("欧洲鲽");
        details.setDescriptionC(" European plaice ");
        details.setDescriptionD("Камбала");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiàn yú");
        details.setDescriptionB("剑鱼");
        details.setDescriptionC(" Swordfish ");
        details.setDescriptionD("Меч-рыба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qí yú");
        details.setDescriptionB("旗鱼");
        details.setDescriptionC(" Sailfish  ");
        details.setDescriptionD(" Парусник ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà mǎ lín yú");
        details.setDescriptionB("大马林鱼");
        details.setDescriptionC("Marlin");
        details.setDescriptionD("Марлин");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jīn qiāng yú ");
        details.setDescriptionB("金枪鱼");
        details.setDescriptionC("Tuna");
        details.setDescriptionD("Тунец");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" huáng qí jīn qiāng yú");
        details.setDescriptionB("黄鳍金枪鱼");
        details.setDescriptionC(" Yellowfin Tuna");
        details.setDescriptionD("Желтопёрый тунец ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mǎ jiāo yú ");
        details.setDescriptionB("马鲛鱼");
        details.setDescriptionC(" Japanese Spanish mackerel ");
        details.setDescriptionD(" Мелкопятнистая макрель ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi shàn");
        details.setDescriptionB("海鳝");
        details.setDescriptionC("Moray eel");
        details.setDescriptionD("Мурена");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu mán lí");
        details.setDescriptionB("欧洲鳗鲡");
        details.setDescriptionC("European eel");
        details.setDescriptionD("Речной угорь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kāng jí mán ");
        details.setDescriptionB("康吉鳗");
        details.setDescriptionC("Conger eel");
        details.setDescriptionD("Конгер  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiǎo chǐ yú ");
        details.setDescriptionB("角齿鱼");
        details.setDescriptionC(" Queensland lungfish ");
        details.setDescriptionD(" Рогозуб /Баррамунда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qī sāi mán ");
        details.setDescriptionB("七鳃鳗");
        details.setDescriptionC("River lamprey");
        details.setDescriptionD("Речная минога ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hǎi qī sāi mán");
        details.setDescriptionB("海七鳃鳗");
        details.setDescriptionC("Sea lamprey");
        details.setDescriptionD("Морская минога ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ní qiū");
        details.setDescriptionB("泥鳅");
        details.setDescriptionC("Weatherfish ");
        details.setDescriptionD("Вьюн-рыба");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xī yáng zhú dāo yú ");
        details.setDescriptionB("大西洋竹刀鱼");
        details.setDescriptionC(" Atlantic saury ");
        details.setDescriptionD("Атлантическая сайра  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("běi jí xuě yú");
        details.setDescriptionB("北极鳕鱼");
        details.setDescriptionC("Polar cod");
        details.setDescriptionD("  Полярная треска/Сайка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zī yú");
        details.setDescriptionB("鲻鱼");
        details.setDescriptionC("Flathead grey mullet");
        details.setDescriptionD("Кефаль");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zūn yú ");
        details.setDescriptionB("鳟鱼");
        details.setDescriptionC("Trout");
        details.setDescriptionD("Форель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bái guī yú");
        details.setDescriptionB("白鲑鱼");
        details.setDescriptionC("Whitefish");
        details.setDescriptionD("Сиг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sān wén yú ");
        details.setDescriptionB("三文鱼");
        details.setDescriptionC("Atlantic Salmon");
        details.setDescriptionD("Сёмга/ Атлантический лосось ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fěn hóng guī");
        details.setDescriptionB("粉红鲑");
        details.setDescriptionC("Pink salmon");
        details.setDescriptionD("Горбуша");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dà mǎ hā yú");
        details.setDescriptionB("大马哈鱼");
        details.setDescriptionC("Dog-salmon");
        details.setDescriptionD("Кета");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yín guī ");
        details.setDescriptionB("银鲑");
        details.setDescriptionC("Silver salmon");
        details.setDescriptionD("Кижуч ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng guī yú ");
        details.setDescriptionB("红鲑鱼");
        details.setDescriptionC("Red salmon/Sockeye salmon");
        details.setDescriptionD("Нерка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  huí yú ");
        details.setDescriptionB("茴鱼");
        details.setDescriptionC("Arctic grayling ");
        details.setDescriptionD(" Сибирский хариус ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" chì shāo yú");
        details.setDescriptionB("赤梢鱼");
        details.setDescriptionC(" Flathead asp");
        details.setDescriptionD("Жерех ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái bān gǒu yú ");
        details.setDescriptionB("白斑狗鱼 ");
        details.setDescriptionC("Northern pike ");
        details.setDescriptionD("Щука");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jù gǔ shé yú ");
        details.setDescriptionB("巨骨舌鱼");
        details.setDescriptionC(" Arapaima/ Pirarucu ");
        details.setDescriptionD("Арапайма/ Пираруку ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("é luó sī xún");
        details.setDescriptionB("俄罗斯鲟");
        details.setDescriptionC("Russian Sturgeon ");
        details.setDescriptionD("Русский осётр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǐ shì xún ");
        details.setDescriptionB("史氏鲟 ");
        details.setDescriptionC("Amur sturgeon ");
        details.setDescriptionD("Амурский осётр");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dá shì huáng ");
        details.setDescriptionB("达氏鳇 ");
        details.setDescriptionC("Kaluga sturgeon ");
        details.setDescriptionD("Калуга ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("ōu zhōu huáng");
        details.setDescriptionB("欧洲鳇");
        details.setDescriptionC("Beluga sturgeon");
        details.setDescriptionD("Белуга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xiǎo tǐ xún");
        details.setDescriptionB("小体鲟 ");
        details.setDescriptionC("Sterlet ");
        details.setDescriptionD("Стерлядь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shǎn guāng xún");
        details.setDescriptionB("闪光鲟");
        details.setDescriptionC("Stellate sturgeon");
        details.setDescriptionD("Севрюга");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tí ");
        details.setDescriptionB(" 鯷");
        details.setDescriptionC("Anchovy");
        details.setDescriptionD("Анчоус/ Хамса ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fēi yú ");
        details.setDescriptionB("鲱鱼");
        details.setDescriptionC("Atlantic Herring");
        details.setDescriptionD("Сельдь атлантическая");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shā dīng yú ");
        details.setDescriptionB("沙丁鱼");
        details.setDescriptionC("Sardine");
        details.setDescriptionD("Сардина");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" qīng yú ");
        details.setDescriptionB("鲭鱼");
        details.setDescriptionC("Mackerel ");
        details.setDescriptionD("Скумбрия / Макрель");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("máo lín yú");
        details.setDescriptionB("毛鳞鱼");
        details.setDescriptionC("Capelin");
        details.setDescriptionD("Мойва / Капелан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn tóu diāo");
        details.setDescriptionB("金头鲷");
        details.setDescriptionC(" Dorado ");
        details.setDescriptionD("Дорада ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("lǐ yú");
        details.setDescriptionB("鲤鱼");
        details.setDescriptionC(" Carp ");
        details.setDescriptionD(" Карп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jìng lǐ ");
        details.setDescriptionB("镜鲤");
        details.setDescriptionC("Mirror Carp");
        details.setDescriptionD("Зеркальный  карп/Королевский карп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái lián yú ");
        details.setDescriptionB("白鲢鱼");
        details.setDescriptionC("Silver carp");
        details.setDescriptionD("Толстолобик /Cеребряный карп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jǐn lǐ ");
        details.setDescriptionB("锦鲤");
        details.setDescriptionC(" Koi carps");
        details.setDescriptionD("Карпы кои");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mù sēn bái guī ");
        details.setDescriptionB("穆森白鲑");
        details.setDescriptionC("Muksun ");
        details.setDescriptionD(" Муксун ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yuán fù yǎ luó yú");
        details.setDescriptionB("圆腹雅罗鱼");
        details.setDescriptionC("﻿Ide  ");
        details.setDescriptionD("Язь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jì yú");
        details.setDescriptionB("鲫鱼");
        details.setDescriptionC("Crucian carp ");
        details.setDescriptionD("Карась");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yín jì");
        details.setDescriptionB("银鲫");
        details.setDescriptionC("Silver prussian carp");
        details.setDescriptionD("Серебряный карась");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("сǎo yú");
        details.setDescriptionB("草鱼");
        details.setDescriptionC("Grass carp");
        details.setDescriptionD("Белый амур");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" méi huā lú");
        details.setDescriptionB("梅花鲈");
        details.setDescriptionC(" Ruffe ");
        details.setDescriptionD("Ёрш ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hé lú");
        details.setDescriptionB("河鲈");
        details.setDescriptionC(" Perch ");
        details.setDescriptionD("Речной окунь ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yì yú ");
        details.setDescriptionB("鮨鱼");
        details.setDescriptionC(" Rock perch ");
        details.setDescriptionD("Каменный окунь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hǎi lú ");
        details.setDescriptionB("海鲈");
        details.setDescriptionC("Sea otter");
        details.setDescriptionD("Морской окунь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suō lú");
        details.setDescriptionB("梭鲈");
        details.setDescriptionC("Pike perch ");
        details.setDescriptionD("Судак");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" tiáo wén yā zuǐ nián ");
        details.setDescriptionB("条纹鸭嘴鲶");
        details.setDescriptionC(" Barred catfish ");
        details.setDescriptionD(" Тигровый сом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu  jù nián ");
        details.setDescriptionB("欧洲巨鲶");
        details.setDescriptionC("European catfish ");
        details.setDescriptionD("Сом");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("huā láng yú");
        details.setDescriptionB("花狼鱼");
        details.setDescriptionC("Wolffish");
        details.setDescriptionD("Пятниская зубатка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lán nián yú");
        details.setDescriptionB("蓝鲶鱼");
        details.setDescriptionC("Blue catfish");
        details.setDescriptionD("Синяя зубатка ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāng xuě  ");
        details.setDescriptionB("江鳕");
        details.setDescriptionC("Burbot");
        details.setDescriptionD("Налим");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn guī yú/dīng guì ");
        details.setDescriptionB("金鲑鱼/丁鱥");
        details.setDescriptionC("Tench ");
        details.setDescriptionD("Линь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fāng tóu yú ");
        details.setDescriptionB("方头鱼");
        details.setDescriptionC(" Red tilefish ");
        details.setDescriptionD("Амадай японский/ Кафельник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hēi xiàn xuě ");
        details.setDescriptionB("黑线鳕 ");
        details.setDescriptionC("Haddock ");
        details.setDescriptionD("Пикша ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" míng tài yú ");
        details.setDescriptionB("明太鱼");
        details.setDescriptionC("Alaska pollock ");
        details.setDescriptionD("Минтай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǎo tóu yú ");
        details.setDescriptionB("老头鱼");
        details.setDescriptionC("Amur Sleeper ");
        details.setDescriptionD("Ротан");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ōu zhōu wú xū xuě ");
        details.setDescriptionB("欧洲无须鳕");
        details.setDescriptionC("Hake ");
        details.setDescriptionD(" Хек/ Европейская мерлуза");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("běi jí guī yú");
        details.setDescriptionB("北极鲑鱼");
        details.setDescriptionC("Arctic charr");
        details.setDescriptionD("Арктический голец ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yín chāng");
        details.setDescriptionB("银鲳");
        details.setDescriptionC(" Silver pomfret ");
        details.setDescriptionD("Серебристый памп/ Рыба-зеркало ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" fáng yú");
        details.setDescriptionB("鲂鱼");
        details.setDescriptionC(" Bream ");
        details.setDescriptionD("Лещ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" nǐ lǐ ");
        details.setDescriptionB("拟鲤");
        details.setDescriptionC("Roach ");
        details.setDescriptionD("Плотва/Вобла");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" wǔ chāng yú ");
        details.setDescriptionB("武昌魚");
        details.setDescriptionC(" Wuchang bream");
        details.setDescriptionD(" Чёрный лещ  ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà gài jù zhī lǐ ");
        details.setDescriptionB("大盖巨脂鲤");
        details.setDescriptionC(" Black Pacu ");
        details.setDescriptionD("Чёрный паку");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shí rén yú");
        details.setDescriptionB("食人鱼");
        details.setDescriptionC("Black Piranha");
        details.setDescriptionD("Чёрная пиранья");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn yú ");
        details.setDescriptionB("金鱼 ");
        details.setDescriptionC("Gold fish ");
        details.setDescriptionD("Золотая рыбка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dàn tú yú  ");
        details.setDescriptionB("弹涂鱼");
        details.setDescriptionC(" Mudskippers ");
        details.setDescriptionD("Илистые прыгуны ");
        detailsList.add(details);
    }
}
