package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C86 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA(" nián ");
        details.setDescriptionB("年");
        details.setDescriptionC("Year");
        details.setDescriptionD("Год");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuè ");
        details.setDescriptionB("月");
        details.setDescriptionC("Month");
        details.setDescriptionD("Месяц");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng qī ");
        details.setDescriptionB("星期");
        details.setDescriptionC("Week");
        details.setDescriptionD("Неделя");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhōu mò");
        details.setDescriptionB("周末");
        details.setDescriptionC("Weekend");
        details.setDescriptionD("Выходные/Уикэнд");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" rì ");
        details.setDescriptionB("日");
        details.setDescriptionC("Day");
        details.setDescriptionD("День");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yè wǎn");
        details.setDescriptionB("夜晚");
        details.setDescriptionC("Night");
        details.setDescriptionD("Ночь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zǎo shàng ");
        details.setDescriptionB("早上");
        details.setDescriptionC("Morning");
        details.setDescriptionD("Утро");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bái tiān ");
        details.setDescriptionB("白天");
        details.setDescriptionC("Daytime");
        details.setDescriptionD("День");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("wǎn shàng");
        details.setDescriptionB("晚上");
        details.setDescriptionC("Evening");
        details.setDescriptionD("Вечер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīng qī yī");
        details.setDescriptionB("星期一");
        details.setDescriptionC("Monday");
        details.setDescriptionD("Понедельник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng qī èr");
        details.setDescriptionB("星期二");
        details.setDescriptionC("Tuesday");
        details.setDescriptionD("Вторник");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng qī sān");
        details.setDescriptionB("星期三");
        details.setDescriptionC("Wednesday");
        details.setDescriptionD("Cреда");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīng qī sì");
        details.setDescriptionB("星期四");
        details.setDescriptionC("Thursday");
        details.setDescriptionD("Четверг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng qī wǔ");
        details.setDescriptionB("星期五");
        details.setDescriptionC("Friday");
        details.setDescriptionD("Пятница");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xīng qī liù");
        details.setDescriptionB("星期六");
        details.setDescriptionC("Saturday");
        details.setDescriptionD("Суббота");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" xīng qī rì");
        details.setDescriptionB("星期日");
        details.setDescriptionC("Sunday");
        details.setDescriptionD("Воскресенье");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zuó tiān ");
        details.setDescriptionB("昨天");
        details.setDescriptionC("Yesterday");
        details.setDescriptionD("Вчера");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jīn tiān ");
        details.setDescriptionB("今天");
        details.setDescriptionC("Today");
        details.setDescriptionD("Сегодня");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("míng tiān");
        details.setDescriptionB("明天 ");
        details.setDescriptionC("Tomorrow");
        details.setDescriptionD("Завтра");
        detailsList.add(details);
    }
}
