package com.backend.api.repository.xml.content;

import com.backend.api.model.details.Details;

import java.util.ArrayList;
import java.util.List;

public class C88 {

    public List<Details> detailsList = new ArrayList<>();

    {
        Details details = new Details();
        details.setDescriptionA("kěn dé jī ");
        details.setDescriptionB("肯德基");
        details.setDescriptionC("KFC (KentuckyFried Chicken) ");
        details.setDescriptionD("КФС");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mài dāng láo");
        details.setDescriptionB("麦当劳");
        details.setDescriptionC(" McDonald's ");
        details.setDescriptionD(" Макдональдс ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hàn bǎo wáng");
        details.setDescriptionB("汉堡王");
        details.setDescriptionC("Burger King ");
        details.setDescriptionD("Бургер Кинг");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bì shèng kè ");
        details.setDescriptionB("必胜客 ");
        details.setDescriptionC("PizzaHut ");
        details.setDescriptionD("Пицца Хат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sài bǎi wèi ");
        details.setDescriptionB("赛百味");
        details.setDescriptionC("Subway");
        details.setDescriptionD("Сабвей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("rè gǒu ");
        details.setDescriptionB("热狗");
        details.setDescriptionC("Hot Dog");
        details.setDescriptionD("Хот дог ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hàn bǎo");
        details.setDescriptionB("汉堡");
        details.setDescriptionC("Hamburger");
        details.setDescriptionD("Гамбургер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("sān míng zhì");
        details.setDescriptionB("三明治");
        details.setDescriptionC("Sandwich");
        details.setDescriptionD("Сэндвич ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" sān míng zhì ");
        details.setDescriptionB("三明治Longer ");
        details.setDescriptionC("Sandwich Longer    ");
        details.setDescriptionD("Сэндвич Лонгер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mài xiāng yú");
        details.setDescriptionB("麦香鱼");
        details.setDescriptionC(" Filet-o-Fish ");
        details.setDescriptionD("Филе-о-Фиш ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jí shì dàn bǎo ");
        details.setDescriptionB("吉士蛋堡");
        details.setDescriptionC("Egg Cheeseburger");
        details.setDescriptionD("Яичный чизбургер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  zhī shì hàn bǎo / jí shì hàn bǎo ");
        details.setDescriptionB("芝士汉堡/ 吉士汉堡");
        details.setDescriptionC("Cheeseburger ");
        details.setDescriptionD("Чизбургер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shuāng céng zhī shì hàn bǎo ");
        details.setDescriptionB("双层芝士汉堡");
        details.setDescriptionC(" Double Cheeseburger ");
        details.setDescriptionD("Двойной чизбургер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("zhá jī hàn bǎo");
        details.setDescriptionB("炸鸡汉堡");
        details.setDescriptionC(" Chikenburger ");
        details.setDescriptionD("Чикенбургер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng gǔ jī tuǐ ");
        details.setDescriptionB("香骨鸡腿");
        details.setDescriptionC(" Spicy Chicken Legs ");
        details.setDescriptionD("Острая куриная ножка");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  xiāng là jī chì");
        details.setDescriptionB("香辣鸡翅");
        details.setDescriptionC(" Hot Wings ");
        details.setDescriptionD("Острые  куриные  крылышки ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī kuài");
        details.setDescriptionB("鸡块");
        details.setDescriptionC("Chicken Nuggets");
        details.setDescriptionD("Чикен наггетс");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" dà xiā ");
        details.setDescriptionB("大虾");
        details.setDescriptionC(" Big Shrimps");
        details.setDescriptionD(" Большие креветки");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jī mǐ huā ");
        details.setDescriptionB("鸡米花 ");
        details.setDescriptionC("Popcorn Chicken");
        details.setDescriptionD("Байтс куриные");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǎo běi jīng jī ròu juǎn ");
        details.setDescriptionB("老北京鸡肉卷");
        details.setDescriptionC("Dragon  Twister ");
        details.setDescriptionD("Твистер ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" mò xī gē jī ròu juǎn ");
        details.setDescriptionB("墨西哥鸡肉卷");
        details.setDescriptionC("Mexican Twister ");
        details.setDescriptionD("Мексиканский твистер");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" quán jiā tǒng");
        details.setDescriptionB("全家桶");
        details.setDescriptionC("Family Big Box");
        details.setDescriptionD("Курица Баскет (большая)");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tǔ dòu ní ");
        details.setDescriptionB("土豆泥");
        details.setDescriptionC(" Mashed Potato");
        details.setDescriptionD(" Картофельное пюре");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎi sǎ shā lā ");
        details.setDescriptionB("凯撒沙拉");
        details.setDescriptionC("Caesar Salad");
        details.setDescriptionD("Салат Цезарь");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yù mǐ shā lā ");
        details.setDescriptionB("玉米沙拉");
        details.setDescriptionC("Corn Salad");
        details.setDescriptionD("Кукурузный салат");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("bǐ sà/pī sà");
        details.setDescriptionB("比萨 /披萨");
        details.setDescriptionC("Pizza");
        details.setDescriptionD("Пицца");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" shǔ tiáo ");
        details.setDescriptionB("薯条");
        details.setDescriptionC(" French fries ");
        details.setDescriptionD("Картофель фри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fān qié jiàng ");
        details.setDescriptionB("番茄酱");
        details.setDescriptionC(" Tomato Ketchup ");
        details.setDescriptionD("Кетчуп");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("jiè mò");
        details.setDescriptionB("芥末");
        details.setDescriptionC("Mustard");
        details.setDescriptionD("Соус Горчичный ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shā lā jiàng ");
        details.setDescriptionB("沙拉酱");
        details.setDescriptionC("Mayonnaise");
        details.setDescriptionD("Майонез ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" zhī shì jiàng ");
        details.setDescriptionB("芝士酱");
        details.setDescriptionC(" Cheese Sauce ");
        details.setDescriptionD("Соус  Сырный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("fēng mì suàn jiàng ");
        details.setDescriptionB("蜂蜜蒜酱");
        details.setDescriptionC(" Honey Garlic Sauce ");
        details.setDescriptionD("Медово-чесночный соус");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shāo kǎo jiàng");
        details.setDescriptionB("烧烤酱");
        details.setDescriptionC("Barbecue Sauce");
        details.setDescriptionD("Соус Барбекю");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("yān xūn shāo kǎo jiàng");
        details.setDescriptionB("烟熏烧烤酱");
        details.setDescriptionC("Smoky Barbecue Dipping Sauce");
        details.setDescriptionD("Соус барбекю с ароматом копчения");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián là jiàng");
        details.setDescriptionB("甜辣酱");
        details.setDescriptionC("Sweet Chilli Dipping Sauce");
        details.setDescriptionD("Сладкий соус чили");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("suān tián jiàng");
        details.setDescriptionB("酸甜酱");
        details.setDescriptionC("Sweet and Sour Sauce");
        details.setDescriptionD("Соус Кисло-сладкий");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("tián gā lí jiàng");
        details.setDescriptionB("甜咖喱酱");
        details.setDescriptionC("Sweet Curry Sauce ");
        details.setDescriptionD("Соус Сладкий карри");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" jiāo táng bīng qí lín ");
        details.setDescriptionB("焦糖冰淇淋");
        details.setDescriptionC("Caramel Ice cream ");
        details.setDescriptionD("Мороженое  карамельное");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiǎo kè lì bīng qí lín");
        details.setDescriptionB("巧克力冰淇淋");
        details.setDescriptionC("Chocolate Ice cream");
        details.setDescriptionD("Мороженое  шоколадное");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cǎo méi bīng qí lín ");
        details.setDescriptionB("草莓冰淇淋");
        details.setDescriptionC("Strawberry Ice cream ");
        details.setDescriptionD("Мороженое клубничное");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" yuán tǒng bīng qí lín");
        details.setDescriptionB("圆筒冰淇淋");
        details.setDescriptionC("Ice cream cone");
        details.setDescriptionD("Мороженое  рожок");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("hēi zhī ma bīng qí lín ");
        details.setDescriptionB("黑芝麻冰淇淋");
        details.setDescriptionC(" Black Sesame Ice cream");
        details.setDescriptionD("Кунжутное мороженое");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("mài xuàn fēng bīng qí lín ");
        details.setDescriptionB("麦旋风冰淇淋");
        details.setDescriptionC(" McFlurry Ice cream");
        details.setDescriptionD(" Мороженое Макфлурри ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xiāng cǎo nǎi xī");
        details.setDescriptionB("香草奶昔");
        details.setDescriptionC(" Vanilla Milkshake ");
        details.setDescriptionD("Молочный коктейль ванильный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("qiǎo kè lì nǎi xī");
        details.setDescriptionB("巧克力奶昔");
        details.setDescriptionC(" Chocolate Milkshake ");
        details.setDescriptionD("Молочный коктейль шоколадный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" cǎo méi nǎi xī ");
        details.setDescriptionB("草莓奶昔");
        details.setDescriptionC(" Strawberry Milkshake ");
        details.setDescriptionD(" Молочный коктейль клубничный");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("niú nǎi");
        details.setDescriptionB("牛奶");
        details.setDescriptionC("Milk");
        details.setDescriptionD("Молоко");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dòu jiāng ");
        details.setDescriptionB("豆浆");
        details.setDescriptionC(" Soya milk ");
        details.setDescriptionD(" Соевое молоко ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("kě kǒu kě lè");
        details.setDescriptionB("可口可乐");
        details.setDescriptionC("Coca Cola");
        details.setDescriptionD("Кока-кола");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" bīng kā fēi ");
        details.setDescriptionB("冰咖啡");
        details.setDescriptionC(" Ice Coffee ");
        details.setDescriptionD("Айс Кофе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kā fēi");
        details.setDescriptionB("咖啡");
        details.setDescriptionC(" Сoffee ");
        details.setDescriptionD("Кофе");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("shuāng bèi nóng suō kā fēi ");
        details.setDescriptionB("双倍浓缩咖啡");
        details.setDescriptionC(" Double espresso ");
        details.setDescriptionD("Двойной Эспрессо");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" kǎ bù qí nuò");
        details.setDescriptionB("卡布奇诺");
        details.setDescriptionC("Cappuccino ");
        details.setDescriptionD("Капучино ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" ná tiě kā fēi ");
        details.setDescriptionB("拿铁咖啡");
        details.setDescriptionC(" Coffee Latte");
        details.setDescriptionD("Кофе Латте");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("xuě dǐng kā fēi ");
        details.setDescriptionB("雪顶咖啡");
        details.setDescriptionC(" Coffee with Ice cream ");
        details.setDescriptionD("Кофе Глясе ");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" hóng chá");
        details.setDescriptionB("红茶");
        details.setDescriptionC("Black Tea");
        details.setDescriptionD(" Чёрный чай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" lǜ chá");
        details.setDescriptionB("绿茶");
        details.setDescriptionC("Green tea ");
        details.setDescriptionD(" Зелёный чай");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("  yīng táo pài ");
        details.setDescriptionB("樱桃派");
        details.setDescriptionC("Cherry Pie ");
        details.setDescriptionD("Пирожок с вишней");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA(" píng guǒ hé ròu guì sōng bǐng ");
        details.setDescriptionB("苹果和肉桂松饼");
        details.setDescriptionC(" Apple and Cinnamon Muffin ");
        details.setDescriptionD("Маффин с яблоком и корицей");
        detailsList.add(details);
        details = new Details();
        details.setDescriptionA("dàn tà ");
        details.setDescriptionB("蛋挞");
        details.setDescriptionC(" Egg Tart");
        details.setDescriptionD("Яичный тарт");
        detailsList.add(details);
    }
}
